### ISSUE TITLE
AkitaNgDevtools (.forFeature ?) to work with lazy loaded modules

### ISSUE THREAD

**Issue by Mooli88** [datorama/akita#101]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behaviour

AkitaNgDevtools isn't working when it's being imported to a module which is lazy loaded (unlike StoreDevtoolsModule of ngrx for example).

## Expected behaviour

For AkitaNgDevtools to work with a lazy loaded module.
Something like AkitaNgDevtools.forFeature().

## What is the motivation / use case for changing the behavior?

Although it seems unlikely, sometimes we want an app which only part of it will implement Akita.

## Environment
<pre><code>
Angular version: 7.1.0 beta

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
I'm not sure what you mean as Akita dev-tools works with lazily loaded modules. What is the problem?

**Comment by Mooli88** [comment]
@NataneBasal
Oh, well I either implemented it in a wrong way or its a bug. 
When I try to import Akita dev-tool to the lazy loaded module, its simply not working. 
But when I import it to the AppModule its work perfectly.

**Comment by NetanelBasal** [comment]
Can you create a simple demo on [stackblitz](https://stackblitz.com) or upload a simple demo to GitHub, please?

**Comment by Mooli88** [comment]
> Can you create a simple demo on [stackblitz](https://stackblitz.com) or upload a simple demo to GitHub, please?

https://stackblitz.com/edit/angular-pvyj9v
1. Devtool is imported to lazy loaded module with no result in the redux extension
2. Comment it out and go to app module. uncomment the akita devtool and see the result in the redux extension.

*might need to hard reload between changes.

**Comment by NetanelBasal** [comment]
Why do you need to inject it in a lazy load module?

**Comment by Mooli88** [comment]
This part of our app needs to be lazy loaded and this is the only part (for now) which implements Akita.
I understand this is a very unusual scenario but this is due to the nature of this app being used for training and experiment purposes.

**Comment by NetanelBasal** [comment]
I will try to investigate, but can't promise anything :)

**Comment by Mooli88** [comment]
That's fine, we still love Akita and looking forward to using it more extensively in the future!

**Comment by NetanelBasal** [comment]
You can't use the `AkitaNgDevtools.forRoot()` module as it relies on the application bootstrap process. But it works with the underline API.

``` ts
import { akitaDevtools } from '@datorama/akita';

akitaDevtools(); <======

const routes: Routes = [
  { path: '', component: LazyLoadedComponent }];

@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild(routes)
  ],
  providers: [ExampleQuery, ExampleStore, ExampleService],
  declarations: [LazyLoadedComponent],
})
export class LazyLoadedModule { }
```
