### ISSUE TITLE
[Feature request - STORE API ] allow prepend when add more entity to store.

### ISSUE THREAD

**Issue by hiepxanh** [datorama/akita#102]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have messases list: 
[{text: 'd', time: 114}, {text: 'e', time: 115}, {text: 'f', time: 116}]

if I fetching more data, I append it to the end instead of begin point:
 `this.messagesStore.add(data)`
[{text: 'd', time: 114}, {text: 'e', time: 115}, {text: 'f', time: 116}, {text: 'a', time: 111}, {text: 'b', time: 112}, {text: 'c', time: 113}]
that not good when you have chat app, we need prepend new message at begin. So I have to update the store manually to keep my order. 
my temporary solution is using: 
``` .ts
let newObject = {};
    data.forEach((item) => newObject[item.messageID] = item)
    this.messagesStore.updateRoot(state => {
      return {
        ids: [...data,state.ids],
        entities: {...newObject, ...state.entities}
      }
    })
```
## Expected behavior

I think that will be good if we have: 
`this.messagesStore.add(data,'prepend')`
then we will have new data append at start:
[{text: 'a', time: 111}, {text: 'b', time: 112}, {text: 'c', time: 113}, {text: 'd', time: 114}, {text: 'e', time: 115}, {text: 'f', time: 116}]

please, let me know your oppinion. If you think that is useful. I can create an PR with the code above

**Comment by NetanelBasal** [comment]
I'm wondering why not using Akita's sorting?

```ts
@QueryConfig({
  sortBy: 'time',
  sortByOrder: Order.ASC or Order.DESC
})
export class MessagesQuery extends QueryEntity<State, Message> {
  ...
}
```

**Comment by NetanelBasal** [comment]
You are right; I will fix it now.

**Comment by NetanelBasal** [comment]
I still think the prepend functionality can be useful. Do you want to create a PR for it? Use options object. { prepend: boolean }

**Comment by hiepxanh** [comment]
thank you. I just want to say, your reply very quick and your project save my team, my time, my life. 
I can make an PR for this

**Comment by hiepxanh** [comment]
but what about the query snapshot not correct? it still need fix, isn't it ?

**Comment by NetanelBasal** [comment]
Pushed a fix.

**Comment by NetanelBasal** [comment]
One of my team members will add this functionality. Thanks anyway. Don't forget to update Akita to the latest version.

**Comment by NetanelBasal** [comment]
@shaharkazaz
