### ISSUE TITLE
Resetting all stores to initialState at once.

### ISSUE THREAD

**Issue by DanielNetzer** [datorama/akita#104]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have to call .update(createInitialState()) for each store instance.

## Expected behavior

A way to access the Akita instance and to reset the entire store to initial state.

## What is the motivation / use case for changing the behavior?

There is no easy way to reset all Akita stores at once, 
common use case is when a user wants to logout.

**Comment by NetanelBasal** [comment]
Yes, It's a helpful suggestion. I need to think about the API.

**Comment by NetanelBasal** [comment]
@DanielNetzer I was thinking about something like:

```ts
import { resetStores } from '@datorama/akita';

resetStores({ exclude: ['storeName'] });
```

**Comment by DanielNetzer** [comment]
looking great, I can make a PR if you don't mind.

**Comment by NetanelBasal** [comment]
Go for it.
