### ISSUE TITLE
test with rest

### ISSUE THREAD

**Issue by fmandres92** [datorama/akita#109]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When i run the test with karma and jasmine the output is  "You need to enable the reset functionality"

## Expected behavior
How i can resolve it ?

## Minimal reproduction of the problem with instructions
It is only the when i run the test

## Environment

<pre><code>
 "dependencies": {
    "@angular/animations": "^6.1.1",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@auth0/angular-jwt": "^2.0.0",
    "@datorama/akita": "^1.17.0",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "@ngx-progressbar/core": "^5.0.1",
    "@ngx-translate/core": "^10.0.1",
    "@ngx-translate/http-loader": "^3.0.1",
    "@toverux/ngx-sweetalert2": "^4.0.0",
    "@types/url-join": "^0.8.2",
    "angularx-social-login": "^1.2.0",
    "bootstrap": "^4.1.1",
    "bootstrap-social": "^5.1.1",
    "chart.js": "^2.7.2",
    "core-js": "^2.5.5",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "leaflet": "^1.3.1",
    "leaflet-image": "^0.4.0",
    "leaflet.awesome-markers": "^2.0.4",
    "moment": "^2.22.2",
    "ng2-charts": "^1.6.0",
    "ng2-file-upload": "^1.3.0",
    "ngx-spinner": "^6.1.2",
    "ngx-toastr": "^8.10.0",
    "popper.js": "^1.14.3",
    "rxjs": "^6.1.0",
    "sweetalert2": "^7.28.11",
    "url-join": "^4.0.0",
    "yarn": "^1.6.0",
    "zone.js": "^0.8.26"
  },

**Comment by NetanelBasal** [comment]
Which tests are you running? Of your application or Akita's?

**Comment by fmandres92** [comment]
In my application, but i need reset the states then i use a this service 
``import { resetStores } from '@datorama/akita';
import { Injectable } from '@angular/core';

​@Injectable({ providedIn: 'root' })
export class ResetStateService {
    logout() {
        resetStores();
    }
}
``

**Comment by NetanelBasal** [comment]
you need to enable it:
```ts
import { akitaConfig } from "@datorama/akita";
​
akitaConfig({
  resettable: true
});

```

**Comment by fmandres92** [comment]
That is in my main.ts. 
if i put in mi componen.spect this is broken

**Comment by NetanelBasal** [comment]
Add it to the `test.ts` file. (assuming you're using angular-cli)

**Comment by fmandres92** [comment]
I don't know where in my compnent.spec.ts i have to  import
 `akitaConfig({
  resettable: true
});`

**Comment by NetanelBasal** [comment]
^^check my comment

**Comment by fmandres92** [comment]
Thanks very much. Now Work xD
