### ISSUE TITLE
getInitialActiveState() should accept a parameter

### ISSUE THREAD

**Issue by GrandSchtroumpf** [datorama/akita#111]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`getInitialActiveState()` set the active state to null

## Expected behavior
`getInitialActiveState()` should accept a parameter

## What is the motivation / use case for changing the behavior?
I would like to set my active state to `"/"` instead of `null` using the `getInitialActiveState()`.

Thanks =)

**Comment by NetanelBasal** [comment]
The `active` key is responsible for the active **entity** id, not the active router state.

**Comment by GrandSchtroumpf** [comment]
I know, just in my case the entities are nodes of a virtual file system and the id of these entities is a path. 
Sorry, my use case was not explicit enough...

**Comment by NetanelBasal** [comment]
That's not a problem. You can set the `active` key by yourself. 

```ts
const initialState = {
  active: '/'
}
```

But anyway it's a nice suggestion, will add it shortly. Thanks.
