### ISSUE TITLE
selectActiveId should have a generic type

### ISSUE THREAD

**Issue by GrandSchtroumpf** [datorama/akita#112]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`selectActiveId()` and `getActiveId()` return type `ID`.  

## Expected behavior
`selectActiveId()` and `getActiveId()` should return the type of the `idKey` if any.
Or at least accept a generic type like : `selectActiveId<string>()`.

## Minimal reproduction of the problem with instructions
```javascript
@Component({...})
class NodeComponent implements OnInit {
  public key: Observable<string>;
  constructor(private query: NodeQuery) {}
  ngOnInit() {
    this.key = this.query.selectActiveId(); // Type Warning ....
  }
}
```

## What is the motivation / use case for changing the behavior?
You need to hard type `as Observable<string>` when using `selectActiveId()` to avoid type warnings;

## Environment

<pre><code>
Angular version: 7.0.4
IDE : Visual Studio Code
</code></pre>

**Comment by GrandSchtroumpf** [comment]
I know I can use `ID`, but if my `keyId` is always a `string` I don't see why I should say it can also be a `number`...

**Comment by NetanelBasal** [comment]
So you want the ability to set a generic? 

`this.query.selectActiveId<number>()`

**Comment by GrandSchtroumpf** [comment]
A generic type would be good. And the best would be that the activeId has the type of the "keyId" if any =)

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by GrandSchtroumpf** [comment]
Ok, I'll try tomorrow =)

Le jeu. 8 nov. 2018 à 18:37, Netanel Basal <notifications@github.com<mailto:notifications@github.com>> a écrit :

Do you want to create a PR?
