### ISSUE TITLE
EntityStore: Entity-Lifetime

### ISSUE THREAD

**Issue by leptoquark1** [datorama/akita#113]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Use case

I want to use Akita in my project where multiple users are working with large data-set for an entity.
For this I want to consider a max lifetime per entity (perishable) before the store has to ask the api for an updated version of the entity.

## Current workaround in my tests

I've created a perishable entity like 

```js
{id: user.id, updatedAt: + new Date(), entity: user}: PerishEntity<User>
```
and defined the EntityStore with it:

```js
class UserStore extends PerishableEntityStore<UserState, PerishEntity<User>>  // [...]
```

However I overwrote the general Query-Class function "select()" to map the PerishEntity<User> to the User Object like:

```js
// [...]
return super.select(project).pipe(
      map((result: any) => {
        if (typeof result === 'undefined' || !isObject(result)) {
          return result;
        } else if (isObject(result.entity)) {
          return result.entity;
        }

        const entities = isObject(result.entities) ? result.entities : result;
        const actualEntities = {};
        Object.values(entities).forEach((value: {id: ID, entity: {}}) => {
          actualEntities[value.id] = value.entity;
        });

        return isObject(result.entities)
          ? Object.assign(JSON.parse(JSON.stringify(result)), {entities: actualEntities})
          : actualEntities;
      })
    ) // [...]
```

I'd ask for perished entity like this (I gave the store a lifeTime property)

```js
  const entity = query.getEntity(id);
  return entity
    ? (+new Date() - entity.updatedAt) / 1000 > store.lifeTime
    : false;
```

## What is the motivation / use case for changing the behavior?

For search functions, tables, update or create forms the user has to see the updated version of the entity. 

## Actual Question

Is this the correct way to implement such a feature in akita, or is there a way I've not considered yet. Otherwise this would be a great feature I'd invest time to contribute.

## Environment

<pre><code>
Angular version: 7.0.0

Browser:
- [x] Chrome (desktop) Evergreen
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.11.0
- Platform:  mac
</code></pre>

**Comment by NetanelBasal** [comment]
I do not completely understand the use case, but from what I do it seems like you need to check if the entity lifetime passed, request the entity and update the store, otherwise, do nothing. Am I missing something?

**Comment by leptoquark1** [comment]
> 
> 
> I do not completely understand the use case, but from what I do it seems like you need to check if the entity lifetime passed, request the entity and update the store, otherwise, do nothing. Am I missing something?

Yes. I thought this could be handled with the UI state per entity, but I don't get the use case by reading the corresponding docs.

About the use case: When the store state not serves, as you mentioned, as the "single source of truth" because the api is. This is caused by by many users updating entities of a large collection simultaneous. To not see any wrong/old entity state in detail, form or tables the entities in store must be checked regulary.

I hope I explained it comprehensible.

**Comment by NetanelBasal** [comment]
It seems like a good case for using web sockets at the server side.

**Comment by leptoquark1** [comment]
I've thought about that too and going to test it.
Anyways, do you thing it's possible to implement such a feature with additionally metadata per entity?

**Comment by NetanelBasal** [comment]
Do you have an API idea in mind?

**Comment by TheAifam5** [comment]
Use SignalR and create a Hub, which connects directly with Akita Store :)

**Comment by DanielNetzer** [comment]
How about exposing an API to dispatch actions similar to NGRX, but the allowed actions are the one Akita expose (just an idea)

**Comment by NetanelBasal** [comment]
Thanks for the suggestion, but Akita it's not Redux, why you need to dispatch actions?

**Comment by DanielNetzer** [comment]
think of opening a listener on the store that can receive an action ie. 'UPDATE' and payload/data.
this way you can just open this listener to a web socket and that socket will send actions with data.

**Comment by NetanelBasal** [comment]
You don't need action; you can use the query.
```ts
query.select(state => {
  // the state has been changed
})
```

**Comment by DanielNetzer** [comment]
maybe I didn't explain myself well, think that you have an open websocket listening on channel 
```
this.socket.on(channelName = TODOS, event: { action: string, payload: data } => {
           // manipulate the store here according to the action sent and the payload
      });
```

**Comment by NetanelBasal** [comment]
So you are saying the action is something like `add/remove/update`, etc.?

**Comment by DanielNetzer** [comment]
exactly

**Comment by NetanelBasal** [comment]
Currently, it will work with a simple `switch` based on the action, but I get your point, I need to think about it.

**Comment by NetanelBasal** [comment]
You can join Akita's Gitter channel, btw.

**Comment by leptoquark1** [comment]
I approve the socket approach @DanielNetzer. A seamless integration of socket emitters to an akita store would be great, indeed. How do you picture such an contract with the emitter in detail?

**To original issue topic:** Is there any other use case for additional entity meta data that could not be represented as an actualy entity attribute? Otherwise I would drop this feature request.

**Comment by NetanelBasal** [comment]
@leptoquark1 No.
