### ISSUE TITLE
Remove(): Return to initial active instead of null

### ISSUE THREAD

**Issue by GrandSchtroumpf** [datorama/akita#114]
When using `remove()`, the `active` value can be set to `null`. I think it would be set to the initial state value instead.

https://github.com/datorama/akita/blob/0a7a4763f5b7b6cc0f9e918c5b3ac15410485137/akita/src/internal/crud.ts#L159

**Comment by NetanelBasal** [comment]
Maybe it's relevant for your use-case. I can't decide on the consumers. You can always call `setActive()` by yourself 😀
