### ISSUE TITLE
[Feature Request] Entity-Query: give index into filter function

### ISSUE THREAD

**Issue by manudss** [datorama/akita#117]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The filter function filterBy provide only the current Element. 

`export interface SelectOptions<E> extends SortByOptions<E> {
  asObject?: boolean;
  filterBy?: ((entity: E) => boolean) | undefined;
  limitTo?: number;
}`

## Expected behavior
Expect to have the index number. 

`export interface SelectOptions<E> extends SortByOptions<E> {
  asObject?: boolean;
  filterBy?: ((entity: E, index?: number) => boolean) | undefined;
  limitTo?: number;
}`

## What is the motivation / use case for changing the behavior?
Permit to have in filter function the index. Can be usefull, for exemple, to test, if odd or even row, to work with position in the list, or filter to get 1 element every x element : 
for exemple, to display list in 3 column, we can get 3 selectAll with modulo. 
`const colum1 = this.entityQuery.selectAll({filterBy: (entity: E, index: number) => index % 3 === 0 });
const colum2 = this.entityQuery.selectAll({filterBy: (entity: E, index: number) => index % 3 === 1 });
const colum3 = this.entityQuery.selectAll({filterBy: (entity: E, index: number) => index % 3 === 2 });
`

## Implement it
It is easy, because, we have the information on each loop. 
`for (let i = 0; i < ids.length; i++) {
    const id = ids[i];

    if (!entityExists(id, entities)) {
      continue;
    }

    if (!filterBy) {
      arr.push(entities[id]);
      continue;
    }

    if (filterBy(entities[id], i)) {
      arr.push(entities[id]);
    }
  }`

**Comment by NetanelBasal** [comment]
Create a PR, please :)

**Comment by manudss** [comment]
> Create a PR, please :)

Yes, I am woking on it ! See PR.
