### ISSUE TITLE
Support dispatching flux standard action objects

### ISSUE THREAD

**Issue by ronnetzer** [datorama/akita#119]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
As I understand (and please correct me if I'm wrong), there is no supported way to "dispatch" flux action to Akita (akita doesn't even work with real actions). The only way to update the store is use the predefined methods exposed in Store class (or use updateRoot which also accepts an object to update).

## Expected behavior
There should be a way to dispatch a "global", flux standard action to the root store (the same actions you see in the devtools), and then the root store should invoke the relevant sub store's update/add/whatever method.

## What is the motivation / use case for changing the behavior?
Let's say that my server have a websocket microservice and in different places and scenarios the server emits actions to the front to update certain parts of the application (new user added to a group, realtime updates of downloading a large amount of data...).
Currently, with Ngrx, I'm just dispatching the received actions and Ngrx takes care of the rest. I believe it should be the same for Akita

Please let me know what you think about it, I would like to make a PR and implement it.

**Comment by NetanelBasal** [comment]
Already talked with your brother, you can create a PR.

**Comment by ronnetzer** [comment]
This is a little different from what you guys discussed. What I want to implement is something more generic and not per store instance.

for example I have auth store, users management store and todos store.

* auth store is used for login/logout
* users management is for viewing/managing users in my group
* todos store is for viewing my group's todos and add/edit/upate/etc a todo.

the server emits actions when:
1. my session expires -> a logout action will be emitted
2. a user is added/removed/updated in my group
3. a todo is edited/done/deleted/etc in my group

I would like to open only one listener in my front and call the invoke(actionFromBackend)

But from what I understood from your discussion is that i'll need to do some switch-case in this listener so i'll call the correct store's invoke() method.

What I'm suggesting is that the rootStore will handle this switch-case thing.

And another thing that's a bit different from your discussion, I want it to be available for regular stores and no only for entity stores (to support my auth store scenario)

**Comment by NetanelBasal** [comment]
> I would like to open only one listener in my front and call the invoke(actionFromBackend)

Can you give me an example for such API?

**Comment by NetanelBasal** [comment]
Closed for now.
