### ISSUE TITLE
EntityStateHistoryPlugin undo allows only 1 ID

### ISSUE THREAD

**Issue by danzrou** [datorama/akita#12]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
undo and redo accept only 1 ID

## Expected behavior
Should accept multilple IDs

## What is the motivation / use case for changing the behavior?
According to documentation, EntityStateHistoryPlugin undo/redo should accept multiple IDs.

## Environment
Akita 1.2.0

**Comment by NetanelBasal** [comment]
Where do you see the problem? I have tested the following code locally, and it works fine.

`this.stateHistoryEntity = new EntityStateHistoryPlugin<Todo>(this.todosQuery, { entityIds: [1,2]});`

**Comment by danzrou** [comment]
According to documentation:

> With this setup you will get the following functionality:
> 
> **undo(entityId?: ID | ID[]) : undo the last change.**
> 
> **redo(entityId?: ID | ID[]) : redo the last change.**
> 
> jumpToPast(entityId?: ID | ID[], index: number) : jump to the provided index in the past (assuming index is valid).
> 
> jumpToFuture(entityId?: ID | ID[], index: number) : jump to the provided index in the future (assuming index is valid).
> 
> clear(entityId?: ID | ID[]) : clear the history. 
> 
> destroy(entityId?: ID | ID[], clearHistory = false) : unsubscribe and optionally clear the history. 

What I see in Entity state history:

```
export declare class EntityStateHistoryPlugin<E, P extends StateHistoryPlugin<E, any> = StateHistoryPlugin<E, any>> extends EntityCollectionPlugin<E, P> {
    protected query: QueryEntity<any, E>;
    protected readonly params: StateHistoryEntityParams;
    constructor(query: QueryEntity<any, E>, params?: StateHistoryEntityParams);
    redo(ids?: ID): void;
    undo(ids?: ID): void;
    hasPast(id: ID): boolean;
    hasFuture(id: ID): boolean;
    jumpToFuture(ids: IDS, index: number): void;
    jumpToPast(ids: IDS, index: number): void;
    clear(ids?: IDS): void;
    destroy(ids?: IDS, clearHistory?: boolean): void;
    protected instantiatePlugin(id: ID): P;
}
```

**Comment by NetanelBasal** [comment]
You are right; it's just a missing type.

**Comment by NetanelBasal** [comment]
Thanks, I'm releasing a fix.
