### ISSUE TITLE
Wider class support for entities

### ISSUE THREAD

**Issue by danzrou** [datorama/akita#120]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently, the constructor for classes accepts only 1 parameter - the merged state of old + new.

## Expected behavior

In my use case, I need to pass additional parameters to the class constructor which I don't want to use as class members.

## What is the motivation / use case for changing the behavior?

My idea - before calling update, store additional constructor parameters as an array in some local variable (in the store?) and then pass it to the constructor with destructing operator (or by calling apply to support < ES6) .
After updating, they should be cleared.

```
const additionalArgs = [1, 'text', {key: 'value'}];
this.store.setConstructorParams(additionalArgs); // name?
```

```
if (isPlainObject(newState)) {
  newEntity = new oldEntity.constructor(merged);
} else {
  newEntity = new (newState as any).constructor(merged, ...args);
  args = [];
}
```

**Comment by NetanelBasal** [comment]
I don't think we're going to add this as we don't recommend using classes as the model. Why you don't add them as class members, it seems like an anti-pattern.

**Comment by danzrou** [comment]
Why you don't recommend on using classes? 
I do understand though that my case is very specific and might sound odd - but generally speaking, it might be a good addition to have more arguments passed in constructor.

**Comment by NetanelBasal** [comment]
1. We can’t store classes in the server. A good case is when you need to save the stores snapshot in the server.
2. The typical pattern in Redux is to work with plain objects.
3. Harder to use with web workers. (serialization)
4. There are various third party (check immer for example ) that only works with plain objects.

**Comment by danzrou** [comment]
Some good points over there.
I know it's not an Akita related discussion now - but how would you implement class methods as functions when you need to reuse them in multiple components in template bindings and also keep DRY?

**Comment by NetanelBasal** [comment]
Can you give me an example? I'm not sure what you mean.

**Comment by danzrou** [comment]
Sure. My current class (which has an Akita store for it ) is of a generic type and one of its members is the type
```
export class A<T extends SomeClass>{
  id: number;
  type: T; 
  ... // other common props
}

export interface SomeClass{
  getCode();
  ...
}

```
I have multiple presentation components which receive `A` as an input, and displays some properties of its `type` where each type can implement it differently.
```
@Input field: A;
...
<div>{{field.type.getCode()}} </div>
```

As far as I know I cannot refer to static functions from the template and I probably would have to add a method to call them explicitly.
Thanks!

**Comment by NetanelBasal** [comment]
> As far as I know I cannot refer to static functions from the template 

Why do you need static functions? I'm not sure I understand the use case. A little demo on stackblitz will help.

**Comment by danzrou** [comment]
In order to make them plain object - I need to implement getCode() method for each type.
Will prepare a stackblitz

**Comment by danzrou** [comment]
Updated the question in previous comment, added SB

**Comment by NetanelBasal** [comment]
Object composition?

**Comment by danzrou** [comment]
Probably.
Thanks
