### ISSUE TITLE
feature : Plugin to manage filters

### ISSUE THREAD

**Issue by manudss** [datorama/akita#125]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
have a better system for filters. There is already a filterBy function. When changing the filter, we must recall selectAll() to apply it. 

## Expected behavior
But it could be good to have a mechanic of multiple filter, via a filter bind.
As soon as we add a filter, or it is removed, it emit a new value filtered to all subscriber of select-all. 

## What is the motivation / use case for changing the behavior?
This could be useful for eg displaying products, like at amazon. We can filter the products with several filters applied. Then we can display the liste of alls filters, and remove one. 

This could also be usefull, to have global config. In config profil, we could set for exemple the liste of category you like it. And then, in all other page, this will display only data from these categories. 

The manage of filter is separated of the display, and any changed was apply in the list.

**Comment by NetanelBasal** [comment]
As we discuss, it will be in a different package.

https://engineering.datorama.com/you-asked-for-it-we-listened-and-now-its-here-akita-v3-92740d0d72e4

**Comment by tony** [comment]
@NetanelBasal Hi!   Any updates on this?  Where does this stand now?

**Comment by NetanelBasal** [comment]
https://github.com/manudss/akita-filters-plugin
