### ISSUE TITLE
function add if not exist

### ISSUE THREAD

**Issue by manudss** [datorama/akita#127]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
There is no function to add one or more elements only if they are not present in the store. The add method, filter the items if they are not present. But it still launches an action in the store.
There is a private function that does this but no public function

## Expected behavior

A function to add one or more items only if they are not present in the store. (just search with the id), and update the store, only if it does not exist.

## What is the motivation / use case for changing the behavior?

This is useful, if we know that the data has not changed, and that we only want to add the new elements that are not present in the store.
For example, if an API returns a list of the latest notifications. We can do a pooling to retrieve these last changes, and keep in the store that separate notifications. Otherwise at each pooling, we make a modification of the slore.

**Comment by NetanelBasal** [comment]
Thanks, but there is no need to create a different method, we don't want to bloat the API. We should make the change in the `add` method to support this.

**Comment by NetanelBasal** [comment]
If the entities exist, we don't need to create a new state and dispatch an action. Can you update the PR, please?

**Comment by NetanelBasal** [comment]
Already did it, there is no need to do it.

**Comment by manudss** [comment]
Thanks
