### ISSUE TITLE
feature : Per component stores

### ISSUE THREAD

**Issue by levitatejay** [datorama/akita#136]
I think it would be a cool feature to easily create stores per component using the Component Providers scope, e.g.

```
@Component({
    selector: 'app-feed-item',
    templateUrl: './feed-item.component.html',
    styleUrls: ['./feed-item.component.scss'],
    providers: [FeedItemQuery, FeedItemService, FeedItemStore]
})
```

That way the component and its children can easily share a state and the stores are cleaned away as the components are removed.

Doing this currently doesn't seem to work because the stores will have the same name. Perhaps a GUID could be appended to their name?

**Comment by NetanelBasal** [comment]
In the last release, you can pass the `storeName` in the constructor.

```ts
 constructor() {
   super(initialState, { storeName: '...' } )
 }
```

**Comment by levitatejay** [comment]
Thanks for that!

Looking @ the dev tools though it looks like the objects are not being removed from the store when the components are destroyed.
I've tried using the following but it is throwing `RangeError: Maximum call stack size exceeded`

```
@Injectable()
export class FeedItemStore extends Store<FeedItemState> implements OnDestroy {
    constructor() {
        super(initialState, { storeName: `FeedItem ${guid()}` });
    }

    ngOnDestroy() {
        this.destroy();
    }
}
```

**Comment by NetanelBasal** [comment]
Remove the ngOnDestroy, Akita does it for you.

**Comment by levitatejay** [comment]
They aren't being removed from the store without ngOnDestroy. That was my (bad) attempt at manually removing it.

**Comment by NetanelBasal** [comment]
You're welcome to join Akita's Gitter room. So it worked?

**Comment by levitatejay** [comment]
I've removed ngOnDestroy and it isn't working.

Sorry for the confusion - I've posted in Gitter now.

**Comment by NetanelBasal** [comment]
It's deleted, you just don't see it in the dev-tools, uploading a fix.
