### ISSUE TITLE
React example in the docs

### ISSUE THREAD

**Issue by markusgattol** [datorama/akita#138]
I'm excited to have stumbled across akita because I'm using rxjs, firebase and react a lot these days. I'm planning to move away from redux and redux-observable soon because of all the ceremony and boilerplate.

I do like the functional approach over class-based approaches better these days so I'm not yet convinced akita will be the right fit with react, firebase and rxjs. There's no blog post and/or statement on that, is there? Maybe some section in the docs I've missed?

What I found missing so far is a proper example in the docs that shows how to use akita with React instead of Angular, one that also elaborates on why you'd still be able to do functional programming going forward even if state management with akita is more or less class-based.

Overall I think reactive approaches, especially with state management, have a bright future because you can decouple applications in a very efficient way and still keep the codebase manageable.

**Comment by NetanelBasal** [comment]
https://engineering.datorama.com/oop-and-rxjs-managing-state-in-react-with-akita-de981e09307

**Comment by NetanelBasal** [comment]
You can also find a dedicated react playground in this repo.

**Comment by markusgattol** [comment]
Excellent, thanks for the pointer ;)
Closing...
