### ISSUE TITLE
Is there a way to remove the store from state completely

### ISSUE THREAD

**Issue by univerze** [datorama/akita#140]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I can remove all entities in a store or reset all the stores to the initial state but is there a way to completely remove the store (key and schema) from state upon navigating away from component (e.g ngDestroy)?

## Expected behavior
Remove everything from state for cleanup/reuse purposes.

## Minimal reproduction of the problem with instructions
n/a

## What is the motivation / use case for changing the behavior?
We use the state on entry creation and display pages and sometimes it's easier to reuse the store key or remove it completely to avoid confusion. In our case there would be a stepFormState, stepDetailsState, stepListState and stepFilterState in the store, but always using one at a time. This would aggregate more when we add similar stores to state making it less readable. Would be nice if we could delete the initial state object.

## Environment

<pre><code>
Angular version: latest

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:
</code></pre>

**Comment by NetanelBasal** [comment]
What about `store.destroy()`?

**Comment by NetanelBasal** [comment]
Another solution can be: https://netbasal.com/angular-services-do-not-have-to-be-singletons-ffa879e62082

**Comment by univerze** [comment]
Hi @NetanelBasal 
Thanks for the prompt reply.
I failed tom mention I'm using the EntityStore, there is no destroy function declared on that class. I have looked into the Store class too but I haven't found destroy() method on that either. The documentation also doesn't mention the destroy method. Am I missing something?

Also since Angular6 services are injected through the providedIn attribute of the injectable decorator
`@Injectable({ providedIn: 'root' })` so we don't use the NgModule providers. However I removed the providedIn attribute and added my Service to the Component providers array, but the store remained in the state after the component was destroyed.

Is there any other solution that comes to mind, or you see this as a new feature?

Thanks.

**Comment by NetanelBasal** [comment]
> However I removed the providedIn attribute and added my Service to the Component providers array, but the store remained in the state after the component was destroyed.

Doesn't sounds correct. Can you reproduce it on stackblitz? 

Regarding the destroy method, you can found it [here](https://github.com/datorama/akita/blob/master/akita/src/api/store.ts#L220). (EntityStore extends Store)

**Comment by univerze** [comment]
Well, this is embarrassing but I failed to check the Akita version and I was using 1.9.1, I have updated to the latest version which worked well. Do you mind updating the documentation with the destroy method, I think it's a great feature and will be useful for future users.

Thanks for your help.

**Comment by NetanelBasal** [comment]
Sure. You can also join Akita's Gitter channel. I'm also available there for any questions you have.
