### ISSUE TITLE
[Entity Store] setActive(null) gives tsc error when strictNullChecks is true

### ISSUE THREAD

**Issue by brianmcd** [datorama/akita#146]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When calling `setActive(null)` with `"strictNullChecks": true`, you get the following compile error:

```
error TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string | number | SetActiveOptions'.                  
  Type 'null' is not assignable to type 'string | number | SetActiveOptions'.
```

## Expected behavior

No compiler error.

## Minimal reproduction of the problem with instructions

* Set `"strictNullChecks": true` in your `tsconfig.json`.
* Attempt to call `setActive(null)` on an entity store.

## What is the motivation / use case for changing the behavior?
Should be able to enable all compiler checks and still use Akita.

## Environment

<pre><code>
Angular version: 7.1.4
 
For Tooling issues:
- Node version: 10.14.1 

Others:
TypeScript version: 3.1.6
</code></pre>

**Comment by brianmcd** [comment]
I found this PR which looks to have fixed this in the past, but the code has changed since this PR was merged: https://github.com/datorama/akita/pull/85.

**Comment by NetanelBasal** [comment]
Thanks for the report.
