### ISSUE TITLE
persistState - stores with names alike are getting mismatched

### ISSUE THREAD

**Issue by danzrou** [datorama/akita#149]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe
</code></pre>

## Current behavior
If you have 2 stores containing similar strings, they get mismatched on peristState initialization.
e.g.:

1. 'MyStore'
2. 'MyStoreUi'

It fails here:

```
const path = include.find(name => name.indexOf(currentStoreName) > -1);
 if (hasExclude && exclude.indexOf(currentStoreName) > -1 === true) {..,}
```

## Expected behavior
Names should be matched uniquely by name and not by containing string

## Environment

<pre><code>
Angular: 7.1.4
Akita: 1.23.3

**Comment by twittwer** [comment]
I would try to fix it since the problem came in by my feature request #59
