### ISSUE TITLE
Docs suggestion: Safer update calls to store (safer typing)

### ISSUE THREAD

**Issue by simeyla** [datorama/akita#153]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I've been struggling (thinking) for a while about how to make the safest 'reducers' to update the store.

It's very easy to get unnoticed errors like this:

```
updateUserName(name: string) {
    this.sessionStore.update(state => ({
      userDetails: {
        ...state.userDetails,
        name,
        importantPrropertyWeSpelledWrong: '123'    // ERROR - NOT CAUGHT BY COMPILER
      }
    }));
  }  
```

The above won't get caught by the compiler. There is a [quite interesting discussion](https://github.com/Microsoft/TypeScript/issues/12936) about 'exact types' in the typescript repo, with various solutions to this typescript typing problem.

After reading the whole thread, and deciding all the ideas in there were too convoluted I smacked myself on the forehead when I realized I could just do this:

```
updateUserName(name: string) {
    this.sessionStore.update(state => state = {
      userDetails: {
        ...state.userDetails,
        name,
        importantPrropertyWeSpelledWrong: '123'        //  !!!!! COMPILE ERROR !!!!!
      }
    ));
  }  
```

What's even cooler is you can now lose the extra `()` around `{ ...state }` because the compiler doesn't get confused anymore by the opening `{` directly after the `=>`.

## Expected behavior
Just provide this syntax as a 'tip' in the [documentation](https://netbasal.gitbook.io/akita/core-concepts/store) where you explain how to use `update` methods.

**Comment by NetanelBasal** [comment]
You are right; it's because of the `Partial` type. I will add a link to this thread in the docs. Thanks.
