### ISSUE TITLE
sortByOrder not working on its own

### ISSUE THREAD

**Issue by danzrou** [datorama/akita#155]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, is sortByOrder is provided without sortBy, it is ignored

## Expected behavior
Items should be sorted according to sortByOrder

## What is the motivation / use case for changing the behavior?
This is from query-entity:

```
if (sortBy) {
    let _sortBy: any = isFunction(sortBy) ? sortBy : compareValues(sortBy, sortByOrder);
    arr = arr.sort((a, b) => _sortBy(a, b, state));
  }
```

## Environment
<pre><code>
Angular version: 7.0.2
Akita: 1.23.3
</code></pre>

**Comment by NetanelBasal** [comment]
But you didn't provide a sortBy `ke`y, so how it should perform the sorting itself?

**Comment by NetanelBasal** [comment]
Check out the docs: https://netbasal.gitbook.io/akita/entity-store/entity-query/sort-by

**Comment by danzrou** [comment]
Sorry, for some reason I assumed sortByOrder would sort by ID by itself (don't mind me) :-)
