### ISSUE TITLE
Code Suggestion: Smarter filterNil operator

### ISSUE THREAD

**Issue by simeyla** [datorama/akita#157]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The `filterNil` operator is great, but I just switched on `strict` mode for typescript and wow do I have a lot of things to fix! That's my own fault, but when correcting my code surrounding `filterNil` I realized it would be very easy to **make a `filterNil` operator that removes the nullability of the input type**. 

Currently `filterNil` just passes through the original `T`, so you still have to check for nulls later.

## Suggested behavior

`FilterNil` should remove `undefined | null` from the input type.

My implementation of this is below.

The only changes are:

* The name (so it's easy to test)
* You have to do `pipe(filterNil())` and not `pipe(filterNil)`
* No change to the predicate runtime logic
* The 'fix' is all done by the added typescript type annotations.

      export const filterNil2 = <T>(): OperatorFunction<T | null | undefined, T> => (source) => {

                // note usage of 'value is T' type guard
                return source.pipe(filter((value): value is T => {

                      // same exact predicate from filterNil
                      return value !== null && typeof value !== 'undefined';

                }));
            };

Then you run it like this:

    export const filterNumbers = from([ 0, 42, 43, 44, undefined, 46 ]).pipe(
    
      tap(x => {

          x;  // typeof x here is number | undefined
      }),

      filterNil2(), 

      tap(x => 
      {
       
          x;   // typeof x is now number!

          if (!x) 
          {
             // x can only possibly be 0 here
             x;
          }

          if (typeof x === 'undefined' || x === null) 
          { 
              // this is unreachable (as it should be)
              const verifyUnreachable: never = x;
          } 
        
      }));

I don't see any obvious downside of this, except for revealing bugs. With the subtleties of typescript there can always be something, but I think this could be very useful. Would need to test in both strict and non-strict mode.

**Comment by simeyla** [comment]
I was basing it off something similar I had already done, but I looks like
you can do this:

        export const filterNil3 = <T>(source: Observable<T | undefined |
null>) => {

            return source.pipe(filter((value): value is T => {

                // same exact predicate from filterNil
                return value !== null && typeof value !== 'undefined';

            }));
        };

I think that should work the same way you have it before.

Personally I prefer always using '()' in operators, but I guess that's
personal preference/
At the very least VSCode shows 'filterNil' in a different color to 'filter'
or 'map', and I like things to look more consistent.

**Comment by simeyla** [comment]
1. Will try to do soon. I have literally hundreds and hundreds of null /
type fixes to do now I enabled 'strict'. It's amazing what it is catching,
but it takes a lot of time.

2. I really think it should be fine. I think it's actually more likely to
*fix* something in somebody's code - if they had been ignoring a warnings.
It could potentially reveal some impossible code paths, but that would be a
good thing. So it's not really 'breaking', more of a 'fixing' change :-)
Would definitely need to be mentioned in release documentation.

Maybe you should try it first with some bigger project to confirm no
unexpected impacts.
It is really nice though that 'filterNil' can actually now completely make
'nil' disappear :-)

**Comment by NetanelBasal** [comment]
I added it. It will be released with v2, next week.

**Comment by NetanelBasal** [comment]
Released in v2.0.0

**Comment by xealot** [comment]
I'm using Akita `@datorama/akita@4.8.1` and found that the `filterNil` utility still doesn't indicate that it removes null and undefined from the possible returns.

I corrected it using module augmentation, but it seems like it should have been included in this issue.

```ts
declare module "@datorama/akita" {
    type Diff<T, U> = T extends U ? never : T; // Remove types from T that are assignable to U
    export const filterNil: <T>(source: Observable<T>) => Observable<Diff<T, null | undefined>>;
}
```

**Comment by NetanelBasal** [comment]
The current version works for me. Can you show a stackblitz example, please?

**Comment by xealot** [comment]
I couldn't use Stackblitz because you get no control over `tsconfig`, at least not that I was able to see. So I did it in codesandbox.io, same diff but can enable strict mode which is obviously a requirement to see `null` differentiated.

https://codesandbox.io/embed/keen-sun-2zork

**Comment by NetanelBasal** [comment]
Why it infers the type as `any`?

![image](https://user-images.githubusercontent.com/6745730/62374334-73665280-b544-11e9-908d-1fbfe23fd591.png)

**Comment by xealot** [comment]
I think you have to say "Open in CodeSandbox" on the left to get it to actually run TS. I'm not sure, I'm not an expert at these tools.

![image](https://user-images.githubusercontent.com/189873/62374559-39785a80-b50a-11e9-9560-3a4f3a3cf9e3.png)

**Comment by NetanelBasal** [comment]
Ok, you're right. Do you want to create a PR, or I will add it?

**Comment by xealot** [comment]
Is my solution good for you?

**Comment by NetanelBasal** [comment]
Yes, but it needs to be done in the source code without the declare module thing.

**Comment by NetanelBasal** [comment]
```ts
type Diff<T, U> = T extends U ? never : T; // Remove types from T that are assignable to U

/**
 * @example
 *
 * query.selectEntity(2).pipe(filterNil)
 */
export const filterNil = <T>(source: Observable<Diff<T, null | undefined>| undefined | null>) => source.pipe(filter((value): value is T => value !== null && typeof value !== 'undefined'));
```

**Comment by NetanelBasal** [comment]
Add the `Diff` type to the types file.

**Comment by xealot** [comment]
Requests updates applied.
