### ISSUE TITLE
Complete mark fails due to trackBy

### ISSUE THREAD

**Issue by GerardvDorth** [datorama/akita#158]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Demo issue only. Add 2 tasks. Mark the top task complete. Filter Active tasks. The active task is marked completed.

## Expected behavior
Add 2 tasks. Mark the top task complete. Filter Active tasks. The active task should not be marked completed.

## Minimal reproduction of the problem with instructions
See above. The problem is gone if TrackBy is not ussed in the *ngFor loop

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Fixed. Thanks.
