### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by ipostu** [datorama/akita#16]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
On the documentation website, for the version 1.2.0 on the Blog Post section the article with Normalized data does not appear.

https://netbasal.gitbook.io/akita/entity-store/blog-posts

## Expected behavior
The article with Normalized data should appear also on the newer version. 
This is how it looks like in v1.1.0 
https://netbasal.gitbook.io/akita/v/1.1.0/entity-store/blog-posts

**Comment by NetanelBasal** [comment]
Thanks! Done. 😃
