### ISSUE TITLE
docs issues

### ISSUE THREAD

**Issue by paxapy** [datorama/akita#160]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

### 1
https://netbasal.gitbook.io/akita/core-concepts/the-query
## Current behavior

```
@Injectable()
export class SessionQuery extends Query<Session> {

  constructor(protected store: SessionStore) {
    super(store);
  }

}
```

## Expected behavior

I belive it should be `SessionState` type, not `Session`, like this:

`export class SessionQuery extends Query<SessionState>`

### 2
https://netbasal.gitbook.io/akita/core-concepts/store
## Current behavior
```
@StoreConfig({ name: 'session' })
export class SessionStore extends Store<SessionState> {
  constructor() {
    super(createInitialState());
  }
}
```
## Expected behavior
I think it's worth to wrap store class with @Injectable() decorator it order to use with angular, otherwise it's not clear how to deal with it

### 3 
https://netbasal.gitbook.io/akita/core-concepts/store
## Current behavior
```
export function createInitialState(): SessionState {
  return {
    token: '',
    userDetails: null
  };
}
```
## Expected behavior
probably worth to use that `createSession` function from models (previous page), to make docs consecutive and understandable

### 4
https://netbasal.gitbook.io/akita/core-concepts/store
## Current behavior
`update(newStateFn: Partial<S> | (state: Readonly<S>) => S`
## Expected behavior
looks like redundant parentheses here:
`update(newStateFn: Partial<S> | state: Readonly<S>) => S`

## What is the motivation / use case for changing the behavior?

to make things clear

I also think, that it worth to provide additional info on how to configure it up with different frameworks. I'm using angular, and so it looks like it's only few steps missing...
anyways, you have a great docs, thanks
i just want to make it better ^^.

**Comment by NetanelBasal** [comment]
Thanks, fixed. You're welcome to join Akita's Gitter channel for more feedback.
