### ISSUE TITLE
Dynamic stores can not be created

### ISSUE THREAD

**Issue by heinerlamprecht** [datorama/akita#162]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
According to the documentation, it shall be possible to dynamically create a store.  Doing so results in an exception:

<code>
core.js:15714 ERROR TypeError: Cannot read property 'resettable' of undefined
    at TrackStore.push.../../node_modules/@datorama/akita/fesm5/datorama-akita.js.Store.isRessetable (datorama-akita.js:1088)
    at TrackStore.Store (datorama-akita.js:792)
    at TrackStore.EntityStore [as constructor] (datorama-akita.js:1209)
   ...
</code>

## Expected behavior
Store should be created without any error message.

## Minimal reproduction of the problem with instructions
See current documentation.

**Comment by NetanelBasal** [comment]
Can you reproduce in stackblitz, please?

**Comment by heinerlamprecht** [comment]
Wow, that was fast 😁

Thanks for the fix, now it work as expected.
