### ISSUE TITLE
A shortcut method for updating UI state of the EntityStore

### ISSUE THREAD

**Issue by DmitryEfimenko** [datorama/akita#163]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Often I find myself following the pattern shown in multiple Akita articles - expanding my EntityStore with a `ui` state:
```ts
export interface ProductsState extends EntityState<Product> {
  ui: UI;
}
export interface UI {
  // ... some other props that go along with the data in the store
}
```
Whenever that happens (very often) I also create a convinience method that updates that specific portion of the store:
```ts
@Injectable()
@StoreConfig({ name: 'products' })
export class ProductsStore extends EntityStore<ProductsState, Product> {
  constructor() {
    super(createInitialState());
  }

  updateUi(ui: Partial<UI>) {
    this.updateRoot(s => {
      const newUi = { ...s.ui, ...ui };
      const newState = { ...s, ui: newUi };
      return newState;
    });
  }
}
```

## Expected behavior/Motivation
Akita already has examples of similar "convinience" methods: `setActive()`, `setError()`.
`updateUi()` follows this pattern. I suggest we include the functionality I write over and over into Akita.

We'd need to add optional type to `EntityState`. I see one issue there though. It already has second optional generic type: `EntityState<E = any, ErrorT = any>`.
Making the `UiT` a third type in the list is ugly. I usually don't use the ErrorT type.
Making it a second type by pushing the `ErrorT` to the third place would make it a breaking change.

@NetanelBasal  What do you think about the idea in general and if you see it useful, how would you suggest to proceed?

**Comment by NetanelBasal** [comment]
This is a helpful suggestion, but the problem is that it will conflict with the pattern describes [here](https://netbasal.gitbook.io/akita/entity-store/ui-state#entity-ui-state).

**Comment by DmitryEfimenko** [comment]
hmm, I see how it could be confusing.
My suggestion does not appear all that good to me anymore. It's great that Akita provides flexibility to basically do whatever you want with the store class. Trying to include a bunch of conventions might hurt Akita's flexibility in this case.
Closing.
