### ISSUE TITLE
Add TSDoc annotations to sources

### ISSUE THREAD

**Issue by mikerobi** [datorama/akita#164]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Add TSDoc annotations to the source code
Add TSDoc comments to provide a way to generate a centralized and always up to date documentation of the Akita api. Adding function and input/output descriptions would be a good start.  Ultimately it would be nice to have comprehensive examples integrated into the API docs.

**Comment by mikerobi** [comment]
> 
> 
> Do you want to contribute and create a PR, or leave it for us?

I'm just making a suggestion.  I'm not yet familiar enough with rxjs and Akita to make a contribution.

I have no expectations of you, you are giving me awesome software for free.  I'm just suggesting a way to make it more awesome.

**Comment by NetanelBasal** [comment]
https://engineering.datorama.com/you-asked-for-it-we-listened-and-now-its-here-akita-v3-92740d0d72e4
