### ISSUE TITLE
CreateOrReplace / Upsert with collections

### ISSUE THREAD

**Issue by levitatejay** [datorama/akita#165]
Feature Request:

I think it would be convenient if the CreateOrReplace & Upsert methods also accepted arrays and/or HashMaps of entities. I'm often writing for loops to do this when doing a refresh or when a store updates a subset of another store.

The tricky part is that you can't always rely on the ID being named 'id'...

```
createOrReplaceFromArray(properties: Property[]) {
    if (!!properties) {
      properties.forEach(property => {
        this.createOrReplace(property.id, property);
      });
    }
  }

  createOrReplaceFromSet(properties: HashMap<Property>) {
    if (!!properties) {
      Object.keys(properties).forEach(normalizedProperty => {
        const property = properties[normalizedProperty];
        this.createOrReplace(property.id, property);
      });
    }
  }
```

**Comment by NetanelBasal** [comment]
We deprecate `createOrReplace` in favor of `upsert`. Will consider your suggestion. Thanks.

**Comment by NetanelBasal** [comment]
https://engineering.datorama.com/you-asked-for-it-we-listened-and-now-its-here-akita-v3-92740d0d72e4

**Comment by brgrz** [comment]
Why was this closed? please tell us how do you use upsert() with a collection/array of items?

**Comment by brgrz** [comment]
Reopened https://github.com/datorama/akita/issues/215
