### ISSUE TITLE
Query triggered with new and old state + confusing actions in redux devtools

### ISSUE THREAD

**Issue by david-bulte** [datorama/akita#166]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Here's a snippet from my AuthStore:

```
  @action({ type: 'setAccessTokenInfo' })
  setAccessTokenInfo(accessTokenInfo: TokenInfo) {
    this.update({accessTokenInfo, loadingAccessToken: false});
  }

  @action({ type: 'setLoadingUserContexts' })
  setLoadingUserContexts(loadingUserContexts: boolean) {
    this.update({loadingUserContexts});
  }

```

In my code I'm calling setAccessTokenInfo() after having received such a token from a Firebase event. Elsewhere I'm listening whether an AccessTokenInfo has been set via listening to a dedicated Query. Whenever the query returns an AccessTokenInfo, I start fetching UserContexts and set the "LoadingUserContexts" flag to true. Here's some code:

```
    ...

    this.authQuery.accessTokenInfo$.pipe(
      filter(accessTokenInfo => !!accessTokenInfo),
      switchMap(accessTokenInfo => {
        if (this.authQuery.hasUserContexts()) {
          return NEVER;
        } else {
          return this.fetchUserContexts();
        }
      })
    ).subscribe();

  ...

  private fetchUserContexts() {
    this.authStore.setLoadingUserContexts(true);
    return this.userContextService.fetchUserContexts().pipe(
      tap(userContexts => {
        ... 
      })
    );
  }



```
There's some strange things going on.

First when I check the Redux Devtools, I notice that the "setAccessTokenInfo" action is missing, and the "setLoadingUserContexts" is changing both the AccessTokenInfo and the LoadingUserContexts!

Here's a screenshot:

![akita-devtools](https://user-images.githubusercontent.com/4194465/52481597-3a5dae80-2baf-11e9-898b-e727082e0071.PNG)

Also, what are the "Set State" actions?

Finally, also weird: after having called AuthStore.setLoadingUserContexts, the Query is triggered twice, once with the "true" and next time with "false". Here's that query:

`  isLoadingUserContexts$ = this.select(store => {
    console.log("===luc===", store.loadingUserContexts);
    return store.loadingUserContexts;
  }).pipe(share());
`

## Expected behavior

After having called setAccessTokenInfo, there should be a separate action in the Redux Devtools. 

After having called setLoadingUserContexts with value "true", the corresponding query should be triggerd only with value "true".

## Environment

<pre><code>
Angular version: 7.2.4
Akita version: ^2.1.1

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Can you reproduce it, please? Here is a live seed. https://stackblitz.com/github/rlminqqq

**Comment by david-bulte** [comment]
Here you go: https://stackblitz.com/edit/github-9u37yb

**Comment by NetanelBasal** [comment]
It's because your code was synchronous, so every you change the value on the same tick which leads to your result. Here's a sample that works:

```ts

import { Injectable, NgZone } from '@angular/core';
import { NEVER, of, throwError, timer } from 'rxjs';
import { catchError, filter, switchMap, tap, map } from 'rxjs/operators';
import { AuthQuery } from './auth.query';
import { AuthStore } from './auth.store';

@Injectable({ providedIn: 'root' })
export class AuthService {
  constructor(private authStore: AuthStore, private authQuery: AuthQuery) {}

  setup() {
    this.mimicFirebase(user => {
      if (user && !this.authQuery.hasValidAccessToken()) {
        user.getIdTokenResult().then(res => {
          const accessToken = {
            token: res.token,
            expirationTime: res.expirationTime
          };
          this.authStore.setAccessTokenInfo(accessToken);
        });
      }
    });

    this.authQuery.accessTokenInfo$
      .pipe(
        filter(accessTokenInfo => !!accessTokenInfo),
        switchMap(accessTokenInfo => {
          if (this.authQuery.hasUserContexts()) {
            return NEVER;
          } else {
            return this.fetchUserContexts();
          }
        })
      )
      .subscribe();
  }

  private mimicFirebase(callback) {
    const tokenInfo = {
      token: '123',
      expirationTime: 'notimportantnow'
    };
    const user = {
      getIdTokenResult: () => {
        return of(tokenInfo).toPromise();
      }
    };
    setTimeout(() => {
      callback(user);
    }, 1000);
  }

  private fetchUserContexts() {
    setTimeout(() => {
      this.authStore.setLoadingUserContexts(true);
    });

    return timer(10).pipe(
      switchMap(() => {
        return of([{ name: 1 }, { name: 2 }]).pipe(
          tap(userContexts => {
            this.authStore.setUserContexts(userContexts as any);
          })
        );
      })
    );
  }
}

```
