### ISSUE TITLE
Loading and Error shouldn't be persisted to localstorage

### ISSUE THREAD

**Issue by DazSanchez** [datorama/akita#167]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Using persisState to save the states to local storage also saves the error and loading state, which maybe is not required sometimes, I can't set this within "include" array

## Expected behavior

Choose if those properties should be saved within local storage.

## Minimal reproduction of the problem with instructions
main.ts
```ts
persistState({
  key: "auth",
  include: ["auth"],
});
```
auth.store.ts
```ts
export interface AuthState {
  token: string | null;
  username: string | null;
}
```

local storage
```ts
{
  "auth":{
    "token":"...",
    "username":"lorem@gmail.com",
    "loading":false,
    "error":null
  }
}
```

## What is the motivation / use case for changing the behavior?

Saving this state could be optional because is not something should be persisted

## Environment

<pre><code>
Angular version: 7.0.4

Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [x ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [x ] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [x ] IE version XX
- [x ] Edge version XX
 
For Tooling issues:
- Node version: 11.2.0 
- Platform: Windows  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Thanks, we'll consider the suggestion.

**Comment by NetanelBasal** [comment]
This is a problem because the `loading` state of an EntityStore is `true` by default.

**Comment by visurel** [comment]
@NetanelBasal What if we would set `loading: false` when initializing the Store? Would this work? Having the loading and error persisted can sometimes lead to weird edge-cases where the loading might be stuck. Any way we could specify to not persist those at all?

**Comment by jongbonga** [comment]
> This is a problem because the `loading` state of an EntityStore is `true` by default.

Hey @NetanelBasal is there a way to change the default value to false?

**Comment by NetanelBasal** [comment]
No

**Comment by jongbonga** [comment]
Thanks for the reply @NetanelBasal , can you please have a look to my question [here](https://github.com/datorama/akita/discussions/800#discussion-3901824)

**Comment by MatkoMilic** [comment]
> 

There should be one :(. How can I have default loading as true while nothing is loading :(
