### ISSUE TITLE
Missing curly braces in docs of StateHistoryEntityPlugin

### ISSUE THREAD

**Issue by twittwer** [datorama/akita#168]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
https://netbasal.gitbook.io/akita/plugins/state-history#options-1
In the code block the curly braces around the options of the StateHistoryEntityPlugin are missing.
```
this.stateHistory = new StateHistoryEntityPlugin<Todo>(this.todosQuery);
this.stateHistory = new StateHistoryEntityPlugin<Todo>(this.todosQuery, entityIds: 1);
this.stateHistory = new StateHistoryEntityPlugin<Todo>(this.todosQuery, entityIds: [1,2]);
```

## Expected behavior
```
this.stateHistory = new StateHistoryEntityPlugin<Todo>(this.todosQuery);
this.stateHistory = new StateHistoryEntityPlugin<Todo>(this.todosQuery, { entityIds: 1 });
this.stateHistory = new StateHistoryEntityPlugin<Todo>(this.todosQuery, { entityIds: [1, 2] });
this.stateHistory = new StateHistoryEntityPlugin<Todo>(this.todosQuery, { maxAge: 3 });
```
---
Is there a way to submit PRs to the docs, so one can suggest changes directly?

**Comment by NetanelBasal** [comment]
No. Fixed. Thanks :)
