### ISSUE TITLE
Asynchronous initial state

### ISSUE THREAD

**Issue by user753** [datorama/akita#171]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Store needs an initialState

## Expected behavior
It should be possible to delay store initialization

## Minimal reproduction of the problem with instructions
For example I have this state 
```
interface State {
   config: Config
}
```
and I need to get config from the server to initialize it

**Comment by NetanelBasal** [comment]
Can you explain more what is your use-case, please?

**Comment by user753** [comment]
The app have a user config that is stored on server. When an user open the app I what to initialize my `AppStore` but first I need to load a config from server
```
interface State {
   config: Config
}
@StoreConfig({ name: 'app' })
export class AppStore extends Store<State> {
  constructor() {
    super(???);
  }
}
```
I can use something like this
```
interface State {
   config?: Config
}
```
But then I have to use `if(state.config) {const foo = state.config.foo}` everywhere and also undefined `config` doesn't make much sense because application cannot exists without config object.

**Comment by NetanelBasal** [comment]
It's not related to Akita. You can learn how to load data before the application starts - https://devblog.dymel.pl/2017/10/17/angular-preload/

**Comment by user753** [comment]
@NetanelBasal But I need this after user log on. It isn't about Angular. 
The question is - how can I initialize store asynchronously?

**Comment by NetanelBasal** [comment]
If you need to add protection, create a `selectConfig` selector and protect it with `filterNil`.

**Comment by ng-alynasser** [comment]
@NetanelBasal I think he was asking for something like init$ lifecycle hook in NgRx which he could use in order to execute some code after the initial state has been added.

**Comment by NetanelBasal** [comment]
I'm not sure what is the use case.

**Comment by ng-alynasser** [comment]
Here's a simple use case; an auth store with an initial state of null token, there's an auth guard that depends on whether the user is logged in or not, and it gets that info from auth query which always returns  the initial state at the start of the app, although the token is in local storage. i could use init$ to get the user info from that token through a request, and update the state.

**Comment by ng-alynasser** [comment]
`@Injectable({ providedIn: 'root' })
@StoreConfig({ name: 'auth', resettable: true })
export class AuthStore extends Store<AuthState> {

  constructor() {
    super(createInitialState());
  }
}`

It'd be no issue if I could pass an observable or a promise besides a plain object in the super method when the state is initialized.

**Comment by NetanelBasal** [comment]
Are you using localstorage?

**Comment by ng-alynasser** [comment]
Yup, I'm.

**Comment by NetanelBasal** [comment]
So update the initial state to:

```ts
function createInitialState() {
  token: localstorage.getItem('token') || null
}
```

**Comment by ng-alynasser** [comment]
```
export interface AuthState {
  token: string;
  user: User;
  isLoggedIn: boolean,
}

export function createInitialState() {
  return {
    token: null,
    user: null,
    isLoggedIn: false,
  };
}
```

I still need to make sure of other info about the user such as permissions and stuff, so there's noway to re-get the user without a request.

**Comment by ng-alynasser** [comment]
Like what if a permission got taken away from a user, and the user routed to an guarded url ? Cannot depend that much on the existence of token in local storage.

**Comment by ng-alynasser** [comment]
export async function createInitialState() {
  return {
    token: null,
    user: await this.getUserByToken(),
    isLoggedIn: false,
  };
}

It'd be no issue if I could pass an observable or a promise instead of plain object in the super method.

**Comment by NetanelBasal** [comment]
But then you can be in a race condition situation. Some components can update the store before the initial state was initialized.

**Comment by ng-alynasser** [comment]
Yeah, that's right. So I worked around and implement that async logic inside the auth guard and got rid of the auth query.

**Comment by ng-alynasser** [comment]
```
canActivate(): Observable<boolean> | Promise<boolean> | boolean {
    this.authQuery.isLoggedIn(); // Always return false!
    return this.authService.getUserByToken()
      .pipe(
        map(user => {
          if (user) {
            return true;
          } else {
            this.router.navigateByUrl('/auth/login');
            return false;
          }
        }),
      );
  }
```
