### ISSUE TITLE
Does Akita really support other storage options than LocalStorage?

### ISSUE THREAD

**Issue by StephanMeijer** [datorama/akita#172]
https://github.com/datorama/akita/blob/master/akita/src/enhancers/persist-state.ts#L31

```
// ...
const notBs = typeof localStorage === 'undefined';
// ...
export function persistState(params?: Partial<PersistStateParams>) {
  if (notBs) return;

  const defaults: PersistStateParams = {
    key: 'AkitaStores',
    storage: localStorage,
// ...
```

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Not sure. What happens if localStorage is unavailable, but other methods are?

## Expected behavior

Support multiple storage options by interface.

**Comment by NetanelBasal** [comment]
I'm not sure I understand this PR. If you want different storage, you can pass it in the options. 

https://github.com/datorama/akita/blob/b07b736b3d501d48625a17eb38f794f57145b2dd/akita/src/enhancers/persist-state.ts#L47

**Comment by StephanMeijer** [comment]
And what happens if I do that and `typeof localStorage === 'undefined';`?

**Comment by NetanelBasal** [comment]
It means that you're not in a browser environment and do nothing. (for example, SSR)
