### ISSUE TITLE
Possibility for implementing isolated persistent storage per app user

### ISSUE THREAD

**Issue by StephanMeijer** [datorama/akita#174]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

1 persistent storage entry for all users in app;

## Wanted behavior

- User logs in, gets assigned an isolated, persistent localstorage-entry
- One persistent localstorage entry for all users for things like the last loggedin user-credentials

## What is the motivation / use case for changing the behavior?

Some data should not interfere because it is dependent on the specific user logged in.

**Comment by NetanelBasal** [comment]
I'm not sure what is the use case. Can you expand more, please?

**Comment by StephanMeijer** [comment]
For the development of our application, we need to save some details, such as PGP Keypairs per specific user. It is just a `Store`, not `EntityStore`, but when we switch users, the store must select another keypair for the specific user.

So some data is specific to a specific user, and another user should get other data. I want to switch the storage Key based on the user being logged in, and when another user logges in, it needs to refresh all data from localstorage or another storage backend.

**Comment by StephanMeijer** [comment]
And besides that, different stores have different behaviors in our application. So there are still stores which need to be globally accessible by all users.

**Comment by NetanelBasal** [comment]
I'm not sure that I understand it correctly. When a user logged in, the data in the stores should be relevant only for this specific user, no? So, when he logs out, this data should be erased anyway. No?

**Comment by StephanMeijer** [comment]
_I'm not sure that I understand it correctly. When a user logged in, the data in the stores should be relevant only for this specific user, no?_ **correct** 

_So, when he logs out, this data should be erased anyway. No?_ **User A logges out, data should remain in Storage backend. User B logges in, data should be get from the Storage backend specificly for user B.**

**Comment by NetanelBasal** [comment]
Two questions:
1. When you say "Storage backend", did you mean the server?
2. "User B logs in, data should be getting from the Storage backend specifically for user B" - what happens to user's A data?

**Comment by StephanMeijer** [comment]
1. Storage Backend as in LocalStorage or IndexedDB
2. It remains, but it shouldn't be touched or loaded until User A logs back in

**Comment by NetanelBasal** [comment]
What you described it's a security vulnerability. It means that every user can see the other users data by inspecting the LocalStorage or IndexedDB.

**Comment by StephanMeijer** [comment]
It'll probably only be encrypted data, but I understand your view. But it might be the only way if you don't want to upload data to an API.

**Comment by NetanelBasal** [comment]
I don't think we're going to implement this soon. It's a rare request. But, you could apply this yourself, it's not that complicated.

**Comment by NetanelBasal** [comment]
Sorry, it will not be implemented. I am closing the issue.
