### ISSUE TITLE
Pagination with search filtering

### ISSUE THREAD

**Issue by stephencarr** [datorama/akita#176]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

When using the pagination plugin I want to be able to apply a text search filter which will reduce the result set to narrow in on the search results. However, if I am on say - page 4 of the unfiltered results and then apply my search the paginator is still asking for page 4 with the additional search params applied. I want to be able to reset the page back to page 1 whenever a search is applied. I can force the request to ask for page 1 but the paginator still thinks its on page 4 and produces an error.

**Comment by NetanelBasal** [comment]
You can set the page manually. https://github.com/datorama/akita/blob/master/akita/src/plugins/paginator/paginator-plugin.ts#L195

**Comment by stephencarr** [comment]
For some reason I didn't see that / couldn't find it. Thanks 🌮

**Comment by owolfy** [comment]
> You can set the page manually. https://github.com/datorama/akita/blob/master/akita/src/plugins/paginator/paginator-plugin.ts#L195

It's a dead link. Can you please post a new one?
Thanks

**Comment by NetanelBasal** [comment]
https://github.com/datorama/akita/blob/master/libs/akita/src/lib/plugins/paginator/paginatorPlugin.ts#L198
