### ISSUE TITLE
Transaction on asynchronous updates

### ISSUE THREAD

**Issue by jogelin** [datorama/akita#178]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I am calling an api and receive a list of entities, I would like to map, by using rxjs, each entity (or do something more complex). Then I am doing an `upsert` on each but I don't want to have a `tick` each time. Transaction would be great but it seems that its not working on asynchronous updates...which is normal.

```javascript
@Injectable({ providedIn: 'root' })
export class EntitiesService {
  constructor(private entitiesDataService: EntitiesDataService, private entitiesStore: EntitiesStore) {
  }

  @transaction()
  getEntities(): void {
    this.entitiesStore.setLoading(true);

    this.entitiesDataService
      .getEntities()
      .pipe(
        switchMap(entities => from(entities)),
        map(entity => ({...entity, date: DateTime.fromISO(entity.date)}))
        finalize(() => this.entitiesStore.setLoading(false))
      )
      .subscribe(
        plan => this.entitiesStore.upsert(entity.id, entity),
        e => log.error(e)
      );
  }
}

```

## Expected behavior
Have the possibility to have a transaction on async call.

## Dirty fix 

```
this.entityQuery.selectAll().pipe(debounceTime(1));
```

It could be fixed if something exist like #165 but I like the rxjs way instead of looping again and again

**Comment by NetanelBasal** [comment]
Store operations are synchronous. I'm not sure why do you need the `from` operator here.

```ts

export class EntitiesService {
  constructor(private entitiesDataService: EntitiesDataService, private entitiesStore: EntitiesStore) {
  }

  getEntities(): void {
    this.entitiesStore.setLoading(true);

    this.entitiesDataService.getEntities()
      .pipe(
        finalize(() => this.entitiesStore.setLoading(false))
      )
      .subscribe(entities => this.updateStore());
  }

  @transaction
  updateStore(entities) {
    for(const entity of entities) {
      entity.date = DateTime.fromISO(entity.date);
      this.entitiesStore.upsert(entity.id, entity); // btw, in v3 you can pass an array
    }
  }
}
```

**Comment by jogelin** [comment]
Thx @NetanelBasal I updated my code in this way. 

I am just using from(list) everywhere for performance reasons... but in this case it doesn't matter... indeed I have to do all lot of business codes in my frontend because apis are shitty and if I use for loop each time I want to make a map/filter/...aie... ;)
