### ISSUE TITLE
Issue when building angular with buildOptimizer on

### ISSUE THREAD

**Issue by Aaltuj** [datorama/akita#179]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report?  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
After building an Angular application with buildOptimizer=true the running application throws the following error:

```
ERROR Error: Uncaught (in promise): ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new AppStore (cs-performance-manager.js.pre-build-optimizer.js:2809)
    at factory (cs-performance-manager.js.pre-build-optimizer.js:2818)
    at core.js.pre-build-optimizer.js:27000
    at tn (core.js.pre-build-optimizer.js:26943)
    at en (core.js.pre-build-optimizer.js:26902)
    at fn.get (core.js.pre-build-optimizer.js:27995)
    at core.js.pre-build-optimizer.js:2169
    at G (core.js.pre-build-optimizer.js:2169)
    at factory (cs-performance-manager.js.pre-build-optimizer.js:4735)
    at core.js.pre-build-optimizer.js:27000
    at tn (core.js.pre-build-optimizer.js:26943)
    at en (core.js.pre-build-optimizer.js:26902)
    at fn.get (core.js.pre-build-optimizer.js:27995)
    at en (core.js.pre-build-optimizer.js:26907)
    at core.js.pre-build-optimizer.js:26977
    at new v (zone-error.js.pre-build-optimizer.js:100)
    at M (zone.js.pre-build-optimizer.js:831)
    at M (zone.js.pre-build-optimizer.js:788)
    at zone.js.pre-build-optimizer.js:892
    at t.invokeTask (zone.js.pre-build-optimizer.js:423)
    at Object.onInvokeTask (core.js.pre-build-optimizer.js:21825)
    at t.invokeTask (zone.js.pre-build-optimizer.js:422)
    at e.runTask (zone.js.pre-build-optimizer.js:195)
    at g (zone.js.pre-build-optimizer.js:601)
```

The error in the application occurs here:
``` javascript
/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes,extraRequire,uselessCode} checked by tsc
 */
/**
 * @return {?}
 */
function createInitialState() {
    return {
        isImpersonated: false,
        canAccessAdmin: false,
        isDebugUser: false,
        activeModule: null,
        activeSection: null,
        navbarResultParams: null,
        allowNegativeDataEntry: false
    };
}
let AppStore = class AppStore extends Store {
    constructor() {   // <--- error line number: 2809
        super(createInitialState());
    }
};
```

It appears that the `this` used in the constructor in the Store class is the cause of the error when buildOptimizer is turned on

``` typescript
export class Store<S> {
  private store: BehaviorSubject<Readonly<S>>;
  private storeValue: S;
  private inTransaction = false;
  private _initialState: S;
  protected cache: StoreCache = {
    active: new BehaviorSubject<boolean>(false),
    ttl: null
  };

  constructor(initialState: Partial<S>, protected options: Partial<StoreConfigOptions> = {}) {
    this.onInit(initialState as S); // <---- cause of the issue??
  }

```

When buildOptimizer is turned off the application start en runs as expected.

## Expected behavior
Compile with following settings:

``` json
 "mock-dev-packages-prod": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.mock.ts"
                }
              ],
              "assets": [
                "src/favicon.ico",
                "src/assets"
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": false,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "preserveSymlinks": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
```

## Minimal reproduction of the problem with instructions

create a store in a Angular application with dependencies:
    "@datorama/akita": "~3.0.0"
    "@angular/animations": "~7.2.8",
    "@angular/common": "~7.2.8",
    "@angular/compiler": "~7.2.8",
    "@angular/core": "~7.2.8",
    "@angular/forms": "~7.2.8",
    "@angular/http": "~7.2.8",
    "@angular/platform-browser": "~7.2.8",
    "@angular/platform-browser-dynamic": "~7.2.8",
    "@angular/router": "~7.2.8",
devDependencies:
    "@angular-devkit/build-angular": "~0.13.5",
    "@angular-devkit/build-ng-packagr": "~0.13.5",
    "@angular/cli": "~7.3.5",
    "@angular/compiler-cli": "~7.2.8",

## Environment

<pre><code>
Angular version: 7.2.8

Browser:
- [ x] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [x ] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [x ] IE version XX
- [x ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.3
- Platform:   Windows 
</code></pre>

**Comment by NetanelBasal** [comment]
Thanks for the report. Can you create a simple repo that reproduces the error? We are not working with this option.

**Comment by Aaltuj** [comment]
@NetanelBasal thanks for your quick response. While creating the repro, i've found the cause:
The target was es2015 and not es5 while building the application. The internal published lib that was used by the application was using the fesm2015 build.
### FESM2015 usedLib.js
``` javascript
function createInitialState() {
    return {
        isImpersonated: false,
        canAccessAdmin: false,
        isDebugUser: false,
        activeModule: null,
        activeSection: null,
        navbarResultParams: null,
        allowNegativeDataEntry: false
    };
}
let AppStore = class AppStore extends Store {
    constructor() {
        super(createInitialState());
    }
};
```
### FESM5 usedLib.js

``` javascript
function createInitialState() {
    return {
        isImpersonated: false,
        canAccessAdmin: false,
        isDebugUser: false,
        activeModule: null,
        activeSection: null,
        navbarResultParams: null,
        allowNegativeDataEntry: false
    };
}
var AppStore = /** @class */ (function (_super) {
    __extends(AppStore, _super);  
    function AppStore() {
        return _super.call(this, createInitialState()) || this;
    }
    AppStore.decorators = [
        { type: Injectable, args: [{ providedIn: 'root' },] }
    ];
    /** @nocollapse */
    AppStore.ctorParameters = function () { return []; };
    /** @nocollapse */ AppStore.ngInjectableDef = defineInjectable({ factory: function AppStore_Factory() { return new AppStore(); }, token: AppStore, providedIn: "root" });
    AppStore = __decorate([
        StoreConfig({ name: 'app' }),
        __metadata("design:paramtypes", [])
    ], AppStore);
    return AppStore;
}(Store));
```
I've added the repro to this comment. 
[akita-repro.zip](https://github.com/datorama/akita/files/2962136/akita-repro.zip)

**Comment by NetanelBasal** [comment]
Why is the source code compiled to FESM2015?

**Comment by NetanelBasal** [comment]
Changing the `target` value in tsconfig to "es5" solves the issue.

**Comment by NetanelBasal** [comment]
It's not an Akita issue. See https://github.com/angular/angular-cli/issues/10658

**Comment by Aaltuj** [comment]
thanks for following up. You are correct by stating that the target build should be `es5`. That's what i also found out when i mentioned that i found the cause. I only posted the repro to make you aware that stuff is breaking when using `es2015` and akita. But as you stated it's not a akita problem but a buildOptimizer problem so no issue here ;) 

keep up the good work, 🧡 akita
