### ISSUE TITLE
"strict" compiler option compatibility

### ISSUE THREAD

**Issue by mxth** [datorama/akita#18]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Errors when compiling with option `"strict": true`

`node_modules/@datorama/akita/src/api/query-config.d.ts(2,35): error TS7006: Parameter 'a' implicitly has an 'any' type.
node_modules/@datorama/akita/src/api/query-config.d.ts(2,38): error TS7006: Parameter 'b' implicitly has an 'any' type.
node_modules/@datorama/akita/src/enhancers/devtools.d.ts(9,17): error TS7006: Parameter 'state' implicitly has an 'any' type.
node_modules/@datorama/akita/src/enhancers/devtools.d.ts(9,24): error TS7006: Parameter 'action' implicitly has an 'any' type.
node_modules/@datorama/akita/src/plugins/dirty-check/dirty-check-plugin.d.ts(4,45): error TS7006: Parameter 'head' implicitly has an 'any' type.
node_modules/@datorama/akita/src/plugins/dirty-check/dirty-check-plugin.d.ts(4,51): error TS7006: Parameter 'current' implicitly has an 'any' type.
node_modules/@datorama/akita/src/plugins/dirty-check/dirty-check-plugin.d.ts(10,22): error TS7006: Parameter 'head' implicitly has an 'any' type.
node_modules/@datorama/akita/src/plugins/dirty-check/dirty-check-plugin.d.ts(10,28): error TS7006: Parameter 'current' implicitly has an 'any' type.`

And thanks for an awesome library. I really like its simplicity. I've been looking for something similar to this.  I've been stuck in the complexity and boilerplate hell of ngrx/redux.

**Comment by NetanelBasal** [comment]
Thanks for the report. I will fix the types and will let you know.
