### ISSUE TITLE
Incorrect information about setActive method in Redux devtools

### ISSUE THREAD

**Issue by xaosaki** [datorama/akita#180]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Now when i use `entityStore.setActive({ next: true })` method and look in Redux devtools I have got message "[Steps] - Set Active (ids: **[object Object]**)"

## Expected behavior
On previous version i had "[Steps] - Set Active (ids: **4**)" message.

## Minimal reproduction of the problem with instructions
1. Use method `entityStore.setActive()` with params { next: true } or { prev: true }
2. Look in Redux devtools

## Info
**It's only a visual bug, active entities changes right.**

**Comment by NetanelBasal** [comment]
Thanks for the report.
