### ISSUE TITLE
Akita array helpers are not exported in lib

### ISSUE THREAD

**Issue by danzrou** [datorama/akita#181]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:

## Current behavior
Akita array helpers such as arrayAdd, arrayRemove etc. exist in source code but are not exported to public api

v3.0.1

**Comment by NetanelBasal** [comment]
Sorry and thank you for the report.
