### ISSUE TITLE
Observable of changes

### ISSUE THREAD

**Issue by leon** [datorama/akita#183]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior
I'm not sure if this is already in akita some where, but I could not find it.

When using a EntityStore and calling .update(1, {something: true})

I would like to be able to have an observable stream with the entities that got changed.

The use case is that as an entity changes I would like to check if a property has changed, and run an animation.

At the moment I must either do a selectAll() and loop though the entities. 
or do a selectEntity(1), but I do not know the id of the entity, I would simply like to react to any change.

This would allow for a more event driven setup where you can hook into changes coming from a particular store.

Would this be possible?
Would it be a good idea?

**Comment by NetanelBasal** [comment]
I will create the following query method:

`query.selectUpdatedEntityIds().subscribe(ids => ...)`

Sounds ok?

**Comment by NetanelBasal** [comment]
Just to be aligned with the API, it will be a `BehaviorSubject` that fires immediately.

**Comment by leon** [comment]
@NetanelBasal Thanks, that is just what I needed :)
