### ISSUE TITLE
setEntities converting ids to numbers

### ISSUE THREAD

**Issue by sircon** [datorama/akita#185]
## I'm submitting a...
<pre><code>
[x] Bug report
</code></pre>

## Current behavior
I just updated to version 3, and now the entity store `.set()` value is not working. It sets the entities in the store but all ids are null. This is because right now Akita is converting the ids to numbers (https://github.com/datorama/akita/blob/master/akita/src/setEntities.ts#L34) and our ids are strings.

## Expected behavior
Don't convert ids into numbers.

**Comment by NetanelBasal** [comment]
Thanks for the report. I will check it later today and fix it.

**Comment by NetanelBasal** [comment]
Can you share the code, please?

**Comment by sircon** [comment]
Ye, sure. I'll create an easy example this weekend. But I just noticed I pointed to the wrong line, it is this one: https://github.com/datorama/akita/blob/master/akita/src/setEntities.ts#L46 where `newIds = Object.keys(newEntities).map(Number);` you map the keys into numbers. If these keys are strings, it will return a `NaN` and fill the entity store with `ids: [null, null, ...]`

**Comment by sircon** [comment]
Easy to check is to run this in javascript:

```
const obj = { "a": {}, "b": {} };
console.log(Object.keys(obj).map(Number));
```

This will return `[NaN, NaN]`

**Comment by NetanelBasal** [comment]
You are right. I always use numbers so didn't take this into account.
