### ISSUE TITLE
PreAdd middleware not running on EntityStore.set()

### ISSUE THREAD

**Issue by levitatejay** [datorama/akita#186]
In the 3.0 blog post and Akita documentation it says:

> The preEntityAdd() middleware is called when we invoke the EntityStore.set() or EntityStore.add() methods with the newly added entity

From what I can tell the middleware is only being called when I use the `EntityStore.add()`
Here is a stackblitz that console logs on add but not on set:
https://stackblitz.com/edit/akita-todos-app-yclvep

**Comment by NetanelBasal** [comment]
Fixed in 3.1.3. Thanks for the report.
