### ISSUE TITLE
The toBoolean() method SO discussion

### ISSUE THREAD

**Issue by oleersoy** [datorama/akita#187]
Just had this discussion on SO about the `toBoolean()` method and thought ya'll might be interested:

https://stackoverflow.com/questions/55289287/is-it-always-enought-to-use-to-obtain-the-correct-boolean-value-in-javascript?noredirect=1#comment97308356_55289287

**Comment by NetanelBasal** [comment]
Thanks. As you can see, this method is internal. Prefer using `!!`.

**Comment by NetanelBasal** [comment]
I will appreciate if you can remove this part: "Akita provides a toBoolean utility method that can be used like this:" as it's not public API. Thanks.

**Comment by oleersoy** [comment]
Removed it.  Thanks for the feedback.  [This tutorial](https://blog.angularindepth.com/state-management-in-angular-using-akita-82f117d282dd) used `toBoolean` in their API, thus I thought it was public.  Here's a snippet of how it's imported in the tutorial:

```
import { Query, toBoolean } from '@datorama/akita';
```
