### ISSUE TITLE
Store Middleware documentation wrong

### ISSUE THREAD

**Issue by sircon** [datorama/akita#188]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The documentation states `akitaPreEntityAdd` and `akitaPreEntityUpdate`

## Expected behavior
It is actually `akitaPreAddEntity` and `akitaPreUpdateEntity`.

**Comment by NicCOConnor** [comment]
is also states "The preEntityAdd() middleware is called when we invoke the EntityStore.set() or EntityStore.add()"

This function is not called when using EntityStore.set()

**Comment by NetanelBasal** [comment]
@sircon thanks, updated the docs. @NicCOConnor already fixed - https://github.com/datorama/akita/issues/186

**Comment by dylanwatsonsoftware** [comment]
It might also be worth editing this blog post: https://engineering.datorama.com/you-asked-for-it-we-listened-and-now-its-here-akita-v3-92740d0d72e4

As I just about made this mistake :(

**Comment by NetanelBasal** [comment]
Done
