### ISSUE TITLE
Removal of Web Workers: mapInWorker from documentation after release 1.24 nothing in release notes to say why and what to use instead

### ISSUE THREAD

**Issue by frakay100** [datorama/akita#189]
## I'm submitting a...

<pre><code>
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[*] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
API docs suggest mapInWorker is available to 1.24 for off thread handling of large data sets

## Expected behavior
 mapInWorker method available

## Minimal reproduction of the problem with instructions
No documented reason why removed in release notes and what is available instead to handle large data set processes

## What is the motivation / use case for changing the behavior?
This is a undocumented breaking change

## Environment

<pre><code>
Angular version: 7.1.4

Others:
Looking to update Akita store in my project to 3.0 but looks like Web Workers are removed. I have large trading data threads and Web Workers are essential. What is available to faciliate using Web Workers within the Akita API?
</code></pre>

**Comment by NetanelBasal** [comment]
It is documented - https://github.com/datorama/akita/blob/master/BREAKING_CHANGES.md. This doesn't belong to Akita core. You can take the code and add it to your application.

**Comment by frakay100** [comment]
Ok thanks I will migrate the code but just wondered if there was a specific issue having it part of the spec rather than streamlining the core?

**Comment by NetanelBasal** [comment]
Because this isn't a common use-case.

**Comment by frakay100** [comment]
Thanks for all your great work Netanel
