### ISSUE TITLE
Initial / Default EntityUi state

### ISSUE THREAD

**Issue by NicCOConnor** [datorama/akita#190]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When adding an entity to an EntityStore that also contains and EntityUIStore I must manually set the UI state per entity  

```typescript
export const defaultUiState: ExerciseUi = {
  isEditing: false,
  isLocked: false,
  isOpen: false,
  isSelected: false
};

@transaction()
  add(name: string): Observable<Exercise> {
    const exercise = createExercise({name});
    
    return this.exercisesService.createExercise(exercise).pipe(
      tap((_exercise: Exercise) => {
        this.exerciseStore.add(_exercise);
        this.exerciseStore.ui.add({id: _exercise.id, ...defaultUiState});
      })
    );
  }
```
## Expected behavior

I would like to have a default EntityUIState added whenever I add an entity to an EntityStore.
```typescript
export interface ExerciseUi {
  id?: string;
  isSelected: boolean;
  isEditing: boolean;
  isOpen: boolean;
  isLocked: boolean;
}
```

```typescript
export interface ExerciseState extends EntityState<Exercise> {
}

export interface ExerciseUIState extends EntityState<ExerciseUi> {
}

export const defaultUiState: ExerciseUi = {
  isEditing: false,
  isLocked: false,
  isOpen: false,
  isSelected: false
};

@Injectable({
  providedIn: ExerciseModule,
})
@StoreConfig({name: 'exercises'})
export class ExerciseStore extends EntityStore<ExerciseState, Exercise> {
  ui: EntityUIStore<ExerciseUIState, ExerciseUi>;
  
  constructor() {
    super();
    this.createUIStore(initialUiState, config, defaultUiState); // Something like this.
  }
```

The purpose being whenever I add an entity to an EntityStore that contains an EntityUIStore that default ui state would automatically be added to the EntityUIStore. Ideally, this would happen when a store is set as well as when an entity is added. 

Originally I thought that the purpose of the `initialUIState` parameter on the `CreateUIStore()` method would provide this, however, after looking at the state this is at the store level and not on a per entity basis. 

I also thought that a good place for this could be the store middleware 
```typescript
akitaPreAddEntity(exercise: Readonly<Exercise>): Exercise {
    this.ui.add({id: exercise.id, ...defaultUiState})
    return exercise;
  }
```
This doesen't work because it seems this function is run before the ui state is initialized. Also,  it seems this function is meant to mutate an entity rather than provide additional functionality. 

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## What is the motivation / use case for changing the behavior?

per entity defaults for an EntityUIStore 

## Environment

<pre><code>
Angular version: 7.2.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
I think I will expose the following functionality:

```ts
@StoreConfig({ name: 'articles' })
class ArticlesStore extends EntityStore<ArticlesState, Article> {
  ui: EntityUIStore<ArticlesUIState, ArticleUI>;

  constructor() {
    super();
    this.createUIStore().setInitialEntityState(entity => ({ isLoading: false, isOpen: true }));
  }
}
```

**Comment by NetanelBasal** [comment]
It will also make sense to handle entity delete. When the model entity removed, we should remove the UIModel automatically.

**Comment by NicCOConnor** [comment]
Thanks, Netanel. I took a stab at trying to create a PR for this but I couldn't wrap my head around the implementation. I'm looking forward to seeing how you handle it.

This looks good! Definitely agree the remove should be handled as well.

**Comment by NetanelBasal** [comment]
You can do it now:

```ts
this.createUIStore().setInitialEntityState(entity => ({ isLoading: false, isOpen: true }));
// Or
this.createUIStore().setInitialEntityState({ isLoading: false, isOpen: true });


```

**Comment by NetanelBasal** [comment]
Btw, I noticed that in your code example you have a `@transaction()`. Pay attention that it will not work as your method is async. You should wrap only the sync code with a transaction.

**Comment by NicCOConnor** [comment]
Working as expected, I really appreciate the fast turn around. I'm really diggin' this library! and thanks for the tip!
