### ISSUE TITLE
Where do I find a CHANGELOG?

### ISSUE THREAD

**Issue by snebjorn** [datorama/akita#194]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Others:
I was wondering where I can find a change log. I see you've release a version 3.2.3. I'm currently on 3.1.3. The version change suggest that there's a new feature. But I cannot find any info :(

Also the github releases is at 3.0.1 but the npm release is at 3.2.3. While I understand they don't have to be aligned, it helps when trying to figure out what has changed :)

**Comment by NetanelBasal** [comment]
We have some issues with the CHANGELOG; we'll fix it soon. In the meantime you can see what's changed via the commits page: 

https://github.com/datorama/akita/commits/master

Thanks.

**Comment by dmk1111** [comment]
Hey guys, any updates on this? It would be nice to have CHANGELOG in one place

**Comment by simeyla** [comment]
I get terrified updating akita every time because of this.
