### ISSUE TITLE
Basic store update

### ISSUE THREAD

**Issue by RonnieRocket147** [datorama/akita#195]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[X] Other... Please describe: Question
</code></pre>

I have a basic store which state is:

<code>{ contact: Contact, location: Location }</code>

How can I update `contact.name` with an `update()` call?

Thanks!

**Comment by NetanelBasal** [comment]
```ts
store.update(state => {
  contact: {
    ...state.contact,
    name: newName
  }
})
```

For more questions, please join Akita's Gitter channel.
