### ISSUE TITLE
Sub State

### ISSUE THREAD

**Issue by mailok** [datorama/akita#197]
Note: Akita is great, an excellent job!!!

Hello everyone, there is something I can not find in the documentation.
In Complex and large state are difficult to manage. Oftentimes we need to break these down into sub states that we can manage on a individual basis. 
**How can I do this with Akita?...**

For example:
My application have 3 features (AdminFeature, StatsFeature, TweetsFeature), and my global state is a object, and in this way I would like to see it in the dev tools:
```
GlobalState {
    AdminFeature
    StatsFeature
    TweetsFeature
}

```

My AdminFeature it's something like this: 

```
AdminFeature {
    Users
    Permissions,
    SelectedRole,
    ActiveTab,
    // among other things...
    }
}
```
**how can I use the power of Entity Store in Users and Permissions(colecctions), if they are a sub-state from store AdminFeature???**

**Every time I see an example of using the Entity Store, never is inside another state**

Something like **combineReducers** in Ngrx and **Sub States** in Ngxs.
Is this possible with Akita? Can I see an example?

**Comment by NetanelBasal** [comment]
You have two options:
1. Create a store for each.
2. Add them as a property to the main store and use Akita's entity array utils to CRUD them. https://netbasal.gitbook.io/akita/entity-store/entity-store/entity-array-utils

Moving the discussion to Gitter.

**Comment by mailok** [comment]
@NetanelBasal So you can not do sub state with Akita

**Comment by mailok** [comment]
@NetanelBasal This can not be considered a proposal??

**Comment by NetanelBasal** [comment]
@mailok I described what is a sub-state in Akita, but will try to make it more comfortable in the future.
