### ISSUE TITLE
persistState clear() clears entire localStorage - very unexpected!

### ISSUE THREAD

**Issue by simeyla** [datorama/akita#199]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[X] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The [`clear()`](https://github.com/datorama/akita/blob/master/akita/src/persistState.ts) method returned by `persistState` clears the entire localStorage instead of just the key being used by Akita. 

This is very unexpected, and other components in your application can be using localStorage. For instance I have a __paypalData__ object that was being destroyed!

## Expected behavior
* `clear()` should only clear the key being used by Akita.

**Comment by NetanelBasal** [comment]
Like the real storage implementation, `clear()` is meant to clear all. I understand the confusion, we'll add this ability to the `clearStore()` method so we don't introduce breaking changes. 

```ts
storage.clearStore('todos');
storage.clearStore(); // will delete all
```
