### ISSUE TITLE
Best practice for relations

### ISSUE THREAD

**Issue by jmls** [datorama/akita#2]
## I'm submitting a...
<pre><code>
[x] Question regarding relations
</code></pre>

## Current behavior
all the documentation currently describes a 1:1 map of models and tables. If you were to have a customer->orders-orderline->[product, user, state] what would be the best practice for Akita ? 

Should we have a store per model - how would you then link the relations together ? Is that done in the service - so should the customer service use the order service, or should it create a method to get the orders of the customer

**Comment by NetanelBasal** [comment]
It depends. Can you give me an example of how the data returns from the server?

**Comment by jmls** [comment]
at the moment, I can make a query that "includes" the relation. so I would get

{name: 'abc inc', address: 'somewhere', orders: [{ordernum: 123, orderlines: [{}...]}}

or I can exclude the relations and make three requests, one for customer, one for orders of customer, and 1..n for orderlines of each order

so I'm just trying to figure out what the best solution would be.

Also, is there any built-in caching ?

**Comment by NetanelBasal** [comment]
The best practice is to keep your state flat as possible and use derived selector. Always think about your state as a database. There are good [examples](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape) in the official redux docs that can help you with that.

I'm not sure what do you mean by saying caching. If you have the data in the store, there is no need to make an additional request. 

I encourage you to go over the shopping cart [example](https://engineering.datorama.com/building-a-shopping-cart-in-angular-using-akita-c41f6a6f7255?source=collection_home---6------0----------------).

If you have any further question, tell me.
