### ISSUE TITLE
Single - spa- angular

### ISSUE THREAD

**Issue by HemendPatel63** [datorama/akita#202]
We are trying to use akita for single-spa design and try to store the data in localstorage using persistState() but its not working. We have created independent app and was able persist the state.

https://github.com/CanopyTax/single-spa-angular.

Do we have to set any property to force this for single-spa

**Comment by NetanelBasal** [comment]
Can you share the code, please?

**Comment by NetanelBasal** [comment]
You call `persistState` in the wrong file. You should call it in `main.single-spa.ts`. Please check your code before you open an issue, thanks.

**Comment by HemendPatel63** [comment]
Thank you so much! - It is working:)
