### ISSUE TITLE
Avoid duplicates in ids and entities for Entity store

### ISSUE THREAD

**Issue by dvaJi** [datorama/akita#203]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Given this set of data:
`[{id: 'doc-0001', name: 'My document name'}, {id: 'doc-0001', name: 'My document name duplicated'}]`
and this model:
`interface DocumentModel {
   id: ID;
   name: string;
}`

when I use query.getCount() I got 2 instead of 1, that happen because ids (inside of my state) is not removing duplicates.

## Expected behavior
non duplicated in both ids and entities

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-facb25

## Environment

<pre><code>
Angular version: 7.2.0
Akita: 3.1.2 (But i tested on latest stable version and still happen)

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by NetanelBasal** [comment]
Why do you have duplicates entities in your store?

**Comment by NetanelBasal** [comment]
Before adding the data into the store, filter duplicates. Use `[lodash](https://lodash.com/docs/4.17.11#uniqBy)` or pure JS.
