### ISSUE TITLE
Single spa state management issue

### ISSUE THREAD

**Issue by HemendPatel63** [datorama/akita#204]
We have implemented single spa angular applications and tried to share the data and maintain the state between multiple apps.  It maintain the status between navigation but do not reflect the change until will refresh the page. 

I am creating store in each angular application. Do we have an option to update data between two applications without refresh the whole page?

**Comment by NetanelBasal** [comment]
What do you mean by saying multiple applications? It's one application that contains various applications or totally separate applications?

**Comment by HemendPatel63** [comment]
Completely separate application put together on angle page using single spa angular

**Comment by NetanelBasal** [comment]
It's not related to Akita. If you want to share the data between applications, you need to save it in a database or local storage and use polling or web sockets.

**Comment by HemendPatel63** [comment]
I was trying this to store in localstorage and use polling to achieve it. I will try it again, May be I miss something.
Thank you very much sir!

**Comment by lucasklassen** [comment]
Hi @HemTech !
Could you solve it? I have the same doubt
