### ISSUE TITLE
Update the store within a query

### ISSUE THREAD

**Issue by smilix** [datorama/akita#205]
## I'm submitting a question or a possible bug.
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I subscribe to a store query and and within this subscription I want to change the same store (but a different field). This second change is not visible. 

## Expected behavior
Both fields will be updated. 

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-b9hh87 (hello.component.ts)
The counter button increments the counter, but the "msg + counter" only the message. After I click the counter button again, the counter is incremented twice. 

## What is the motivation / use case for changing the behavior?
I want to update update another field in the same store inside a store query subscription. 

## Environment

<pre><code>
Angular version: 7.2.5
Akita: 3.5.5
</code></pre>

**Comment by NetanelBasal** [comment]
It's not related to Angular, that's how RxJS works. In your case, your code is synchronous, so the order of subscriptions is important. 

The `query.msg$` is subscribed before `query.counter$`. You can use `setTimeout` or refactor the code so the `query.counter$` subscription will happen first. 

You can verify this by running the following code:
```ts
  ngOnInit(): void {
    this.query.counter$.subscribe(console.log);
    this.query.msg$.subscribe(msg => {
      this.fooService.incrementCounter();
    });
  }
```
