### ISSUE TITLE
encrypt/decrypt with persistState

### ISSUE THREAD

**Issue by nayfin** [datorama/akita#206]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The persist state functionality is great, but we have a requirement to encrypt our data as it goes into localStorage and decrypt as it comes out. It looks like we maybe able to leverage the `serialize` and `deserialize` function parameters to accomplish this. If so and you have any thoughts on this we would love to hear your thoughts. If this isn't a good way to accomplish this, our team would love to see it as an option. A few of us can make time to help with the contribution.

## Expected behavior

A simple api for encrypting/decrypting state data in/out of localStorage

## What is the motivation / use case for changing the behavior?
To help secure state data cached in localStorage

**Comment by nayfin** [comment]
After reading more about this, I can see how this could be out of scope for the api and would be difficult to build in a robust way. LocalForage considers encryption/decryption out of scope for their project, so I won't be surprised if this is deemed out-of-scope here as well. All that being said, it would still be a really nice addition, even if it is only an example in the docs using serial/deserialize or a similar hook built with these ends in mind. Thanks for this awesome library and for all the work you've spent adding upgrades. If I find a way to use the current api to pull this off in a meaningful way, I'll make PR to the docs.

**Comment by NetanelBasal** [comment]
As you said, the best option is using the `serialize/deserialize`, it should look something like this:

```ts
persistState({
  deserialize: function(data) {
    const decrypted = ..
    return JSON.parse(decrypted);
  }
  serialize: function(data) {
    const encrypted = ..
    return JSON.stringify(encrypted);
  }
});
```

**Comment by NetanelBasal** [comment]
Using the `deserialize` and `serialize` properties is the solution.

**Comment by amitvchaudhary** [comment]
Hi @NetanelBasal , I used serialize and deserialize methods and tried to encrypt/decrypt data but in vain. Below is my code.

    persistStorage = persistState({
      serialize: function (data: any) {
        return simpleCrypto.encrypt(data);
      },
      deserialize: function (data: any) {
        return simpleCrypto.decrypt(data);
      },
    });

I tried all combinations but couldn't make it work. In the above code, I have used 'simple-crypto' library and also checked with 'crypto-js' library too. But I think somewhere the key $cache in 'AkitaStores' object is causing problem. But this is just an assumption. If I try to encrypt/decrypt data with simple objects outside somewhere, it works fine. So, there is no problem with the libraries but the data. Could you please help me here as I want to encrypt/decrypt whole Akita store in the local storage.
