### ISSUE TITLE
`selectMany` return `[undefined]`

### ISSUE THREAD

**Issue by pldespaigne** [datorama/akita#210]
## I'm submitting a...
- [X] Bug report

## Current behavior
When doing `selectMany` with an array of entites on a state with no entity the result is an array with one `undefined` (`[undefined]`) value instead of an empty array.

## Expected behavior
should be an empty array

## Minimal reproduction of the problem with instructions
```typescript
store.set([]);
query.selectMany([1,2]).subscribe(); // [undefined]
```
## Where is the problem
The select many uses the `selectEntity` function for each given id and the `selectEntity` return `undefined` if no entity with that id is found : [this line](https://github.com/datorama/akita/blob/master/akita/src/queryEntity.ts#L153)

**Comment by NetanelBasal** [comment]
Why you call `set` with an empty array and then `selectMany`?

**Comment by pldespaigne** [comment]
This is the inital value of the state. The store can be slow to be filled.
Depending on the network the process can looks like that :
1 - Initial state
2 - Get the id to select
3 - Select the entities
4 - Fill the state with the entities
The problem is that we do `ngFor` on the result, if it's an empty array it's ok it will be fill with the entities on step 4. But if it's `undefined` it throw errors.

**Comment by pldespaigne** [comment]
The workaround is to use the `selectLoading`, but we end up doing : 
```typescript
query.selectLoading().pipe(
  filter(isLoading => !isLoading),
  switchMap(_ => query.selectMany([1, 2]),
)
```
Instead of just `query.selectMany([1, 2])`

**Comment by NetanelBasal** [comment]
How do you know the ids in advance?

**Comment by NetanelBasal** [comment]
Also, you don't display a loading indicator for the users? 

```html
<spinner *ngIf="loading$ | async; else list"></spinner>

<ng-template #list>
 <list-item *ngFor="let item of entities$ | async"></list-item>
</ng-template>

```

**Comment by pldespaigne** [comment]
Those ids are stored elsewhere, we have two states : organizations and movies.
We already have the organizations and we want to perform a join `org.id = movie.orgId` to add an array of movies inside an organization, but movies are retreived from the network, and we don't want to put a spinner because we already have the organizations to display to the user.

**Comment by NetanelBasal** [comment]
Ok, give me a sec.

**Comment by pldespaigne** [comment]
Thanks you for the really fast answer ! 👍
