### ISSUE TITLE
Add support for paging on client (within the store)

### ISSUE THREAD

**Issue by brgrz** [datorama/akita#213]
## I'm submitting a...

[ X] Feature request

## Current behavior
The query method `selectAll()` supports `sortBy`, `sortByOrder `and `limitTo `but to effectively perform paging on the client a `skip `parameter is missing.

## Expected behavior

Add `skip` parameter to `selectAll()`
Also would be better if `limitTo `was renamed to `take`

**Comment by NetanelBasal** [comment]
We're not going to support client-side pagination. You can use [JS](https://github.com/NetanelBasal/paginate-array) for this:

```ts
selectAll().pipe(map(entities) => {
  return paginate(collection[,pageNumber, numItemsPerPage]);
})
```

**Comment by brgrz** [comment]
When you have limitTo, sortBy and sortOrder it kinda makes sense to add the skip too but...whatever
