### ISSUE TITLE
Bugs in PaginatorPlugin

### ISSUE THREAD

**Issue by rimamct** [datorama/akita#214]
## I'm submitting a...
 
[X] Bug report  
 

## Current behavior
 

 **1. If you don't specify "total" in server response, paginator assume [total=number of pages * number of rows per page ]. This is wrong , last page can have fewer rows than rows per page]

2. Also the 'to' in last page is calculated same way and presents the wrong number of rows 
[to= this.currentPage * this.pagination.perPage]**, last page could have fewer records than perPage rows

## Expected behavior

Browser:
- [ X] Chrome (desktop) version XX

**Comment by NetanelBasal** [comment]
> last page could have fewer records than perPage rows

We can't predict the last page number of rows.

**Comment by rimamct** [comment]
If server respone provides the “total” you can😊

**Comment by NetanelBasal** [comment]
Sure.

**Comment by NetanelBasal** [comment]
But you just mention - "If you don't specify "total" in server response"

**Comment by rimamct** [comment]
Yes, that's why 'IF'  is for bug number 1, while bug 2 is persists even if you specify the total count.
At least note in documentation would clarify it.
{
  "perPage": 10,
  "lastPage": "10",
  "currentPage": "3",
  "data": [...]
}

**Comment by NetanelBasal** [comment]
You should always provide `total` rows.

**Comment by NetanelBasal** [comment]
We'll check it out and fix it soon. Thanks for the report.

**Comment by NetanelBasal** [comment]
Updated the docs about the `total` value and fixed the `to` field issue.
