### ISSUE TITLE
Playground app won't compile.

### ISSUE THREAD

**Issue by nfdavenport** [datorama/akita#218]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The playground application will not current compile with a fresh clone and npm install.

## Expected behavior

Should compile and run

## Minimal reproduction of the problem with instructions
git clone https://github.com/datorama/akita.git
cd akita
npm install
cd playground
npm install
npm run start

## Environment
windows 10

<pre><code>
Angular version: X.Y.Z
Whatever is in your package.json

For Tooling issues:
- Node Windows 

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Is it the RxJS imports issue?

**Comment by NetanelBasal** [comment]
Delete the RxJS folder inside the playground.

**Comment by nfdavenport** [comment]
The only RxJS folder I can find is down in the node_modules folder.  I tried deleting that and just got further issues.  Where is this RxJS folder in the repo?

**Comment by nfdavenport** [comment]
It is a lot of errors like the following:

```
ERROR in src/app/products/products.component.ts(24,5): error TS2322: Type 'import("C:/nfd/research/akita/node_modules/rxjs/internal/Observable").Observable<boolean>' is not assignable to type 'import("C:/nfd/research/akita/playground/node_modules/rxjs/internal/Observable").Observable<boolean>'.
  Types of property 'source' are incompatible.
```

**Comment by NetanelBasal** [comment]
Pull the latest version and run npm install in the playground.

**Comment by NetanelBasal** [comment]
Yes, the rxjs folder inside the playground node modules folder.

**Comment by nfdavenport** [comment]
I see the install tried to delete it and failed.  I deleted it successfully.  But now it just can't find rxjs?

`
Cannot find module 'rxjs'
Error: Cannot find module 'rxjs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\nfd\research\akita\playground\node_modules\inquirer\lib\ui\prompt.js:3:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
`

**Comment by NetanelBasal** [comment]
Run npm install in the root folder

**Comment by nfdavenport** [comment]
that did it.  I swear I tried that as well.  But I don't think I was being careful enough changing directories when running installs and deletes.  Finally got it working.  Just in time.  Just finished 90 minutes of an ngrx workshop at ng-conf that convinced me I really want something sleeker like Akita!  Thank you!

**Comment by NetanelBasal** [comment]
Thanks :). You're welcome to join Akita's Gitter channel for any further questions.
