### ISSUE TITLE
'ng add @datorama/akita' destroys nx workspace schematics when opt for akita devtools

### ISSUE THREAD

**Issue by lincze** [datorama/akita#219]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
(not sure that it is a bug or a feature request)
</code></pre>

## Current behavior

- create a workspace w/ nx (https://nx.dev)
- run "ng generate --help" (and see nx related entries)
- use ng add to add akita and opt for devtools
- run "ng generate --help" (and see nx related entries wiped out)

and ng stops acting as a workspace manager, instead, you'll have an akita enhaced cli for a single angular project.

## Expected behavior

would be nice to have this facility to work together w/ nx

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## Environment

<pre><code>
angular-cli: 7.3.1
nrwl schematics and builders: 7.8.4
akita: 3.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   v10.15.3
- Platform:   Linux 

Others:

Linux 5.0.9-200.fc29.x86_64 #1 SMP Mon Apr 22 00:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

</code></pre>

**Comment by NetanelBasal** [comment]
We want to avoid extending `nrwl` schematics as not everyone using it. You can still use their schematics by running the complete command, for example:

`ng generate @nrwl/schematics:node-application appName`

**Comment by lincze** [comment]
> We want to avoid extending `nrwl` schematics as not everyone using it. You can still use their schematics by running the complete command, for example:
> 
> `ng generate @nrwl/schematics:node-application appName`

Thanks. At the moment, I've installed akita with "npm i --save" + installed akita-cli, globally. That avoids these conflicts.

**Comment by NetanelBasal** [comment]
Yes, it's an option.
