### ISSUE TITLE
docs: incorrect user avatar in Contributors

### ISSUE THREAD

**Issue by voronovmax** [datorama/akita#225]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Ido Glikman has Amit b.h's avatar. 

## Expected behavior

Ido Glikman should have a different avatar.

**Comment by NetanelBasal** [comment]
Thanks! fixed.
