### ISSUE TITLE
State changes don't reset state history future

### ISSUE THREAD

**Issue by flmariano** [datorama/akita#227]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

State updates don't reset the future of the state history, meaning that "redoing" is still possible after the state has changed.

## Expected behavior

If I undo an action and make another one I want that new action to be the latest event in the history. The user should not be able to redo states that don't include the effects of the latest state change.

## What is the motivation / use case for changing the behavior?

The state history should behave (or at least there should be an option to make it behave) like the history in web browsers and most other applications, meaning that the "Forward/Redo" button greys out after e.g. a link has been clicked or a line of code changed. If it works differently, it's confusing for users.

**Comment by NetanelBasal** [comment]
Can you create a simple demo, please?

**Comment by flmariano** [comment]
Ok. Here you go. https://stackblitz.com/edit/akita-todos-app-9bxbyt

**Comment by NetanelBasal** [comment]
I'm not sure what's the "wrong" behavior here?

**Comment by flmariano** [comment]
If I e.g. create a todo, then undo that, then create another todo, the expected behaviour would be that the redo button becomes grey and I can't step forward in the history anymore since the action I just took is the most recent state.

What happens instead is that I can step forward to a state in which the todo I just created does not exist but the undone one does. Is that how it should be? I don't think it's "wrong" per se, it just seems counterintuitive to me since I'm used to not being able to step forward in situations like that.

**Comment by NetanelBasal** [comment]
I see, but it's not the standard behavior with Redux implementations. We save the whole operations history. You can call `clear()` when needed.

**Comment by flmariano** [comment]
Ok, thanks for clarifying. Makes sense that it doesn't get deleted automatically. 

`clear()` wouldn't work for this purpose though because I only want to delete the future, not the past. Could there perhaps be a method for only clearing future states? Or maybe an option parameter you can pass into the constructor to make it automatically do it?

**Comment by NetanelBasal** [comment]
We can add an option to the `clear()`. Do you want to create a PR?

**Comment by flmariano** [comment]
Ok, sure, I can do that. What should the option look like? Something like `onlyFuture: boolean` or more along the lines of `states: 'past' | 'present' | 'future'`?

**Comment by NetanelBasal** [comment]
`states: 'past' | 'present' | 'future'`, use `coerceArray` to support multiple.

**Comment by flmariano** [comment]
Could you please explain what you mean by using `coerceArray` for that? Isn't the only thing it does wrapping a string in an array or am I wrong about that?

The way I've coded it so far is as follows and it seems to work but there's probably a cleaner way to do it:
```typescript
  clear(states: ('past' | 'present' | 'future')[] = ['past', 'present', 'future']) {
    this.history = {
      past: states.includes('past') ? [] : this.history.past,
      present: states.includes('present') ? null : this.history.present,
      future: states.includes('future') ? [] : this.history.future
    };
  }
```

**Comment by NetanelBasal** [comment]
Let's make it more powerful and clean. Accept an optional callback where you pass the current history and return a new history object:

```ts
  clear(customUpdateFn?: (history: type) => type) {
    this.history = isFunction(customUpdateFn) ? customUpdateFn(this.history) : {
      past:  this.history.past,
      present: this.history.present,
      future: this.history.future
    };
  }
```

Don't forget to add specs, please.

**Comment by flmariano** [comment]
I wrote that customUpdateFn like this:
```ts
(history: { past: S[], present: S, future: S[] }) => { past: S[], present: S, future: S[] }
```

**Comment by NetanelBasal** [comment]
Yes, that's good. However, you can extract it to a `type` instead of repeating it.

**Comment by NetanelBasal** [comment]
```ts
export type History<S> = {
  past: S[],
  present: S,
  future: S[]
}
```

**Comment by lilas78** [comment]
The correction was done for StateHistoryPlugin. Would it be possible to make it available for EntityStateHistoryPlugin ?
We could then use :
 entityStateHistory.clear(ids, (history) => {
      return {
        past: history.past,
        present: history.present,
        future: []
      };
    });
