### ISSUE TITLE
persistState across windows

### ISSUE THREAD

**Issue by nickcam** [datorama/akita#228]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
[ ] Other... Please describe:
</code></pre>

## Basic repro here:
[https://stackblitz.com/edit/akita-persiststate-windowed](https://stackblitz.com/edit/akita-persiststate-windowed)

Just looking for some guidance or best practices if this has been done before. 
I'm attempting to access state across windows - ie from a window I've opened within the app using persistState (localStorage or sessionStorage). When the new window first opens, all good, state from the main window is read from storage.

Updating the state in one window obviously doesn't reflect in the other window though. Do you have any recommendations on how to sync state between windows?
One these hooks perhaps - deserialize and serialize, preStorageUpdate or preStoreUpdate?

Fantastic work on the project as well!

**Comment by NetanelBasal** [comment]
What about something like:

```ts
export class AppComponent {
  ngOnInit() {
    fromEvent<StorageEvent>(window, 'storage')
      .pipe(
        // listen to our storage key
        filter(event => event.key === 'AkitaStores'),
        tap(event => {
          const stores = JSON.parse(event.newValue);
          snapshotManager.setStoresSnapshot(stores);
        })
      ).subscribe();
  }
}

```

**Comment by NetanelBasal** [comment]
Actually, it will cause an infinite loop. Let me think about it.

**Comment by nickcam** [comment]
Awesome, thanks for super quick response.
I thought there may have been some sort of existing hook or workaround, if not no worries I'll start having a more in depth look.
Using the storage events is a good idea, at the least it's a perfect place to start.

**Comment by NetanelBasal** [comment]
![image](https://user-images.githubusercontent.com/6745730/58880212-1551f600-86e0-11e9-999c-f1190d5e8ac9.png)

**Comment by NetanelBasal** [comment]
![tSLKQfPTCa](https://user-images.githubusercontent.com/6745730/58880291-46322b00-86e0-11e9-893d-76e0f1a9b314.gif)

**Comment by NetanelBasal** [comment]
```ts
    fromEvent<StorageEvent>(window, 'storage')
      .pipe(
        // listen to our storage key
        filter(event => event.key === 'AkitaStores'),
      ).subscribe(event => {
        const stores = JSON.parse(event.newValue);
        snapshotManager.setStoresSnapshot(stores, { skipStorageUpdate: true });
     });
```

**Comment by nickcam** [comment]
You're a legend! Thanks for the quick response again. I've just given it a quick spin but it is working perfectly.

**Comment by NetanelBasal** [comment]
You're welcome. I'm wondering what a real-world use case for this functionality is?

**Comment by nickcam** [comment]
Yeah it's a bit of weird one. Basically it's for multiple monitor support. I'm prototyping replacing a desktop system that has a heavily utilised GIS display in separate form so users can interact with it independently of the main form on a different monitor. Plenty of common state between the forms...easy for desktop apps running in the same process :). The persons list in the example is completely contrived, in reality it would be a store of geographic objects.

**Comment by foreground-voice** [comment]
Hi, @NetanelBasal, your solution looks like a workaround. Why don't you want to make this behaviour as default? 
I see that AkitaStores was changed from one window and of course it is similar in another window because of localStorage, but the event did not happen. This is not right I'm guessing. All subscriptions must work well!
