### ISSUE TITLE
App-Shell not building with AkitaNgDevtools enabled

### ISSUE THREAD

**Issue by EigenTheory** [datorama/akita#233]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When building a project utilizing [Angular App-Shell](https://angular.io/guide/app-shell), `AkitaNgDevtools` causes the application shell to not be generated. When running `ng run demo:app-shell` there are no errors emitted. If the same command is run via an NPM script the following error occurs...

![image](https://user-images.githubusercontent.com/1594192/59163386-1e6b0a80-8ac6-11e9-8290-0568a67a2113.png)

## Expected behavior

When building an Angular application with `ng generate app-shell` schematic, the application should provide application shell with `AkitaNgDevtools` enabled.

## Minimal reproduction of the problem with instructions
- Create new Angular application with `ng new demo --routing`

- Create the app-shell `ng generate app-shell --client-project demo --universal-project server-app`

- Add Akita `ng add @datorama/akita`

- Build with `ng run demo:app-shell`

- Inspect `./dist/demo/index.html` and observe that with `AkitaNgDevtools` enabled in `app.module.ts` that `<app-shell>` never gets compiled in. If commenting out `AkitaNgDevtools` the app-shell is compiled in.

Desired output in `index.html` is...

![image](https://user-images.githubusercontent.com/1594192/59163488-76eed780-8ac7-11e9-948f-d260f4c03827.png)

## Environment

<pre><code>
Angular version: 8.0.0

Browser:
- [x] Chrome (desktop) version 75.0.3770.80
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.15.3  
- Platform:  Mac

Others:

</code></pre>

**Comment by EigenTheory** [comment]
@NetanelBasal Why was this closed?

**Comment by NetanelBasal** [comment]
Because it was fixed.
