### ISSUE TITLE
Can't run both Augury and Akita Ngdevtools

### ISSUE THREAD

**Issue by rjfranco** [datorama/akita#234]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When `akita-ngdevtools` is installed, augury continuously attempts to refresh component states and freezes Chrome

## Expected behavior
Augury/Chrome work as expected

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

Can be reproduced with just the seed, so long as you have both augury and the devtools installed the error will occur.

https://rlminqqq.github.stackblitz.io/

## Environment

<pre><code>
Angular version: 7.2.22

Browser:
- [x] Chrome (desktop) version 75.0.3770.80
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15.3
- Platform:  MacOS 10.14.5
</code></pre>

**Comment by NetanelBasal** [comment]
It's something related to Redux devtools. It's only happens when calling `__REDUX_DEVTOOLS_EXTENSION__.connect();`.

**Comment by NetanelBasal** [comment]
Unfortunately, we can't help with this as this not related to Akita. Its something with Augry and Redux dev-tools.
