### ISSUE TITLE
Allow to specify exactly which keys of a store to persist with persistState

### ISSUE THREAD

**Issue by visurel** [datorama/akita#236]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I want to be able to specify exactly which parts of a store I want to persist with persistState, e.g. when I want to `includes: ['profile.token', 'profile.entities', 'profile.ids']` and omit all other keys from being persisted, I can't do this right now, because only the last, in this case, `profile.ids` will be persisted and all others will be ignored. Actually it will also behave pretty weird and persist it just strangely.

## Expected behavior

I should be able to specify the keys as mentioned above and get only those parts of the store to be persisted.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/github-vqnjrk?file=src%2Fmain.ts
Simply check the LocalStorage. Also added a ADD TODO button in the TodosComponent

## What is the motivation / use case for changing the behavior?

For cases where I want to explicitly only want some keys, I can't do that. e.g. I want to omit the loading and error keys completely.

## Environment

<pre><code>
Angular version: 7.0.4
Akita: 3.17.1 (same happens in 3.17.0)

</code></pre>

**Comment by NetanelBasal** [comment]
Using custom hooks, you have complete control of what to save. https://netbasal.gitbook.io/akita/enhancers/persist-state#custom-hooks
