### ISSUE TITLE
Class Query export and Query Instance export

### ISSUE THREAD

**Issue by CILP** [datorama/akita#237]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I noticed that the Query file created by Akita CLI is exporting the Query Class definition, but also exporting an instance, my question is why this behaviour? Since angular uses DI.

`https://github.com/datorama/akita/edit/master/cli/templates/ts/query.tpl`

## Expected behavior
NA

## Minimal reproduction of the problem with instructions
NA

## Environment

<pre><code>
Angular version: 7.2.x

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.x
- Platform:  Mac

Others:
NA
</code></pre>

**Comment by NetanelBasal** [comment]
You need to set the template to `Angular`. 

```ts
// package.json
"akitaCli": {
  "template": "angular"
}
```
