### ISSUE TITLE
Upgrade store with Dynamic

### ISSUE THREAD

**Issue by KANekT** [datorama/akita#240]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

for select I can use:
1. this.query.select(state => state.form_comp)
2. this.query.select('form_comp');

for update I can use:
1. this.store.update({ form_comp: res.data });

## Expected behavior
How do i upgrade store with Dynamic for non-entity updates
1. this.store.update('form_comp', res.data });

## Environment

<pre><code>
Angular version: 8.0.0

</code></pre>

**Comment by NetanelBasal** [comment]
I'm not sure I understand your request. Can you elaborate more, please? Are you talking about `EntityStore` or `Store`? What do you mean "i upgrade store with Dynamic for non-entity updates"?

**Comment by NetanelBasal** [comment]
Do you mean that you have a dynamic property you need to update on a `Store`?

`this.store.update({ [propName]: res.data }})`

**Comment by KANekT** [comment]
Yes:

Do you mean that you have a dynamic property you need to update on a Store?

this.store.update({ [propName]: res.data }})

but propName is string and Dynamic

**Comment by NetanelBasal** [comment]
It's not related to Akita. You can use the dynamic property syntax:

`this.store.update({ [propName]: res.data }})`

**Comment by KANekT** [comment]
Thx.
