### ISSUE TITLE
Error: ...is not assignable to parameter of type 'never'  on arrayAdd() 

### ISSUE THREAD

**Issue by ToledoNicola** [datorama/akita#245]
## I'm submitting a...

<pre><code>
[] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Argument of type 'Accesskey[]' is not assignable to parameter of type 'never'.

## Expected behavior

be able to update  the store with arrayAdd() 

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## Environment

<pre><code>
Angular version: 7.3.9

Browser:
- [x] Chrome (desktop) version 75.0.3770.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.6.0  
- Platform: Mac  

Others:

`import { Injectable } from "@angular/core";
import { Store, StoreConfig, ID, arrayAdd } from "@datorama/akita";
import { firestore } from "firebase";

export interface User {
  id: ID;
  tenantId: string;
  email: string;
  name: string;
  storeId: string;
  accesskeys: Array<Accesskey>;
  created: firestore.Timestamp;
}
export interface Accesskey {
  id: ID;
  storeId: string;
  tenantId: string;
  promoterId: string;
  created: firestore.Timestamp;
}

export interface AuthState {
  user: User | null;
}

export function createInitialState(): AuthState {
  return {
    user: null
  };
}

export function createAuth(user: User) {
  return { ...user };
}

export function createAccessKey(tenantId, storeId, promoterId) {
  return {
    tenantId,
    storeId,
    promoterId,
    created: firestore.FieldValue.serverTimestamp()
  };
}

@Injectable({ providedIn: "root" })
@StoreConfig({ name: "auth" })
export class AuthStore extends Store<AuthState> {
  constructor() {
    super(createInitialState());
  }
  login(data: User) {
    const user = createAuth(data);
    this.update({ user });
  }

  logout() {
    this.update(createInitialState());
  }

  addAccessKey(tenantId, storeId, promoterId) {
    const accesskey = createAccessKey(tenantId, storeId, promoterId);
    this.update((state) => ({
      user: {
        ...state.user,
        accesskeys: arrayAdd(state.user.accesskeys, accesskey)// <--- error TS2345: Argument of type 'Accesskey[]' is not assignable to parameter of type 'never'.
      }
    }));
  }
<img width="1031" alt="Schermata 2019-07-08 alle 18 47 00" src="https://user-images.githubusercontent.com/32549447/60827581-d1f01900-a1b0-11e9-89fa-3fd168a3e71b.png">

}
`
</code></pre>

**Comment by NetanelBasal** [comment]
Works fine for me:
![image](https://user-images.githubusercontent.com/6745730/60837649-5b174800-a1d1-11e9-9502-0a1369eb1a58.png)

**Comment by NetanelBasal** [comment]
It's because `createAccessKey(tenantId, storeId, promoterId);` doesn't return the correct type - `Accesskey`. You're missing the `id` property.

**Comment by ToledoNicola** [comment]
@NetanelBasal  thanks for the quick response, i changed the `createAccessKey` funcion with `createAccessKey(tenantId, storeId, promoterId,accesskeyId);`
but the issue remains 😩, could be in the tsconfig?

**Comment by NetanelBasal** [comment]
You added the `id` property to `createAccessKey`?

**Comment by ToledoNicola** [comment]
ok now work 🎉, the problem was the missing `id` and a wrong type in `created` property👍🏼

**Comment by jitendershiprocket** [comment]
productsArray = [];
newcart = {
    "id":1,
    "device_id": localStorage.device_id,
    "vendor_id": this.vendor_id,
    "products": this.productsArray
  }


  saveList(list) {
    this.productsArray.push({
      "p_id":list.product_id,
      "po_id":list.options[0].product_option_id,
      "pov_id":list.options[0].option_value[0].product_option_value_id,
      "q":1
    })  
    this.shopikaService.addList(this.newcart);
![Screenshot from 2020-03-02 13-27-35](https://user-images.githubusercontent.com/53769221/75656317-b4b11300-5c89-11ea-9b78-e0f508a911ef.png)

  }
