### ISSUE TITLE
PaginatorPlugin data not sync with store

### ISSUE THREAD

**Issue by techaks** [datorama/akita#247]
`store.add(value)`
```

{
"perPage": 10,
"lastPage": "10",
"currentPage": "3",
"data": [...]
}

```

here **data** not updated after add value into store

unable to get added value in paginationRef

**Comment by techaks** [comment]
@bh86 @amateurhuman @hoisel @dintel

**Comment by NetanelBasal** [comment]
The `data` property should come from your server. What do you mean?

**Comment by techaks** [comment]
@NetanelBasal  

after performing

`store.add(value)`

value must be added in 

```

{
"perPage": 10,
"lastPage": "10",
"currentPage": "3",
"data": [...]
}

```

otherwise there is no advantage of akita

**Comment by techaks** [comment]
```
i have two pages 

1 . add computer 
2 list computer  ( using pagination)
everytime i add a computer it does not reflect in list computer.... i have to refresh whole page for that
```

**Comment by NetanelBasal** [comment]
Can you share the code, please?

**Comment by techaks** [comment]
```
private getAll() {
    const sortByValue = this.paginatorRef.metadata.get('sortBy') || 'createdAt';
    this.sortByControl = new FormControl(sortByValue);
    const perPage$ = this.perPageControl.valueChanges.pipe(startWith(10));
    const sort$ = this.sortByControl.valueChanges.pipe(startWith(sortByValue));

    this.items$ = combineLatest(
      this.paginatorRef.pageChanges,
      combineLatest(sort$, perPage$).pipe(tap(_ => this.paginatorRef.clearCache()))
    ).pipe(
      switchMap(([page, [sortBy, perPage]]) => {
        const requestFn = () => this._service.getAll({ page, sortBy, perPage }, this.where);
        this.paginatorRef.metadata.set('sortBy', sortBy);
        this.paginatorRef.metadata.set('perPage', perPage);
        this.paginatorRef.metadata.set('currentPage', (page as any).offset || 0);
        return this.paginatorRef.getPage(requestFn).pipe(
          tap((page: any) => {
            this.paginatorRef.metadata.set('total', page.total);
          })
        );
      }),
      // untilDestroyed(this)
    );
  }
```

**Comment by NetanelBasal** [comment]
The plugin performs **server-side** pagination. When you add a new entity, Akita can't know the new pagination data. You need to re-fetch it to get the updated data from the server.

**Comment by techaks** [comment]
we are using akita for faster processing , i think, this plugin will slow down the process.

**Comment by NetanelBasal** [comment]
This is not related to Akita. This is how server-side pagination works. The client can't know the updated data such as `lastPage`, etc.

**Comment by glennverschooren** [comment]
But what if I want to change a property from an item in the list where we don't need to invalidate the cache.
Not every change in the list will affect the paginated result from the server.

**Comment by Sefibrah** [comment]
> The plugin performs **server-side** pagination. When you add a new entity, Akita can't know the new pagination data. You need to re-fetch it to get the updated data from the server.

How do you do this?
