### ISSUE TITLE
EntityStore.upsertMany should also have an update hook

### ISSUE THREAD

**Issue by RobYed** [datorama/akita#248]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently `EntityStore.upsertMany()` does not use any pre-action hook like `EntityStore.update()` does with `EntityStore.akitaPreUpdateEntity()`. 

## Expected behavior
It would be really helpful to also have such a hook for `EntityStore.upsertMany()`, like e.g. `EntityStore.akitaPreUpsertMany()`.

## What is the motivation / use case for changing the behavior?
I have to manually add an `idKey` before adding or updating Entities in the store, which I usually do within the hook methods, but can't do in this case.
I guess this is a quite common use case for the hook methods (like seen in #196 ), so maybe you could add this feature to a future version of Akita :-)

## Environment

<pre><code>
Angular version: 8.0.0

</code></pre>

## Thanks!
I am currently adding Akita step-by-step to a quite large Angular application. We had many cluttered and inconsistent custom StateServices all over the code base. Akita seemed like a perfect fit for our existing app, as it is similar to how we handled states before. It does not have such an immense influence on the whole app architecture like ngrx does. So Akita seems like the better fit for our use case. Thanks for open-sourcing it! So far its a breeze to use it 👍

**Comment by RobYed** [comment]
You are crazy! Thank you so much! 👍

**Comment by RobYed** [comment]
I just updated Akita to take advantage of this great addition. Unfortunately it turned out, that the moment at which the pre-action hooks are called, is too late to be used for adding the idKey to the entity. Akita is checking whether the entity already exists in the store by checking the new entities' idKey. In my case the idKey is still missing at the time of that check. Thus it always adds the entity and never updates it. Do you see any solution for this issue? I know you need to check which path to go. On the other side, I can't use the upsertMany-hooks as they are now :/

**Comment by NetanelBasal** [comment]
How can Akita check if the entity exists in the store?

**Comment by RobYed** [comment]
What I meant was this check within `upsertMany()`:
![](https://i.imgur.com/5IIkA4d.png)

**Comment by NetanelBasal** [comment]
Yes, I know, that's my question. If we don't have the `id`, how we can check that it exists?

**Comment by RobYed** [comment]
Yeah, you are right. Thats also what I meant. The point is, that the behaviour is different from the other methods. If I only `update` an entity, I can add the idKey within the hook and it works just fine. Sure, there you do not need to check, whether it already exists. Nevertheless, from an outside perspective it is unclear why it behaves differently.

**Comment by NetanelBasal** [comment]
That's a logical problem, sorry I couldn't help.

**Comment by RobYed** [comment]
At least it would be helpful, if the docs would point out, that the hooks for upsertMany expect the idKey to be existant. In #196 you recommended using the hooks exactly for this use case. Now, for `upsertMany` it doesn't work like this.
Another solution could be, to have a different hook for upsertMany.
I think this is a legitimate point, isn't it?

**Comment by NetanelBasal** [comment]
> to have a different hook for upsertMany

And how would you solve the `isExists` issue?

**Comment by NetanelBasal** [comment]
I mean, how you expect to use an `upsert` method when you can provide a way to verify whether the entity exists or not?

**Comment by NetanelBasal** [comment]
Maybe we can add through the `options` parameter the following:

```ts
for (const entity of entities) {
  const e =  options.beforeCheck(entity);
  const id = e[this.idKey];

  if (hasEntity(this.entities, id)) { }
```

Does it make sense?

**Comment by RobYed** [comment]
Yes, it would solve the problem of adding a missing key :) 
What's wrong with having a hook like `akitaPreCheckEntity` to be consistent with the current hooks?

**Comment by NetanelBasal** [comment]
Yes, just checked whether it would solve the issue. I will add it.

**Comment by RobYed** [comment]
Yeah I'd like, for sure! I guess I can do that at sunday :)
