### ISSUE TITLE
NPM Audit vulnerability with @angular-devkit

### ISSUE THREAD

**Issue by bradrich** [datorama/akita#249]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:

NPM Audit vulnerability
</code></pre>

## Current behavior

There is an NPM audit vulnerability in the `@angular-devkit` dependency of your package.

```
Prototype pollution
Package: set-value
Patched in: >=3.0.1
Path: @datorama/akita > schematics-utilities > @angular-devkit/core > ... > set-value
More info: https://npmjs.com/advisories/1012
```

## Expected behavior

NPM vulnerability needs to be handled.

## Minimal reproduction of the problem with instructions
Repro can be accomplished by running `npm audit`

## Environment

Angular version 7.2.15
Akita version: 4.4.3
Node version: 12.4.0

**Comment by bradrich** [comment]
It does not look like `v0.802.0-next.0` of @angular-devkit/build-angular has a fix for the `set-value` package...

**Comment by NetanelBasal** [comment]
I am closing it for now as it's not an Akita issue.
