### ISSUE TITLE
Update entity and custom state at same time

### ISSUE THREAD

**Issue by yoan-asdrubal** [datorama/akita#252]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am new with akita, I have experience with ngrx and I am analyzing the possibility of migrating the application of my company to this framework. . 
I am currently working in a state where I need to store paging settings for different tables on the same entities, and when I am going to update the data in a table I must first update the entities and then the paged, so the data selector emits two times, when changing the entities and when changing the configuration of the desired table. 

## Expected behavior

Update the state of the entities as well as the status of the paged in the same operation so that it only emits once.  I have read in the documentation and in the examples on the internet but I have not found any way to do it.

## Minimal reproduction of the problem with instructions
I have this Bases definitions

State
<pre>
export interface BaseState extends EntityState {
    pageable: {
        [key: string]: CustomPageableState;
    }
}

export const baseInitialState = {
    pageable: {}
}

export class BaseStore<T extends BaseState> extends EntityStore<T> {
    constructor(initialState: any = baseInitialState) {
        super(initialState);
    }
}

/** This function allow me to add other prop to my custom properties of state */
export const createInitialState = (state: any) => Object.assign({}, baseInitialState, state);

</pre>
Query
<pre>
export class BaseQuery<T extends BaseState> extends QueryEntity<T> {

    constructor(protected store: BaseStore<T>) {
        super(store);
    }
  
    selectTableData(tableId: string) {
        return this.select(state => state.pageable[tableId].data);
    }

    selectTableEntities(tableId: string) {
        const entities = combineLatest(
            this.selectTableData(tableId),
            this.selectAll({asObject: true}),
            (tableData, entities) => tableData.filter(t => !!entities[t]).map(t => entities[t]));
        return entities;
    }
}
</pre>
My generic service look's like this.
<pre>
export class BaseModel  {
    id: string | number;
}

export abstract class BaseService<T extends BaseState, M extends BaseModel> {

    constructor(private store: BaseStore<T>, private query: BaseQuery<T>) {
    }
 
    getPageableValue() {
        return this.query.getValue().pageable;
    }
 
    selectTablesEntities(tableId: string): Observable<any[]> {
        return this.query.selectTableEntities(tableId);
    }
 
     addTableData(tableId: string, data: any[]) {
        const newData = data.map(d => this.createFunction()(d));
        const obj: any = {
            pageable: {
                ...this.getPageableValue(),
                [tableId]: {
                    query: {},
                    tableId: tableId,
                    data: newData.map(d => d.id)
                }
            }
        };
        this.store.upsertMany(newData);
        this.store.update(obj);

    }
/** This function must be implement in every extension of the class to get me  the function to create entity with Partial */
    abstract createFunction(): Function;
}
</pre>
Implementations to Person Entity
Model and Create function
<pre>
export interface PersonaModel {
    id: ID;
    nombre: string;
    edad: number;
}

/**
 * A factory function that creates PersonaModel
 */
export function createPersona({nombre, edad}: Partial<PersonaModel>) {
    return {id: guid(), nombre, edad} as PersonaModel;
}
</pre>

State 
<pre>
export interface PersonaState extends BaseState {

}

const initialState = createInitialState({})

@Injectable({providedIn: 'root'})
@StoreConfig({name: 'persona'})
export class PersonaStore extends BaseStore<PersonaState> {

    constructor() {
        super(initialState);
    }

}
</pre>
Query
<pre>
@Injectable({
    providedIn: 'root'
})
export class PersonaQuery extends BaseQuery<PersonaState> {

    constructor(protected store: PersonaStore) {
        super(store);
    }
}
</pre>

Service
<pre>
@Injectable({providedIn: 'root'})
export class PersonaService extends BaseService<PersonaState, PersonaModel> {

    constructor(private personaStore: PersonaStore, private personaQuery: PersonaQuery) {
        super(personaStore, personaQuery)
    }

    createFunction(): Function {
        return createPersona;
    }
}
</pre>

Use from my component
<pre>
export class PersonaPageComponent implements OnInit, OnDestroy {
    personas$: Observable<PersonaModel[]>;
    tables$: Observable<any>; 
    activeTableCtrl = new FormControl();

    personasToAdd = [];

    constructor(private personaService: PersonaService) {
    }

    ngOnInit() {
        this.tables$ = this.personaService.getTablesId();
        this.personas$ = this.activeTableCtrl
            .valueChanges
            .pipe(
                untilDestroyed(this),
                switchMap(val => this.personaService.selectTablesEntities(val))
            );

        this.personas$
            .pipe(
                untilDestroyed(this),
                tap(val => console.log('personas$', val))
            )
            .subscribe()
    }

    ngOnDestroy(): void {
    } 

   submit() {
        this.personaService.addTableData(this.activeTableCtrl.value, this.personasToAdd);
    }
 
}
</pre>
Basically I subscribe to the data of the table I select, everything works without problems except when I want to modify the data of the selected table, I call the function this.personService.addTableData (table, data []); and it is in that function where is the detail that I need to solve. It only happens in that instant of modifying, then everything continues to work without any unexpected behavior

## What is the motivation / use case for changing the behavior?

I need to have control over several tables that use same entity.

## Environment

<pre><code>
Angular CLI: 8.1.2
Angular: 8.1.2
Akita : 4.6.0
Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.12.0
- Platform:  Windows  x64

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Hey,

Do you mean that `BaseQuery.selectTableEntities` is called twice?

**Comment by NetanelBasal** [comment]
In the latest version, you can use the `combineQueries` function. https://netbasal.gitbook.io/akita/general/transactions

**Comment by yoan-asdrubal** [comment]
Hi @NetanelBasal , thanks for your answer, I read the docs and have all sense to me, however do not work in my app and I don't know why. 
I meant my subscription get twice changes, when change pageable state and change entities value. 
I used @transaction() in my function and work the same, right now I have this way with  applyTransaction(()=>{})
<pre>
addTableData(tableId: string, data: any[]) {
        const newData = data.map(d => this.createFunction()(d));
        const obj: any = {
            pageable: {
                ...this.getPageableValue(),
                [tableId]: {
                    query: {},
                    tableId: tableId,
                    data: newData.map(d => d.id)
                }
            }
        };
        applyTransaction(() => {
            this.store.update(obj);
            this.store.upsertMany(newData);
        });
</pre>
 Should I have something more than part of what is related to transactionality?
Thanks for your time.

**Comment by NetanelBasal** [comment]
You don't need the transaction. Install the latest version and use `combineQueries`.

```ts
selectTableEntities(tableId: string) {
  return combineQueries([
           this.selectTableData(tableId),
           this.selectAll({asObject: true})
        ]
}
```

**Comment by yoan-asdrubal** [comment]
It worked, I have only one broadcast of my changes.
Is there any way to modify only the reference to one  table instead of a full pageable object? because when change pageable other tables subscriptions get broadcast even when their data do not change, of course that it's right because state change.
 With this selector
<pre>
selectTableData(tableId: string) {
        return this.select(state => state.pageable[tableId].data);
    }
</pre>
I should have broadcast only when reference to data property change, no matter pageable change,  I think with  ...this.getPageableValue(), I get every value of pageable whit their reference.
![image](https://user-images.githubusercontent.com/42411788/61543330-3d3bb580-aa11-11e9-9dab-fe2af2a34872.png)
When change table1 , table2 subscription emit too.
I dont know if that its an issue, the original issue it was solved.
thanks a lot

**Comment by yoan-asdrubal** [comment]
I thinks its because when pageable changes, also entities change, that fire a reference change and table2 subscription get broadcast. 
Thanks again for your answer and your time.
