### ISSUE TITLE
EntityDirtyCheckPlugin get dirty values (diff)

### ISSUE THREAD

**Issue by snebjorn** [datorama/akita#253]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?
EntityDirtyCheckPlugin is just awesome. However I think it would be very useful to have a way to extract all the changed values for something like a PATCH payload.

    this.widgets$ = this.widgetsQuery.selectAll();
    /** All entities will also track new entities added to the store */
    this.collection = new EntityDirtyCheckPlugin(this.widgetsQuery);
    this.collection.setHead();

    // ... change some values

    this.collection.getDirty(); // returns dirty values

Lets say my store looks like this

```
entity {
  a: 1,
  b: 2,
  children: [
    { foo: 1, bar: 'bar' }
    { foo: 2, bar: 'baz' }
  ]
}
```

and I change `entity.chlidren[1].foo = 3`, then getDirty(entity) returns `{ children: [{ foo: 3 }] }`
Perhaps an EntityState needs to be added to track statuses like Added/Modified/Deleted

The funktionalitet  probably needs to be flushed out some more. But hope I discribed the general idea good enough :)

**Comment by NetanelBasal** [comment]
A quick update. We decided that we're not going to do that because there was no demand. We'll reconsider if there will be a demand — closing for now.
