### ISSUE TITLE
"schematics-utilities": "^1.1.1" is outdated for angular 8

### ISSUE THREAD

**Issue by ivanpadavan** [datorama/akita#256]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[X] Other... Please describe:
</code></pre>

## Current behavior
NPM resolves `@angular-devkit/core`, `@angular-devkit/schematics` versions as 7.3.9 which leads to unexpected behaviour, unless explicitly set versions in package.json 

## Expected behavior
Don't have a mess with not really stablilized schematics modules.

**Comment by NetanelBasal** [comment]
I'm not sure what you mean. We explicitly using v7.0.4:

```ts
"@angular-devkit/core": "7.0.4",
"@angular-devkit/schematics": "7.0.4",
```

**Comment by ivanpadavan** [comment]
`schematics-utilities` is the package that breaks proper dependency resolution. This issue can be reproduced by following those steps:

- `ng new projec1 --skip-install` (with 8.1.2 cli)
- `npm i @datorama/akita`
- `npm i`

After that you'll get `@angular-devkit/core` and `@angular/devkit/schematics` of version 7.3.9.
`package-lock.json` investigation shows that the only package that requires ^7.x.x version is `schematics-utilities` which, in turn, is required by akita.

**Comment by NetanelBasal** [comment]
We can't move to v8 as `schematics-utilities` still [requires](https://github.com/nitayneeman/schematics-utilities/blob/master/package.json#L38) v7.
