### ISSUE TITLE
EntityDirtyCheckPlugin doesn't seem to function

### ISSUE THREAD

**Issue by snebjorn** [datorama/akita#258]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`EntityDirtyCheckPlugin` doesn't seem to function.

`isDirty` / `someDirty` doesn't seem to update.

`reset` doesn't seem to change the store, though the `@DirtyCheck - Revert` action is triggered

## Expected behavior
It should work

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/akita-todos-app-hxhgp9

1. Add an item to the list
2. Observe that `isDirty` / `someDirty` doesn't update
3. Click reset
4. Observe the list or the store doesn't change

It doesn't work when setting `{ entityIds }` either

1. Add an item to the list
2. Click "Init new collection with entity ids"
3. Add an item to the list
4. Observe that `isDirty` / `someDirty` doesn't update
5. Click reset or reset(ID)
6. Observe the list or the store doesn't change

`DirtyCheckPlugin` seems to work as expected
https://stackblitz.com/edit/akita-todos-app-hhkwub

#### todos-page.component.ts
```ts
import { Component, OnInit } from '@angular/core';
import { initialFilters, VISIBILITY_FILTER } from '../filter/filter.model';
import { Todo } from '../state/todo.model';
import { TodosQuery } from '../state/todos.query';
import { TodosService } from '../state/todos.service';
import { Observable } from 'rxjs';
import { ID, EntityDirtyCheckPlugin } from '@datorama/akita';
import { map } from 'rxjs/operators';

@Component({
  selector: 'app-todos-page',
  templateUrl: './todos-page.component.html'
})
export class TodosPageComponent implements OnInit {
  collection: EntityDirtyCheckPlugin;
  ids: ID[];
  todos$: Observable<Todo[]>;
  activeFilter$: Observable<VISIBILITY_FILTER>;
  filters = initialFilters;

  constructor(private todosQuery: TodosQuery,
    private todosService: TodosService) {
  }

  ngOnInit() {
    this.todos$ = this.todosQuery.selectVisibleTodos$;
    this.activeFilter$ = this.todosQuery.selectVisibilityFilter$;

    /** All entities will also track new entities added to the store */
    this.collection = new EntityDirtyCheckPlugin(this.todosQuery);
    this.collection.setHead();
  }


  add(input: HTMLInputElement) {
    this.todosService.add(input.value);
    input.value = '';
  }

  complete(todo: Todo) {
    this.todosService.complete(todo);
  }

  delete(id: ID) {
    this.todosService.delete(id);
  }

  changeFilter(filter: VISIBILITY_FILTER) {
    this.todosService.updateFilter(filter);
  }

  reset(ids: ID | ID[]) {
    this.collection.reset(ids);
  }

  sethead() {
    this.collection.setHead();
  }

  initWithIds() {
    this.ids = this.todosQuery.getAll().map(x => x.id);
    this.collection = new EntityDirtyCheckPlugin(this.todosQuery, {entityIds: this.ids});
    this.collection.setHead();
  }
}
```

#### todos-page.component.html
```html
<div class="input-field">
	<i class="material-icons prefix">add_alarm</i>
	<input type="text" class="form-control" placeholder="Add Todo..." #input (keydown.enter)="add(input)">
</div>

<app-todos-filters (update)="changeFilter($event)" [filters]="filters" [active]="activeFilter$ | async">
</app-todos-filters>

<app-todos [todos]="todos$ | async" (delete)="delete($event)" (complete)="complete($event)"></app-todos>

<button (click)="reset()">reset</button>
<button (click)="sethead()">sethead</button>
<div>IsDirty(): {{ collection.isDirty() }}</div>

<hr>

<button (click)="initWithIds()">Init new collection with entity ids</button>
<button (click)="reset(ids)">reset({{ ids }})</button>
<button (click)="sethead()">sethead</button>

<div>IsDirty({{ ids }}): {{ collection.isDirty(ids, false) }}</div>
<div>SomeDirty(): {{ collection.someDirty() }}</div>
```

**Comment by shaharkazaz** [comment]
@snebjorn Are you trying to watch dirtiness for entities count?

**Comment by snebjorn** [comment]
I'm trying to reset the store to the head state.

So at the beginning the head is the initial (empty) list.
I add some items and want to revert everything.

Next up I want to add some items and set that as my head. Then add/remove some and revert to the head state.

I'm really just exploring the API atm, no real goal - yet :)

**Comment by shaharkazaz** [comment]
@snebjorn 
Ok so it sounds like what you might need is the regular `DirtyCheckPlugin`, the `EntityDirtyCheckPlugin` watches for changes in the entities that he holds, but doesn't monitor removal or addition of new entities like you want.

In the (sample application)[http://akita.surge.sh/widgets] check out the Widgets tab and check out the (source code)[https://github.com/datorama/akita/blob/master/angular/playground/src/app/widgets/widgets.component.ts].
The `DirtyCheckPlugin` there is watching the entities property and get's triggered upon addition or removal, and I thinks that's what you are looking for.

I'll update the docs to make it clearer.

**Comment by snebjorn** [comment]
@shaharkazaz I see, thank you. You're right the docs threw me of.

It says this :)

```ts
/** All entities will also track new entities added to the store */
this.collection = new EntityDirtyCheckPlugin(this.widgetsQuery);
```

**Comment by shaharkazaz** [comment]
@snebjorn I'm Glad I could help :)
