### ISSUE TITLE
[AkitaNgFormsManager] form array in a form group

### ISSUE THREAD

**Issue by gavenda** [datorama/akita#260]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

I don't know if its a missing feature or a bug so I checked both.

## Current behavior

The state is properly stored. The issue is when propagating the values from state to FormGroup which has a FormArray.

A console.log on the FormGroup is fine after an upsert. But the field with a FormArray on it is empty.

## Expected behavior

The values from state should propagate as well to a FormArray within a FormGroup.

## Minimal reproduction of the problem with instructions
A simple form created like this:
```TypeScript
buildForm() {
  this.form = this.formBuilder.group({
      name: [],
      traits: new FormArray([])
    });
  this.formsManager.upsert(this.form);
  console.log(this.form) // name is propagated
  console.log(this.form.controls.traits) // empty array even with redux dev tools report having multiple values
}
```

## What is the motivation / use case for changing the behavior?
Only fields in a FormGroup have their values propagated, it would be nice to have it support (fix?) FormArray as well.

## Environment

<pre><code>
Angular version: 8.1.0

Browser:
- [x] Chrome (desktop) version 60
 
For Tooling issues:
- Node version: v11.14.0
- Platform:  Windows

</code></pre>

**Comment by danzrou** [comment]
You must provide the array control factory.
https://netbasal.gitbook.io/akita/angular-plugins/angular-forms-manager

**Comment by NetanelBasal** [comment]
Hey,

This isn't the relevant repo for this issue. Please use the [official](https://github.com/NetanelBasal/akita-ng-forms-manager) repo.

As @danzrou said, you need to provide the array control factory. Also, based on your code, the `traits` initial value is an empty array.

If you still need help, you can check the [official](https://github.com/NetanelBasal/akita-ng-forms-manager/blob/master/src/app/home/home.component.ts) playground, Akita's Gitter [channel](https://gitter.im/akita-state-management/Lobby), or the open an issue in the official repo.
