### ISSUE TITLE
Entity update broken if entity instance is built using a constructor like new MyEntity()

### ISSUE THREAD

**Issue by gpeel** [datorama/akita#261]
## I'm submitting a
<pre><code>
[ ] Regression 
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
 When using this.store.update() on an instance build with form with 'new' => akita  re-creates a new entity using the original constructor and passing the new entity state as param.

<pre><code>

export interface TasksState extends EntityState<Task, number> {
}

// OK with simple interface
// const INITIAL_TASKS: Task[] = [
//   TaskUtil.createTask('Aller boire des bières'),
//   TaskUtil.createTask('Dormir', true),
//   TaskUtil.createTask('Faire du sport (non je rigole)')
// ];

// PB if using new
const INITIAL_TASKS: Task[] = [
  new TaskModel('Aller boire des bières'),
  new TaskModel('Dormir', true),
  new TaskModel('Faire du sport (non je rigole)')
];

@Injectable()
@StoreConfig({name: 'tasks'})
export class TasksStore extends EntityStore<TasksState> {

  constructor() {
    super();
    this.add(INITIAL_TASKS);
  }
 
  updateTask(task: Task): void {
    this.update(task.id, task);
  }
}
</code></pre>

If I want to complete a Task in a TodoMvc app, for example the first one:

<pre><code>
      '0': {
        label:  'Aller boire des bières',
        completed: false,
        id: 0
      },
</code></pre>

becomes : 

<pre><code>
      '0': {
        label: {
          label: 'Aller boire des bières',
          completed: true,
          id: 0
        },
        completed: false,
        id: 3
      },
</code></pre>

If I don't use a constructor to build my Task instances (in the example above by uncommenting/commenting the way INITIAL_TASKS is built, all is OK:

<pre><code>
      '0': {
        label:  'Aller boire des bières',
        completed: true,
        id: 0
      },
</code></pre>

In the JS Akita code, the behavior originate form line 1265 in datorama-akita.js in function updateEntities()

<pre><code>
             if (isPlainObject(newState)) {
                newEntity = new ((/** @type {?} */ (oldEntity))).constructor(merged);  <<<< HERE
            }

</code></pre>

**Comment by NetanelBasal** [comment]
I'm not sure I understand what you're doing. Can you create an example in stackblitz, please?

**Comment by NetanelBasal** [comment]
When you choose to work with classes rather than plain objects, when you call update, we save the class instance form and create a new instance for you.

**Comment by gpeel** [comment]
hi Netanel

thanks for responding so fast!


here is the full cli code project :

https://drive.google.com/open?id=10YNYkEPTPLmQr_ddAGOVu1l50rXNgZ7I

After start, try to complete a Task
You will have something like:
[OBJECT OBJECT]_3   for the new label
This show the PB.

if you edit file     src/app/crud/state/akita/tasks.store.ts
where I create the Task instances using 'new' in INITIAL_TASKS

Switching to commented code for INITIAL_TASKS,
 show that creating Entity instances with object litterals solves the PB.
But if I want to create Task instances with class/new strategy it seems to
be a problem

Gauthier

**Comment by NetanelBasal** [comment]
There is a restriction when working with classes. As mentioned in the [docs](https://app.gitbook.com/@netbasal/s/akita/general/class-support):

**Important: The class constructor should accept one parameter which is a plain object**

**Comment by NetanelBasal** [comment]
To give you a direction, this is how it should be:

```ts
export class TaskModel implements Task {
  id: number;
  label;
  completed;

  constructor({ label, completed, id }) {
    this.label = label;
    this.completed = completed;
    this.id = id === undefined ? TaskUtil.getNextId() : id;
  }
}
```

**Comment by gpeel** [comment]
thanks !

I had not seen that restriction.
