### ISSUE TITLE
 "export 'default' (imported as 'rxjs') was not found in 'rxjs' on /datorama-akita-ng-entity-service

### ISSUE THREAD

**Issue by hiepxanh** [datorama/akita#266]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/16970990/62432773-ac2c4480-b75b-11e9-8a18-059332fab56a.png)

## Expected behavior

we need get rid of warning

## Minimal reproduction of the problem with instructions
[https://github.com/hiepxanh/akita-bug](https://github.com/hiepxanh/akita-bug) That my repository

reproduce step:
- ng new akita-bug
- ng add @datorama/akita
- yes for 3 prompt question

I guest `ng add` causing issue?

## What is the motivation / use case for changing the behavior?

```
{
  "name": "App",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@capacitor/core": "1.1.0",
    "@capacitor/ios": "^1.1.0",
    "@datorama/akita": "^4.9.0",
    "@datorama/akita-ng-entity-service": "^1.0.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.1.0",
    "cordova-android": "8.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^4.1.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.13.8",
    "@angular-devkit/build-angular": "~0.13.8",
    "@angular-devkit/core": "~7.3.8",
    "@angular-devkit/schematics": "~7.3.8",
    "@angular/cli": "~7.3.8",
    "@angular/compiler": "~7.2.2",
    "@angular/compiler-cli": "~7.2.2",
    "@angular/language-service": "~7.2.2",
    "@capacitor/cli": "1.1.0",
    "@datorama/akita-ng-router-store": "^3.1.3",
    "@datorama/akita-ngdevtools": "^3.0.2",
    "@ionic/angular-toolkit": "~1.5.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~12.0.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.12.0",
    "protractor": "~5.4.0",
    "ts-node": "~8.3.0",
    "tslint": "~5.17.0",
    "typescript": "~3.1.6"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {}
    },
    "platforms": [
      "android"
    ]
  }
}
```

## Environment

<pre><code>
Angular version: 7.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  node 10
- Platform:  Windows

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Where do you get it? When running `ng serve` it works fine:

![image](https://user-images.githubusercontent.com/6745730/62442247-08916300-b760-11e9-8184-f3466bdb0f95.png)

**Comment by namdien177** [comment]
facing this on Angular/Electron
However, it was a bright red error instead of warning
![image](https://user-images.githubusercontent.com/29449869/62473426-ec76db80-b7ca-11e9-9a93-124d53ec381e.png)

**Comment by hiepxanh** [comment]
[https://github.com/hiepxanh/akita-bug](https://github.com/hiepxanh/akita-bug) That my repository

reproduce step:
- ng new akita-bug
- ng add @datorama/akita
- yes for 3 prompt question

I guest `ng add` causing issue?

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/62478356-1df4a480-b7d5-11e9-9788-67cae27ec027.png)
this image I capture from akita-bug project

**Comment by namdien177** [comment]
> https://github.com/hiepxanh/akita-bug That my repository
> 
> reproduce step:
> 
> * ng new akita-bug
> * ng add @datorama/akita
> * yes for 3 prompt question
> 
> I guest `ng add` causing issue?

can you use Store? I only get this error when using EntityStore.
I was using `ng add` too

**Comment by hiepxanh** [comment]
I use everything normally, just comment `NG_ENTITY_SERVICE_CONFIG` in app.module.ts

**Comment by namdien177** [comment]
> I use everything normally, just comment `NG_ENTITY_SERVICE_CONFIG` in app.module.ts

it's weird that I don't even have that yet still getting the error :sweat_smile:

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/62479750-5944a280-b7d8-11e9-966a-ddfdc6cf5fc8.png)
 that line calling ng-entity-service that causing errors

**Comment by NetanelBasal** [comment]
Thanks for the information. I will check it soon, and let you know.

**Comment by NetanelBasal** [comment]
Please try v1.0.1

**Comment by namdien177** [comment]
seems working fine to me. Thanks 🍾

**Comment by hiepxanh** [comment]
@NetanelBasal  that really smooth complie,  I love it. Thank you for the best plugin, since I use that, I fogot about what ngrx is. I'm so addict this plugin, I cannot start new project without it. best wish to you 💌  
have a nice day
