### ISSUE TITLE
DirtyCheckPlugin constructor missing generic type parameter

### ISSUE THREAD

**Issue by simeyla** [datorama/akita#268]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The constructor for `DirtyCheckPlugin` is missing the generic type for `DirtyCheckParams`

     constructor(protected query: Queries<State>, private params?: DirtyCheckParams, 
                 private _entityId?: any) {

## Expected behavior
When this is changed to `params?: DirtyCheckParams<State>` you get typing on the as intended.

eg. this will now be a compilation error:

        this.dirtyCheck = new DirtyCheckPlugin<ClubEditState>(this.clubEditQuery, 
                         { watchProperty: ['thisDoesntExist'] }).setHead();

May or may not be similar issue with the entity dirty check plugin too.

**Comment by NetanelBasal** [comment]
Hi, thanks. Do you want to contribute and create a PR that fix this?

**Comment by bogusweb** [comment]
@simeyla I apologize for stealing the issue but I was quite bored. I hope that this is not a problem ✌
