### ISSUE TITLE
Schematics unexpected token error

### ISSUE THREAD

**Issue by odahcam** [datorama/akita#271]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Schematics does not works.
```

$ yarn ng g @datorama/akita:as todos
yarn run v1.16.0
$ ng g @datorama/akita:as todos
Unexpected token ] in JSON at position 1052
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behavior
Working schematics.

## Minimal reproduction of the problem with instructions
Install Akita and try to use any schematics.

## Environment

<pre><code>
Angular version: 8.0.6 (cli)

For Tooling issues:
- Node version: 10.16.0
- Platform:  Windows
</code></pre>

**Comment by GrandSchtroumpf** [comment]
Hello, which version of Akita are you using ?
I cannot reproduce. I did : 
```
ng new test-schematics
cd test-schematics
npm install @datorama/akita
ng g @datorama/akita:as todos
```
And it worked fine (node v10.15.0 on Windows10).

From my experience `Unexpected token ]` comes from an issue in your `angular.json` or `nx.json` (if you're using nrwl). Can you try again on a pristine project ?

**Comment by NetanelBasal** [comment]
@GrandSchtroumpf is right. It's working fine with the latest version.

**Comment by odahcam** [comment]
All right, I'll take a look tomorrow morning. It's strange because my Angular CLI throws no error with default schematics, but you still can be right because I didn't verify it.

**Comment by odahcam** [comment]
It really was an `angular.json` problem, trailing commas in different points inside the styles array. It just never come to me that the problem could be `angular.json` since the Angular schematics runs fine. Thanks for the support.
