### ISSUE TITLE
Question: multiple entity store

### ISSUE THREAD

**Issue by eitanfr** [datorama/akita#273]
Before my question, I want to mention that you guys did a great job with this package :)

## I'm submitting a question
I have a use case where I need 2 lists in the same store, For example on the same page I have 2 different lists, let's say users and markers. 
What is the best way to the store the data?
Of course, I can create 2 separate `entityStore`s and `entityQuery`s but it feels redundant because the 2 lists are related logically and related to the same UI, so it would be more comfortable to have 1 store object. 
Another option I thought of, is to create a store object that has 2`entityStore`s as field members, but I am not sure about it.
I tried to look it up in the doc but didn't find information about this use case, So my question is what is the best practice for this scenario? 

Thx

**Comment by NetanelBasal** [comment]
Thanks. Your second solution is right. You can do something like:

```ts
class StoreName {
  users = new EntityStore<UsersState>({});
  markers = new EntityStore<MarkersState>({});
}
```

Same goes for the Query.

**Comment by zhuliminl** [comment]
> Thanks. Your second solution is right. You can do something like:
> 
> ```ts
> class StoreName {
>   users = new EntityStore<UsersState>({}, { name: 'users' });
>   markers = new EntityStore<MarkersState>({}, { name: 'markers' });
> }
> ```
> 
> Same goes for the Query.

can you get more specific code for this question. still I can not get how to organize multiple entity store in one store

**Comment by mhosman** [comment]
Hello team, could you please provide an example of how to use this example? (Store, Service, Query). Thanks!

**Comment by cmalard** [comment]
Looks related to https://netbasal.gitbook.io/akita/general/dynamic-stores :
```js
export class MyService {
  createStore(name: string) {
    const store = new Store(initialState, { name});
    const query = new Query(store);
    return { store, query }
  }  
}
```

**Comment by DmitryEfimenko** [comment]
the above link is broken. It'd be great to see a dedicated section on this in the official [docs](https://datorama.github.io/akita/).

**Comment by AntonGrekov** [comment]
@DmitryEfimenko That looks more like just a dynamic creation of store. I was thinkig about same issue as OP: to combine two or more entity stores under one regular store. So in Redux Tools it would be: MainStore

**Comment by AntonGrekov** [comment]
Is there a way to gropu Stores ? I have two Store Entities in my app: UserList and ProductList which i'd like to group under MarketSection. 

There are many MarketSections so i am unable to create UserList, ProductList stores at root as they will conflict with each other. 
I would like to have State like this

````js
MarketSection1:
    UserList
    ProductList

MarketSection2:
    UserList
    ProductList
````

How do i achive this with Akita ? @NetanelBasal
