### ISSUE TITLE
selectActive should take the same options as selectAll

### ISSUE THREAD

**Issue by KyleW** [datorama/akita#274]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`QueryEntity.selectAll` takes an options argument. `QueryEntity.selectActive` does not. It would be nice if the api matched.

## What is the motivation / use case for changing the behavior?
The difference is a little confusing and the options argument provides a bunch of handy short cuts that I'd like to use in other places.

**Comment by NetanelBasal** [comment]
How things like `sort`, `filterBy`, `asObject`, are related to `selectActive`?

**Comment by NetanelBasal** [comment]
I am closing the issue as it does not valid functionality.

**Comment by KyleW** [comment]
Sorry for the delayed response. It's fine if you want to close, but  . . . yes, I think selectAll and selectActive should take the same arguments. For me, it's just about consistency. If selectAll has an  orderBy option or takes a predicate, then I would expect all the selectors too (selectActive, selectIds, etc, etc.)

This may be a sign that I'm using selectActive differently than it's intended, but it works for my team.
