### ISSUE TITLE
persistState serialisation

### ISSUE THREAD

**Issue by gekitz** [datorama/akita#275]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm using `persistState` with `AsyncStorage` with RN. There is something odd happening when serialising the data. If I check AsnyStorage, that's what I see:
<img width="968" alt="Screenshot 2019-08-14 13 41 04" src="https://user-images.githubusercontent.com/298673/63018492-45b0d000-be99-11e9-8812-c3418fb2285f.png">

The data stored looks quite chaotic and unlike json.

I'm using Akita with version `3.12.1` in another project and serialisation works just fine there.
Not sure if I'm doing something wrong or if there was a change somewhere along the lines.

## Expected behavior
That it's actually serialised as json.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## Environment

<pre><code>
RN: 0.60.5
Akita: 4.9.4

</code></pre>

**Comment by gekitz** [comment]
Note, this could also be an AsyncStorage issue, will check that too.

**Comment by gekitz** [comment]
Note, I don't believe it's AsyncStorage related since when I directly interact with the API stored items look just fine.

**Comment by NetanelBasal** [comment]
Hi, can you share your `AsyncStorage`, please?

**Comment by gekitz** [comment]
I'm using the RN `AsyncStorage`. According to this issue:  https://github.com/react-native-community/async-storage/issues/113 it says in the description that it stores the data in a dictionary on the file system. So far so good. 

That explains the weird representation when we write the data to the storage. The problem happens when we try to load the data on application start from the storage. When we try that, it tries to `deserialize` the data and crashes, because it expects json but it gets this object representation.

**Comment by NetanelBasal** [comment]
Can you tell the data type so we can check why the function returns `false`, please?

**Comment by gekitz** [comment]
I guess there is a general problem. The `RN AsyncStorage` api for getting and setting and item expects that we set an item of type `string` and that we return a `string` from `getItem`.

Which basically means the API expects that the item is stored already in a serialized way. 

An easy solution would be providing a custom implementation of the storage, that basically wraps the AsyncStorage API, serializes and deserializes before it hits AsyncStorage and finally providing this custom implementation to persistState. 

I'll try that and report back.

**Comment by gekitz** [comment]
Yep, exactly what I expected. Wrapping it worked.

```
export class AkitaStorageWrapper {
    public static getItem(key: string, callback?: (error?: Error, result?: string) => void): Promise<any | null> {
        return AsyncStorage.getItem(key, callback).then((value: string | null) => {
            if (value === null) {
                return null;
            }
            return JSON.parse(value);
        });
    }

    public static setItem(key: string, value: any, callback?: (error?: Error) => void): Promise<void> {
        const stringifiedValue = JSON.stringify(value);
        return AsyncStorage.setItem(key, stringifiedValue, callback);
    }

    public static clear(): void {
        AsyncStorage.clear();
    }
}
```

**Comment by gekitz** [comment]
@NetanelBasal thanks for your help.

**Comment by lincolnthree** [comment]
@gekitz Sorry, just seeing this now. I was involved in the discussion regarding this initial change. Just a little background:

I initially spoke with @NetanelBasal about removing the pre-serialization from the persistState API due to the fact that some storage providers will perform an additional serialization step in some native layers (like LocalForage and other databases). This caused some performance overhead (approaching 200%) when Object sizes were large enough.

The solution we landed on was to remove pre-serialization/parsing and allow users to handle it themselves, which, it sounds like you ultimately figured out.

**Comment by lincolnthree** [comment]
Here is the relevant commit: https://github.com/datorama/akita/commit/b182303

**Comment by gekitz** [comment]
@lincolnthree thank you for the explanation. Totally agree, the change makes a lot of sense. It was a little bit confusing for me since I came from an old version where it still worked without any changes in my end. In any case, thanks for sharing the reasoning behind the change. 👍
