### ISSUE TITLE
removeAction doesn't work if the active state is singular (not an array)

### ISSUE THREAD

**Issue by jkossis** [datorama/akita#277]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When trying to remove an entity that has been previously marked as active, the following error occurs:

`ERROR TypeError: state.active.filter is not a function`

I think the issue lies in that the code (found in the subsequent link) assumes that the state stores the `active` property as an array.

https://github.com/datorama/akita/blob/master/akita/src/entityStore.ts#L457

Below is a screenshot of what my store looks like the line above where the error occurs. As noted above, the active property is singular here, and not an array, and therefore does not have the filter method on its prototype.

![akita-issue](https://user-images.githubusercontent.com/1247832/63109822-05fced80-bf58-11e9-9682-113e5d1eebb2.PNG)

## Expected behavior

The entity store properly removes the active status from the entity that has the passed in id.

## Minimal reproduction of the problem with instructions

1) Mark an entity as active with `setActive(...)` (after extending`ActiveState`)
2) Try to call `removeActive(...)`

## What is the motivation / use case for changing the behavior?

It seems to be a valid use case as the active property supports both a singular id and an array of ids.

## Environment

<pre><code>
Angular version: 8.1.1

Browser:
- [x] Chrome (desktop) version 76.0.3809.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Windows

</code></pre>

**Comment by shaharkazaz** [comment]
@jkossis Basically this function was only supported for multi-active (as mentioned in the docs) but in order to be consistent, I added support for singe active as well.
Available from v4.9.6

**Comment by wundo** [comment]
@shaharkazaz I'm experiencing the same issue in 5.2.2, any idea why?

**Comment by wundo** [comment]
I'm in this versions:
```
    "@datorama/akita": "^5.2.2",
    "@datorama/akita-ng-entity-service": "^5.0.0",
    "@datorama/akita-ngdevtools": "^5.0.3",
```
