### ISSUE TITLE
Invalid config used in NgEntityService.get function

### ISSUE THREAD

**Issue by kragoth** [datorama/akita#278]
The call to mapResponse on line 99 in ng-entity-service.ts uses the 'config' variable rather than using the _config variable. This means that if you attempt to do a get({config}) type call where the config contains a mapping function the mapping function is not used.

https://github.com/datorama/akita/blob/1d4d2ee9960337339e5aedf42ece284a1a39b5fd/angular/playground/projects/ng-entity-service/src/lib/ng-entity.service.ts#L99

I believe if the line was changed to:
`
mapResponse(_config);
`
This would fix the problem.

If anyone else runs into this problem you can work around it by doing this:
`
    my-ng-entity-service.get<Array<Type>>(config, config);
`

**Comment by kragoth** [comment]
@NetanelBasal thanks for the quick fix! :)

**Comment by kragoth** [comment]
@NetanelBasal Your patch fixed my issue but, unfortunately the same issue is now on line 113
https://github.com/datorama/akita/blob/33aab4b43980e7c60a783b631746d4e6c9f03050/angular/playground/projects/ng-entity-service/src/lib/ng-entity.service.ts#L113

The catchError is using config instead of _config. Do you want me to raise a new issue?

**Comment by NetanelBasal** [comment]
Oops, releasing a new version with a fix.
