### ISSUE TITLE
Error message when using Query.getEntity 

### ISSUE THREAD

**Issue by heinerlamprecht** [datorama/akita#281]
I'm getting the following error message during compile:

> Argument of type 'string | number' is not assignable to parameter of type 'getIDType'.

the respective code where it happens:

`
search(idLink: ID): E | null {
        return this.query.getEntity(idLink);
}
`

How is it supposed to work?

**Comment by NetanelBasal** [comment]
Can you share the store and the query, please?

**Comment by heinerlamprecht** [comment]
We have several data sources, which all extend a common base:

`export abstract class BaseDataSource<E extends DataItem, S extends EntityState<E>,
    Q extends QueryEntity<S>, T extends EntityStore<S>> implements DataSource {}
`

SampleDataSource:

`export class SampleSource extends BaseDataSource<DataItem, DataItemState, DataItemQuery, DataItemStore> {}`

`export class DataItemState implements EntityState<DataItem> {}`

`export class DataItemStore extends EntityStore<DataItemState> {}`

`export class DataItemQuery extends QueryEntity<DataItemState> {}`

`export interface DataItem {
    id: string;
}`

(additional properties of DataItem skipped)

**Comment by NetanelBasal** [comment]
Can you reproduce the error on Stacklitz, please?

**Comment by NetanelBasal** [comment]
Any news on this issue?

**Comment by heinerlamprecht** [comment]
I’m currently traveling and didn’t have the time yet to prepare anything.  Will be back next week.

**Comment by heinerlamprecht** [comment]
Sorry for the day.  Now I got the time to put is on Stackblitz:

https://stackblitz.com/edit/typescript-fcqqqa

Just open .../data-item/base-data-source.ts.  The editor shows the error for the search function.

**Comment by NetanelBasal** [comment]
```ts
import { EntityState, EntityStore, ID, QueryEntity, getIDType } from '@datorama/akita';

import { DataItem } from './data-item';
import { DataSource, SourceResolver } from './data-source';

export abstract class BaseDataSource<
  Entity extends DataItem,
  State extends EntityState<Entity>,
  Query extends QueryEntity<State>,
  Store extends EntityStore<State>
> implements DataSource {

  store: Store;
  query: Query;

  search(idLink: getIDType<State>): Entity | null {
    return this.query.getEntity(idLink);
  }
}

```
