### ISSUE TITLE
Group Akita's Stores

### ISSUE THREAD

**Issue by CILP** [datorama/akita#282]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently you can define a store and use the name property at the decorator to set the key accessor to that store but will be helpful if akita provides a way to group stores as modules.

## Expected behavior
Something like
@StoreModule({ name: 'MyModuleA' }) or @Bucket({ name: 'MyBucketB' })
or 
@StoreConfig({ name: 'MyStore', module: 'MyModule' })

Why? because when you have multiple projects on an angular project it will be helpful to group by module or by behavior

## What is the motivation / use case for changing the behavior?
Simplify use of akita with multiple modules/projects

**Comment by NetanelBasal** [comment]
I'm not sure what is the use case, and how we should use it?

**Comment by NetanelBasal** [comment]
I still not sure why we need this. You're welcome to discuss your suggestion in our Gitter channel - closing for now.
