### ISSUE TITLE
Group Error/Loading state for any stores (to allow global notification)

### ISSUE THREAD

**Issue by Jak3b0** [datorama/akita#283]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I don't seem to be able to find a way to group errors and/or loading states. 

## Expected behavior
I would like to be able to have a way of identifying if any store are currently loading (to show a global indicator that something is currently happening) and the same for errors. 

I would like to include a loading indicator in my main layout (with the app bar and all) but my stores are located in lazy-loaded modules. Same for the errors. 

## Environment
<pre><code>
Angular version: 8.2.1

**Comment by NetanelBasal** [comment]
Hey, we could add store actions dispatcher, but I still need to think about it:
```ts
describe('storeActions', () => {

  it('should dispatch loading', () => {
    const spy = jest.fn();
    storeActions().subscribe(spy);
    store.setLoading(false);
    expect(spy).toHaveBeenCalledWith({
      storeName: 'articles',
      payload: false,
      type: 'loading'
    });

    store.setLoading(true);
    expect(spy).toHaveBeenCalledWith({
      storeName: 'articles',
      payload: true,
      type: 'loading'
    });
  });

  it('should dispatch error', () => {
    const spy = jest.fn();
    storeActions().subscribe(spy);
    store.setError({ error: 'error' });
    expect(spy).toHaveBeenCalledWith({
      storeName: 'articles',
      payload: { error: 'error' },
      type: 'error'
    });
  });

});
```

**Comment by NetanelBasal** [comment]
Another option is to expose the Queries:

```ts
const loading = Object.keys(queries).map(q => queries[q].selectLoading);
merge(...loading).subscribe();
```

**Comment by GrandSchtroumpf** [comment]
You can create an external service that manage that : 
```typescript
@Injectable({ providedIn: 'root' })
export class LoadingManager {
  private loadingStores = new BehaviorSubject<Record<string, boolean>>();
  public loadingStores$ = this.loadingStores.asObservable();

  update(storeName: string, isLoading: boolean) {
    const loadinStores = this.loadingStores.getValue();
    loadStores[storeName] = isLoading;
    this.loadingStores.next(loadStores);
  }
}
```
And in each query : 
```typescript
export class MyQuery extends Query {
  constructor(protected store: MyStore, loadingManager: LoadingManager) {
    super(store);
    this.selectLoading.subscribe(isLoading => loadingManager(store.storeName, isLoading));
  }
}
```

**Comment by Jak3b0** [comment]
Thank you guys! 

I think having a built in solution might be something useful but the proposed solution is simple and elegant. I will give it a try. :)

**Comment by NetanelBasal** [comment]
Thanks. We will reconsider if there will be a demand — closing for now.
