### ISSUE TITLE
Name transactions

### ISSUE THREAD

**Issue by yarrgh** [datorama/akita#288]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently transactions show up as `@Transaction` in the dev tools.

![image](https://user-images.githubusercontent.com/1577822/63899032-93a8f600-c9b8-11e9-9507-b9025a9266b1.png)

## Expected behavior
Transactions to have a custom name. (ex: `Load Policies`)

## What is the motivation / use case for changing the behavior?
Being able to name a transaction would allow for transactions to be more easily understood and to be found much quicker when debugging using the dev tools

**Comment by NetanelBasal** [comment]
Did you try https://netbasal.gitbook.io/akita/enhancers/devtools#custom-actions?

**Comment by yarrgh** [comment]
`@action()` didn't perform as expected. It actually added an additional item/action to the dev tools when used with a transaction.

`logAction()` however worked beautifully.

Thanks!
