### ISSUE TITLE
How to get loading of firstTime ? while not loading more state

### ISSUE THREAD

**Issue by zhuliminl** [datorama/akita#289]
state loading is useful for pagination. but also the loading first time state is important to set skeleton UI . hope you get what I mean

**Comment by NetanelBasal** [comment]
You can use [selectLoading](https://netbasal.gitbook.io/akita/entity-store/entity-query/loading-state) and [paginatorRef.isLoading$](https://netbasal.gitbook.io/akita/plugins/server-side-pagination).
