### ISSUE TITLE
Cancel uncompleted actions on repeat

### ISSUE THREAD

**Issue by filipjnc** [datorama/akita#29]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Running three actions of the same type in a row will always result in three updates of the store. 

## Expected behavior
The ability to set an option that would cancel the execution of the previous action stream (switchMap behavior).

Maybe something like:
`{ type: '[Todos] Fetch All', cancelUncompleted: true }`

## What is the motivation / use case for changing the behavior?
Clicking three times on the fetch button should normally not end up in three updates of the store.

I am not sure Akita can support this out of the box, but at least a documentation recipe of how can this be achieved with RxJS would be helpful.

**Comment by NetanelBasal** [comment]
It's not related to Akita. You can use the `exhaustMap` operator.
