### ISSUE TITLE
Cache non-entity data in EntityStore

### ISSUE THREAD

**Issue by DaleMatthews** [datorama/akita#291]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I cannot use the built-in cache functionality to cache non-entity data on the EntityStore.

## Expected behavior

Use the `set` method to set non-entity state (such as `filter` in the EntityStore example) that way the `cacheable` helper function works. A `@cacheable` decorator would also be nice to have.

## What is the motivation / use case for changing the behavior?

`filter` might be a saved user preference that you have to fetch once the user logged in. But you may want to lazy-load that preference, as in not fetch it until a component needs it, then cache that state for when the component is reinitialized. I noticed the documentation mentions Store.setCache but I don't see its definition anywhere.

## Environment

<pre><code>
Angular version: 8.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 68.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by DaleMatthews** [comment]
If there's already a simple way to do this or if this is just a bad pattern to follow, I am open to suggestions.

**Comment by NetanelBasal** [comment]
> I cannot use the built-in cache functionality to cache non-entity data on the EntityStore.

What do you mean by saying "non-entity data on the EntityStore"?

**Comment by DaleMatthews** [comment]
I mean the extended state, such as `filter` in the example [here](https://netbasal.gitbook.io/akita/entity-store/entity-store).

**Comment by DaleMatthews** [comment]
Perhaps this feature doesn't make sense. You'd basically be implementing a caching functionality for all stores, and the consumer would have to write their own `isCached` logic for each property. Though Akita could facilitate that. Thoughts?

**Comment by NetanelBasal** [comment]
When the value in the store, it's already cached. Do you read the cache functionality [section](https://netbasal.gitbook.io/akita/entity-store/cache-functionality)?

You can also [persist](https://netbasal.gitbook.io/akita/enhancers/persist-state) it to the local storage.

**Comment by NetanelBasal** [comment]
Oh, I understand. You want it to work outside the entities scope.

**Comment by NetanelBasal** [comment]
You can always call `setHasCache(true)` when you want. In your case, after you add the `filter` into the store.

**Comment by NetanelBasal** [comment]
ping

**Comment by kimdah3** [comment]
I've stumbled upon this post trying to figure out the same kind of pattern. I have entities that needs to be updated and not cached while the ```filter``` should be cachead.

**Comment by NetanelBasal** [comment]
When you update the filter, you should call `setHasCache(true)`

**Comment by kimdah3** [comment]
Okey, something like this?

```
listShipments(): void {
  const filter = this.shipmentQuery.filter;
  this.store.setHasCache(false);
  this.shipmentEndpoint.listShipments(filter).subscribe({
    next: (result: PagedResult<Shipment>) => {
      this.store.set(result.content);
    },
    error: err => (this.store.set([]), this.store.setError(true))
  });
}

updateFilter(filter: Filter) {
  this.store.setHasCache(true);
  this.store.update({ filter });
}
```

**Comment by NetanelBasal** [comment]
What's your use-case? I can't see where you check if the filters in the cache.
