### ISSUE TITLE
Efficient Entity Queries

### ISSUE THREAD

**Issue by jczacharia** [datorama/akita#292]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

What is the most _efficient_ way to select all entities in a store in such a way that if one entity's data changes, only that entity's data will be pushed through the pipe (Akita selector/query)?

I've seen that `this.selectAll()` uses `combineLatest` so that if one entity's data changes, all the entities are pushed through the pipe. This is not an efficient solution since I only want a single subscription for each entity that will not be affected by other entities.

A potential solution I have experimented with is:

```
this.query
      .select(s => s.ids)
      .pipe(
        switchMap(ids => from(ids)),
        mergeMap(id => this.query.selectEntity(id)),
        ...
```
This works well until another entity is added/removed from the store and then the array of ids are pushed though the pipe which then triggers all entities to be reselected.

Is there a way that I can create a query such that it creates a single subscription for each entity and will never reselect a pre-existing entity if another entity is added or another entity's data changes?

**Comment by NetanelBasal** [comment]
> What is the most efficient way to select all entities in a store in such a way that if one entity's data changes, only that entity's data will be pushed through the pipe 

Do you mean something like:

```ts
selectAll().subscribe((data) => {
  data should be the only entity that has been changed?
})
```

**Comment by jczacharia** [comment]
Yes, something like that. I have an application that I want to be performant since it is using a graphics library and I do not want to redraw each item/entity when another entity's data changes or the store adds/removes an entity.

**Comment by NetanelBasal** [comment]
So use [Entity actions](https://netbasal.gitbook.io/akita/entity-store/entity-query/api#entity-actions) and listen to update.

**Comment by jczacharia** [comment]
I was just looking at! I've been using Akita for about 5 months now and this is the first performance-intensive application that I am doing with it so the EntityActions are new to me but it looks like exactly what I need.

Thank you!!! And awesome work with everything!!

**Comment by NetanelBasal** [comment]
No problem. Thanks. Closing for now.
