### ISSUE TITLE
Mistake with Paginator plugin on gitbook documentation 

### ISSUE THREAD

**Issue by bogusweb** [datorama/akita#293]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In gitbook documentation u require use `Paginator` as type of inject, here:
![image](https://user-images.githubusercontent.com/5169399/64617520-eafa8d80-d3de-11e9-9cfc-724913964adf.png)

but when i type like in documentation, tslint show error: 'Paginator' refers to a value, but is being used as a type here.
![image](https://user-images.githubusercontent.com/5169399/64618121-f8644780-d3df-11e9-8759-56e5ae5ced56.png)

## Expected behavior

In playground u use `PaginatorPlugin` as type. So the question is, is this a mistake in documentation or typing?

## What is the motivation / use case for changing the behavior?

Clean and correct documentation

**Comment by NetanelBasal** [comment]
It's a typo in the docs. It should be: `@Inject(CONTACTS_PAGINATOR) public paginatorRef: PaginatorPlugin<ContactState>`. Updating the docs. Thanks.
