### ISSUE TITLE
[CollectionService][Firestore] Deleting a collection and recreating it with new data leads to dead entries in the local cache

### ISSUE THREAD

**Issue by Jak3b0** [datorama/akita#296]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Deleting a collection directly in Firestore and recreating it with new data will leave the local cache with the previous data plus the new items.

## Expected behavior

Only the new items should be in the local cache.

## Minimal reproduction of the problem with instructions

1. Create a collection in Firestore
2. Add some data to it
3. Configure your app to use a `CollectionService` to load the data from firestore
4. Use `persistState` using `localForage` with IndexedDB as the driver
5. Launch the app
6. Close the app (so that a local cache is saved of the data)
7. In Firestore, delete the collection
8. Create a collection with the same name and add some new data to it
9. Launch the app
10. Notice that the old items will still be there and the sync will add the new items leaving the local cache invalid.

## Environment

<pre><code>
Angular version: 8.2.5
Akita: 4.10.4
Akite NG Fire: 1.4.1
Firebase: 6.6.1

**Comment by GrandSchtroumpf** [comment]
Hi, I think this issue is related to how `akita-ng-fire` update the store and not how `akita` persiste data.
If this is the case, can you open an issue here instead : 
https://github.com/dappsnation/akita-ng-fire/issues

**Comment by NetanelBasal** [comment]
I'm closing it. If you found that it's related to Akita itself re-open it.
