### ISSUE TITLE
missing example for sortBy function

### ISSUE THREAD

**Issue by Maxstgt** [datorama/akita#297]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Or you can set it dynamically per `selectAll():``
```
this.products$ = this.sortControl.valueChanges.pipe(
   startWith('Title'),
   switchMap((sortBy) => this.productsQuery.selectAll())
 );
```
## Expected behavior
Or you can set it dynamically per `selectAll()`
You have to return a number just like the [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) function:
```
this.products$ = this.sortControl.valueChanges.pipe(
   startWith('title'),
   switchMap((sortIdentifier) => this.productsQuery.selectAll({ sortBy: (a,b) => {
              switch (sortIdentifier) {
                case 'Title':
                  return a.main.localeCompare(b.main);
   }
}))
 );
```

## What is the motivation / use case for changing the behavior?
It would be more clear what the capabilities are for the sortBy function.

**Comment by NetanelBasal** [comment]
Fixed. Thanks.
