### ISSUE TITLE
Need help with master/child with lazy loading structure

### ISSUE THREAD

**Issue by Jak3b0** [datorama/akita#304]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

Hi,

I am trying to setup my stores/states for my needs and I am not sure what would be the best way to do it. 

To put you in context, here is the structure I am trying to achieve:

#### Fields
  - accountId
  - name
  - email

  - sessions (external source A - Loaded on demand)
    #### Fields
    - date
    - value

    #### States
    - isLoading (from the store/query)
    - error (from the store/query)

    #### Caching
    - Local storage persistence
    - Caching with TTL

  - plannerStatus (external source B - Loaded on demand)
    #### Fields
    - date
    - lateTasksCount
    - unplannedTasksCount

    #### States
    - isLoading (from the store/query)
    - error (from the store/query)

    #### Caching
    - Local storage persistence
    - Caching with TTL

  #### States
  - isLoading (from the store/query)
  - error (from the store/query)
  
  #### Caching
  - Local storage persistence
  - Caching with TTL

Basically, I have a model (Account) that expose properties. For this part, I understand that an `EntityStore` is what I need since I will be loading all the accounts at once and I want to be able to easily get just one.

Where things are getting confusing for me is for the `sessions` and `plannerStatus` field of the `account` model. I would like to expose those as stores to have states (loading, error) and the possibility to have caching (local storage and cache with TTL) on it. 

Also, those will be loaded on demand only and just for a specific account at a time. 

I saw and was pointed to use the `Entity UI Store` but, as it seems to be what I need, it does not allow me to have multiple sub-store per store (there is only one `ui` property) preventing me from handling caching and states independently.

Is there something built-in that could help me achieve this? Am I going in a wrong direction? Do you have some kind of tips that would help me?

Thank you!

**Comment by NetanelBasal** [comment]
You can create a `SessionStore` which will be an `EntityStore` and link it to an account.

**Comment by Jak3b0** [comment]
What do you mean by "link it to an account"?

**Comment by NetanelBasal** [comment]
```ts
Session = {
  accountId: number
}
```

**Comment by Jak3b0** [comment]
Ok, so basically, there is no direct link between the Account entity and the AccountSession entity (except for the ID). I am ok with this (I just though you were linking the store to an actual account entity to match something like in the structure I posted above).

The thing that confuses me with having one EntityStore for all the account sessions is that the store seems to be built to load all the entities at once (except when working with server-side paging). In my case, I only want to load the sessions for an account when I load the details for that account. So if I go to the detail of account A, the store will be set to loading (even if only loading the sessions for account A). This could lead to mismatch in the loading state of the store if I navigate to account B while A is not finished loading (there is no ref-count on the loading state, just a boolean) or having the store in error only because one of the account/sessions were not able to load.

Also, since I am interested in using [caching](https://netbasal.gitbook.io/akita/entity-store/cache-functionality) to avoid performing requests multiple time, I do not see how I could setup the store properly. 

So far, I am creating a dynamic store for each account/sessions (the entity key is `accountId` and there is a sessions property of type `AccountSession[]`). I created a service to handle the creation of in-memory singleton of those stores. This is working great so far but I am not sure if having 1000 stores could cause me issues in the long run (like with local storage persistence).

Could you shed some light for me please? :)

**Comment by NetanelBasal** [comment]
You need to have a `UIStore` for each `EntityStore`:

```ts
@StoreConfig({ name: 'accounts' })
export class AccountsStore extends EntityStore<AccountsState> {
  ui: EntityUIStore<AccountsUIState>;

  constructor() {
    super();
    this.createUIStore().setInitialEntityState({ isLoading: false, isCached: false });
  }

  setLoadingAccount(id, isLoading) {
    return this.ui.update(id, { isLoading } );
  }
}

@StoreConfig({ name: 'sessions' })
export class SessionsStore extends EntityStore<SessionsState> {
  ui: EntityUIStore<SessionsUIState>;

  constructor() {
    super();
    this.createUIStore().setInitialEntityState({ isLoading: false, isCached: false });
  }

  setLoadingSession(id, isLoading) {
    return this.ui.update(id, { isLoading } );
  }
}
```

Then you can query each one of the UI entity's state:
```ts
export class SessionsQuery extends QueryEntity<SessionState> {
  ui: EntityUIQuery<SessionsUIState>;

  constructor(protected store: SessionStore) {
    super(store);
    this.createUIQuery();
  }

  isLoadingSession(id) {
    return this.ui.getEntity(id).isLoading;
  }
}
```

**Comment by NetanelBasal** [comment]
I'm closing the issue. If you have any further questions, ask them on Gitter, please. Thanks.
