### ISSUE TITLE
[Question] Use DI into the EntityStore class

### ISSUE THREAD

**Issue by C0ZEN** [datorama/akita#305]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other
</code></pre>

## Question
Is it possible to use the DI when creating the store class ?

I want to use the `akitaPreAddEntity` hook with a service inside it provided inside the constructor of the store class.  
Nevertheless, since the store class must be created by hand with `new`, how can I inject the Angular dependencies ?

## Example
```typescript
const initialState = {
  active: null
};

@StoreConfig({
  name: 'dummy-name'
})
export class DummyStore extends EntityStore<DummyState> {

  public constructor(
    private dummyLoggerService: DummyLoggerService
  ) {
    super(initialState);
  }

  public akitaPreAddEntity(newDummy: Dummy): Dummy {
    this.dummyLoggerService.debug('this is a dummy log');

    return newDummy;
  }
}

export const DUMMY_STORE = new DummyStore();
```

Obviously, the problem here is `new DummyStore();` which requires the `dummyLoggerService` token as argument.  
Is there a way to achieve it ?

Thanks !

## Environment
<pre><code>
Angular version: 8.2.8
</code></pre>

**Comment by NetanelBasal** [comment]
Why you create the store manually?

**Comment by C0ZEN** [comment]
Thanks for the reply so soon.  
I create the store instance like it was done in the documentation (fresh v2 of akita).  
It seems that this is no longer the way to do it from the doc though...

**Comment by NetanelBasal** [comment]
If you are using Akita CLI, you need to set the template to `angular`. https://github.com/datorama/akita/tree/master/cli#base-path

**Comment by C0ZEN** [comment]
Well I will made some changes asap.  
I see that now the store is provided from the constructor so it should do it, nice work and thanks for asking the real question here.  
I do not use the CLI nevertheless I use the `ng update` command so it could have been a schematics issue perhaps ?

**Comment by C0ZEN** [comment]
I changed the way to create the store instance but I still have a problem.  
I used the debugger to check if the constructor received the right tokens and it is.

```typescript
const initialState = {
  active: null
};

@StoreConfig({
  name: 'dummy-name'
})
export class DummyStore extends EntityStore<DummyState> {

  public constructor(
    private dummyLoggerService: DummyLoggerService
  ) {
    super(initialState);
  }

  public akitaPreAddEntity(newDummy: Dummy): Dummy {

    // this is undefined here
    this.dummyLoggerService.debug('this is a dummy log');

    return newDummy;
  }
}
```

Do you have any why `this` seems not available inside the hooks ?  
Could be something from my implementation but at this point I doubt it.

Thanks.

**Comment by NetanelBasal** [comment]
It's a JS concept. You need to use `bind`.

`this.akitaPreAddEntity = this.akitaPreAddEntity.bind(this)`

**Comment by C0ZEN** [comment]
Thanks again for the fast reply and as a matter of fact, the final solution.  
Here is the final working exemple if someone has the same need.

```typescript
const initialState = {
  active: null
};

@StoreConfig({
  name: 'dummy-name'
})
export class DummyStore extends EntityStore<DummyState> {

  public constructor(
    private dummyLoggerService: DummyLoggerService
  ) {
    super(initialState);
    this.akitaPreAddEntity = this.akitaPreAddEntity.bind(this);
  }

  public akitaPreAddEntity(newDummy: Dummy): Dummy {
    this.dummyLoggerService.debug('this is a dummy log');

    return newDummy;
  }
}
```

**Comment by ntziolis** [comment]
@NetanelBasal Would it be possible todo the binding in the base class as using `this` inside these methods is a very common use case and binding manually seems like boilerplate code that could easily be forgotten?

**Comment by NetanelBasal** [comment]
I would love to see a PR.

**Comment by ntziolis** [comment]
My understanding of this part of js is limited so my approach might be a bit naive of just dumping this line into the constructor of the base blass:
```
this.akitaPreAddEntity = this.akitaPreAddEntity.bind(this);
```
On the other hand when thinking about how angular handles OnInit etc with no need todo binding it feels like there is a more robust & elegant way to handle these overrides. On the other hand maybe angular does the binding behind the curtains.

Any pointer is welcome.
