### ISSUE TITLE
synchronous store update in query observable

### ISSUE THREAD

**Issue by xstex** [datorama/akita#307]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
If store updates are issued synchronously inside observables (of queries of the same store), the resulting state is unchanged sometimes.

## Expected behavior
Not sure if it is a bug in the calling code, but I would expect the store to update.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/akita-ste-test
If you click on 'next number' button, the first time the store stays at 0.
If you update store with a settimeout (by swapping comment on lines 31,32 of number.component), then it works.

I investigated the code a bit and actually the store gets updated to 1, then, since we are still in the requestNext update (which is only updating the boolean field) it writes back the previous 0 value. Not sure why on subsequent calls it works, though...

## Environment
<pre><code>
Angular version: any (7, 8)
Browser: any
</code></pre>

**Comment by NetanelBasal** [comment]
The reason is that your code synchronous. You update the store to `true` and then to `false` on the same tick.

**Comment by xstex** [comment]
so, is it just a bad store design or the fact that query observer should never synchronously invoke the relative service? In the latter case it should be explicitly warned in the documentation. Or it could be guarded against by always notifying the query on the next tick.

(btw, the update of the requestNext attribute to false is not triggering any action, since the selectRequestNext$ query filters only true values. it's the selectNumber$ observable that receives 1 and then 0 in the same tick)

**Comment by NetanelBasal** [comment]
> Or it could be guarded against by always notifying the query on the next tick.

It's not the responsibility of Akita.

Join Akita's Gitter channel for any further questions. Thanks :)

**Comment by Sidewinder1138** [comment]
I can't help but agree that a note/warning about this would be helpful in the documentation. I was really tripped up by this. Related is #205 .

**Comment by NetanelBasal** [comment]
Where do you think we should add this?
