### ISSUE TITLE
Schematics generate service outside of state folder

### ISSUE THREAD

**Issue by DK8ALREC** [datorama/akita#309]
## I'm submitting a...
<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When generating a new feature with the akita schematics like this:
`ng g @datorama/akita:feature test`

it generates the following files:
CREATE src/app/state/test.store.ts (375 bytes)
CREATE src/app/state/test.query.ts (307 bytes)
CREATE src/app/test.service.ts (133 bytes)    
CREATE src/app/state/test.model.ts (203 bytes)

## Expected behavior
I expected the store, query and service to all be generated inside the state folder.

## Minimal reproduction of the problem with instructions
Run `ng g @datorama/akita:feature test`.

Pick 'Default'.

## What is the motivation / use case for changing the behavior?
The [documentation](https://netbasal.gitbook.io/akita/general/application-structure) recommends structuring projects like this:
- todos
  - state
    - todos.query.ts
    - todos.store.ts
    - todos.service.ts
  - todos.module.ts
  - todos-page.component.ts
  - todo
    - todo.component.ts 
    - todo.component.html
    - todo.component.scss
    - todo.component.spec.ts     

## Environment

<pre><code>
Angular version: 8.2.8
 
For Tooling issues:
- Node version: 10.13.0
- Platform:  Windows
</code></pre>

**Comment by NetanelBasal** [comment]
This is a regression, thanks.

**Comment by DK8ALREC** [comment]
I have edited the report to be a regression.

**Comment by DK8ALREC** [comment]
I used Default.
