### ISSUE TITLE
Docs: memoized / combined selectors

### ISSUE THREAD

**Issue by filipjnc** [datorama/akita#31]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
No examples in the docs about combining selectors in a memoized way.

## Expected behavior
There should be a mention of memoization / combination of selectors. There is a slight hint given in your article on working with normalized data (`combineLatest`). Yet that still left me with a couple of question marks:
1. Is `combineLatest `enough to provide an efficient memoized selector?
2. Is `auditTime `absolutely necessary and what kind of trick is `auditTime(0)`?

If both `combineLatest `& `auditTime `are needed in >90% of the cases, I would suggest creating a `createSelector()` method that wraps everthing up for the user.  

## What is the motivation?
Minimizing the boilerplate in Query services and the deterrence across the audience with no deep understanding of RxJS.

**Update:**
After more digging I found the use case for `auditTime(0)`. It's basically a performance boost in case of concurrent updates in the selectors being combined. Basically a substitute for `@transaction` when the latter is not applicable. The following chart would be helpful in the docs if the team decides for not implementing a `createSelector()` method:
https://user-images.githubusercontent.com/16118391/43370518-983476a0-9380-11e8-980c-828a8da819d0.png

**Comment by NetanelBasal** [comment]
`auditTime()` is not a hack, it's a powerful selector that helps with the specific case I mentioned in the article. 

This is the power of Akita; we don't need `reselect`, we just need RxJS.

**Comment by NetanelBasal** [comment]
Will keep writing more blog posts.
