### ISSUE TITLE
Update the docs to include new features in 4.9.0

### ISSUE THREAD

**Issue by KyleW** [datorama/akita#310]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The latest version of the docs on https://netbasal.gitbook.io/akita/ is 4.7.0. The latest version of Akita is 4.10.8.

The last several versions seem to be exclusively bug fixes which may not require doc updates, but there are some new schematics and cli features introduced in 4.9.0 that are currently undocumented.

At the least, we should bump the version on the docs to indicate that they are still current.

## What is the motivation / use case for changing the behavior?
The docs are great. Let's keep them up to date.

**Comment by NetanelBasal** [comment]
Thanks, done.
