### ISSUE TITLE
[PaginationPlugin] return type of getPage() is unknown

### ISSUE THREAD

**Issue by cbb-it-minds** [datorama/akita#311]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
return type of `PaginatorPlugin<Todo>.getPage()` gives the following type-error:
`Observable<PaginationResponse<unknown>>` is not assignable to type `Observable<PaginationResponse<Todo>>`

![image](https://user-images.githubusercontent.com/53167185/66759433-8bd9de00-eea0-11e9-95ba-125ce706b1f0.png)

## Expected behavior
expected return type should be State not unknown:
`Observable<PaginationResponse<Todo>>`

## Minimal reproduction of the problem with instructions
1. Open `todos.component.ts`
2. Hover over `getPage` on line 32: `return this.paginatorRef.getPage(req)`
3. Observe type is `PaginationResponse<unknown>` expected  `PaginationResponse<Todo>`

https://stackblitz.com/edit/github-ekomtg

## What is the motivation / use case for changing the behavior?
Types should be proper

## Environment

akita version: 4.10.8

**Comment by NetanelBasal** [comment]
You should pass the whole state:
```ts
private paginatorRef: PaginatorPlugin<TodosState>
```

**Comment by cbb-it-minds** [comment]
Thanks you @NetanelBasal 

The documentation implies otherwise :)

https://gist.github.com/shaharkazaz/3a416c0beec77e09065a805098d78c44#file-contacts-page-component-ts

**Comment by NetanelBasal** [comment]
https://netbasal.gitbook.io/akita/plugins/server-side-pagination
