### ISSUE TITLE
ActiveState returns null/undefined when none are active

### ISSUE THREAD

**Issue by snebjorn** [datorama/akita#312]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`getActiveId`, `getActive`, `selectActiveId` and `selectActive` are defined as

```ts
getActiveId(): ID
getActive(): E
selectActiveId(): Observable<ID>
selectActive(): Observable<E>
```

https://netbasal.gitbook.io/akita/entity-store/entity-store/active-state#getters

However `getActiveId`/`selectActiveId` returns `null` and `getActive`/`selectActive` returns `undefined` when there are none active.

Also calling `EntityStore.set(...)` clears the active. I agree that's the correct behavior. But it's not mentioned in the documentation.

## Expected behavior

While I prefer `undefined`* over `null`, the latter appears to be the intended value. So this would be the expected.

```ts
getActiveId(): ID | null
getActive(): E | null
selectActiveId(): Observable<ID | null>
selectActive(): Observable<E | null>
```

*) any chance for `undefined` support 😃❓ 
## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/github-omu5du

Goto the [TODO page](https://github-omu5du.stackblitz.io/todos) and click the buttons to observe the value and type of `active`.

**Comment by NetanelBasal** [comment]
I prefer not to change it as it will be a breaking change. I'm not sure why you need this? You can check `isNil` on both.

**Comment by snebjorn** [comment]
It's not a breaking change because it currently behaves like this.

See 
![image](https://user-images.githubusercontent.com/1266245/66990482-95dd2600-f0c6-11e9-91e8-5eaea05683d6.png)

The type change could be argued that it's a breaking change. But the people using the active selectors will have broken code because the type is incorrect. So they'll be "forced" to fix their broken code :)

**Comment by NetanelBasal** [comment]
Types changes are a breaking change. I will consider it for V5. Thanks.
