### ISSUE TITLE
More content for the "Core Concepts"/"The Service" chapter of the documentation.

### ISSUE THREAD

**Issue by afluegge** [datorama/akita#313]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Documentation currently states:
_"Akita recommends using a service rather than call the store methods directly by a component."_

## Expected behavior
Some more depth to the issue.  Why is Akita recomending it? Why not using the Store directly?  Why show the samples that Query is used directly? Why not also using Query indirectly through the service?

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
A component doesn’t need to know its data source, so we recommend not to inject the store inside components, but have store updates pass-through service.

The component only should know how to get the data, and therefore it injects the Query.

This rule isn't written in stone. I saw people that encapsulate both the Store and the Query behind a Service and use it. That approach is totally valid. 

Here is one example from Robert Dey:

> After I repeated myself in many components, I decided to create services per domain(= store) that handle getting/setting data in the store/backend. Of course, there is still only one direction: data is requested from the backend -> is updated in the store -> is streamed to subscribing components. Components change data -> data is updated in the backend -> is updated in the store... So far, it works fine.

That's the beauty of Akita. You can do what works best for you.
