### ISSUE TITLE
Cacheable() not working

### ISSUE THREAD

**Issue by Disane87** [datorama/akita#315]
## I'm submitting a...
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Support request
- [ ] Other... Please describe:

## Current behavior
Actually I've written a dataservice which contacts my api to get data from it. For this case a service is extended from the `data.class.ts`:

```ts
import { HttpClient } from '@angular/common/http';
import { cacheable, EntityState, EntityStore, QueryEntity } from '@datorama/akita';
import { Observable, of } from 'rxjs';
import { tap } from 'rxjs/operators';

export class Data<T> {

  private readonly API_URL = 'http://localhost:3000/api';
  private _request: Observable<any>;

  constructor(private query: QueryEntity<EntityState<T>, T>, private endpoint: string, private http: HttpClient) {

  }
  public get(_id?: string): Observable<T> {
    return this.call(HttpMethod.get, _id);
  }

  private call(method: HttpMethod = HttpMethod.get, id?: string, data?: T): Observable<T> {
    let request$: Observable<any>;
    const mockData = { name : 'test-product' }

    if (this.query.getHasCache()) {
      console.log(`${this.endpoint} from cache`);
    } else {
      console.log(`${this.endpoint} not from cache`);
    }

    switch (method) {
      case HttpMethod.get: request$ = of(mockData).pipe(tap(this.updateStore)); break;
    }
    return cacheable(this.query.__store__, request$);
  }
  
  private updateStore = (data: any) => this.query.__store__.update(data);
}

enum HttpMethod {
  get,
  post,
  patch,
  delete
}

```

A proper Service would be created by me like this (`product.service.ts`):
```ts
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Data } from '../classes/data.class';
import { Product } from './models/product.model';
import { ProductQuery, ProductStore } from './stores/product.store';

@Injectable({
  providedIn: 'root'
})
export class ProductService extends Data<Product> {
  constructor(_store: ProductStore, _query: ProductQuery, http: HttpClient) {
    super(_query, 'config', http);
  }
}

```

My `product.store.ts`:
```ts

import { Injectable } from '@angular/core';
import { EntityState, EntityStore, QueryEntity, StoreConfig } from '@datorama/akita';
import { Product } from '../models/product.model';

export interface ProductState extends EntityState<Product> {

}

@StoreConfig({ name: 'products' })
@Injectable({
  providedIn: 'root'
})
export class ProductStore extends EntityStore<ProductState, Product> {
  constructor() {
    super();
  }
}


@Injectable({
  providedIn: 'root'
})
export class ProductQuery extends QueryEntity<ProductState, Product> {
  constructor(protected store: ProductStore) {
    super(store);
  }

  get(): Promise<ProductState> {
    return this.selectFirst().toPromise();
  }
}

```

My `product.model.ts`
```ts
import { ID } from '@datorama/akita';

export interface Product {
  _id: ID;
  name: string;
}

export function createProduct({ name }: Partial<Product>) {
  return {
    name
  } as Product;
}
```

How I query the data: 
```ts
import { Component } from '@angular/core';
import { Observable } from 'rxjs';
import { ProductQuery, ProductState } from './shared/stores/product.store';
import { ProductService } from './shared/product.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  constructor(private productQuery: ProductQuery, private productService: ProductService){}
  productFromService: Promise<ProductState>;
  productFromQuery: Promise<ProductState>;

  ngOnInit(){
    
    // Product is filled
    this.productFromService = this.productService.get().toPromise();

    // Product is not filled
    this.productFromQuery = this.productQuery.get();
  }
}

```

In 99% of my use case, the data is retrived by the dataservice, so I prefer the hard wired way to get them over a query but with this implementation, there is actually data in the `localStorage` (because I presisted it) but it seems there is no data in the store (when it's cached). The service always returns the data from the dataservice, but the query seems to be empty (especially the store).

## Expected behavior
The cached instance of the data should be returned.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/github-kfnhy2

## What is the motivation?
I want to reduce the boilerplate code for a small project.

## Environment

@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
Browser:
- [x] Chrome (desktop) version 77.0.3865.120
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.16.3
- Platform:  Windows x64

**Comment by NetanelBasal** [comment]
You need to call `setHasCache(true)`:

```ts
private updateStore = (data: any) => {
   this.query.__store__.setHasCache(true);
   this.query.__store__.update(data);
};
```

Only the `set` method calls it internally.

**Comment by Disane87** [comment]
> ```ts
> private updateStore = (data: any) => {
>    this.query.__store__.setHasCache(true);
>    this.query.__store__.update(data);
> };
> ```
Oh wow, thanks for the really fast reply. Really appreciate this!
Updated the stackblitz according to this. but as you can see, the data is empty from the `service`the data from the query is `null`.

**Comment by NetanelBasal** [comment]
You have several issues:
1. You need to change the `idKey` to `_id`. https://netbasal.gitbook.io/akita/entity-store/entity-store/entity-id

2. You are using `toPromise` which resolved once - remove it.

**Comment by Disane87** [comment]
> You have several issues:
> 
> 1. Based on your model, you need to change the `idKey` to `_id`. https://netbasal.gitbook.io/akita/entity-store/entity-store/entity-id

For simplicity I've changed this to the default `id`.

> 2. You are using `toPromise`, which resolved once - remove it.
I actually removed all `toPromise` but the only thing which has changes it, that there is not data from the service.

The query returns nothing as well.
I guess there is something strange with the store, but I don't get whats missing at all.

**Comment by NetanelBasal** [comment]
You are working with entities. You need to call `this.query.__store__.set/add(data)`, not `update`.

**Comment by Disane87** [comment]
> You are working with entities. You need to call `this.query.__store__.set/add(data)`, not `update`.

Doh! That makes sense. Sorry for bothering you with that 😀

**Comment by agroves333** [comment]
> You need to call `setHasCache(true)`:
> 
> ```ts
> private updateStore = (data: any) => {
>    this.query.__store__.setHasCache(true);
>    this.query.__store__.update(data);
> };
> ```
> 
> Only the `set` method calls it internally.

@NetanelBasal Can you update the docs from `Store.setCache` to `Store.setHasCache`?

https://netbasal.gitbook.io/akita/entity-store/cache-functionality

**Comment by NetanelBasal** [comment]
Sure, thanks.
