### ISSUE TITLE
[REQ][NgEntityService] HttpConfig.mapResponseFn should have access to HttpResponse

### ISSUE THREAD

**Issue by snebjorn** [datorama/akita#319]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently `mapResponseFn` only have access to the response body.

## Expected behavior
Would be handy if it had access to the entire response.

## What is the motivation / use case for changing the behavior?
When pairing NgEntityService with PaginatorPlugin it's sometimes needed to access headers for stuff like `X-Total-Count`.

```ts
this.paginatorRef.getPage(() =>
  this.myEntityService.get({
    mapResponseFn: (res: HttpResponse<IEntity[]>): PaginationResponse<IEntity> => ({
      currentPage: 1,
      data: res.body,
      lastPage: 1,
      perPage: 10,
      total: res.headers.get('X-Total-Count'),
    })
  })
);
```

## Environment

<pre><code>
Others:
"@datorama/akita": "4.10.9",
"@datorama/akita-ng-entity-service": "1.1.1",
</code></pre>

**Comment by snebjorn** [comment]
Hmm, I can't find a way to access the response headers in the current implementation of NgEntityService.

**Comment by snebjorn** [comment]
I found an undocumented workaround

```ts
this.paginatorRef.getPage(() =>
  this.myEntityService.get({
    mapResponseFn: (res: HttpResponse<IEntity[]>): PaginationResponse<IEntity> => ({
      currentPage: 1,
      data: res.body || [],
      lastPage: 1,
      perPage: 10,
      total: Number(res.headers.get('X-Total-Count')),
    }),
    observe: 'response', // <----- this
  })
);
```

**Comment by NetanelBasal** [comment]
As you said, both write to the store, so they can't work together.

**Comment by NetanelBasal** [comment]
Make the HTTP call without using `NgEntityService`.

**Comment by snebjorn** [comment]
@NetanelBasal 
they can't work together, fair enough.

But would you be open to a PR it?

**Comment by NetanelBasal** [comment]
What's in your mind?

**Comment by snebjorn** [comment]
Either a config flag that skips store writes, or adding overrideable hooks to the NgEntityService so you can control what happens with the response, like the store writes

**Comment by NetanelBasal** [comment]
Ok, go for it.
