### ISSUE TITLE
akita/cli barrel circular dependency 

### ISSUE THREAD

**Issue by filipjnc** [datorama/akita#32]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Because of the barrel index files, I always get circular dependency warnings at compile time. Example: 
1. `movies/state/index.ts` imports `movies/state/movies.service.ts`
2. The latter imports `actors/state/actor.model.ts` via barrel `actors/state/index.ts`
3. `actors/state/index.ts` imports `actors/state/actors.query.ts`
4. The latter imports `movies/state/movies.query.ts` via barrel `movies/state/index.ts`
5. Three circular dependency warnings 😞 

Such cases are unfortunately very common and the barrel files create more unconviniences than they help. Have you encountered such cases and how do you go around with it? Do you just remove the barrel? Thanks!

PS. Are the missing line breaks around `providedIn: 'root'` in the CLI for Store intentional?
PPS. Is there a slack/gitter room for asking such small questions?

**Comment by NetanelBasal** [comment]
We consider removing the barrel file. We are going to release Angular schematics support and will not include it. 

> Are the missing line breaks

Not sure what you mean.

> Is there a slack/gitter room

We'll open soon, meantime you can ask here.

**Comment by filipjnc** [comment]
The entity-store.tpl contains `@Injectable({ providedIn: 'root' })` whereas in other services and also in the Angular docs `@Injectable({
providedIn: 'root'
})`

**Comment by NetanelBasal** [comment]
One line makes the code shorter.

**Comment by filipjnc** [comment]
Agree. Then it would make sense to have it also in one line in the Query and Service templates 😊
