### ISSUE TITLE
Observable doesn't update Angular template as expected

### ISSUE THREAD

**Issue by ZaLiTHkA** [datorama/akita#320]
>**Disclaimer:** This is my first time using Akita and I'm also only just getting started with Observables, so this may very well just be a big misunderstanding on my part...

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Using the instructions in both [this tutorial](https://engineering.datorama.com/ui-state-management-made-easy-with-akita-and-angular-6e460566ec7c) and the official documentation, I created an `EntityStore` in my Ionic 4 Angular app.

My research resulted in the following relevant code snippets:

```ts
// peripheral.store.ts

export interface PeripheralState extends EntityState<Peripheral> {}

@Injectable({ providedIn: 'root' })
@StoreConfig({ name: 'peripheral', resettable: true })
export class PeripheralStore extends EntityStore<PeripheralState> {
  constructor() {
    super();
  }
}
```

```ts
// peripheral.query.ts

@Injectable({ providedIn: 'root' })
export class PeripheralQuery extends QueryEntity<PeripheralState> {
  constructor(protected store: PeripheralStore) {
    super(store);
  }
}
```

```ts
// peripheral.service.ts

@Injectable({ providedIn: 'root' })
export class PeripheralService {
  constructor(
    private peripheralStore: PeripheralStore
  ) { }

  add(peripheral: Peripheral) {
    this.peripheralStore.add(peripheral);
  }
}
```

The following Ionic component is the main landing page of my app, so I'm **not** using lazy-loading for this one. Take special note of the `DEV:` comments below.

```ts
// home.page.ts

export class HomePage implements OnInit {
  devices$: Observable<Peripheral[]>;

  constructor(
    private ngZone: NgZone,
    private ble: BLE,
    private peripheralService: PeripheralService,
    private peripheralQuery: PeripheralQuery
  ) { }

  ngOnInit(): void {
    this.devices$ = this.peripheralQuery.selectAll();

    // DEV: I used the following simply to inspect changes on the observable as it appears:
    // this.devices$.subscribe((data) => {
    //   console.log('new data found:', data);
    // });
  }

  ionViewDidEnter() {
    this.startDeviceScan();
  }

  startDeviceScan() {
    this.ble.isEnabled().catch(() => {
      // if Bluetooth is not already enabled, prompt the user to turn it on
      return this.ble.enable();
    }).then(() => {
      // now start the scanning process
      this.ble.scan([], 10).subscribe((peripheral: Peripheral) => {
        console.log('found Bluetooth peripheral:', peripheral);
        if (peripheral.name && peripheral.name === 'CUSTOM_DEVICE_IDENTIFIER') {

          // DEV: with this, my template only updates after I navigate to a different tab and back to "Home":
          this.peripheralService.add(peripheral);

          // DEV: with this, my template updates as soon as this method runs:
          this.ngZone.run(() => {
            this.peripheralService.add(peripheral);
          });

        }
      }, (error) => {
          console.error('error in BLE scan:', error);
      });
    });
  }
}
```

```html
<!-- home.page.html -->

<pre>{{ (devices$ | async) | json }}</pre>
```

## Expected behavior

As per the documentation and multiple tutorials, I would expect *not* to need to wrap my `this.peripheralService.add(peripheral)` call in `this.ngZone.run()`.

Am I misunderstanding something here? Do I need to use `NgZone` simply because I'm building an Angular app? I've only seen suggestions to do this where other people have complained about templates not updating, I don't see any mention of it in the docs, tutorials or demo "skeleton" app templates that I've found.

## Minimal reproduction of the problem with instructions

Note: I haven't used the `akita-issue-seed` on Stackblitz to try recreate this, simply because I can't run the Ionic Native "BLE" plugin there.. I suspect what I'm experiencing might be related to the fact that my Akita store `add` call is inside the subscription to the observable returned by `this.ble.scan()`.

## Environment

<pre><code>
Angular version: 8.2.13

Browser:
- [ ] Chrome (desktop) version XX
- [x] Chrome (Android) version 78.0.3904.62
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15.1
- Platform: Windows 10 Pro

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
It doesn't seem like something related to Akita. If you could create a reproduce, I will try to help.

**Comment by ZaLiTHkA** [comment]
Hi @NetanelBasal, I found a few examples of using Observables in Angular last night that also wrapped actions inside a subscription with `NgZone.run()`..

So just for clarification (considering my first note in the issue description), this would be something related to Observables in general then, yes?

**Comment by NetanelBasal** [comment]
Yes, it's not related to Akita.

**Comment by ZaLiTHkA** [comment]
Cool beans, thanks. :)
