### ISSUE TITLE
Select on query returns delayed values, different from what's in the store

### ISSUE THREAD

**Issue by FunnyGhost** [datorama/akita#321]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have a Query with this property:
<pre><code>
  rentingWizardPercentage$ = this.select(
    (state: AddACarState) => state.rentingWizardPercentage
  ).pipe(tap(data => console.log('select new renting wizard percentage', data)));
</code></pre>
I'm logging here so I can see which values go through

Then, in my component I do this:
<pre><code>
    this.query.rentingWizardPercentage$
      .pipe(tap(data => console.log('ngOnInit new renting wizard percentage', data)))
      .subscribe();
</code></pre>
Same here. Logging to see what comes in.

Now, I'm calling update on the store with rentingWizardPercentage 57, 86 and then 100.
If I check the Redux developer tools in the browser it says that the value in store is 100.
However, the logs that I get are: 
<pre><code>
set percentage complete 57
select new renting wizard percentage 57
ngOnInit new renting wizard percentage 57
set percentage complete 86
select new renting wizard percentage 86
ngOnInit new renting wizard percentage 86
select new renting wizard percentage 57
ngOnInit new renting wizard percentage 57
select new renting wizard percentage 86
ngOnInit new renting wizard percentage 86
set percentage complete 100
select new renting wizard percentage 100
ngOnInit new renting wizard percentage 100
select new renting wizard percentage 86
ngOnInit new renting wizard percentage 86
</code></pre>

So the last value that comes through select is 86. For some reason, it keeps going back 1 value and I don't understand why.

## Expected behavior

I am expecting the values that go through select to be 50, 86, 100. In this order.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [ ] Chrome (desktop) version 78.0.3904.70 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.14.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
It's hard to tell. Can you provide a stackblitz demo, please?

**Comment by FunnyGhost** [comment]
I'm trying but I can't reproduce. I also added breakpoints everywhere I do store.update and where the select fires a new value. 
What I saw is that the select breakpoint is triggered twice with 2 different values without any store.update being called in between. That's weird, right? Feels like there's a throttleTime somewhere.

**Comment by FunnyGhost** [comment]
Also the fact that the store actually has 100 as the value and not 86 makes it super weird.

**Comment by NetanelBasal** [comment]
Sorry, I can't help if I can't see it.

**Comment by NetanelBasal** [comment]
I'm closing this for now. Feel free to reopen it if you can reproduce it.

**Comment by DDeis** [comment]
I ran into a similar issue twice, I don't remember what was the workaround the first time but here is a reproduction example: [https://stackblitz.com/edit/akita-test-issue-321]()

The problem seems to appear when a store update triggers another store update.

**Comment by NetanelBasal** [comment]
The link is broken @DDeis

**Comment by DDeis** [comment]
Sorry @NetanelBasal, here it is : [https://stackblitz.com/edit/akita-test-issue-321](https://stackblitz.com/edit/akita-test-issue-321)

**Comment by hagbid** [comment]
I have this issue as well, exactly as is explained in OP

**Comment by nzav** [comment]
Seeing the same issue
