### ISSUE TITLE
Allow deep/nested stores

### ISSUE THREAD

**Issue by PsychoPflanze** [datorama/akita#322]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently you can only create stores in the root level.
E.g.
- books
- books.old
- articles
- articles.old

## Expected behavior

It would be nice to have a way of nesting stores, for better structure and readability
E.g.
- books
  - old
- articles
  - old

## What is the motivation / use case for changing the behavior?

The motivation would be to have stores more structured and readable. I'm currently using NGRX for every personal project and for work. I would like to switch over to Akita for personal projects and maybe even work, but i currently can't, because this should be an essential feature for state management.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
I'm not sure what is `old`. Can you provide the entity shape, please?

**Comment by PsychoPflanze** [comment]
It's not supposed to be an entity, my bad. `books` and `articles` are stores.

**Comment by PsychoPflanze** [comment]
And so are the two `old`.

**Comment by NetanelBasal** [comment]
What's is `old`? `OldBooksStore`?

**Comment by PsychoPflanze** [comment]
For example yes, such as `BooksStore` has a "child" store called `OldBooksStore` and `ArticlesStore` has a "child" store called `OldArticlesStore`.

**Comment by NetanelBasal** [comment]
You can create sub stores:

```ts
export interface OldBooksState extends EntityState<Book> {}
export interface BooksState extends EntityState<Book> {}

@StoreConfig({ name: 'books' })
export class BooksStore extends EntityStore<BooksState> {
  
  olds = new EntityStore<OldBooksState>({}, { name: 'old-books' });  

  constructor() {
    super();
  }
}
```

Same for the Query part.

**Comment by NetanelBasal** [comment]
There is no concept of a child because it doesn't give any value. You can also inject it:

```ts

export interface OldBooksState extends EntityState<Book> {}
export interface BooksState extends EntityState<Book> {}

@StoreConfig({ name: 'books' })
export class BooksStore extends EntityStore<BooksState> {
  
  olds = new EntityStore<OldBooksState>({}, { name: 'old-books' });  

  constructor() {
    super();
  }
}
```

**Comment by PsychoPflanze** [comment]
Alright, i'll give that a try. I thought that was too simple coming from NGRX :(

**Comment by NetanelBasal** [comment]
Ok, if you need any help, join Akita's Gitter channel :)
