### ISSUE TITLE
[Question]: Heavy calculations based on the entire Entity list

### ISSUE THREAD

**Issue by stefanwalther** [datorama/akita#323]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## First of all
Thanks a lot to the Akita team, this solution is really great and a huge productivity booster!

## What I am looking for
I am looking for a solution to enrich the models of an entity-list with additional information, all calculated on the client.

### Detailed description
I am loading entities from an endpoint using a model, EntityStore, EntityQuery and EntityState.

- Now I have to enrich each model with about a dozen of additional fields, which are
  - compute intense to calculate
  - therefore I cannot do this at (templating) runtime in Angular
- I'd like to store these calculations for further usage in a derived model
- These additional properties on the model need to be re-calculated every time
   - an item is edited, updated, deleted or
   - the entire list of items is fetched again from the backend.

I am unsure which approach to use with Akita and would by very thank for any hint, advice or working example.

Thx a lot in advance!

<pre><code>
Angular version: 8
Akita: 4.10.7
</code></pre>

**Comment by NetanelBasal** [comment]
You can use middleware. https://netbasal.gitbook.io/akita/general/store-middleware

**Comment by stefanwalther** [comment]
Thx @NetanelBasal, I tried that, but the challenge is that for calculating each of these fields I still need the entire list, that would mean - using the middleware - that I had to query the middleware and then calculate each of the items again, then set all values (for each entity).
The store-middleware concept does not seem to be the right thing, as it is very much focused on setting values for a single entity ... or am I missing something?

**Comment by stefanwalther** [comment]
After experimenting two evenings with different approaches, I finally chose the following approach, absolutely not ideal, but the best compromise ...

I decided to add the calculated fields in the service (as I have a pretty clean `PATCH` solution in my backend, I do not run into risk, that those fields are every added to the database):

```js
  get() {
    const operation = 'get';

    const request$ = this.http.get<Window[]>(`${this.settingsService.settings.api}/windows`)
      .pipe(
        tap(windows => {
          // Calculate the meta fields before inserting into the store
          this.windowsStore.set(this.calcMeta(windows));
        }),
        catchError(ErrorHandling.handleError(`${source}:${operation}`, []))
      );
    return request$;
  }

  calcMeta(windows: Window[]): Window[] {

    // add some calculated fields

    return {
        ...windows,
        meta: {
        calculatedField: 'foo'
        }
    }
  }
```

Then I am doing the same for `add/delete/update/patch`:

```js
  delete(window: Window) {
    const operation = 'delete';
    return this.http.delete(`${this.settingsService.settings.api}/windows/${window.id}`)
      .pipe(
        tap(_ => {

          this.windowsStore.remove(window.id);

          const windows = this.windowsQuery.getAll();
          this.windowsStore.set(this.calcMeta(windows));

        }),
        catchError(ErrorHandling.handleError(`${source}:${operation}`, []))
     
```

I now, it's recommended not to include the Query in the service (https://netbasal.gitbook.io/akita/general/best-practices), but that's really the only nicely working solution I found.



I am very interested in hearing some feedback and ideally getting to know some alternatives I can experiment with.

**Comment by NetanelBasal** [comment]
LGTM. There is nothing wrong with your solution.

The `preAddEntity()` middleware is called when you invoke the `EntityStore.set()` or `EntityStore.add()` methods with the newly added entity.

You can still access the entities in each middleware:

```ts
@StoreConfig({ name: 'windows' })
export class WindowsStore extends Store<WindowsState> {
  constructor() {
    super();
    this.akitaPreUpdate = this.akitaPreAdd.bind(this);
  }
  
  akitaPreAdd(window: Window) {
    const windows = this._value().entities;
 	
  }

  calcMeta(windows: Window[]): Window[] {}
}
```

In the next release, I will expose the whole state in the middleware:
```ts
akitaPreAdd(window: Window, state: WindowsState) {
  const windows = state.entities;
}
```

**Comment by stefanwalther** [comment]
Thank you @NetanelBasal , this is good additional info, and looking forward to the next release!
