### ISSUE TITLE
After updating to angular 9 rc1 i have some issues

### ISSUE THREAD

**Issue by nesmrten** [datorama/akita#324]
i have issue after update to angular 9, so i dont know certainly that this is connected to akita.
[0] ERROR in Tried to overwrite .../node_modules/@datorama/akita-ngdevtools/index.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.

Best regards from Slovenia

**Comment by NetanelBasal** [comment]
Can you reproduce it, please?

**Comment by NetanelBasal** [comment]
It's Not related to Akita. I created a new CLI project with `v9.rc-1`, and it works fine.
