### ISSUE TITLE
Sort stores alphabetically in Redux devtools

### ISSUE THREAD

**Issue by fen89** [datorama/akita#325]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Stores are appended to the end of the list of the devtools when they are activated.

## Expected behavior
Display stores sorted alphabetically.

## What is the motivation / use case for changing the behavior?
It would be really nice if the displayed stores are generally sorted alphabetically, because it is a huge pain to navigate if the store is really big. 

Please let me know if you need any additional information!

**Comment by NetanelBasal** [comment]
Do you want to create a PR? You need to sort the `appState` here: https://github.com/datorama/akita/blob/master/akita/src/devtools.ts#L107

**Comment by fen89** [comment]
@NetanelBasal Thanks for pointing me to the right direction! I'll have a look at this :)
