### ISSUE TITLE
persistState wait for initialized with async driver

### ISSUE THREAD

**Issue by spike-rabbit** [datorama/akita#329]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using persistState with an asynchronous driver it is not possible to wait until the data from the storage was restored.

## Expected behavior
I can wait for the persistState being initialized e.g. the data from storage was written into the stores.
In opposite to `preStoreUpdate` I would expect that initialized also fires if no data was found in the storage.

## What is the motivation / use case for changing the behavior?
When storing credentials via persistState and an asynchronous driver the application must wait until the data from the storage was written into the stores before checking if the user is signed in.

**Comment by NetanelBasal** [comment]
We can't control the stores' initialization time. You should subscribe using the Query.

**Comment by spike-rabbit** [comment]
But how can I figure out with a query when the data from storage was written to it's store? Waiting for a specific value being present does not work if the application is used the first time.

**Comment by NetanelBasal** [comment]
Why do you need to know?

**Comment by spike-rabbit** [comment]
We are using akita on an Ionic mobile app in combination with the secure storage plugin. The whole application data is stored via the persistState plugin. 
Everytime the app starts it checks if the user is signed in. If not the app shows a login screen. The login token is managed via akita.
Loading the data with the secure storage plugin takes up to 1 second. In the meantime the Application is already running and queried the login tokens which were not present. Waiting for the login tokens being present only works for users who already have tokens. For users who run the app the first time the tokens will never be present so the app would wait endlessly. 
So in order to check if the user is signed in the app has to wait for the storage data being written into stores before it queries the login token.

**Comment by NetanelBasal** [comment]
Maybe I'm missing something, but why the following code doesn't work for you?

```ts
@Injectable({ providedIn: 'root' })
export class AuthQuery extends Query<AuthState> {
  isLoggedIn$ = this.select(user => !!user.token);

  constructor(protected store: AuthStore) {
    super(store);
  }
}
```

Now, in the case of a new user, `isLoggedIn` emits `false`. In the case of an existing user, it'll first emit `false`, and then when it loads it from the storage, it'll emit `true`.

**Comment by NetanelBasal** [comment]
@spike-rabbit I understand the use-case now. I'll expose a `selectPersistStateInit` observable. For example:

```ts
import { selectPersistStateInit } from '@datorama/akita';

@Injectable({
  providedIn: 'root'
})
export class AuthGuard {
  constructor(private router: Router, private authQuery: AuthQuery) {
  }

  canActivate(): Observable<boolean> {
    return combineLatest([
      this.authQuery.isLoggedIn$,
      selectPersistStateInit(),
    ]).pipe(
      map(([isAuth]) => {
        if(isAuth) {
          return true;
        }
        this.router.navigateByUrl('login');
        return false;
      }),
      take(1)
    );
  }
}
```

Sounds fine?

**Comment by spike-rabbit** [comment]
Awesome.
This is exactly what I was looking for.
Thanks

**Comment by mburger81** [comment]
@NetanelBasal hello, I have the problem, I register more `persistState,` like this

```
const secureStoragePersistStorage = persistState({
  include: ['secure-storage'],
  key: 'secure-storage',
  storage: localForage,
});

const walletsPersistStorage = persistState({
  include: ['wallets'],
  key: 'wallets',
  storage: localForage,
});
```

In this scenario the `selectPersistStateInit()` does not work, because it is fired not after all states are init but just after the first one is init and I've a lot more then just 2 states 👍 

p.s. I need to have more states, because I need different keys, I need to distinguish some storages, if not storing the datamodel takes to much time on a android device
