### ISSUE TITLE
(cli): Consider using schematics ?

### ISSUE THREAD

**Issue by MonsieurMan** [datorama/akita#33]
> Finally got around testing akita for a small project, a 2D map editor for a game. I'll keep you updated. Pretty excited ! :smiley: 

What do you think about using @angular/schematics for the CLI ?
It's pretty simple and makes sense *imo* as this framework is coupled to the angular ecosystem.

There's a funny tutorial [here](https://medium.com/@jorgeucano/your-fist-angular-schematics-f711d70cb37c).

Seems simple enough I can PR if you want !

**Comment by MonsieurMan** [comment]
Oh nice !
Guess I'll close this issue then.

**Comment by shaharkazaz** [comment]
@MonsieurMan Thanks for the feedback! 
We have already developed schematics and it's going to come out in the upcoming days.
If there is anything else you thought of and want to help let us know!
