### ISSUE TITLE
Wrong selectEntity() overload is selected for predicate, when IDType is not specified

### ISSUE THREAD

**Issue by simeyla** [datorama/akita#332]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

**Important: Strict mode for any must be on to see this issue**

When trying to create a simple `selectEntity` selector the wrong overload is chosen by the compiler if `IDType=any`.

These are the overloads for `selectEntity` from the current source:

    selectEntity<R>(id: IDType): Observable<EntityType>;
    selectEntity<K extends keyof EntityType>(id: IDType, project?: K): Observable<EntityType[K]>;
    selectEntity<R>(id: IDType, project: (entity: EntityType) => R): Observable<R>;
    selectEntity<R>(predicate: ItemPredicate<EntityType>): Observable<EntityType>;

The simple selector shown here gives a compiler warning:

    return this.selectEntity(x => x.username == username);

> error TS7006: Parameter 'x' implicitly has an 'any' type.

## Why is this happening?
My Query is defined as `QueryEntity<CustomerState>` so the `IDType` gets inferred to be `any`.

As a result the *first* overload for `selectEntity` is chosen by the compiler instead of the `ItemPredicate` one. Of course at runtime it works, but the compiler may not be able to show other errors.

## Workaround:
* Just specify `IDType` in the QueryEntity type.
* Specify the entity type `(x: Customer)`

## Permanent fix:
Simply moving the overload for Predicate to the top fixes this, because the compiler now matches this one correctly first - even if `IDType` is `any`.
     
    selectEntity<R>(predicate: ItemPredicate<EntityType>): Observable<EntityType>;
    selectEntity<R>(id: IDType): Observable<EntityType>;
    selectEntity<K extends keyof EntityType>(id: IDType, project?: K): Observable<EntityType[K]>;
    selectEntity<R>(id: IDType, project: (entity: EntityType) => R): Observable<R>;

## What is the motivation / use case for changing the behavior?
* Should match expected overload.
* If not using strict mode then `any` is used and the user many not realize - resulting in incorrect code compiling and causing unexpected errors.

## Other
* I'm not clear why many of these `selectEntity` have `<R>` in them.
* I still don't know how to do a pull - sorry ;-) !

## Environment
Latest Akita.
Strict mode

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Why the `IDType` type is `any` in your case?

**Comment by simeyla** [comment]
Because that's the default if you don't specify it in your `EntityState` subclass

    export interface EntityState<E = any, IDType = any> {

Interestingly in your [docs](url) you have it as:

    export interface EntityState<Entity, IDType = string | number>

but in the actual[current source](https://github.com/datorama/akita/blob/master/akita/src/types.ts) it's been changed to `any`.

There's several ways to fix this in my code of course - but I don't see any reason not to move the predicate overload to be first in the list to make sure it gets chosen by the compiler.

**Comment by NetanelBasal** [comment]
We recommend always set the type of the `id` key. I'll update the docs.
