### ISSUE TITLE
[FeatureRequest] NgEntityService: baseUrl is undefined. Need return the value or ... globalConfig should be public variable instead of private variable

### ISSUE THREAD

**Issue by hiepxanh** [datorama/akita#335]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior
Yeah, in this image you can see that `weatherService.baseUrl` return `undefined` but the `globalConfig` return the value I need. I would like to access `baseUrl` so I can make some `httpClient` request inside service file. Because I'm trying reuse akita from library. 

![image](https://user-images.githubusercontent.com/16970990/69476363-a7bf9080-0e0b-11ea-8bbd-84b004f429a3.png)

here it is in my project
![image](https://user-images.githubusercontent.com/16970990/69476319-2c5ddf00-0e0b-11ea-9779-992312fc897e.png)

## Expected behavior
`xxxService.baseUrl` return value from `globalConfig` as default if user unset. 
Or you can public `globalConfig`

## Minimal reproduction of the problem with instructions
[stackblitz](https://stackblitz.com/edit/github-tqxdvd?embed=1&file=src/app/weather/weather.component.ts)

## What is the motivation / use case for changing the behavior?
I'm using akita as library, so I want to reuse many place, then I want to make an specific query from httpClient like this image, but the baseUrl not there for me.

![image](https://user-images.githubusercontent.com/16970990/69476393-f1a87680-0e0b-11ea-8b12-f3a2ae084738.png)

## Environment

<pre><code>
Angular version:8.2.11

Browser:
- [x] Chrome (desktop) version XX

For Tooling issues:
- Node version: v10.16.2
- Platform:  Windows 
</code></pre>

## Others:
BTW: Other question here, while using akita in angular library, did you ever seen that, do you know how to fix that? You can answer or not, thanks you so much sir:

```
WARNING: No name was provided for external module '@datorama/akita' in output.globals – guessing 'akita'      
WARNING: No name was provided for external module '@datorama/akita-ng-entity-service' in output.globals – guessing 'akitaNgEntityService'
```

![image](https://user-images.githubusercontent.com/16970990/69476428-519f1d00-0e0c-11ea-9efe-a831e8695d1b.png)

Have a good day

**Comment by NetanelBasal** [comment]
I've added a `getConfig` method, you can use it. Btw, you can change two things in your current code:

1. There is no need to inject `HttpClient`, you can call `this.getHttp()`.
2. You can use the [new](https://netbasal.gitbook.io/akita/general/custom-operators) `setLoading` operator.

**Comment by hiepxanh** [comment]
thanks you sir, have a good day
