### ISSUE TITLE
Providing default store config

### ISSUE THREAD

**Issue by danzrou** [datorama/akita#337]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently there is no way to provide a default config which will be used by all stores.
My use case is to set a global `ttl` and `resettable` values for all stores without explicitly settings it for each store's config.

If you find it useful too, I can create a PR for that.

**Comment by NetanelBasal** [comment]
You can set the resettable option via the global [config](https://github.com/datorama/akita/blob/master/akita/src/config.ts#L9) object. You can create a PR that exposes the `ttl` option too.
