### ISSUE TITLE
PersistNgFormPlugin doesn't restore state after page reload

### ISSUE THREAD

**Issue by cojack** [datorama/akita#338]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I do in component

```typescript
    this.persistForm = new PersistNgFormPlugin(this.storyService.query, createStory, {
      debounceTime: 300,
      formKey: 'storyForm'
    })
      .setForm(this.storyForm, this.fb);
```

And I fulfill the form next reload the page by F5, then form is empty with initial values,

## Expected behavior

It should sync form with values from store, I suppose.

## Minimal reproduction of the problem with instructions
Source code at https://github.com/cojack/angular-akita-nestjs-socket.io
in path: `web/src/app/examples/components/persist-form/story-form.component.ts`

After you start a server, there will be a `Persist Form` menu item, there you will be able to test this behaviour. 

## What is the motivation / use case for changing the behavior?

I just follow the documentation steps, wanna to try, check how it works.

## Environment

<pre><code>
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@datorama/akita": "^4.14.1",
    "@datorama/akita-ng-entity-service": "^1.0.0",
    "@datorama/akita-ng-forms-manager": "^3.3.0",
    "localforage": "^1.7.3",
    "ngx-socket-io": "^3.0.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },

Browser:
- [x] Chrome (desktop) version 78
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 70
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.13.1  
- Platform: Linux 

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
It persists the form only in the same session. Checkout the persist state plugin.

**Comment by cojack** [comment]
So @NetanelBasal basically there is no difference between Persist Form and Form Manager Plugin in general, one store state in global store, second store state in your specific store but none of them are able to restore state from store even if it exists.

If you can see in main.ts in web project, I have implemented perist plugin, so question remian open from my side, do I have to literally do it manually, like in query fetch specific key from store and manually set form value?

**Comment by NetanelBasal** [comment]
There is a difference between the two. The `PersistForm` plugin persists a form to a specific store whether the `FormsManagerPlugin` holds the form's state in a global store.

You can't use the persist state plugin with `FormsManagerPlugin` as it is read-only. You can use `PersistForm` and save the store's state in local storage by using the persist state plugin.

**Comment by cojack** [comment]
@NetanelBasal okey, but question still remains open, how to restore state?

**Comment by NetanelBasal** [comment]
I see what you mean. I'm thinking of adding an option to persist the FormsManager state to the storage. This will make it even more powerful. Do you want to add it?
