### ISSUE TITLE
Pagination slips out of sync with the store

### ISSUE THREAD

**Issue by stephencarr** [datorama/akita#342]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm not sure if I've misunderstood something, or not implemented it properly, but here is the situation I have...

Using the pagination plugin I fill a store with a list of entities. These entities are represented in a table in the UI. Clicking on an entity fetches more data for that entity and updates the entity in the store with the new information retrieved. The table, which is tied to the paginated list does not subscribe to changes in the store and does not update to reflect the new data.

## Expected behavior
If the store changes the pagination representation should update with the new information represented in the store.

## What is the motivation / use case for changing the behavior?
I want my paginated collection to remain up-to-date with changes in the store.

## Environment

<pre><code>
Angular version: ^7.2.0

Browser:
- [x] Chrome (desktop) version Evergreen
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 11.2.0
- Platform:  Mac

**Comment by NetanelBasal** [comment]
Updating the store doesn't affect the paginator **as the server is the single source of truth** in this case. Imagine that there are filters or sorting applied - you'll get the wrong data from the plugin.
