### ISSUE TITLE
AkitaNgFormsManager state does not update when calling form.reset() and navigating away right after

### ISSUE THREAD

**Issue by ntziolis** [datorama/akita#343]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
After calling `form.reset()` form state is still the same as before calling `reset()` in some situations.

## Expected behavior
After calling `form.reset()` form state should be reset in all situations.

## Minimal reproduction of the problem with instructions
```
someObservable.pipe(
 tap(() => {
     this.form.reset();  
  }),
  switchMap(voucher => this.router.navigate(['voucher-register']))
);
```

Workarounds:
- `formsManager.remove()`
    - when replacing `this.form.reset()` with `this.formsManager.remove('someFormName')` the form is properly cleared.
    - however in our case the user can choose if he is redirected and by calling `remove` we would have to call `formsManager.upsert` right after calling remove to re-enable binding the form to the state
- delay
    - by introducing a delay between `form.reset()` and navigating away from the component the state is properly reset

Suggestion:
- Assuming this is an angular lifecycle issue, what about introducing a `formsManager.reset(formName)` method that uses the forms manager and not the form as the injection point for emitting the reset event

## What is the motivation / use case for changing the behavior?
Redirecting to a different page after form completion is a common use case (for example, list orders after creating an order).

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by NetanelBasal** [comment]
Can you create a simple reproduction, please?

**Comment by ntziolis** [comment]
Here you go:
https://stackblitz.com/edit/github-8tzzkh?file=src%2Fapp%2Fhome%2Fhome.component.ts

Notes:
- form is on the home component
- check form manager state via Redux dev tools after page load
- click No Delay button
  - this resets the form
  - and navigates to todos
- check form manager state again => still the same
- reload page and do the same as above but using the with delay button
- form manager state will be properly reset

**Comment by NetanelBasal** [comment]
I see the issue. Internally there is a debounce applied to the valueChanges observable. Therefore the unsubscribe call in ngOnDestroy is invoked before the reset emits the new value.

You can get around this by updating the store directly:

```ts
    of(null)
      .pipe(
        tap(() =>
          this.fm.store.update({
            form: {
              value: {
                id: null,
                someValue: null
              }
            }
          } as any)
        ),
        switchMap(voucher => this.router.navigate(["todos"]))
      )
      .subscribe();
```

Feel free to create a PR that simplifies this snippet.

**Comment by ntziolis** [comment]
I see, totally makes sense that there would be a debounce especially when looking at the upsert config object ... my bad.

Looking at the code:
```
this.valueChanges[formName as any] = merge(form.valueChanges, form.statusChanges.pipe(distinctUntilChanged()))
      .pipe(debounceTime(merged.debounceTime))
      .subscribe(() => this.updateStore(formName, form));
```

Simplest way to make sure updates made always end up in the store would be to wrap this into a  `Observable.create` + call ùpdateStore` when unsubscribe is called:
```
    this.valueChanges[formName as any] = Observable.create(observer => {
      const subscription = merge(form.valueChanges, form.statusChanges.pipe(distinctUntilChanged()))
        .pipe(debounceTime(merged.debounceTime))
        .subscribe(() => this.updateStore(formName, form));
      () => {
        subscription.unsubscribe();
        this.updateStore(formName, form);
      };
    }).subscribe();
```
Downside is that it might make a single unnecessary call to `updateStore`. On the other hand `valueChanges` on a form is not shy of emitting values and we could always be sure that the last value of a form is stored in the state, hence it might be acceptable.

What do you think?

**Comment by NetanelBasal** [comment]
I see two options:
1. In the unsubscribe method, to add the last call update.
2. To expose an `updateFormValue(formName, value)` method, and use it.

**Comment by ntziolis** [comment]
In my eyes the form managers job is to keep the form synced with the state. The user should not have to know or choose how to make sure that the state is updated.
What I like most about the form manager is that besides wiring it up during `OnInit` and tearing it down in `OnDestroy`, the code looks 100% the same as it would when working with reactive forms. This really helps when others are looking at the code that are not familiar with akita.

For those reasons I would go with Option 1, assuming the additional update call is acceptable.

**Comment by NetanelBasal** [comment]
Yes, but make it optional. Add a new option called `updateStore` to the `config` object in the unsubscribe method. (defaults to false)
