### ISSUE TITLE
application structure ionic 4

### ISSUE THREAD

**Issue by ToledoNicola** [datorama/akita#345]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

in ionic 4 every page is a module and from what I understand from the documentation if I create a store entity (for example todos) inside a module **A**, and the same entity also serves me in another module **B**, do I have to duplicate the same entity store? or can I use the one created in module A?
thank you very much

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
You need to use `providedIn: root`, and it will be available anywhere in the application:

```ts
@Injectable({ providedIn: 'root' })
@StoreConfig({ name: 'todos' })
export class TodosStore extends EntityStore<TodosState> {
  constructor() {
    super();
  }
}
```

**Comment by ToledoNicola** [comment]
@NetanelBasal yes thanks and for this reason I have structured my application in this way:
`
-pages
- - todo
- - - todo.module
- - - todo-page-component
- stores
- - todo
- - - todo.store
- - - todo.query
- services
- - todo.service
- data
- - todo-data.service
`
because I use the todo store at the global root level,
while if I used it for functionality then I put it inside its module, what do you think makes sense?
thanks

**Comment by NetanelBasal** [comment]
I would put it inside the feature it belongs to. It doesn't matter where you use it later on.

**Comment by ToledoNicola** [comment]
ok thanks @NetanelBasal also for super fast response🙂
