### ISSUE TITLE
Missing imports in persist-state documentation

### ISSUE THREAD

**Issue by ashfahan** [datorama/akita#346]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

on page `https://netbasal.gitbook.io/akita/enhancers/persist-state`

the example code of main.ts is missing few imports

`import { AppModule } from './app/app.module';`
`import { environment } from './environments/environment';`

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by NetanelBasal** [comment]
Thanks, fixed.
