### ISSUE TITLE
ERROR TypeError: Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by Hugofromfrance** [datorama/akita#348]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The problem occurs when i try to set a store with data provided by firestore.

```
this.contractsCollection.valueChanges()
    .subscribe((contracts: Contract[]) => {
      console.log(contracts)
      this.bookStore.set(contracts);
});
```
The output show `contracts` array with correct data but when i use `this.contracts$ = this.contractQuery.selectAll();` in the component i got `undefined` and this error in the console

```
core.js:7187 ERROR TypeError: Cannot read property 'host' of undefined
    at Object.push../node_modules/@firebase/firestore/dist/index.cjs.js.Firestore.configureClient (index.cjs.js:21069)
    at Object.push../node_modules/@firebase/firestore/dist/index.cjs.js.Firestore.ensureClientConfigured (index.cjs.js:21061)
    at Object.get [as _isTerminated] (index.cjs.js:21015)
    at datorama-akita.js:481
    at Array.forEach (<anonymous>)
    at deepFreeze (datorama-akita.js:474)
    at datorama-akita.js:484
    at Array.forEach (<anonymous>)
    at deepFreeze (datorama-akita.js:474)
    at datorama-akita.js:484
```

When i try to set the store like this i dont get error anymore.

```
this.contractsCollection.valueChanges()
    .subscribe((contracts: Contract[]) => {
      console.log(contracts)
      this.bookStore.set([
            {
                        id: "1"
            },
            {
                        id: "2"
            },
            {
                        id: "3"
            }
      ]);
});
```

## Expected behavior
I would like to use data provided by firestore to set an Akita store.

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [x] Chrome (desktop) version 78.0.3904.108 (Build officiel) (64 bits)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 11.14.0
- Platform:  Mac

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
I don't work with firebase. @GrandSchtroumpf any thoughts on this? BTW, we have a firebase integration with Akita.

**Comment by GrandSchtroumpf** [comment]
I've never seen this error before, can you try that : 
```typescript
@Component({
  selector: 'my-component',
  template: '<ul><li *ngFor="let book of books$ | async">{{ book | json }}</li></ul>'
})
class MyComponent implements OnInit {
  books$ = this.query.selectAll();
  // MyStore extends EntityStore, MyQuery extends QueryEntity
  constructor(private db: AngularFirestore, private store: MyStore, private query: MyQuery) {}
  ngOnInit() {
    this.db.collection('books').valueChanges({ idField: 'id' }).subscribe(books => this.store.upsertMany(books));
  }
}
```

**Comment by Hugofromfrance** [comment]
@NetanelBasal @GrandSchtroumpf Thanks for your time.

I created a new project by following this tutorial :
https://github.com/dappsnation/akita-ng-fire

I always have the same error.

Is it possible that the problem comes from the configuration of firestore ?

However, if i dont use Akita, i can retrieve my data from firestore.

**Comment by GrandSchtroumpf** [comment]
What version of `akita-ng-fire` are you using ? If you think this issue is related to `akita-ng-fire` and not Akita, then could you create an issue on the `akita-ng-fire` repo instead ?

Also, it would be great if you could create a stackblitz example! Don't forget to add rules to your firestore project and add the strackblitz url to the list of authorized url in firebase config.

**Comment by Hugofromfrance** [comment]
`akita-ng-fire` version 1.5.13
I will create a stackblitz example asap

Thanks for help

**Comment by NetanelBasal** [comment]
@Hugo-Hontans see the discussion in #354

**Comment by dylanwatsonsoftware** [comment]
@Hugofromfrance I've detailed how I ended up solving this issue in #354. Basically a combo of akita-ng-fire `preFormat` hook and the in-build Akita hook `akitaPreAddEntity` to remove the Document References from the firebase objects.
