### ISSUE TITLE
arrayFind id param should allow number and string types

### ISSUE THREAD

**Issue by dexster** [datorama/akita#349]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
arrayFind only allows number type:
`export function arrayFind<T>(ids: number 
`

## Expected behavior
arrayFind should allow number | string type:
`export function arrayFind<T>(ids: number | string
`

</code></pre>

**Comment by dexster** [comment]
I'm looking at this. Should I do this:
`export function arrayFind<T>(ids: number | string
`

or this using your ID type?

`export function arrayFind<T>(ids: ID
`

**Comment by NetanelBasal** [comment]
`ID`
