### ISSUE TITLE
(feat): Helper function: addAndSetActive()

### ISSUE THREAD

**Issue by MonsieurMan** [datorama/akita#35]
## I'm submitting a...

```
[x] Feature request
```

## Expected behavior
A function for EntityStore:
```typescript
addAndSetActive(entity: E)
```

## What is the motivation / use case for changing the behavior?
I think it is a pretty common use case to create an entity and set it as active right after.  
> In my case I'm creating an area in my map and the user then edits it.

**Comment by NetanelBasal** [comment]
I don't think we need to pollute the API. There are many "two-lines methods" that are common. I would suggest the following:
`add(entity, { setActive: true })`

But I can't see how it's better from writing:
```ts
add(entity);
setActive();
```

You know what I mean?

**Comment by MonsieurMan** [comment]
I thought Akita was managing ID creation internally at first.  
As it's not the case, you have the id at the moment of the creation so it's simple.  
I'm with you then, no need to pollute the API.  

That said, what do you think about providing an opt in *(or configurable)* default ID creation strategy ?
I mean that entity created with `null` or `undefined` ids would automatically get one.

This would make the framework even more easy to use.

**Comment by NetanelBasal** [comment]
That's an interesting idea. I would love to see what you have in mind (maybe a high-level design of the API) and a PR.

**Comment by MonsieurMan** [comment]
Sure !  
I'll get around it when I'll have a more global vision of the framework as it could change a few other things.
> By the way, great job, loving the clean and simple API so far ! :heartbeat:

**Comment by NetanelBasal** [comment]
Looking forward to hearing from you, thanks.

**Comment by NetanelBasal** [comment]
I'm suggesting closing this issue and open a new feature request - auto ID creation.

**Comment by MonsieurMan** [comment]
Closing until re-opening, now tracked in #38
