### ISSUE TITLE
doc: non functional examples

### ISSUE THREAD

**Issue by Badisi** [datorama/akita#351]
## I'm submitting a...
`[x] Documentation issue or request`

## Current behavior
A few examples in the documentation make use of the observer pattern in observable.subscribe().
Those examples are not functional as `this` inside the callbacks represents the observable and not the component.

```ts
@Component({
  template: `<div *ngIf="error">{{error}}</div>`
})
class TodosComponent {
  updateTodo() {
    this.todosService.updateTodo().subscribe({
      error(error) {
        this.error = error;
      }
    })
  }
}
```

## Expected behavior
Callbacks should be written as arrow functions :

```ts
error: (error) => {
  this.error = error;
}
```

**Comment by NetanelBasal** [comment]
You are right. Can you give me the link/s, please?

**Comment by Badisi** [comment]
As far as I can tell :

https://netbasal.gitbook.io/akita/angular/ng-entity-service
```ts
update(id) {
    this.postsService.update(id, { title: 'New title' }).subscribe({
      error(error) {
        this.error = error;
      }
    });
  }
```

https://netbasal.gitbook.io/akita/general/error-handling#local-component-error
**todos.components.ts**
```ts
@Component({
  template: `<div *ngIf="error">{{error}}</div>`
})
class TodosComponent {
  updateTodo() {
    this.todosService.updateTodo().subscribe({
      error(error) {
        this.error = error;
      }
    })
  }
}
```

https://netbasal.gitbook.io/akita/general/error-handling#success-notifications
**todos.component.ts**
```ts
@Component({
  template: `<div *ngIf="success">🦄</div>`
})
class TodosComponent {
  addTodo() {
    this.todosService.addTodo(this.todoForm.value).subscribe({
      next() {
        this.success = true;
      },
      error() { ... }
    })
  }
}
```

**Comment by Badisi** [comment]
You missed the error callback in [success-notifications](https://netbasal.gitbook.io/akita/general/error-handling#success-notifications) ;-)
