### ISSUE TITLE
What is the purpose of auditTime(0) in combineQueries operator ?

### ISSUE THREAD

**Issue by msarsha** [datorama/akita#353]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[X ] Other... Please describe:
</code></pre>

On this line:
https://github.com/datorama/akita/blob/master/akita/src/combineQueries.ts#L8

Is this done to wait for the next tick?

**Comment by NetanelBasal** [comment]
Yes.
