### ISSUE TITLE
Bug Report - TTL not expiring the cache after manually setting.

### ISSUE THREAD

**Issue by WillPoulson** [datorama/akita#356]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm setting a TTL in my store however my cache isn't invalidating.

## Expected behavior
It would invalidate the cache after the defined TTL and would trigger the selectHasCache.

## Minimal reproduction of the problem with instructions
1. Set up a project
2. Create a basic store
3. Add a TTL to the cache I chose 180000 for 3 mins
4. In a component subscribe to the selectHasCache
5. Manually set the cache to true via setHasCache(true, { restartTTL: true })
6. Wait 3 mins... Nothing triggers

## Environment

<pre><code>
Angular version: 9.0.0-next.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

</code></pre>

**Comment by NetanelBasal** [comment]
Can you create a basic demo on stackblitz, please?

**Comment by mhosman** [comment]
Also, after every request, getHasCache is always in true (without setting setHasCache(true)).... this never happened to me in the past.

**Comment by NetanelBasal** [comment]
Could you provide a live example, please?

**Comment by WillPoulson** [comment]
Apologies for the delay reply.
I'm not very familiar with how to use StackBlitz would you mind updating the seed for bug reports to the latest Akita version so I can start one from there :)

https://stackblitz.com/github/NetanelBasal/akita-issue-seed

Thanks!

**Comment by NetanelBasal** [comment]
You should fork the project and make your changes.

**Comment by NetanelBasal** [comment]
@WillPoulson it works as expected - https://stackblitz.com/edit/akita-issue-76bfl7

**Comment by WillPoulson** [comment]
Hi, thanks for getting that demo going for me. I was able to replicate that working on my code base too...

It appears it may be an issue with persistent storage?
For example:

- I set the cache to true with the reset TTL
- The cache expires
- I refresh the page in the browser and when it loads it thinks the cache is set to true and never expires after the TTL.

How is persistState intended to work with a TTL and cache? :) 
Thanks for all your hard work on Akita!

**Comment by NetanelBasal** [comment]
The TTL is per session. It doesn't persist on reloads.

**Comment by WillPoulson** [comment]
I've been able to replicate my issue in a stackblitz for you 👍 
I've included the steps to reproduce within it

[Stackblitz Link](https://stackblitz.com/edit/akita-issue-cgkjgr)

The expected behaviour would be after it's loaded from storage it would start the TTL counter and expire after the 30 seconds.

Thanks!

**Comment by NetanelBasal** [comment]
Try the latest version.

**Comment by WillPoulson** [comment]
Hi, just updated my demo and it seems to work as expected.

Thanks for sorting this out 👍
