### ISSUE TITLE
cannot exclude properties form persisteSate using localForage

### ISSUE THREAD

**Issue by amr-alamir** [datorama/akita#361]
I think this may be a bug.
I reproduces the problem in [this stackblitz](https://stackblitz.com/edit/akita-persiststate-exclude)
I used this code in `main.ts` to persist state in indexeddb and exclude `ui` from `user` entity store:
```typescript
localForage.config({
  driver: localForage.INDEXEDDB,
});

persistState({
  storage: localForage,
  exclude: [
    'user.ui',
  ]
});
```
the `user.ui` key is still being persisted in indexeddb and state rehydrated from storage at startup.
Also this may be a feature request to exclude `ui` state by default from persistence.
thanks in advance...

**Comment by NetanelBasal** [comment]
`exclude` is deprecated. Use `includes` with a callback.

**Comment by amr-alamir** [comment]
can you share an **example** or **link** of `include`  with callback?

**Comment by NetanelBasal** [comment]
In that case, you should use [custom hooks](https://netbasal.gitbook.io/akita/enhancers/persist-state#custom-hooks), and remove it in the `preStorageUpdate` hook.

**Comment by amr-alamir** [comment]
I used custom hooks like this:
```typescript
preStorageUpdate: ( storeName, state  ) => {
  if( storeName == 'user' ) {
    const { ui, ...stateWithoutUi } = state;
    return stateWithoutUi;
  }
}
```
it actually returned the state without excluded props, but this gives me some errors, like:
```
Cannot read property 'filter' of undefined
```
or
```
Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at GlobalStore.deepFreeze
```

so for now, I'm going to split stores with ui into 2 store ( eg `UserStore` and `UserUiStore`) and exclude ui stores with `include` callback.

thanks with the help, and wished in you can consider adding `exclude` back again.

**Comment by NetanelBasal** [comment]
Can you create an example [here](https://stackblitz.com/edit/akita-issue?file=src%2Fapp%2Fauth%2Fstate%2Fauth.query.ts), please? I want to see why you get this error.

**Comment by amr-alamir** [comment]
ok,I'll try to reproduce it. just saw your message.

**Comment by amr-alamir** [comment]
here is the [link with error](https://stackblitz.com/edit/akita-issue-5qnvxl)

by clicking todos link (direct link [here)](https://akita-issue-5qnvxl.stackblitz.io/todos) you get the error:
```
ERROR
Error: Cannot read property 'filter' of undefined
```
by inspecting the  devtools, I found that rehydrating the state from persistence (indexddb here)  overwrites the initial state and totally remove the excluded properties from the state, so when you seek this props (by a query) you get the error.

**Comment by NetanelBasal** [comment]
I see the bug, and I will fix is ASAP.

**Comment by NetanelBasal** [comment]
Fixed in the latest version.

**Comment by amr-alamir** [comment]
thanks for the fix
