### ISSUE TITLE
Why choose akita over ngrx? 

### ISSUE THREAD

**Issue by johnico** [datorama/akita#362]
Hi 
I am in front of decieison about choosing between ngrx abd Akita to my Angular 8 project.

My app is not to big but for now with a lot of polling events fired to the app. So my event is build in kind of flow l until i havr the full data. 
It means i need to show part of the data each time i got event.

i did not find realy good comparison between them.

Could you tell me or point me to why should I choose Akita ?

My thought basiclly are: 
1.  ireduce the boilerplate
2.  keep the store out of the "core" app.

What is the diffrent between ngrx entity to akita? 

Sorry If its not the right place.
Thanks

**Comment by NetanelBasal** [comment]
I'm sorry, it's not the place, and it's not appropriate to ask. I suggest to investigate both solutions and go with the one that works best for you and your team.

Here is an article you can start with: [10 Reasons Why You Should Start Using Akita as Your State Management Solution](https://engineering.datorama.com/10-reasons-why-you-should-start-using-akita-as-your-state-management-solution-66b63d033fec)

Good luck :)

**Comment by ibrahimab** [comment]
On the "10 Reasons" page, under bullet point 6, you have a link that goes to blog posts (https://netbasal.gitbook.io/akita/general/blog-posts) which does not exist.
