### ISSUE TITLE
There's a typo in the "the-query" docs

### ISSUE THREAD

**Issue by lherman-cs** [datorama/akita#363]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Description
There's a typo in the second code block on https://netbasal.gitbook.io/akita/core-concepts/the-query. 

`this.select[state => state.name, state => state.age]` should be `this.select([state => state.name, state => state.age])`

**Comment by NetanelBasal** [comment]
Fixed, thanks.
