### ISSUE TITLE
Cannot use clearStore('key') when persistence is set to localForage & IndexedDB

### ISSUE THREAD

**Issue by nodesmichael** [datorama/akita#364]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using localForage for storage exactly as instructed in the [docs](https://netbasal.gitbook.io/akita/enhancers/persist-state#async-support) we cannot use the method `clearStore('<KEY>')` because the method is trying to `deserialize()` the contents in IndexedDB and throws an error saying it cannot parse it as a JSON string, since the data are not a string, they are already stored deserialized.

changing   
https://github.com/datorama/akita/blob/a6db2ea2b6cff98964b0ae79446631144f589340/akita/src/persistState.ts#L243

into

```
        clearStore(storeName) {
            if (isNil(storeName)) {
                /** @type {?} */
                const value = observify(storage.setItem(key, '{}'));
                value.subscribe();
                return;
            }
            /** @type {?} */
            const value = storage.getItem(key);
            observify(value).subscribe((/**
             * @param {?} v
             * @return {?}
             */
            v => {
                /** @type {?} */
                const storageState = v || '{}'; // not using deserialize
                if (storageState[storeName]) {
                    delete storageState[storeName];
                    /** @type {?} */
                    const value = observify(storage.setItem(key, storageState)); // not using serialize
                    value.subscribe();
                }
            }));
        }
```

seems to fix the issue, but I guess that would fail for Local and Session storage mechanisms?

## Expected behavior

As in your examples in the docs you suggest to support IndexedDB (and adding values seems to work fine) I guess there should be a way to support clearing values?

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

1. Use localForage for storage exactly as instructed in the [docs](https://netbasal.gitbook.io/akita/enhancers/persist-state#async-support)
2. Make sure something gets stored in IndexedDB using some key to be reused in the next step
2. Try to use  `clearStore('<KEY>')` programmatically.

## What is the motivation / use case for changing the behavior?

Clearing specific keys from the persisted store which uses localForage/IndexedDB

## Environment

<pre><code>
Angular version: 8.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
We should use the same technique as here: https://github.com/datorama/akita/blob/a6db2ea2b6cff98964b0ae79446631144f589340/akita/src/persistState.ts#L151

**Comment by nodesmichael** [comment]
I just noticed the serialize/deserialize configs. Silly me. So it works fine if I do

```
    this.statePersistedStore = persistState({
      key: 'aegis',
      include: ['somekey'],
      storage: localForage,
      serialize: v => v,
      deserialize: v => v
    });
```
So we're good on our side!

**Comment by NetanelBasal** [comment]
Great :)
