### ISSUE TITLE
persistState() clearStorage() code example from the docs is unclear

### ISSUE THREAD

**Issue by micobarac** [datorama/akita#365]
if I have this code inside `main.ts`:

```typescript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableAkitaProdMode, persistState } from '@datorama/akita';
import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
  enableAkitaProdMode();
}

persistState();

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch(err => console.log(err));
```

Where does this code go:

```typescript
export const storage = persistState();

storage.destroy(); // Stop sync the state
storage.clearStore(); // Clear the storage
storage.clearStore('todos'); // Clear the todos store from storage
```

Should `export const storage = persistState();` be set somewhere globally or what?
Should `persistState()` only be called once, inside `main.ts`?
Do you have some working example of using the state persistence and clearing?

**Comment by NetanelBasal** [comment]
It doesn't matter. You can expose it from `main.ts` or from the `AppComponent` for example:

```ts
export class AppComponent {
  ngOnInit() {
    this.persistState = persistState({ ... });
  }
}
```

**Comment by micobarac** [comment]
But my question is, should `persistState()` be only called once in the app? If so, how do you access it inside some service?

**Comment by NetanelBasal** [comment]
Yes, it should be called once per application. You can expose it from the main.ts file.

```ts
export const storage = persistState();
```

And access it in your services:

```ts
import { storage } from 'path/to/main';

@Injectable({ providedIn: 'root' })
export class TodosService {
  constructor(private todosStore: TodosStore) {
    
  }

  clear() {
    storage.clearStore('todos');
  }
}
```

No, it only clears the storage value.

**Comment by NetanelBasal** [comment]
You can also use DI. 

```ts
const storage = persistState(...);

platformBrowserDynamic([{ provide: 'persistStorage', useValue: storage }])
  .bootstrapModule(AppModule)
  .catch(err => console.log(err));

export class TodosService {
  constructor(@Inject('persistStorage') persistStorage) {
  }
}
```

**Comment by micobarac** [comment]
Thank you very much, for extraordinary tool called Akita and for a swift support :)

**Comment by micobarac** [comment]
I used DI, but have an issue though, `clearStore()` doesn't clear storage values at all :(. The values are still there, in the storage.

![image](https://user-images.githubusercontent.com/16001837/73523902-3522f080-440c-11ea-8f0f-3697cc3347d7.png)

**Comment by NetanelBasal** [comment]
Works for me. Make sure you're not updating the store again. It clears the storage once. If you update the store immediately, you'll see these values.

**Comment by Rush** [comment]
I have the same issue, `clearStore` is not saving to `persistState` at all.
Could it be due to?
```
    const storage = persistState({
        preStorageUpdateOperator: () => auditTime(AKITA_STORAGE_UPDATE_AUDIT_TIME),
```
I am using indexedDb

**Comment by NetanelBasal** [comment]
`clearStorage` updates only the storage.
