### ISSUE TITLE
Support multiple calls in NgEntityService

### ISSUE THREAD

**Issue by samu** [datorama/akita#369]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
With the following code, i load pages of a users endpoint into the users store, using Ng Entity Service:

```TypeScript
usersService.get({params: {page: 1}, mapResponseFn: r => r.data}).subscribe();

usersService.get({params: {page: 2}, mapResponseFn: r => r.data}).subscribe();

usersQuery.selectAll().subscribe(console.log);
```

What i see printed to the console is the contents of page one, then the contents of page two.

## Expected behavior
I would expect the entities of page one and two to accumulate in the store. Am i missing something?

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-1224u4

**Comment by NetanelBasal** [comment]
These are **two** separate HTTP requests. When you get the response of the first page, you update the store and the `selectAll` observable emits. The same goes for the second response.

**Comment by samu** [comment]
Thanks for the quick reply. Yes indeed, it's two separate HTTP requests. But i expected to be able to make multiple calls to the endpoint and gradually build up the contents of the store. I don't see why this shouldn't be possible, because, as far as i understand, it is also possible to add entities to the store with `add`, right?

**Comment by NetanelBasal** [comment]
Yes, but each time you call the `get` method, it adds the response to the store. What you need is a new API - `getAll`.

**Comment by samu** [comment]
Yes. I think an equivalent `setAll` on the store would make sense, too. Or, maybe it should be a an option to `EntityStore.get` and `Store.set`. For example, `Store.set([{...}, {...}], {accumulate: true})`

**Comment by NetanelBasal** [comment]
That's not related to the store. It's related to NgEntityService.

**Comment by samu** [comment]
You're, right, i meant `EntityStore` and `NgEntityService`.

**Comment by NetanelBasal** [comment]
We decided that it should not be built in the service. You can achieve what you want using the following code:

```ts

const getPage = page => 
            usersService.get({params: {page}, mapResponseFn: r => r.data});

forkJoin[getPage(1), getPage(2)].pipe(
   switchMap(() => usersQuery.selectAll())).subscribe(console.log);
```

**Comment by smachi** [comment]
Hi @NetanelBasal 

I'm having the same issue exposed by @samu . I understand the solution you provided would work when you know in advance the number of pages you need and would perform 2 distinct API requests, but what if you don't know which pages you need to request, so the number of calls to perform would be dynamic and would depend on the users' interaction (so you need to request page 1 at load, then page 13 a minute after and finally page 3)?
Shouldn't there be a way to accumulate all the retrieved data in the store and to retrieve them all when needed?

Thanks in advance!

**Comment by NetanelBasal** [comment]
@samu, that's not the store's responsibility. Moreover, this scenario isn't Akita related.

**Comment by NetanelBasal** [comment]
> so you need to request page 1 at load, then page 13 a minute after and finally page 3

Why would you want to wait for all the pages to return before showing the data?

**Comment by smachi** [comment]
Hmmm. Let me reformulate it.
Getting as an example your post [here](https://engineering.datorama.com/building-production-quality-real-world-applications-with-angular-akita-bf18d516f2f7), let's say we have a products' service that gets a set of products from my API and then, the user wants to go to one to the listed products, so when moving to the product's component, I'd expect to get the product data from the previously retrieved list instead of making another request to the server (that's what it is happening to me).
When I move to the product component and try to make use of the productsQuery.hasProduct(productId), it returns false (and I can see there is a post with that ID when inspecting it on the Redux DevTools). Is this the expected Akita's behavior or am I missing something?

What I've noted is: if I later go to the same single product that was previously requested, this time the hasProduct method returns true and does not perform a new request for it. And the same happens for the list of products on the products' list component.

Thanks.

**Comment by NetanelBasal** [comment]
> When I move to the product component and try to make use of the productsQuery.hasProduct(productId), it returns false (and I can see there is a post with that ID when inspecting it on the Redux DevTools)

Are you sure that the product is in the store? Can you share the `hasProduct` method?

**Comment by smachi** [comment]
I've tried the 2 ways you mention there.  With this:

`
hasProduct( id: ID ) {
	return this.getValue().cachedIds.hasOwnProperty( id );
}
`

and with this one:

`
hasProduct( id: ID ) {
	return this.hasEntity( id );
}
`

In the first one, it throws an error saying that cachedIds is undefined, in the second one, it just returns false (both of these on the single product component). However, if I try to use any of the above versions of the hasProduct method, after adding the products to the store (on the products' list component), it returns the values correctly.

**Comment by NetanelBasal** [comment]
> In the first one, it throws an error saying that cachedIds is undefined

You know that you need to add it manually, right?

> However, if I try to use any of the above versions of the hasProduct method, after adding the products to the store (on the products' list component), it returns the values correctly.

I'm not sure I understand what you mean. It'll return `true` only if the product is in the store.

**Comment by smachi** [comment]
> You know that you need to add it manually, right?

Yes, this is what I've done after retrieving  the list of posts from my API:

`
this.productsStore.upsert(product.id, product);								this.productsStore.updateCachedIds(product.id);
`

And just after that, if I  run a console log:

`console.log(this.productsStore.getValue().cachedIds);`

It works correctly.

> I'm not sure I understand what you mean. It'll return true only if the product is in the store.

Sure. I know. But, as I have said previously, there is a product with that ID on the store (it can be seen on the Redux DevTools under the products entity).

**Comment by NetanelBasal** [comment]
It feels like a race. If the product in the store it should return `true`. It's a simple check. Can you reproduce it?

**Comment by smachi** [comment]
Sorry. How do you want me to reproduce it?

Check these screenshots, please:

<img width="1680" alt="Redux DevTools" src="https://user-images.githubusercontent.com/6269226/74099837-1b7a5b00-4b28-11ea-8b2d-e70c972d7c21.png">

<img width="1680" alt="Error" src="https://user-images.githubusercontent.com/6269226/74099841-246b2c80-4b28-11ea-9f4d-927cc2ad96c9.png">

Both of them are being shown on the single product component (well, post in my case). I'm getting the post with ID 8 that you can see it's on the store but when getting it from the single post component, it cannot find it.
Also, note the empty array that it's shown at top, that it's the result of doing this on the ngOnInit():

`console.log(this.postsQuery.getAll());`

**Comment by NetanelBasal** [comment]
@samu can we move to Gitter, please? It'll be easier to communicate.
