### ISSUE TITLE
Question/Suggestion: Is there a way to get static value of Loading or Error?

### ISSUE THREAD

**Issue by NathanAlcantara** [datorama/akita#370]
## I'm submitting a...

<pre>
<code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code>
</pre>

## Current behavior
Today, to get a static value of a loading or error i need to do something like that:
<pre>
<code>
@Injectable({ providedIn: "root" })
export class Query extends QueryEntity<Entity> {
	loading$ = this.selectLoading();

	constructor(protected store: Store) {
		super(store);
	}
}
</code>
</pre>
`const { loading } = this.query.loading$.source.source.source.getValue()`

## Expected behavior
I think that will be awesome if exist a way to get the static value of loading and error, aka:
`this.query.getLoading()` or `this.quey.getError()`

## What is the motivation / use case for changing the behavior?
I need to use in a conditional of another context if the store are loading in that moment

## Environment
<pre>
<code>
Angular version: 8.2.14
 
For Tooling issues:
- Node version: v10.16.0
- Platform:  Windows
</code>
</pre>

**Comment by danzrou** [comment]
You can simply call `store.getValue().loading`

**Comment by NathanAlcantara** [comment]
> You can simply call store.getValue().loading/error.
> Those props exist on the root object of your state

Sorry, i'm talking about Entity Store and don't exist this method :c

**Comment by NetanelBasal** [comment]
Use `query.getValue().loading`.

**Comment by NetanelBasal** [comment]
You can add it to your query:

```ts
class YourQuery extends QueryEntity {
  getLoading() {
    return this.getValue().loading;
  }
}
```
