### ISSUE TITLE
(feat): Automatic id creation

### ISSUE THREAD

**Issue by MonsieurMan** [datorama/akita#38]
## I'm submitting a...
```
[x] Feature request
```

## Current behavior
As of now users have to manage ids on their own.

## Expected behavior
Opt in or configurable automatic id creation. *(or opt-out and configurable but this would introduce a breaking change)*

## What is the motivation / use case for changing the behavior?
This would make the framework even more easy to use if you're not using custom IDs.

## Todo
- [ ] API design ideas
- [ ] Reopen #35 as it would make sense with automatic id creation.

**Comment by NetanelBasal** [comment]
Closing this issue. I have added the [guid()](https://netbasal.gitbook.io/akita/entity-store/additional-functionality/store-utils) method to simplify the id creation. You can now do the following:

```ts
import { guid } from '@datorama/akita';

export function createPerson(name: string): Person {
  return {
    id: guid(),
    name,
    guests: 0,
    attending: false
  };
}
```
