### ISSUE TITLE
Angular 9 ModuleWithProviders migration

### ISSUE THREAD

**Issue by tehshin** [datorama/akita#380]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When importing AkitaNgDevtools you get the following error with JIT compilation:
```
ERROR in node_modules/@datorama/akita-ngdevtools/index.d.ts:12:57 - error NG6005: AkitaNgDevtools.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.
```

## Expected behavior
No error.

## Minimal reproduction of the problem with instructions
New angular 9 project and add `AkitaNgDevtools.forRoot()` to the `app.module` imports and serve it.

## What is the motivation / use case for changing the behavior?
https://angular.io/guide/migration-module-with-providers

## Environment

<pre><code>
Angular version: 9.0.2

Browser:
- [x] Chrome (desktop) version 80.0.3987.122 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.4.0
- Platform:  Windows 10
</pre>

**Comment by NetanelBasal** [comment]
We should upgrade to v9 soon. In the meantime you can call it directly in the `main.ts` file:

```
import { akitaDevtools } from '@datorama/akita';

akitaDevtools()
```

**Comment by NetanelBasal** [comment]
Upgrade to v4, and remove the `forRoot` call.

**Comment by tehshin** [comment]
Thanks, appreciate the fast response 😄 

have a nice day

**Comment by snebjorn** [comment]
@NetanelBasal The doc for this is incorrect

https://netbasal.gitbook.io/akita/enhancers/devtools
```ts
import { DevtoolsOptions } from '@datorama/akita';

{
  provide: DevtoolsOptions,
  useValue: { actionsBlacklist: ['@@INIT'] }
}
```
should be 

```ts
import { DEVTOOLS_OPTIONS } from '@datorama/akita-ngdevtools';

{
  provide: DEVTOOLS_OPTIONS,
  // tslint:disable-next-line: no-object-literal-type-assertion
  useValue: { actionsBlacklist: ['@@INIT'] } as DevtoolsOptions,
}
```

**Comment by guidolx** [comment]
Hello, 
I started playing with Akita today and it still had a dependency to "@datorama/akita-ngdevtools": "^3.0.2" which throws the above exception.
Thanks for this nice looking library.
I am using Angular 10
