### ISSUE TITLE
Problem in preStoreUpdate when include async function

### ISSUE THREAD

**Issue by femike** [datorama/akita#381]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When include async function in `preStoreUpdate` `AuthGuard` return `false` after refresh browser.
I would like refresh token after get him from storage, `preStoreUpdate` nice place for that, but when return `fetch` `Promise` with result `AuthGuard` return `false`, how to fix it?

*sorry for google translate eng.*
*It will be nice if you correct me!*

## Minimal reproduction of the problem with instructions

`main.ts`
```js
preStoreUpdate(storeName: string, state: any) {
    if (storeName === 'auth' && !!state.token) {
      return fetch(`${window.location.protocol + environment.ApiHost}/refresh-token`, {
        method: 'POST',
        cache: 'no-cache',
        headers: {
          Authorization: `Bearer ${state.token}`
        },
        redirect: 'error',
        referrer: 'no-referrer'
      }).then(response => {
        const { token, exp_at }: any = response.json();
        return {
          ...state,
          token,
          exp_at,
        };
      }).catch(err => {
        return { token: null, exp_at: Date.now() };
      });
    }
    return state;
  },
```
`auth.guard.ts`

```js
import { selectPersistStateInit } from '@datorama/akita';

@Injectable({
  providedIn: 'root'
})
export class AuthGuard {
  constructor(private router: Router, private authQuery: AuthQuery) {
  }

  canActivate(): Observable<boolean> {
    return combineLatest([
      this.authQuery.isLoggedIn$,
      selectPersistStateInit(),
    ]).pipe(
      map(([isAuth]) => { // <--- return false
        if(isAuth) {
          return true;
        }
        this.router.navigateByUrl('login');
        return false;
      }),
      take(1)
    );
  }
}
```

## Environment

<pre><code>
Angular version: 9.0.0

Browser:
- [x] Chrome (desktop) version 80
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Hooks doesn't support async operations.

**Comment by NetanelBasal** [comment]
Which storage do you use?

**Comment by femike** [comment]
> Which storage do you use?

Right now i use localStorage, but in future i planned use indexedDB

**Comment by NetanelBasal** [comment]
You shouldn't do this call in the `preStorageUpdate`. Do it in your `AuthGuard`

**Comment by femike** [comment]
thanks, I'll try.
