### ISSUE TITLE
resetStores fires before persistance restoration on page reload

### ISSUE THREAD

**Issue by Benny739** [datorama/akita#382]
The restStores function fires before the store gets restored from the localStorage on a page reload. 
Workaround ist to wrap the resetStores function in a setTimeout or a delay(0).

**Comment by NetanelBasal** [comment]
Can you explain the use case, please? Why would you use persist state, and immediately call `resetStores`?

**Comment by Benny739** [comment]
I have a multi tenant application, some stores are completely related to the current tenant. When the user switches between tenants, I have to reset these stores. It could happen, that the user saves the url and just opens another tenant via url. In this case I track the active tenant id and when the id changes I reset the stores.

**Comment by NetanelBasal** [comment]
Akita also exposes the `selectPersistStateInit` observable. This observable emits after Akita initialized the stores based on the storage's value.

```ts
import { selectPersistStateInit } from '@datorama/akita';

selectPersistStateInit().subscribe(() => {
  resetStores();
})
```

**Comment by NetanelBasal** [comment]
I'm closing this issue. If my solution doesn't work for you, reopen it.
