### ISSUE TITLE
[Question] Allowing null types, is it a good thing ?

### ISSUE THREAD

**Issue by C0ZEN** [datorama/akita#383]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

For example:  

When using the method `update` from the `entityStore`.  
The definition is `update(id: OrArray<IDType> | null, newState: Partial<EntityType>): any;`.  

With a dummy interface like:
```typescript
export interface IDummy {
   id: number;
   name: string;
   description?: string;
}
```

Using it like:
```typescript
public updateEntity(entityId: number, entity: Partial<IDummy>): void {
   this.dummyStore.update(entityId, entity);
}
```

Will works fine because the dummy interface allows a partial interface.  
The equivalent of the interface is then:
```typescript
export interface IDummy {
   id: number | undefined;
   name: string | undefined;
   description: string | undefined;
}
```

Nevertheless, in my app, we also handle the null values whenever is it possible.  
Since Angular 9 release and TypeScript version upgrade, the checks are more powerfuls.  
And the TypeScript's flag `strictNullChecks` is enabled.  
And then the shit happened.

So, in my app, the dummy interface would be in reality like:
```typescript
export interface IDummy {
   id: number;
   name: string;
   description?: string | null | undefined;
}
```

Using it like:
```typescript
public updateEntity(entityId: number, entity: CustomPartial<IDummy>): void {
   this.dummyStore.update(entityId, entity);
}
```

With CustomPartial:
```typescript
export type CustomPartial<T> = {
  [P in keyof T]?: T[P] | null | undefined;
};
```

And it will not works because the dummy interface allows a partial interface.  
And the equivalent of the interface in my app is then:
```typescript
export interface IDummy {
   id: number | null | undefined;
   name: string | null | undefined;
   description: string | null | undefined;
}
```

Which is not the same than akita's definition.

## Expected behavior

Not throwing errors by allowing null or undefined values.

## What is the motivation / use case for changing the behavior?

I am not sure if akita needs a change.  
But my app is not working in Angular 9 if I use the TypeScript's flag `strictNullChecks` to `true`.

I could create a pull request to bring some changes but I want to check with you guys if this is something that you agree with.  
Moreover, I am not sure if adding explicits null types could lead to a breaking change on the types.

On the other side, if you think that my team should change something in my app because this is a bad design, let me know please.

Thank you !

## Environment

<pre><code>
Angular version: 9.0.4

</code></pre>

**Comment by NetanelBasal** [comment]
The `update` method is typed to `null` as it can take `null`. `null` means that you want to update all the entities. 

> Which is not the same as Akita's definition.

Akita doesn't care about the entity type, so I'm not sure how it's related to Akita.

**Comment by C0ZEN** [comment]
@NetanelBasal maybe I should provide a real example with StackBlitz.  

Changing akita's definition to `update(id: OrArray<IDType> | null, newState: CustomPartial<EntityType>): any;` fix the error because the entity could now have null values.

**Comment by NetanelBasal** [comment]
Provide a StackBlitz example, please.

**Comment by C0ZEN** [comment]
I created [a StackBlitz](https://stackblitz.com/edit/angular-akita-custom-partial-bug?file=src%2Fapp%2Fdummy.service.ts) nevertheless I am not able to reproduce the error.  
Sorry for the trouble, I close this issue.
