### ISSUE TITLE
resetStores should also clear the storage (Problems with lazy loaded modules)

### ISSUE THREAD

**Issue by Benny739** [datorama/akita#386]
When selectPersistStateInit observable fires Akita has not initialized stores from lazy loaded modules. So calling resetStores then doesn't have any effect on those stores. These stores still get restored, when the lazy loaded module gets initialized. Currently the only way I see is clearing the storage manually. 
I think resetStores should also delete everything from the persisted State (that is not excluded from resetting). Because when I call resetStores, why would I wanna keep something in the localStorage that then accidentally gets restored, because the module was not initialized.

Edit:
Even clearing the storage manually doesn't help. After akita initialized the persisted state, but has not initialized lazy loaded stores, the state is somewhere hidden and untouchable.

**Comment by NetanelBasal** [comment]
`resetStores` and `persistState` are unrelated functionalities. If you want to clear the storage, you can use the [API](https://netbasal.gitbook.io/akita/enhancers/persist-state).

**Comment by Benny739** [comment]
Imagine the following scenario:
- user navigates through the whole app and all stores get persisted
- user refreshes the page, and not opens all lazy loaded modules and then loggs out.
- on logout we call resetStores, but only the stores which are initialized get reset. The stores which were not initialized, still stay in the storage and when another user loggs in and navigates to one of the lazy loaded modules, the state from the storage (which belongs to the previous user) gets restored.

**Comment by NetanelBasal** [comment]
I understand the use case. But as I said, those features aren't coupled. When you call `resetStores`, also call `storage.destroy()`
