### ISSUE TITLE
Support for effects as an observable stream

### ISSUE THREAD

**Issue by didii** [datorama/akita#389]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Updating the store is done using plain methods where no option to use observables is currently out-of-the-box implemented.

## What is the motivation / use case for changing the behavior?
When translating user-actions to store updates, we often want to fetch additional data that would be preferably done using a reactive stream that is started by that action such that we can `switchMap` or `debounce` the http call without having to manually manage a subject and a subscription.

Note that this is different to middleware (from #143) since (as far as I can see) they are simply methods and thus do not support reactivity.

Currently I have made a base class that does the managing of the subject and subscription for me, but it relies on some conventions and is restricted to having a single output observable which is not ideal.

How I can use it in my services
```ts
// Helper types so the observable stream inherits the parameters of the action function
type AnyFunction = (...args: any[]) => any;
type Stream<T extends AnyFunction, TOut = unknown> = OperatorFunction<Parameters<T>, TOut>;

class MyService extends StoreService {
    public constructor(private store: Store, private apiService: ApiService) {
        super('MyService');
        this.storeInit(); // Initialise the base service 
    }

    // Declare an action such typescript doesn't complain (the base class will implement this)
    // In this example: a user has typed in a search box and the filter value is updated
    public search!: (filter: string) => void;
    // Define an observable stream for async actions
    private search$: Stream<this["search"]> = pipe(
        // Side effect: update the store with the new filter value
        tap(([filter]) => this.store.update({
            search: {
                filter: filter,
            },
        })),
        debounceTime(350), // wait a bit
        switchMap(([filter]) => this.apiService.search(filter)), // fetch data based on filter
        // update the store with the fetched data
        tap(data => this.store.update({
            myData: data,
        })),
    );
}
```

Note that the above behaviour is notoriously hard and error-prone to write in plain functions. 

The base class
```ts
export class StoreService implements OnDestroy {
    public constructor(private name: string) { }

    private subjects: { [name: string]: Subject<any> } = {};

    public storeInit() {
        // Use this as any so we can access all properties
        const _this = <any>this;
        for (let key of Object.getOwnPropertyNames(this)) {
            // For every property that ends with a '$'
            if (key.endsWith('$')) {
                const actionName = key.substr(0, key.length - 1);
                // Create a subject and action that calls .next on it
                let subject = new Subject();
                let action = (...payload: any[]) => {
                    logAction(this.name + ' - ' + actionName);
                    (this.subjects[actionName] as Subject<any>).next(payload);
                };
                // Pipe the observable with the found property and subscribe to it
                let obs = subject.pipe(
                    _this[key],
                    catchError(err => { // Also some generic error handling
                        console.error(err);
                        return empty();
                    }),
                );
                obs.subscribe();

                // Keep list of subjects and expose the action
                this.subjects[actionName] = subject;
                _this[actionName] = action;
            }
        }
    }

    ngOnDestroy(): void {
        // Release all resources on destroy
        for (let actionName in Object.getOwnPropertyNames(this.subjects)) {
            this.subjects[actionName].complete();
        }
    }
}
```

**Comment by NetanelBasal** [comment]
I'm not sure how it's related to Akita. You have two options here:

1. Implement a Dispatcher class that emits events. For example:

```ts
class myService {
  constructor(dispatcher: Dispatcher) {
     this.search();
  }

  search() {
    this.dispatcher.pipe(filterEvent(SEARCH))...
  }
}
```


2. Use `fromEvent` and `switchMap`:

```ts
class MyComponent {

  ngAfterViewInit() {
    fromEvent(input, 'input').pipe(switchMap(() => service.search()));
  }
}
```

**Comment by didii** [comment]
>I'm not sure how it's related to Akita.

I thought having built-in observable stream actions available out-of-the-box from Akita could be a nice plus, since it's what I'm struggling with the most. I assumed I would not be the only one.

Thanks for the suggestions. The first seems worth a try and could heavily simplify my logic. If I have the time I'll see what I can come up with.

**Comment by NetanelBasal** [comment]
Sure. If you have something, you're welcome to share it with us. I'm closing this for now.
