### ISSUE TITLE
(bug): Active stays hydrated after calling store.set()

### ISSUE THREAD

**Issue by MonsieurMan** [datorama/akita#39]
## I'm submitting a...
```
[x] Bug report 
```

## Current behavior
After calling `store.set()`, `active` stays hydrated.

## Expected behavior
Maybe calling `store.set()` should reset `active` to null and then set entities for more robustness ?

## What is the motivation / use case for changing the behavior?
By example, if we call `store.set([])`, the id `active` is pointing to won't exist anymore and could cause many bug.

**Comment by NetanelBasal** [comment]
In our application, we have cases like that, but we call `setActive(null)`. I will check if it makes sense to do it out of the box.

**Comment by NetanelBasal** [comment]
@bh86 what do u think?
