### ISSUE TITLE
akitaPreUpdateEntity is not bind to the EntityStore

### ISSUE THREAD

**Issue by GrandSchtroumpf** [datorama/akita#390]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`akitaPreUpdateEntity` is not bind to the store. 
Here is an example:
```typescript
export class EventStore extends EntityStore<EventState> {
  constructor(private authQuery: AuthQuery) {
    super();
  }
  // Works good
  akitaPreAddEntity(event) {
    return createCalendarEvent(event, this.authQuery.userId);
  }
  // cannot read "authQuery" of undefined
  akitaPreUpdateEntity(prev, next) {
    return createCalendarEvent(next, this.authQuery.userId);
  }
}
```

## Expected behavior
`akitaPreUpdateEntity`should behave the same as `akitaPreAddEntity`

Others:
I think it comes from this line: 
https://github.com/datorama/akita/blob/master/akita/src/entityStore.ts#L191

**Comment by NetanelBasal** [comment]
You need to use `bind`:

```ts
export class EventStore extends EntityStore<EventState> {
  constructor(private authQuery: AuthQuery) {
    super();
    this.akitaPreUpdateEntity = this.akitaPreUpdateEntity.bind(this); 
    this.akitaPreAddEntity = this.akitaPreAddEntity.bind(this); 
  }

  akitaPreAddEntity(event) {
    return createCalendarEvent(event, this.authQuery.userId);
  }

  akitaPreUpdateEntity(prev, next) {
    return createCalendarEvent(next, this.authQuery.userId);
  }
}
```

**Comment by GrandSchtroumpf** [comment]
Sure, I can use bind. It's more the mismatch of behaviour between the two methods that I wanted to point out in this issue :).
I guess it's more an inconsistency than a bug though.
