### ISSUE TITLE
store.toggleActive() throws Cannot read property 'includes' of null

### ISSUE THREAD

**Issue by mcroker** [datorama/akita#392]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
If store.toggleActive() is called prior to setting an active element then an exception is thrown. 
```
MyTeamsPage.html:23 ERROR TypeError: Cannot read property 'includes' of null
    at datorama-akita.js:1877
    at Array.filter (<anonymous>)
    at TeamsStore.toggleActive (datorama-akita.js:1879)
    at TeamsStore.<anonymous> (datorama-akita.js:660)
    at applyTransaction (datorama-akita.js:618)
    at TeamsStore.<anonymous> (datorama-akita.js:656)
    at TeamsService.toggleActive (teams.service.ts:41)
    at MyTeamsPage.toggleGroup (myteams.page.ts:30)
    at Object.eval [as handleEvent] (MyTeamsPage.html:23)
    at handleEvent (core.js:38098)
```

## Expected behavior

With no active element set, I would expect toggleActive() to set the element passed in the arguments to be the active element.

## Minimal reproduction of the problem with instructions

Reproduce - stackblitz https://stackblitz.com/github/rlminqqq
Just click ToDo and then the button "hello" that subsequently appears

## What is the motivation / use case for changing the behavior?

As things stand the external code is required to work around this, effectively rendering the toggleActive() function a little redundant.   This is exacerbated because (as far as I can tell) the store don't expose anything like getActive() to allow the active element to be easily retrieved.

## Environment

<pre><code>
martin@martins-mbp-2 client % grep akita package.json 
    "@datorama/akita": "^4.19.2",
    "@datorama/akita-ng-router-store": "^4.0.0",
    "@datorama/akita-ngdevtools": "^4.0.0",

martin@martins-mbp-2 client % ng --version     

Angular CLI: 8.1.3
Node: 12.14.0
OS: darwin x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@angular/cdk                      8.1.4
@angular/material                 8.1.4
@angular/youtube-player           8.2.3
@ngtools/webpack                  8.0.6
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.5.4
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by NetanelBasal** [comment]
If you're working with the multi-active feature, you need to initialize the value manually. https://netbasal.gitbook.io/akita/entity-store/entity-store/active-state#managing-multiple-active-entities
