### ISSUE TITLE
Allow multiple stores under one state folder via schematics 

### ISSUE THREAD

**Issue by Disane87** [datorama/akita#393]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When I add a new feature with `ng g af todo/todo` there will be generated folder structure like this:
```
- state
-- feature.model.ts
-- feature.query.ts
-- feature.service.ts
-- feature.store.ts
```

But now we want to have a structure like this (with a custom folder name `_store`):
```
- _store
-- feature
--- feature.model.ts
--- feature.query.ts
--- feature.service.ts
--- feature.store.ts
```

## Expected behavior
There should be a way to customize the root store-foldername from `store` to `_store` and create a subfolder for  every feature like above.

## Minimal reproduction of the problem with instructions
Only execute `ng g af toto/todo`.

## Environment
Angular version: 8.0.0

**Comment by theorlovsky** [comment]
@NetanelBasal I can try to take this on.

**Comment by theorlovsky** [comment]
@Disane87 I took a look at this. So basically instead of `ng g af toto/todo` you can run `ng g af todo/_store/todo --dirName todo` to get the desired structure. Is that what you mean?

**Comment by theorlovsky** [comment]
Or do you want something like `ng g af todo/todo --parentDir _store`?

**Comment by theorlovsky** [comment]
@Disane87 As far as I understand, your motivation is to be able to create multiple states for the same feature in a convenient way. For example, you want to run the commands below:
```shell
ng g af todo/todos --parentDir _store
ng g af todo/new-todo --parentDir _store
```
and end up with the following structure:
```shell
todo
└── _store
    ├── new-todo
    │   ├── new-todo.model.ts
    │   ├── new-todo.query.ts
    │   ├── new-todo.service.ts
    │   └── new-todo.store.ts
    └── todos
        ├── todo.model.ts
        ├── todos.query.ts
        ├── todos.service.ts
        └── todos.store.ts
```

Is that right?

**Comment by Disane87** [comment]
Need to check that, but apparently I'm pretty busy with stuff going on at work

**Comment by NetanelBasal** [comment]
@theorlovsky it would be great if you can add it to the docs. 

@Disane87 I'm closing it for now. If it's not solved, feel free to reopen it.

**Comment by theorlovsky** [comment]
@NetanelBasal I guess this issue was closed by mistake, I haven’t finished with this yet.

**Comment by Disane87** [comment]
@theorlovsky I've checked your post from a few days ago. Sorry for the long delay :) 

Imageine, I have a module "CRM" where I have a few entities, like addresses or contacts. Now I want to have one single folder under "CRM" with "_state" or whatever and under that for every store a subfolder like this:

CRM
└── _store
    ├── address
    │   ├── address.model.ts
    │   ├── address.query.ts
    │   ├── address.service.ts
    │   └── address.store.ts
    └── contacts
        ├── contacts.model.ts
        ├── contacts.query.ts
        ├── contacts.service.ts
        └── contacts.store.ts


So your approach seems reasonable and looks like it's working for my juse case.

**Comment by Disane87** [comment]
@NetanelBasal No IMHO it's not solved because an option like @theorlovsky suggested is not available `--parentDir`

**Comment by NetanelBasal** [comment]
Oh, I thought it's something that exists in Angular schematics :)

**Comment by NetanelBasal** [comment]
Btw `_store` should be `state` by default.

**Comment by Disane87** [comment]
> Btw `_store` should be `state` by default.
> 
> ```
> CRM
> └── state
>     ├── address
>     │   ├── address.model.ts
>     │   ├── address.query.ts
>     │   ├── address.service.ts
>     │   └── address.store.ts
>     └── contacts
>         ├── contacts.model.ts
>         ├── contacts.query.ts
>         ├── contacts.service.ts
>         └── contacts.store.ts
> ```

Indeed `state` is a better term for this :)

**Comment by theorlovsky** [comment]
@NetanelBasal so now what I need to do is to basically implement a `--flat` flag that is `true` by default for backward compatibility?

**Comment by NetanelBasal** [comment]
No, it should be a new option.

**Comment by NetanelBasal** [comment]
You can add something like:

```
ng g af CRM/address --grouped
ng g af CRM/contact --grouped
```

**Comment by theorlovsky** [comment]
I thought `--flat` is a new option since there is no one in `akita-cli` now. And the usage is:
* `ng g af CRM/address` (same as `ng g af CRM/address --flat true`) – current behavior
* `ng g af CRM/address --flat false` – desired behavior:

   ```sh
   CRM
   └── state
       └── address
           ├── address.model.ts
           ├── address.query.ts
           ├── address.service.ts
           └── address.store.ts
   ```

I believe that `--flat` has more obvious meaning than `--grouped`.

**Comment by NetanelBasal** [comment]
Agree

**Comment by theorlovsky** [comment]
And one can easily combine it with existing `--dirName`:

`ng g af CRM/address --flat false --dirName _store`

```sh
CRM
└── _store
    └── address
        ├── address.model.ts
        ├── address.query.ts
        ├── address.service.ts
        └── address.store.ts
```

**Comment by theorlovsky** [comment]
Ok then, I'll open a PR this Saturday
