### ISSUE TITLE
Log actions produces incorrect actions in redux devtools

### ISSUE THREAD

**Issue by danyo1399** [datorama/akita#396]
## I'm submitting a bug where logAction does not log actions accurately in redux dev tools

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using logAction in certain scenarios, the actions dont correlate with the with the updates to state. Plus one action can be logged as two actions in redux devtools. See stackblitz below where you will see "set id" action logged twice for the one action

https://stackblitz.com/edit/angular-jfucsj

## Expected behavior
Actions should correlate with state changes + duplicate actions should not raised in dev tools for the one action

## Minimal reproduction of the problem with instructions
Open https://stackblitz.com/edit/angular-jfucsj 
have redux devtools installed.
open in new window so redux devtools binds to the app.
click the button.
then click the button again and see "set id" action logged twice for the one action

## What is the motivation / use case for changing the behavior?
The one thing i miss when moving from redux to Akita is the logging info you can get out of redux dev tools

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  stackblitz
- Platform:  mac / stackblitz

Others:

</code></pre>

**Comment by chriszrc** [comment]
@danyo1399 Thanks for posting the stack blitz repro, I can definitely see that it's logging to actions. Have you been able to replicate the other behavior that you mention in this issue, namely that action names are not corresponding to the actions beginning executed?
