### ISSUE TITLE
Router store no longer updates on navigations that don't run resolvers (5.0.0)

### ISSUE THREAD

**Issue by NickLargen** [datorama/akita#398]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Navigation that only changes query parameters does not emit new values when using `selectQueryParams`.

## Expected behavior
Router store always reflects the current url.

Would switching from `resolveEnd` to `navigationEnd` cause any problems?
For now I'm using `runGuardsAndResolvers: 'always'` instead of reverting to 4.0.

## Minimal reproduction of the problem with instructions
Run `this.router.navigate([], { queryParams: { foo: 'bar' }, queryParamsHandling: 'merge' });` and observe no router state changes.

## Environment
<pre><code>Angular version: 9.1.1
</code></pre>

**Comment by NetanelBasal** [comment]
The `navigationEnd` doesn't [return](https://angular.io/api/router/NavigationEnd) the current state. We can try using `ActivatedRoute` to get this information. You can test it and create a PR.

**Comment by NickLargen** [comment]
That makes sense. I will create a PR over the weekend.

**Comment by NetanelBasal** [comment]
v5.1.0. Thanks!
