### ISSUE TITLE
Differences from NGRX

### ISSUE THREAD

**Issue by xvs32x** [datorama/akita#4]
Why is this state manager better than NGRX? I have a choice. Thanks!

**Comment by NetanelBasal** [comment]
It's not a competition; they are both a good choice and will give you the same result, it's a matter of personal style.

**Comment by andrewtw** [comment]
@xvs32x 
If your project relies on Angular, and you are much more familiar with the Angular structure and DI, you will soon find the major differences.
Talking is cheap, checking the official example from Stackblitz is the better way.

NGRX: https://stackblitz.com/github/ngrx/platform/tree/61cbfe537f9df8cef3dd4a6ee0b8f483e49653f4
Akita:
https://stackblitz.com/edit/akita-todos-app?file=src%2Fapp%2Ftodos%2Fstate%2Ftodo.model.ts
