### ISSUE TITLE
Define Lint Rules

### ISSUE THREAD

**Issue by snebjorn** [datorama/akita#401]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe: linting
</code></pre>

## Current behavior

Running linters gives a lot of errors/warnings

## Expected behavior

No linting errors

## Minimal reproduction of the problem with instructions

1. Run `nx run-many --target=lint --all`

## What is the motivation / use case for changing the behavior?

Enforcing linting rules makes for a healthy code base.
Perhaps a linter config discussion is in order :)

### Libs

- [ ] Phase 1: Apply a loose-ish set of rules on the code base
- [ ] Phase 2: Apply a strick set of rules on the code base
  - [ ] enable disabled rules in akita tests
- [ ] Phase 3: Turn on TSC --strict

### Apps

- [ ] Phase 1: Apply a loose-ish set of rules on the code base
- [ ] Phase 2: Apply a strick set of rules on the code base
- [ ] Phase 3: Turn on angulars strictTemplates and strictInjectionParameters

**Comment by snebjorn** [comment]
I'll be trying to go for this config
```
"extends": [
    "airbnb-typescript/base",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier",
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended"
  ],
```

I might loosen it a bit as Akita alone have `✖ 978 problems` 😨

**Comment by snebjorn** [comment]
I want to adjust the prettier `printWidth` so a line doesn't exceed the width of the PR review page width. Currently it's giving horizontal scrollbars 😢 

Would also be nice to be able to fit files side by side in the editor.

**Comment by NetanelBasal** [comment]
No

**Comment by NetanelBasal** [comment]
Any news here?

**Comment by snebjorn** [comment]
No sorry. I'm still planning on doing it

**Comment by NetanelBasal** [comment]
Closing this for now.
