### ISSUE TITLE
Mark akita-schematics as deprecated

### ISSUE THREAD

**Issue by snebjorn** [datorama/akita#402]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

https://www.npmjs.com/package/akita-schematics is listed as an active package

## Expected behavior

https://www.npmjs.com/package/akita-schematics should be marked as deprecated and inform that it's part of https://www.npmjs.com/package/@datorama/akita as of version X

## What is the motivation / use case for changing the behavior?

It's confusing for newcomers :)

Here's a guide on how to do it https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions#deprecating-an-entire-package

**Comment by NetanelBasal** [comment]
Done. Thanks
