### ISSUE TITLE
`cacheable` should return an actual type instead of just `Observable<any>`

### ISSUE THREAD

**Issue by orlovskyalex** [datorama/akita#407]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Let's say you have a method like this:
```typescript
getString(): Observable<string> {
  const request = of(123);

  return cacheable(this.store, request); // no error here
}
```

It emits no error while there should be one: `Type 'Observable<number>' is not assignable to type 'Observable<string>'`. This is because `cacheable` returns `Observable<any>`.

## Expected behavior

I want to see an error if I made some. Thus, `cacheable` should return `Observable<T | undefined | never>`.

**Comment by NetanelBasal** [comment]
Sure, do you want to create a PR?

**Comment by orlovskyalex** [comment]
Yeah, sure, I'd like to try
