### ISSUE TITLE
persistOnDestroy in persistState options don't work

### ISSUE THREAD

**Issue by xuxicheta** [datorama/akita#409]
I made setup of persistState 
<pre><code>
persistState({
  include: ['teststore'],
  preStorageUpdateOperator: () => debounceTime(400),
  persistOnDestroy: false,
});
</code></pre>

And create and destroy store 'teststore'

## Current behavior
'teststore' have created in localStorage but not destroyed.
`persistOnDestroy`: `false` or `true` cause no reaction
## Expected behavior
if `persistOnDestroy: false` stores must be cleaned from localStorage after destroy.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/akita-641644613

## Environment
Akita 4.22.0

**Comment by NetanelBasal** [comment]
This is a horrible name. This property is only for the `cache` part.

**Comment by NetanelBasal** [comment]
It should be named `persistCacheOnDestroy`. If you don't want it in the `localstorage`, don't add it in the first place.

**Comment by xuxicheta** [comment]
@NetanelBasal 
I want it in localstorage, as example until my form will be submited or any other user action. Not form data, but anything else.
As I see i can get  `export const storage = persistState();` from main.ts, but It seems no good architecture decision

**Comment by NetanelBasal** [comment]
That's fine. Use DI for that. See https://github.com/datorama/akita/issues/365#issuecomment-580624210
