### ISSUE TITLE
Improve typing of entity's queries

### ISSUE THREAD

**Issue by xbaun** [datorama/akita#410]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using `selecEntity` or `getEntity` (and other methods returning single entity objects) on an `EntityQuery`, the return value may be `undefined` if the Entity ID does not exist. 
The method signature of these functions does not reflect the possible `undefined` return value, so Typscript cannot correctly check/warn when a possibly undefined entity is returned and then accessed.

## Expected behavior

Methods that select/get a single entity on an EntityQuery should be extended to a union type with `undefined` as an additional return value.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/typescript-wcf4a9

## What is the motivation / use case for changing the behavior?

Prevent the throwing of `Uncaught TypeError: Cannot read property 'XXX' of undefined` errors.

**Comment by NetanelBasal** [comment]
I'm afraid this will lead to a breaking change.

**Comment by xbaun** [comment]
I agree, but in the long run it's a small improvement that highly increases the fault tolerance.

**Comment by NetanelBasal** [comment]
Agree, but it'll be added in v5.

**Comment by NetanelBasal** [comment]
@xbaun it's a good time to add it.

**Comment by xbaun** [comment]
I only refactored the return values of the query entity functions without compiler type checking support. For further releases two major tsconfig adjustments should be done:
- Enabling at least the compile option `strictNullChecks` (preferable would be to directly enable `strict`) and `noImplicitAny`.
- Update Typescript to 3.7 or above to use optional chaining for easier refactoring of all dependent tests and functions.
- Remove explicit `any` definitions as far as possible.

This will probably require more time to implement because a lot of code needs to be touched.
