### ISSUE TITLE
 NullInjectorError: No provider for InjectionToken NgEntityServiceGlobalConfig!

### ISSUE THREAD

**Issue by manudss** [datorama/akita#411]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I Have follow this informations to work ng-entity-service : 
https://netbasal.gitbook.io/akita/angular/ng-entity-service

But I have this errors : 

core.js:6185 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(WithServerDemoModule)[PhotosFiltersService -> PhotosFiltersService -> PhotosService -> InjectionToken NgEntityServiceGlobalConfig -> InjectionToken NgEntityServiceGlobalConfig -> InjectionToken NgEntityServiceGlobalConfig]: 
  NullInjectorError: No provider for InjectionToken NgEntityServiceGlobalConfig!
NullInjectorError: R3InjectorError(WithServerDemoModule)[PhotosFiltersService -> PhotosFiltersService -> PhotosService -> InjectionToken NgEntityServiceGlobalConfig -> InjectionToken NgEntityServiceGlobalConfig -> InjectionToken NgEntityServiceGlobalConfig]: 
  NullInjectorError: No provider for InjectionToken NgEntityServiceGlobalConfig!

Any idea about this errors ? Thanks. 

## Minimal reproduction of the problem with instructions
Open the akita filters plugins with gitpod 
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/c6920c40-e2d3-4db9-b51d-6fcbe0974f7d)

juste run the demo : npm run start 

Go to photos page ! 

See on console the error . 

## Environment

<pre><code>
Angular version: 9.0.7
</code></pre>

**Comment by NetanelBasal** [comment]
Did you provide `NG_ENTITY_SERVICE_CONFIG`?

**Comment by manudss** [comment]
Yes like this :  {
    provide: NG_ENTITY_SERVICE_CONFIG,
    useValue: {
      baseUrl: 'https://jsonplaceholder.typicode.com'
    }
  }

**Comment by NetanelBasal** [comment]
@snebjorn, can you check it, please?

**Comment by snebjorn** [comment]
Not entirely sure why NG_ENTITY_SERVICE_CONFIG is registered in time. Probably some odd angular lazy load behavior. Guess we need to look into that - at some point.

But you move the provider to app.module then it works

**Comment by snebjorn** [comment]
Think I found the reason.

https://medium.com/@kevinwkds/angular-dependency-injection-service-lazy-loading-18ccb3f423a1

> 🔑 How lazy loading works in Angular Dependency Injection system
> When lazy-loading an NgModule during routing, the providers registered in the lazy-loaded NgModule and its children aren't available during the bootstrap process and Angular is unable to register them at that time. Therefore, they are added as providers only when the route is loaded and **furthermore they are scoped to be injected starting at the lazily-loaded NgModule and its children**. If there are multiple lazy-loaded NgModules attempting to register the same providers, each of these nodes of the NgModule tree end up with different instances. Then here comes the problem: What if we wants to share a singleton service instance across all lazy loaded modules ?

NG_ENTITY_SERVICE_CONFIG is registered in the lazy loaded module scope and you use `providedIn: root` on your service. That's different scopes

**Comment by NetanelBasal** [comment]
As @snebjorn `PhotosService` and `NG_ENTITY_SERVICE_CONFIG` are not on the same injector. Provide `NG_ENTITY_SERVICE_CONFIG` in the app module, and it'll work.

**Comment by manudss** [comment]
Thanks, for your quick anwser. Yes it working, and it make sens. 

Maybe it could be a good idea to add some information about this in the documentation.

**Comment by snebjorn** [comment]
You're welcome.
It's not really an Akita issue. It's how Angular is made and they've documented that behavior in their docs.
