### ISSUE TITLE
Refresh akita on store update performed from another tab?

### ISSUE THREAD

**Issue by Rush** [datorama/akita#417]
I have a PWA running Akita as a state management solution and have integrated localforage with IndexedDB as the `persistState` storage backend. Users of my application can interface with it from multiple tabs of their browsers. Would it be possible to detect IndexedDB state changes done in one application instance and have its own akita state automatically refresh based on the IndexedDB update?

**Comment by Rush** [comment]
Actually ... IndexedDB observers seem to be an experimental flag on Chrome only! https://www.chromestatus.com/feature/5669292892749824

**Comment by Rush** [comment]
That said maybe it could be achieved with polling on some "updateCounter". Is it possible to programmatically instruct Akita to reload its state from the latest version of the store?

**Comment by NetanelBasal** [comment]
It works with [localstorage](https://dev.to/arielgueta/keeping-browser-tabs-in-sync-using-localstorage-angular-akita-p39). You can try to use the same technique with IndexedDB.

**Comment by NetanelBasal** [comment]
https://dev.to/arielgueta/keeping-browser-tabs-in-sync-using-localstorage-angular-akita-p39
