### ISSUE TITLE
Don't export the 'createInitialState' function from a store

### ISSUE THREAD

**Issue by theorlovsky** [datorama/akita#421]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In case you have multiple states in one directory (which is not very good, but still), let's say it's a `state` directory with the following structure:
```
.
├── index.ts
├── state-a
│   ├── index.ts
│   ├── state-a.query.ts
│   ├── state-a.service.ts
│   └── state-a.store.ts
└── state-b
    ├── index.ts
    ├── state-b.query.ts
    ├── state-b.service.ts
    └── state-b.store.ts
```

And your `index.ts` files look like this (by default):
```
export * from './somewhere';
```

Then you're gonna have the following error in your top-level `index.ts`:
```
TS2308: Module './state-a' has already exported a member named 'createInitialState'.
Consider explicitly re-exporting to resolve the ambiguity.
```

## Expected behavior

I believe that in most cases you don't need the `createInitialState` function outside its state directory. If so, it might be a good idea to exclude this function from the corresponding `index.ts` file. Like this:
```
export * from './state-a.query';
export * from './state-a.service';
export { StateAState, StateAStore } from './state-a.store';
```

## What is the motivation / use case for changing the behavior?

I want the error above to be omitted by Akita, without the need to manage exports manually. What do you think about changing the schematics accordingly?

**Comment by NetanelBasal** [comment]
Agree. There is no reason to export the `createInitialState` function. You are welcome to submit a PR. Thanks.

**Comment by theorlovsky** [comment]
I'm not sure how to test `akita-cli`. Is there a way to build and use it locally?

**Comment by NetanelBasal** [comment]
Run `node index.js`

**Comment by theorlovsky** [comment]
Ok, thanks.
