### ISSUE TITLE
vuejs app

### ISSUE THREAD

**Issue by KANekT** [datorama/akita#422]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[X] Other... Please describe:
</code></pre>

Please add example for using Akita in VueJs

**Comment by NetanelBasal** [comment]
https://github.com/NetanelBasal/akita-vue

**Comment by KANekT** [comment]
@NetanelBasal thanks 

maybe create readme in https://github.com/datorama/akita/tree/master/apps

for this link to example )

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR with a complete application based on this template. I don't work with Vue.
