### ISSUE TITLE
Add an rxjs operator that handles the loading state of a store per operation

### ISSUE THREAD

**Issue by theorlovsky** [datorama/akita#426]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If you want to toggle the loading state, you basically has to do smth like this:
```ts
makeRequest(): Observable<any> {
  this.store.setLoading(true);

  return this.http.get(this.url).pipe(
    tap((data) => {
      this.store.update(data);
    }),
    tap(() => {
      this.store.setLoading(false);
    }),
  );
}
```

## Expected behavior

It would be nice and handy to do this instead (feel free to suggest a better name or/and approach):
```ts
makeRequest(): Observable<any> {
  return this.http.get(this.url).pipe(
    tap((data) => {
      this.store.update(data);
    }),
    withLoading(this.store),
  );
}
```

## What is the motivation / use case for changing the behavior?

To implement this logic in an operator, write less code and increase readability.

**Comment by theorlovsky** [comment]
I have a working prototype in our project, so I can open a PR if you find this feature helpful.

**Comment by NetanelBasal** [comment]
https://datorama.github.io/akita/docs/additional/operators#setloading

**Comment by theorlovsky** [comment]
Oh, it's already there 😅
Great, thanks!

**Comment by NetanelBasal** [comment]
We want to extend/replace the caching functionality and make it more powerful. If you have something in mind, let us know.

**Comment by theorlovsky** [comment]
At the moment I don’t, haven’t thought about it. But I’ll let you know if anything changes.
