### ISSUE TITLE
SSR: window is not defined at enableAkitaProdMode()

### ISSUE THREAD

**Issue by mateuszroszczyk** [datorama/akita#427]
## I'm submitting a...

<pre><code>[x] Regression
[x] Bug report
</code></pre>

## Current behavior

Reference error is being thrown in production mode.

## Expected behavior

No error is thrown.

## Minimal reproduction of the problem with instructions

1. Create new angular app.
2. ng add @nguniversal/express-engine
3. ng add @datorama/akita
4. add 'enableAkitaProdMode()' inside src/main.server.ts
5. npm run build:ssr
6. npm run serve:ssr - here you get the error

**Comment by NetanelBasal** [comment]
Yes, I see. We need to add protection [here](https://github.com/datorama/akita/blob/87933d2f959f8e034b649f83438a102d8b1f30a9/libs/akita/src/lib/env.ts#L5). Do you want to create a PR?

You can use [this](https://github.com/datorama/akita/blob/master/libs/akita/src/lib/root.ts#L1) function.

**Comment by mateuszroszczyk** [comment]
Sure, I'll get it done.
