### ISSUE TITLE
Akita resetStores() not returning initial states

### ISSUE THREAD

**Issue by jongbonga** [datorama/akita#431]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Calling `resetStores()` on a store initialised like

```
export function createInitialState(): UserState {
  return {
    data: {
      recordNumber: 1,
      recordName: 'site',
      title: 'Akita',
      description: 'Some description here',
      logoUrl: 'https://datorama.github.io/image/2009030915-0-5500-300x100/logo.png',
      theme: 'f5app',
      colorScheme: 'placeholder',
      userName: 'Guest User',
      firstName: 'Guest',
      lastName: 'User',
      userUniqueId: 'guest-user',
      userImageUrl: 'https://datorama.github.io/image/Icon9_char.png',
      userImageWidth: '45',
      userImageHeight: '45',
      userLanguage: 'en_US',
      isGuest: 'true',
      canAddProfiles: 'false',
      canAddProjects: 'false',
      canInviteByEmail: 'true',
      canPostActivity: 'false',
      canPostEvents: 'false',
      canPostPhotos: 'false',
      canPostTopics: 'false',
      canCreateNotifications: 'false',
      lastCheckInDate: '',
      lastLocation: ''
    }
  };
}
```
results in data to be cleared and I get an empty object {} instead of the initialised values

1. Create store with akita cli
2. add initial state manually
3. update state with new data when user login
4. reset state when user logout

## Expected behavior

Expecting `resetStores()` to reinitialise value instead of clearing them 

## Environment

<pre><code>
Angular version: 9.1.6
Akita : 4.23.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
The initial state is what you pass in the constructor.

**Comment by jongbonga** [comment]
this is what I have

```
constructor() {
    super(createInitialState());
  }
```

**Comment by NetanelBasal** [comment]
Could you reproduce it [here](https://stackblitz.com/edit/akita-issue?file=src%2Fapp%2Fauth%2Fstate%2Fauth.query.ts), please?

**Comment by jongbonga** [comment]
it's behaving as it should on the stackblitz 😕 ... I might be doing something wrong 😞😞

**Comment by jongbonga** [comment]
So I narrow down when the problem occurs. when I use userStore/userQuery in one of my services and reset the store, it clears it.

so if I call `logout(){ userStore.reset()}` from my `auth.service` , it empty th store

**Comment by jongbonga** [comment]
I deleted my service, and recreated it! it's working now but I still don't know what I was doing wrong.

**Comment by field123** [comment]
@jongbonga did you ever work out what was happening having a similar issue? With the same setup you had.

`constructor() {
    super(createInitialState());
  }`

![image](https://user-images.githubusercontent.com/3082064/109648938-1fbe4f80-7b53-11eb-9ea7-f6065fc9ea97.png)
![image](https://user-images.githubusercontent.com/3082064/109648961-2947b780-7b53-11eb-9fde-ea2a31952a32.png)

**Comment by jongbonga** [comment]
@field123 

> I deleted my service, and recreated it! it's working now but I still don't know what I was doing wrong.
