### ISSUE TITLE
Generic Query with generic EntityStore constructor type incompatibility

### ISSUE THREAD

**Issue by kvetis** [datorama/akita#432]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm building a generic store/service/query on top of `QueryEntity` and `EntityStore`.

The problem is that I cannot call the `QueryEntity` constructor with the `GenericStore`.

```
export interface GenericItem {
  id: string;
  aProp: number;
}

export abstract class GenericStore<TEntity  extends GenericItem> extends EntityStore<
  EntityState<TEntity, string>,
  TEntity,
  string
> {}

export abstract class GenericQuery<
  TEntity extends GenericItem,
  T extends EntityState<TEntity, string> = EntityState<TEntity, string>
> extends QueryEntity<T, TEntity, string> {
  constructor(store: GenericStore<TEntity>) {
    super(store);
         ------
  }
}
```

The problem is following:
```
Argument of type 'GenericStore<TEntity>' is not assignable to parameter of type 'EntityStore<T, getEntityType<T>, getIDType<T>>'.
  Types of property 'selectEntityAction$' are incompatible.
    Type 'Observable<EntityAction<string>>' is not assignable to type 'Observable<EntityAction<getIDType<T>>>'.
      Type 'EntityAction<string>' is not assignable to type 'EntityAction<getIDType<T>>'.
        Type 'string' is not assignable to type 'getIDType<T>'.
```

## Expected behavior

The constructor should be callable with the genericly typed store.

## Minimal reproduction of the problem with instructions

Try to compile the above code.

Or open the [code in stackblitz editor](https://stackblitz.com/edit/akita-abstract-query)

## What is the motivation / use case for changing the behavior?
I'm creating an abstract reusable store for my app use. This is a minor issue, since casting
the store in contructor to `super(store as EntityStore<T>);` is safe and quick workaround.

I understand that this issue is connected to whole QueryEntity <-> Entity Store generic relationship with the ease of use the single `<S>` generic argument.

Still, I think this issue should be filed, should someone else face the same problem.

## Environment

<pre><code>
Akita 4.23.2
Typescript 3.8.3
</code></pre>

## Further details

I dug deeper into the problem and when changing the `QueryEntity` constructor to:

`constructor(store: EntityStore<S, EntityType, IDType>, options?: QueryConfigOptions);`

the constructor call also fails to compile due to some other inner incompatibilities of the store.

**Comment by danzrou** [comment]
Typescript expects the same types as you inherit, meaning:

1. `TEntity` should use Akita's `getEntityType<T>`
2. `string` should use Akita's `getIDType<T>`

**Comment by kvetis** [comment]
@danzrou If Akita disallows using different generic types for `EntityType` and `IDType` than the defaults for store and query, then these types should not be generict at all.

I'm updating the original question to clarify the need to use `TEntity`.
The `TEntity extends GenericItem` is used because it ensures type safety for the operations/query on the store - the query can use `aProp` in a type safe manner.

**Comment by kvetis** [comment]
@danzrou But thanks for providing an approach for this.
I've dug deeper into approach you're suggesting and the problem (and the reason I started with specifically use `TEntity`) is that the `EntityType` is not inferred to child of `GenericEntity`.

```
/** Alternative approach */
export interface GenericState<
  EntityType extends GenericItem = any,
  IDtype = any
> extends EntityState<EntityType, IDtype> {}

export abstract class SecondGenericStore<
  TState extends GenericState
> extends EntityStore<TState> {}

export abstract class SecondGenericQuery<
  TState extends GenericState
> extends QueryEntity<TState> {
  constructor(store: SecondGenericStore<TState>) {
    super(store);

    // item is inferred as getEntityType<TState>, item.aProp is not inferred (any)
    this.selectAll({filterBy: item => item.aProp})
    
  }
}
```

**Comment by danzrou** [comment]
Sure thing - did that solve it out?

**Comment by kvetis** [comment]
@danzrou Unfortunately no, sorry for not being clear. In the code in [previous comment](https://github.com/datorama/akita/issues/432#issuecomment-632049025) the `selectAll` unfortunately does not infer the item properties correctly. Since I'm using a generic query with predefined selects for two types of entities it was the reason I rewrote my query to accept the entity type as an generic argument.

I see two options here. Wait and see if the typescript inference gets better (I haven't tried 3.9 yet) or I could try an PR for a wider generic compatibility of the store/query.

**Comment by danzrou** [comment]
I'm not sure if that can help you but I hope it will - below you'll find my implementation for an entity query which inherits Akita's entity query and is generic:

https://gist.github.com/danzrou/6dcedcb483c4f0a900cfb6447710b307

**Comment by kvetis** [comment]
That's quite interesting implementation. It made me look over my code again and I came up with a solution that corrects the inference ignoring the `extends` type constraint of the `EntityType` generic parameter. I consider this a workaround of typescript incompleteness.
```
export interface ThirdGenericState<
  // the `= GenericItem` is used as the inferred 
  // if you put Elephant in there, the item in the selectAll function is inferred as Elephant
  EntityType extends GenericItem = GenericItem,
  IDtype = string
> extends EntityState<EntityType, IDtype> {}

export abstract class ThirdGenericStore<
  TState extends GenericState
> extends EntityStore<TState> {}

export abstract class ThirdGenericQuery<
  TState extends ThirdGenericState
> extends QueryEntity<TState> {
  constructor(store: ThirdGenericStore<TState>) {
    super(store);

    // the lack of inference is corrected by the default generic value on line 48.
    this.selectAll({filterBy: item => item.aProp > 1})
  }
}
```

But still I believe that my first implementation is technically correct and should be compilable - when the Akita query and store have generic parameters, they should be compatible when explicitly set.

**Comment by danzrou** [comment]
I can agree - but I think the gap here is TS's mismatch between `getEntityType` and others which are totally compatible.

**Comment by NetanelBasal** [comment]
I am closing this issue. If there is any news here, feel free to reopen it.
