### ISSUE TITLE
React Native Issue, "Unable to resolve module"

### ISSUE THREAD

**Issue by Venipa** [datorama/akita#434]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

throws
```
error: Error: Unable to resolve module `state/application.query` from `src\AppWrapper.tsx`: state/application.query could not be found within the project.
```
i've already cleared the cache and followed already followed shared guides

## Minimal reproduction of the problem with instructions

you can use the initial react-native typescript template

## Environment

<pre><code>
React Native: 0.62.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.14.1
- Platform:  Windows (, Android)

Others:
- using yarn
</code></pre>

**Comment by NetanelBasal** [comment]
I'm not sure how it's related to Akita.

**Comment by Venipa** [comment]
i've ticked the support request since im looking for help to get it to run in "react" native.
some other people got it to run but i just dont know what im doing wrong there.

**Comment by NetanelBasal** [comment]
Try Stackoverflow.
