### ISSUE TITLE
Performance of Akita under heavy load

### ISSUE THREAD

**Issue by mateubo** [datorama/akita#435]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm considering to use Akita in a project but during the research reading I came across the following article: https://medium.com/@vpranskunas/deep-comparison-of-state-management-solutions-in-angular-562985d4474e

It states that Akita has some performance issues compared to e.g. NGRX. 
StackBlitz with performance tests is here: https://stackblitz.com/edit/angular-state-management-solutions-performance-comparison

## Expected behavior

I was hoping for a similar performance compared to other state management libriaies.
Is it caused by the test suite written incorrectly and the results can be improved or indeed it's Akita's issue?

**Comment by NetanelBasal** [comment]
You can read my comments in the article.

**Comment by mateubo** [comment]
I know the article was written by an author of one of these libs under comparison, meaning that the contents shall be taken cautiously, but focusing on the StackBlitz only - I wonder whether I'm going to eventually face some performance issues when using Akita, because, at least for this specific type of test, NGRX doesn't seem to underperforming.
I realize that such a test doesn't necessarily fit into real world example, but still.

**Comment by NetanelBasal** [comment]
I have no interest in convincing you. Use whatever you want. 

First, we are a big-data company, and we don't have any performance issues.

Second, the test uses `EntityStore.update/add()` methods, which supports many update variations that you'll not find in any other library. You can always update the entity directly using the underline `setState` method.
