### ISSUE TITLE
Improve type safety for entity state operations

### ISSUE THREAD

**Issue by xbaun** [datorama/akita#436]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If `upsert` is invoked on an `EntityStore` for a previously non-exsiting entity, an empty entity (object) is passed to `UpdateStateCallback`. This behavior is correct under the assumption that all fields of the entity state model are declared optional (nullable). Non-optional fields are not taken into account and are thus implicitly initialized with `undefined` which is incorrect. Therefore, when a new entity is created by `upsert`, non-optional fields must be explicitly initialized by the caller in-place or through a separate callback.

## Expected behavior

Pass `undefined` as old state to [`UpdateStateCallback()`](https://github.com/datorama/akita/blob/master/libs/akita/src/lib/entityStore.ts#L219) or provide a separate entity initializing callback argument in `upsert`. If `undefined` is passed, it indicates that the caller has to initialize the entity state in-place. 

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-ivy-jzvwgs?file=src%2Fapp%2Fapp.component.ts

## What is the motivation / use case for changing the behavior?

Improve/fix type safety for entity state operations: When using `upsert` in combination with https://github.com/datorama/akita/issues/153 a type safe entity store can be enforced.

**Comment by NetanelBasal** [comment]
Do you want to create a PR?
