### ISSUE TITLE
Two versions of docs

### ISSUE THREAD

**Issue by seangwright** [datorama/akita#438]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The description of the repository links to the original Titbook docs: https://netbasal.gitbook.io/akita/

The README of the repository links to the GitHub docs: https://datorama.github.io/akita/

## Expected behavior

There is only 1 definitive docs site that includes docs for the latest version

## Minimal reproduction of the problem with instructions

n/a

## What is the motivation / use case for changing the behavior?

I find myself ending up at both docs sites depending on what I happen to click on when looking to reference something.

Also, there are some interesting docs on one site that aren't on the other.

Example: [Best Practices: Subscription Management](https://netbasal.gitbook.io/akita/other/best-practices#subscription-management).

I find the above example to be helpful and this is a question I get regularly when introducing Akita to teams.

It isn't found in the [new docs](https://datorama.github.io/akita/docs/best-practices).

---

I'd be happy to make a PR but wanted to first check if you have plans for deprecated one of the docs sites and adding more to the other.

I know a lot of your blog posts (and posts from others at Datorama) detail a lot of Akita's functionality already, but those are a bit scattered around the web.

Btw, thanks for keeping this project going - I've used it in all my Angular apps since it was released.

**Comment by NetanelBasal** [comment]
The Gitbook is deprecated. You're welcome to submit a PR. I'll update the repo. Thanks.

**Comment by NetanelBasal** [comment]
Done.
