### ISSUE TITLE
(feat): PersistState - better ux for exclude / include

### ISSUE THREAD

**Issue by MonsieurMan** [datorama/akita#44]
## I'm submitting a...
```
[x] Feature request
```

## Current behavior
```typescript
persistState({
   exclude: [ 'test-store' ]
});
```
## Expected behavior
```typescript
import { TestStore } from '---/state/test.store';

persistState({
   exclude: [ TestStore ]
});
```

## Motivations
Using imports with class would make for a better development experience => compile time errors.  
This is trivial to implement using metadata attached with `@StoreConfig()`.

## Note on breaking change
This could either lead to a breaking change if we now only take classes.  
Or we could make the `include` & `exclude` arrays now take a `string` or a `class` as input and check on our end.  

I think going for the second option and then going for the class only option in the next major release would be the best.

> edit: would like to do a PR but npm hangs on a package because of the proxy at my company...

**Comment by NetanelBasal** [comment]
You will break lazy load stores with that.

**Comment by MonsieurMan** [comment]
Oh, forgot about them, for sure...
