### ISSUE TITLE
selectEntity types report error when used according to docs

### ISSUE THREAD

**Issue by IAMtheIAM** [datorama/akita#440]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
return this.todosQuery.ui.selectEntity(id, 'isOpen');

```
` src/app/todos/todos.component.ts(37,48): error TS2345: Argument of type '"isOpen"' is not assignable to parameter of type '(entity: {}) => {}'.
`
## Expected behavior

No type errors
## Minimal reproduction of the problem with instructions

Add code above into any comopnent or query.

## Environment

<pre><code>
Angular version: 9.x.x

Browser:
- [x] Chrome (desktop) version latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   v12.16.3

- Platform:   windows

Others:

</code></pre>

The typescript definitions don't show an option for a string as a second argument, but the docs and example stackBlitz use it like this. Does the type definition need updating or is this no longer a valid usage? It does work at runtime.

**Comment by NetanelBasal** [comment]
Please share a reproduction on stackblitz.

**Comment by NetanelBasal** [comment]
Is this still an issue?

**Comment by NetanelBasal** [comment]
Feel free to open it if it's still an issue.
