### ISSUE TITLE
inject service class in store and assign value from that service to initial value in store

### ISSUE THREAD

**Issue by rajeshgatla** [datorama/akita#442]
## I'm submitting a...

<pre><code>

[ ] Feature request
[ ] Support request

##**Question**

Can we inject a service class and set the value to the store from that service object?
 Instead of injecting session service in every component and setting the session values to form manually is tedious. 
Rather can we set this session values to store i.e in initialState? so that we can prevent boilerplate code in components.

 Current behavior

I am unable to set value that gets from session service and set to initial value in-store.
Getting undefined properties error.

Expected behavior :

I should be able to set value that gets from session service and set to initial value in-store.

Example

const initialState = {
  active: null,
  user : {
 userId : dummyLoggerService.getLoggedUser().userId,
 userLocation : dummyLoggerService.getLoggedUser().userLocation,
   }
};
@StoreConfig({
  name: 'dummy-name'
})
export class DummyStore extends EntityStore<DummyState> {

  public constructor(
    private dummyLoggerService: DummyLoggerService
  ) {
    super(initialState);
  }
}

 //  I also tried by AppInjector(UserSession).getLoggedUser().userId,
 //  AppInjector(UserSession).getLoggedUser().userLocation 
// didnt worked.

 Environment 

<pre><code>
Angular version: 9.0.7

 
For Tooling issues:
- Node version: 12.14.1
- Platform:    Windows

**Comment by NetanelBasal** [comment]
You can ask questions in our Gitter channel.
