### ISSUE TITLE
akita-ng-router-store@5.1.0 breaks prod build

### ISSUE THREAD

**Issue by katyapavlenko** [datorama/akita#446]
<pre><code>[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>
 
Hi! I updated akita-ng-router-store from 5.0.0 to 5.1.0 and my *production*(only) build broke

Here is the error:
```
ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[AkitaNgRouterStoreModule -> RouterService]: 
  StaticInjectorError(Platform: core)[AkitaNgRouterStoreModule -> RouterService]: 
    NullInjectorError: No provider for RouterService!
NullInjectorError: StaticInjectorError(AppModule)[AkitaNgRouterStoreModule -> RouterService]: 
```

Here are my deps:
```
    "@angular-devkit/build-angular": "~0.803.25",
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^7.3.7",
    "@angular/cli": "^8.3.25",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@datorama/akita": "^4.17.1"
```

Fixing version to `akita-ng-router-store@5.0.0` solved the issue
What should I change to be able to use 5.1.0?

**Comment by NetanelBasal** [comment]
@NickLargen can you check it, please? v5.1.0 is with your changes only.

**Comment by NickLargen** [comment]
That's weird. Could you list how you are importing `AkitaNgRouterStoreModule` and what the difference is between your development builds and production builds?

**Comment by katyapavlenko** [comment]
@NickLargen its imported regulary in `imports` block. 
This is where I import the class:
`import { AkitaNgRouterStoreModule } from '@datorama/akita-ng-router-store'`

Maybe the fact that it is imported in lazy loaded module, affects the build?
```
{
    path: 'path',
    canActivate: [AuthGuard],
    loadChildren: () => import('./moduleWithAkita.module').then(mod => mod.ModuleWithAkita),
  },
```
Unfortunately I can't easily update ng to 9, cause we have a huge project

here are builds:
```
 "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "outputHashing": "all",
            "aot": true,
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/assets/styles"
              ]
            },
            "assets": [
              "src/assets",
              "src/assets/favicon.ico"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [
              "src/assets/plugins/TweenMax.min.js"
            ]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
```

**Comment by NetanelBasal** [comment]
Is this the only place you import the module? Not in the `AppModule`?

**Comment by katyapavlenko** [comment]
yep, cause I only need it in one lazyloaded module

**Comment by NetanelBasal** [comment]
So v5 works with lazy, and 5.1 not?

**Comment by katyapavlenko** [comment]
yes, I can say so

**Comment by NetanelBasal** [comment]
In the meantime, use v5. I'll check it out when I can.

**Comment by NetanelBasal** [comment]
I just tried it in our playground, and it works fine.

**Comment by NetanelBasal** [comment]
If you can create a reproduction, I'll check it out.

**Comment by NetanelBasal** [comment]
@katyapavlenko any news here? It seems to work fine.

**Comment by katyapavlenko** [comment]
@NetanelBasal represented. Check readme for instructions
https://github.com/katyapavlenko/akita-bug

**Comment by xbaun** [comment]
The problem is that akita is currently compiled with ngc version 9, which produces build files which aren't compatible with angular 8 when using `buildOptimizer` (default for `--prod`). The problem is that ngc version 9  renamed `ngInjectableDef` token to `ɵprov` when computing injectable dependencies. With `buildOptimizer` enabled in angular 8 all decoraters are scrubbed away and thus for the akita-ng-router-store package files, too. Therefore angular cannot not read any provider information from decoraters or static injectable tokens when using `buildOptimizer`.

There are two options that should solve this issue:
* using ngc 8 to compile akita and its libs
* only support angular 9 as peer dependency and don't support angular 8

**Comment by NetanelBasal** [comment]
Thanks @xbaun, I was about to say the same :)

We should take the first approach. It's not about Akita. Akita doesn't depend on Angular. We should do it for the Angular plugins.

**Comment by NetanelBasal** [comment]
@katyapavlenko try v5.1.6.
