### ISSUE TITLE
Managing acess rights using Akita

### ISSUE THREAD

**Issue by zvnt** [datorama/akita#45]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

How about a blog post (or a recipe in the documentation, or just a couple of tips) which describes managing access rights, roles, and user groups using Akita? Would be great to see something like that.Thx :)

**Comment by NetanelBasal** [comment]
Will do. Thanks for the suggestion.

**Comment by NetanelBasal** [comment]
Hey, just wanted to say that I didn't forget you. I have an article about this topic, will publish it soon.

**Comment by NetanelBasal** [comment]
Here is an article about the topic. If you have any further questions, let me know.

https://blog.ng-book.com/managing-user-permissions-in-angular-using-akita/

**Comment by elhamabbasi** [comment]
I am wondering if you figured out any good solution for your problem? I want to have a dynamic Model the same as you.

**Comment by HackPoint** [comment]
> Here is an article about the topic. If you have any further questions, let me know.
> 
> https://blog.ng-book.com/managing-user-permissions-in-angular-using-akita/

Hi, I would like to ask you. 

`    <button *hasPermission="['write', 'admin']">Delete</button>
  </li>
</ul`

You have this part of code. But you didn't showed how you handling this issue when you admin+[array of roles] or you have an inherited roles like each role has base functionality which is inherited from the parent or grandparent object.
