### ISSUE TITLE
error on importing AkitaNgRouterStoreModule

### ISSUE THREAD

**Issue by kukubadze** [datorama/akita#454]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
error on importing AkitaNgRouterStoreModule
`inject() must be called from an injection context `

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-9-starter-material-rz8pt8

## Environment
Angular CLI: 9.1.9
Node: 12.18.0
OS: win32 x64
Angular: 9.1.11
Ivy Workspace: Yes
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        7.3.10
@angular/cdk                      9.2.4
@angular/cli                      9.1.9
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.41.6

**Comment by NetanelBasal** [comment]
I'll investigate soon. In the meantime use a lower version.

**Comment by NetanelBasal** [comment]
Can you try 5.1.2-beta.0, please?

**Comment by kukubadze** [comment]
@NetanelBasal 5.1.2-beta.0 works perfect. thank you

**Comment by NetanelBasal** [comment]
You can use 5.1.2.
