### ISSUE TITLE
Property 'options' is protected but type 'EntityStore<S, EntityType, IDType>' is not a class derived from 'EntityStore<S, EntityType, IDType>'

### ISSUE THREAD

**Issue by vladimirdrayling** [datorama/akita#459]
## I'm submitting a...

<pre><code>
[x] Other: typescript error when compiling a service
</code></pre>

The error:
```ts
ERROR in src/app/state/user.service.ts:7:14 - error TS2415: Class 'UserService' incorrectly extends base class 'NgEntityService<UserState>'.
  Types of property 'store' are incompatible.
    Type 'UserStore' is not assignable to type 'EntityStore<UserState, User, any>'.
      Property 'options' is protected but type 'EntityStore<S, EntityType, IDType>' is not a class derived from 'EntityStore<S, EntityType, IDType>'.

7 export class UserService extends NgEntityService<UserState> {
               ~~~~~~~~~~~
src/app/state/user.service.ts:9:11 - error TS2345: Argument of type 'UserStore' is not assignable to parameter of type 'EntityStore<UserState, User, any>'.

9     super(store);
```
Same error as img:
![image](https://user-images.githubusercontent.com/16114644/85122033-366f8100-b226-11ea-8be4-6272714785d9.png)

## Current behavior

The app works in the browser without any errors.

## Expected behavior

Typescript compiler shouldn't throw errors.

## Minimal reproduction of the problem with instructions

[Repo](https://github.com/vladimirdrayling/akita-errors)

0. Serve the app
0. Open `UserService`. The IDE should show the error already. If not
0. The error appears in console, too.

## Environment

<pre><code>
Angular version: 9.1.9

Browser:
- [x] Chrome (desktop) 83.0.4103.106 (Official Build) (64-bit)

For Tooling issues:
- Node version: v12.17.0
- Platform: Windows 10 x64

Others:
- IDE: WebStorm 2020.1.2
</code></pre>

**Comment by xbaun** [comment]
@NetanelBasal the  current `akita-ng-entity-service` npm package (5.0.0) has akita 5.0.2 as dependency. In the root `package.json` of the test repo above akita is in version 5.0.3 is installed. For typescript, it looks like the `NgEntityService` class extends a different class than `UserStore` in `user.model.ts`, despite it has the same class definition but comes from different packages.

```
npm show @datorama/akita-ng-entity-service                                                                                                                          14:47:28

@datorama/akita-ng-entity-service@5.0.0 | Apache-2.0 | deps: 1 | versions: 13
Akita entity service
https://github.com/datorama/akita/tree/master/libs/akita-ng-entity-service#readme

keywords: angular, akita

dist
.tarball: https://registry.npmjs.org/@datorama/akita-ng-entity-service/-/akita-ng-entity-service-5.0.0.tgz
.shasum: afefd1c6379f08ca97f15dce0a266411f2c6c9c4
.integrity: sha512-IxNOUuham/4Cls5qkrXoTCfGpTgu7fSXHmEA2gk6iCD109kzeY9JAh1/jY+ZqjMae8vWrbXUj3JHHby9VvCGAg==
.unpackedSize: 336.1 kB

dependencies:
@datorama/akita: 5.0.2 

maintainers:
- abh86 <amitbar@gmail.com>
- amitb <amit.barat@salesforce.com>
- ashakked <ashakked@salesforce.com>
- eliran.aharoni <eaharoni@salesforce.com>
- epessach <epessach@salesforce.com>
- gurdotan <gurdotan@gmail.com>
- iglikman <iglikman@salesforce.com>
- isinai <isinai@salesforce.com>
- keinans <crazypixel@gmail.com>
- lron <lron@salesforce.com>
- netanel-datorama <netanel.basal@datorama.com>
- netbasal <netanel7799@gmail.com>
- nhaimov <nhaimov@salesforce.com>
- org86 <or.gimel@gmail.com>
- ritox <gili842@gmail.com>
- samerkinaan <skinaan@salesforce.com>
- shahar.kazaz <shahar.kazaz@gmail.com>
- ssegal <ssegal@salesforce.com>
- tidhar.peer <tpeer@salesforce.com>

dist-tags:
latest: 5.0.0  
```

**Comment by NetanelBasal** [comment]
> the current akita-ng-entity-service npm package (5.0.0) has akita 5.0.2 as dependency

Where do you see it?

**Comment by xbaun** [comment]
In the output form `npm show @datorama/akita-ng-entity-service`, see my previous comment:

```
dependencies:
@datorama/akita: 5.0.
```

**Comment by NetanelBasal** [comment]
It doesn't specify any dependencies in package.json

**Comment by xbaun** [comment]
I was wondering, too. I verified it by installing akita 5.0.2 and and the error has gone. I also checked the `node_modules` directly and npm installs akita separately for `akita-ng-entity-service` in its own version.

**Comment by NetanelBasal** [comment]
I'm checking

**Comment by NetanelBasal** [comment]
Ok, I see that on build Nx adds Akita as a dependency. But it adds v5.0.2. Are you sure it works with v5.0.2? what about v5.0.3?

**Comment by NetanelBasal** [comment]
The --with-deps option cause this.

**Comment by NetanelBasal** [comment]
Ok, so it installed v5.0.2 because of the local dependency. v5.0.3 work. I'll remove the --with-deps option.

**Comment by xbaun** [comment]
> Ok, I see that on build Nx adds Akita as a dependency. But it adds v5.0.2. Are you sure it works with v5.0.2? what about v5.0.3?

When akita is installed as v5.0.3, then `akita-ng-entity-service` 5.0.0 isn't compatible anymore to the class definitions of v5.0.3 (presumably because of the protected field).

**Comment by NetanelBasal** [comment]
@vladimirdrayling delete akita-ng-entity-service, and try @datorama/akita-ng-entity-service@5.0.1.

**Comment by vladimirdrayling** [comment]
@xbaun and @NetanelBasal awesome work! Thank you! This issue is solved!
