### ISSUE TITLE
Akita devtools doesn't work in v5

### ISSUE THREAD

**Issue by NetanelBasal** [datorama/akita#460]
@xbaun  I think your recent changes cause issues

**Comment by NetanelBasal** [comment]
First, we need to add the `forRoot`. It doesn't enter `$$addStore.subscribe`.

**Comment by NetanelBasal** [comment]
For others that need the devtools, a workaround, for now, is to import `akitaDevtools` in `main.ts`.

```ts
import { akitaDevtools } from '@datorama/akita';

akitaDevtools();
```

**Comment by xbaun** [comment]
The problem is that `devTools.init()` is not called because DevTools [dispatches](https://github.com/datorama/akita/blob/master/libs/akita/src/lib/devtools.ts#L138) 'START' instead.

**Comment by NetanelBasal** [comment]
It worked before, what's happened?

**Comment by NetanelBasal** [comment]
and why it works when we don't use the module?

**Comment by xbaun** [comment]
I think a `devTools.init()` is missing in some other place. I'm gonna go check it out, but if I remember correctly, I haven't touched this.

**Comment by xbaun** [comment]
It's the same problem as https://github.com/datorama/akita/issues/459: The `akita-ngdevtools` package has a dependency to akita of its own, so messages for DevTools get dispatched to a instance of a different package. 

``` npm show @datorama/akita-ngdevtools 

@datorama/akita-ngdevtools@5.0.1 | Apache-2.0 | deps: 1 | versions: 14
Akita integration for Redux dev-tools chrome extension
https://github.com/datorama/akita/tree/master/libs/akita-ng-devtools#readme

keywords: angular, akita, akita devtools, devtools

dist
.tarball: https://registry.npmjs.org/@datorama/akita-ngdevtools/-/akita-ngdevtools-5.0.1.tgz
.shasum: ca98ce6fefc9170227dbf3940345726ff3c9d7a9
.integrity: sha512-uefwx+CJCIzNPzOMzvDjCLh7kYQQ5g3GeOKY0B/8pM4N5s5krUukvzCBEBkk+Ug/lma4LekPZpay6GuhPQNhpw==
.unpackedSize: 83.5 kB

dependencies:
@datorama/akita: 5.0.3 
```

**Comment by xbaun** [comment]
The [docs](https://datorama.github.io/akita/docs/enhancers/devtools/) need also a fix: `.forRoot()` is missing.
```ts
import { AkitaNgDevtools } from '@datorama/akita-ngdevtools';

@NgModule({
  imports: [environment.production ? [] : AkitaNgDevtools.forRoot()]
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by mhosman** [comment]
Yeah @xbaun, with .forRoot() is working okay. I don't know if this is part of the same problem but @NetanelBasal, the AkitaNgRouterStoreModule is also not working (nothing in the inspector).

**Comment by mhosman** [comment]
Not working for me with .forRoot(). Just with the @NetanelBasal main.ts workaround. Anyway, with this workaround, the AkitaNgRouterStoreModule is not working.

**Comment by xbaun** [comment]
@mhosman The `.forRoot()` is always required for `@datorama/akita-ngdevtools` . Currently, it does not work because there is a dependency problem that affects all other packages.

@NetanelBasal A fix would be to declare akita as a peerDependency for all akita libraries. Nx then skips the generation of an explicit dependency entry in package.json.

**Comment by NetanelBasal** [comment]
@xbaun I removed the `--with-deps` flag. I don't know what it was added again. Thanks for the help.

**Comment by NetanelBasal** [comment]
Fixed in akita-ngdevtools v5.0.2.

**Comment by xbaun** [comment]
When I run `nx build akita-ng-devtools --prod` (and omit `--width-deps` flag), a dependency entry is always generated in the package.json lib. If I understand `--width-deps` correctly (which isn't well documented) the flag only ensures that dependent projects are built in the right order.

I looked at the source code of NX and stumbled upon this code line: https://github.com/nrwl/nx/blob/7301930d3d4df16b444ced2b46ae7f18cd45e7aa/packages/workspace/src/utils/buildable-libs-utils.ts#L266. Apparently the generation of a dependency entries is only omitted if the project dependency is specified as peerDependecy in package.json.

...or maybe I'm just misunderstanding something here :grimacing:

**Comment by NetanelBasal** [comment]
This is the only package that does this. In the others, we don't specify Akita as peer dependency, and it doesn't add it as a dependency when we build it. When I have time, I will check why the devtools package is different.

**Comment by xbaun** [comment]
Currently, the other akita lib packages have the same dependency to akita set:
```bash
$ npm show @datorama/akita-ng-router-store dependencies version
dependencies = { '@datorama/akita': '5.0.3' }
version = '5.1.4'
```
```bash
$ npm show @datorama/akita-ng-entity-service dependencies
dependencies = { '@datorama/akita': '5.0.3' }
version = '5.0.1
```
```bash
$ npm show @datorama/akita-ng-forms-manager dependencies version
dependencies = { '@datorama/akita': '5.0.3' }
version = '5.0.1'
```

**Comment by NetanelBasal** [comment]
That's weird. Ok, I'll just add Akita as a peer dependency.

**Comment by mhosman** [comment]
Any news on this? Is still not working!

**Comment by xbaun** [comment]
In the latest version this issue should be fixed. I did a quick test and devtools worked correctly.

**Comment by mhosman** [comment]
Sorry but is not working for me. I'm using the latest version of Akita, latest version of AkitaNgDevtools, and latest version of AkitaNgRouterStoreModule with Angular 10. The DevTools just not work.

**Comment by xbaun** [comment]
Can you please provide a code sample to reproduce this. I also tested ng 10 and it worked.

**Comment by mhosman** [comment]
Hey @xbaun thanks for the response. I tested AkitaNgDevtools with .forRoot() and worked so maybe it could be great to add that change in the docs. Thanks!!

**Comment by xbaun** [comment]
No problem, glad i could help. The docs are already updated :)

**Comment by mhosman** [comment]
@xbaun it's not updated 😆

https://datorama.github.io/akita/docs/angular/router

**Comment by xbaun** [comment]
Oh you are right 😁  I only checked https://datorama.github.io/akita/docs/enhancers/devtools/#usage. @NetanelBasal fyi, a `forRoot` is still missing in the docs.

**Comment by NetanelBasal** [comment]
@xbaun where it's missing?

![image](https://user-images.githubusercontent.com/6745730/86018978-b2d84000-ba2e-11ea-965f-6a0e0715d695.png)

**Comment by xbaun** [comment]
> @xbaun it's not updated 😆
> 
> https://datorama.github.io/akita/docs/angular/router

DevTools are used in the router documentation and there is `forRoot` missing in the example of `app.module.ts`.

**Comment by field123** [comment]
I don't know the difference between the docs at https://netbasal.gitbook.io/akita/enhancers/devtools and https://datorama.github.io/akita/docs/enhancers/devtools/ but the gitbook.io is showing 
![image](https://user-images.githubusercontent.com/3082064/86493144-4c259000-bd68-11ea-9cde-9c07c9b2f426.png)

Find the multiple docs a little confusing. But adding .forRoot() solved my issue. Thanks.

**Comment by NetanelBasal** [comment]
@field123 netbasal.gitbook.io/akita/enhancers/devtools is deprecated.

**Comment by 2advancesolutions** [comment]
> ```ts
> import { akitaDevtools } from '@datorama/akita';
> ```

Update your docs

**Comment by C-Dub1978** [comment]
Is this still broken? I am using latest akita, latest devtools  ( akita 7.1.1, devtools 7.0.0).... I definitely have both the forRoot being called, and also called akitaDevtools() in my main.ts.... Odd thing is that I am getting a list of devtools actions in the extension, up to a certain point, and then it just stops logging - I am expecting to see state updating after some specific actions and its like devtools is just frozen at a certain point... I am logging the results of this.store.getValue() and I can see my store has been updated, but devtools is just stuck/stopped at that point....... Also i used a crazy  number in the forRoot options for maxAge, like 5000 so that shouldn't be the issue. Thanks
