### ISSUE TITLE
Change log version seems off in the docs

### ISSUE THREAD

**Issue by jacobdr** [datorama/akita#464]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Changelog doc format seems different than the Breaking Changes format. The version numbers in the changelog do not reflect the actual versions of the library

## Expected behavior

I would expect that the versions in the Changelog would reflect the versions of the library as they are published on NPM and in the Github releases

## Minimal reproduction of the problem with instructions

Look at the version numbers in the following docs:

Changelog Doc (from latest 5.0.5 release) -- [link](https://github.com/datorama/akita/blob/akita-v5.0.5/CHANGELOG.md)
Breaking Changes Doc (from latest 5.0.5 release) -- [link](https://github.com/datorama/akita/blob/akita-v5.0.5/BREAKING_CHANGES.md)

## What is the motivation / use case for changing the behavior?

I want to make it easier to understand what has changed between versions

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
We are using an automated tool to create the changelog. Sometimes there are some bad commits. To make it clearer, I've created the breaking changes file, so use it as a reference.

**Comment by cshouts-tasc** [comment]
@NetanelBasal I'm confused. Why is the latest entry in the changelog for v0.1.0 released on 2020-06-18? Where is the changelog for v5.2.2 of the `@datorama/akita` package?

**Comment by NetanelBasal** [comment]
It's a bug. We've added this: https://github.com/datorama/akita/commit/3085dc8e742960c4fe905f546f3e6370fb9a6a14
