### ISSUE TITLE
Schematics: `withMultiActive` option

### ISSUE THREAD

**Issue by vladimirdrayling** [datorama/akita#468]
## I'm submitting a...

[x] Feature request

## Current behavior

There's no option `withMultiActive` in schematics.

![image](https://user-images.githubusercontent.com/16114644/85710535-a37f8c80-b6e6-11ea-99ee-5ea1a71abc05.png)

## Expected behavior

The `withMultiActive` option in schematics next to `withActive` or as a dropdown with two options: `withActive` and `withMultiActive`.

If a state can extend `withActive` and `withMultiActive` simultaneously then two checkboxes else a dropdown with options.

**Comment by NetanelBasal** [comment]
You're welcome to create a PR.

**Comment by vladimirdrayling** [comment]
Unfortunately, I don't have enough time right now. Hope starting it later
