### ISSUE TITLE
Module not found: Error: Can't resolve '@datorama/akita/lib/runStoreAction'

### ISSUE THREAD

**Issue by fritzschoff** [datorama/akita#472]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If you import the runStoreAction like in the docs [here](https://datorama.github.io/akita/docs/additional/events/)
you get this error:
`'Module '"../../../../../node_modules/@datorama/akita/datorama-akita"' has no exported member 'EntityStoreAction'.ts`
and if you import like VSCode suggestes:
```
import {getEntityType } from '@datorama/akita';
import { StoreAction, runEntityStoreAction, EntityStoreAction, runStoreAction } from '@datorama/akita/lib/runStoreAction';
```
you get: `Module not found: Error: Can't resolve '@datorama/akita/lib/runStoreAction'`
## Environment

<pre><code>
Angular version: 9.0.1

</code></pre>

**Comment by xbaun** [comment]
Don't import from subfolders of the akita package. Import only from the package root:
```
import { getEntityType, StoreAction, runEntityStoreAction, EntityStoreAction, runStoreAction } from '@datorama/akita';
```
But there is currently an error that `StoreAction` and `EntityStoreAction` are not exported. A PR is pending.

**Comment by silverstory** [comment]
My akita app is not working anymore when upgraded to angular version 10
and also upgraded akita to
@datorama/akita version 5.2.5

Help me! Now!!!

App error is complaining about line 4 and line 8 in this file:
https://github.com/silverstory/akita-socketio/blob/master/src/app/livefeed-list.service.ts

Link to app
https://github.com/silverstory/akita-socketio
