### ISSUE TITLE
Save states to different storages

### ISSUE THREAD

**Issue by gritschf** [datorama/akita#480]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I want to save states to different storages. (localstorage and sessionstoagre).  

I did this by including some stores to the localstorage `persistState` and excluding them from the sessionStorage
```

persistState({storage: localStorage, include: ['state1', 'state2']});
persistState({storage: sessionStorage, exclude: ['state1', 'state2']});
```

so everything except state1 and state2 is saved to sessionStorage (and state1 and state2 are saved to localStorage)

But now exclude was removed

## Expected behavior

How can a save states to different storages? (maybe i did miss something in the documentation)

## What is the motivation / use case for changing the behavior?

I need some states saved in the localstorage but others in the sessionStorage

## Environment

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by xbaun** [comment]
You can pass a filter function through the [`include`](https://github.com/datorama/akita/blob/3f4e5ae87c9a9bca46b5b41f8db6cd57390e77bb/libs/akita/src/lib/persistState.ts#L64) param to select only certain stores.

**Comment by gritschf** [comment]
@xbaun nice! i didn't know that. works like a charm. thanks!
