### ISSUE TITLE
Store Values are clearing on Refresh

### ISSUE THREAD

**Issue by sylendra7** [datorama/akita#485]
On Refreshing of page store values are getting cleared . I'm getting the data from API where I used AKkita to store my data .While navigating from page to page data is there , whenever I refresh the page then data is getting lost . I can use localStorage or sessionStorage but as we can see the values from browser developer tools I don't want to use this . Can you please help me on how to maintain the data throw out the app even though I refresh the browser 

export class AuthorizationService {

  constructor(private authStore: AuthorizationStore) {
  }

  UpdateUserPermissions(permissions:AppPermissions){
    // this.authStore.reset();
    this.authStore.update(permissions);
  }
}
@Injectable({ providedIn: 'root' })
@StoreConfig({ name: 'Authorization' })
export class AuthorizationStore extends Store<AppPermissions>{

  constructor() {
    super(createInitialState());
  }
}

**Comment by NetanelBasal** [comment]
Use [persist-state](https://datorama.github.io/akita/docs/enhancers/persist-state).
