### ISSUE TITLE
Typo: "Tailored Made"

### ISSUE THREAD

**Issue by duckflyer** [datorama/akita#487]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe: Just a typo :)
</code></pre>

## Current behavior

Misspelled "Tailored-Made"
 
## Expected behavior

"Tailor-Made"

## Minimal reproduction of the problem with instructions

See the readme on github.

**Comment by NetanelBasal** [comment]
Thanks!

**Comment by NetanelBasal** [comment]
Fixed.
