### ISSUE TITLE
getStoreValue(storeName)

### ISSUE THREAD

**Issue by fritzschoff** [datorama/akita#488]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Usually retrieving the value from a story works flawlessly with the query. But there are might be occasions where you want to get the value without using the query cause the query is not reachable at the moment.

## What is the motivation / use case for changing the behavior?

I'm thinking of the `runStoreAction` function, which lets you perform crud operations. Now why not having it the otherway around. 
`getValueFromStore(storeName: string)`, so you can get the a snapshot of information from a store. If this issue got a positive feedback i can do a PR.

**Comment by NetanelBasal** [comment]
You can already access the store by using `getStoreByName`.

**Comment by fritzschoff** [comment]
yes agreed. `getStoreByName` works fine for me!
