### ISSUE TITLE
More detailed documentation for UI State

### ISSUE THREAD

**Issue by vildhjarta8** [datorama/akita#49]
## I'm submitting a...

<pre><code>
[_] Regression (a behavior that used to work and stopped working in a new release)
[_] Bug report  
[_] Performance issue
[_] Feature request
[X] Documentation issue or request
[_] Support request
[_] Other... Please describe:
</code></pre>

Hello. First of all, thank you guys for this amazing product.
Can you please write some examples or complete the documentation section about UI State.
Most interesting thing is how I can read/write UI state?

**Comment by NetanelBasal** [comment]
I updated the [documentation](https://netbasal.gitbook.io/akita/entity-store/ui-state). If you have additional questions, we'd be happy to help. Thanks!
