### ISSUE TITLE
selectNavigationExtras and getNavigationExtras are part of Angular router store documentation but doesnt seem to exist anymore

### ISSUE THREAD

**Issue by brice-noowu** [datorama/akita#491]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular router store part of the doc states that there's `selectNavigationExtras` and a `getNavigationExtras` method, but those doesnt seems to be part of the `RouterQuery` anymore

## Expected behavior

Remove those selectors from the doc

**Comment by NetanelBasal** [comment]
https://github.com/datorama/akita/blob/b706365dd421e7f5e8efa3eb7f6f67dcd6cf35a3/libs/akita-ng-router-store/src/lib/router.query.ts#L134

**Comment by brice-noowu** [comment]
Sorry I wasnt on the correct repo https://github.com/datorama/akita-ng-router-store
