### ISSUE TITLE
Introduce UI state for Store

### ISSUE THREAD

**Issue by ArulRozario** [datorama/akita#492]
We have UI state for entity store which is a great thing. It would be great to have UI state for the store as well. Maybe there are ways already. I store both UI state and data state in the same store which triggers unnecessary rxjs change events.

**Comment by NetanelBasal** [comment]
Just create a `ui` property and add the UI data in there. https://engineering.datorama.com/ui-state-management-made-easy-with-akita-and-angular-6e460566ec7c

**Comment by ArulRozario** [comment]
That's my current setup. But every time there is a change in the UI property the whole store emits, unlike Entity Stores where entities and UI have different BehaviourSubjects. UI state changes in Entity stores don't conflict with entity changes and vice versa.

**Comment by NetanelBasal** [comment]
But every time there is a change in the UI property the whole store emits

That's not true. If you update a UI property and you have a subscriber to a selectEntity for example, it'll not emit.
