### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by aloifolia** [datorama/akita#495]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

On page https://datorama.github.io/akita/docs/best-practices, the `Array Utils` link is not correct:

<img width="855" alt="Screenshot 2020-07-21 at 08 41 37" src="https://user-images.githubusercontent.com/1295054/88021661-379a1380-cb2e-11ea-8278-8c3d99590b7f.png">

It leads to:

<img width="550" alt="Screenshot 2020-07-21 at 08 42 20" src="https://user-images.githubusercontent.com/1295054/88021670-3cf75e00-cb2e-11ea-9e5a-7378e9cc3c79.png">

## Expected behavior

The correct address would be `https://datorama.github.io/akita/docs/additional/array/`.

**Comment by geromegrignon** [comment]
i'm not able to reproduce it with current behavior.

**Comment by aloifolia** [comment]
The link seems to be fixed, now 🤷 .
