### ISSUE TITLE
Discuss: Plans to create an akita-lite or akita-core

### ISSUE THREAD

**Issue by menosprezzi** [datorama/akita#499]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Hello Guys!
I'd love akita and Rxjs state management. I'm now using it with React and Observable hooks, based on facades approach by Thomas Burlenson... But I was thinking that this lib is bit large (I know that's tree shakable) so if is there a way to provide an akita-lite, with no cache logic, no entity logic, just plain RxJS, minimal Redux approach with devtools integration.

Thanks you all!

**Comment by NetanelBasal** [comment]
@xbaun and I are working on a light version of Akita. But as you said, everything is tree-shakable. If you only need the `Store` it's the only code that you'll see in the bundle.
