### ISSUE TITLE
Feature Request: QueryEntity#selectEntityAction accept multiple EntityActions

### ISSUE THREAD

**Issue by talohana** [datorama/akita#501]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

[`QueryEntity#selectEntityAction`](https://github.com/datorama/akita/blob/8a6465d4819de470cfc18900ff633c8fdab65e18/libs/akita/src/lib/queryEntity.ts#L301) currently accepts a single `EntityActions` or none,

## Expected behavior
[`QueryEntity#selectEntityAction`](https://github.com/datorama/akita/blob/8a6465d4819de470cfc18900ff633c8fdab65e18/libs/akita/src/lib/queryEntity.ts#L301) should accept multiple `EntityActions` similarly to ngrx's [`ofType`](https://ngrx.io/api/effects/ofType) operator.

## What is the motivation / use case for changing the behavior?

In our app we sometime need to listen to a subset or all of `EntityActions`, in order to get these actions we need to use RxJS `merge` operator and select each `EntityActions` separately, for example:  
```typescript
    merge(
      this.itemQuery.selectEntityAction(EntityActions.Add),
      this.itemQuery.selectEntityAction(EntityActions.Remove)
    ).subscribe(() => {
      // ... do something accordingly
    });
```

A workaround is to expose a selector which holds the above code.
With `selectEntity` accepting multiple `EntityActions` the above code could be reduced to:

```typescript
    this.itemQuery
      .selectEntityAction(EntityActions.Add, EntityActions.Remove)
      .subscribe(() => {
        // ... do something accordingly
      });
```

Would be happy to submit a PR if needed :)

**Comment by roee264** [comment]
That could realy help my project too. We encountered it also

**Comment by xbaun** [comment]
Hi, we would be glad if you create a PR. I think about something like this:
```ts

selectEntityAction(...actions: EntityActions[]): Observable<IDType[] | EntityAction<IDType>> {

    if (actions.length === 0) {
        return this.store.selectEntityAction$;
    }

    return this.selectEntityAction$.pipe(
        filter(action => actions.include(action.type),
        map(({ type, ids }) => ({ [type]: ids })))
    );

}
```
The result would be objects like `{ [EntityActions.Update]: [1,2,3,4] }` with the action as key and the ids as value.

**Comment by talohana** [comment]
@xbaun I wonder whether it's worth to check if the array has only single element to keep current behavior or to be consistent and change even for a single action type.

**Comment by talohana** [comment]
@xbaun I encountered a weird test assert while implementing, in [entityActions.spec.ts](https://github.com/datorama/akita/blob/8a6465d4819de470cfc18900ff633c8fdab65e18/libs/akita/src/__tests__/entityActions.spec.ts#L59) there is call to [`entityStore.remove()`](https://github.com/datorama/akita/blob/8a6465d4819de470cfc18900ff633c8fdab65e18/libs/akita/src/lib/entityStore.ts#L419) with now parameters.
After debugging and going over the code it seems that is emits a `{ type: EntitiesActions.Remove, ids }` where `ids` are set to `null`. 
The mentioned test asserts it emits `ids` as `[3, 4]` and somehow passes, am I missing something?

**Comment by xbaun** [comment]
Seems to be an error in the specs: After each entity store function call `spy.mockClear();` should be called and therefor the last test seems to be wrong.

@NetanelBasal There seems also to be a failure in `entityStore.remove()` which probably should not emit an entity action if no arguments are provided to remove.

**Comment by NetanelBasal** [comment]
Why? it means to remove all.

**Comment by xbaun** [comment]
Ok I see. But the emitted entity action has the ids payload set to `null`, instead of the complete entity stores ids array.

**Comment by NetanelBasal** [comment]
This is a bug.

**Comment by talohana** [comment]
@NetanelBasal created issue #503 to fix this before moving on with this feature
