### ISSUE TITLE
Create Akita devtools

### ISSUE THREAD

**Issue by NetanelBasal** [datorama/akita#502]
We're looking for a contributor that wants to create our own devtools.

**Comment by NetanelBasal** [comment]
Sure.

**Comment by shammy8** [comment]
Any more info?

**Comment by NetanelBasal** [comment]
It doesn't need to be a chrome extension. It can be an Angular library that the consumer installs in the application. It should allow the following:

- See the stores list and their current state
- See the actions and the diff between the states of each one
- Allow updating the state

Are you familiar with the redux devtools?

**Comment by shammy8** [comment]
Yes I know the basics at least.  What will the Akita devtool offer that the redux one doesn't already?

I really enjoy using Akita so far btw been messing about with it the past few days. Think I need to familiarise myself with Akita more first before starting this.

**Comment by NetanelBasal** [comment]
Sure, thanks.

**Comment by KamilSocha91** [comment]
@shammy8  What's state of this topic, sound really helpful.

**Comment by NetanelBasal** [comment]
Idle.

**Comment by drackp2m** [comment]
But it already works with Redux DevTools, why create another add-on?

(https://github.com/reduxjs/redux-devtools)
