### ISSUE TITLE
Transfering state from SSR -> Client when using Angular Universal

### ISSUE THREAD

**Issue by wundo** [datorama/akita#508]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using angular universal, Akita runs fine on SSR, but the state doesn't transfer to the client, causing some flickering on the page. Besides one glitter question about it (without answer) I could not find any documentation about either Akita supports it or not, or how to achieve this.

## Expected behavior

Some clear documentation or guide about this would be great :)

## Minimal reproduction of the problem with instructions

Create any project with Angular Universal and Akita :)

**Comment by NetanelBasal** [comment]
I'm not sure how it's related to Akita.
