### ISSUE TITLE
Conditional import of akita-ngDevtools with Angular9 and Ivy

### ISSUE THREAD

**Issue by Roseidon** [datorama/akita#509]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When I want to conditionally import the DevTools for Angular9 (with ivy), like
![image](https://user-images.githubusercontent.com/19248263/90152267-eb866b80-dd87-11ea-9825-c5c09c22b022.png)
and run the build with `npx ng build coolproject --configuration=development --aot=true` I get an error:
```
ERROR in projects/coolproject/src/app/app.module.ts:43:12 - error NG1010: Value at position 0 in the NgModule.imports of AppModule is not a reference: [object Object]

 43   imports: [
               ~
 44     environment.production ? [] : AkitaNgDevtools.forRoot(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 66     }),
    ~~~~~~~
 67   ],
    ~~~
```

## Expected behavior
I expect to have no error but have the DevTools for development only, not production

## Minimal reproduction of the problem with instructions

- Use Angular9 with Ivy
- Install @datorama/akita-ngdevtools v5.0.3
- Try to use it in your app.module.ts as conditional import

## What is the motivation / use case for changing the behavior?

The motivation is to not have users in production see the developer tools

## Environment

<pre><code>
Angular version: 9.1.12

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.16  
- Platform: Windows WSL  

Others:

</code></pre>

**Comment by Roseidon** [comment]
(I am asking here, hoping someone else using the Devtools has found a solution :))

**Comment by NetanelBasal** [comment]
I will check it out. In the meantime, you don't have to use the module. You can import the function and use it:

```ts
import { akitaDevtools } from '@datorama/akita';

if(dev) {
  akitaDevtools(options?);
}
```

**Comment by Roseidon** [comment]
@NetanelBasal I just tested it, it works perfectly! 👍
