### ISSUE TITLE
combineQueries should match combineLatest arguments

### ISSUE THREAD

**Issue by talohana** [datorama/akita#511]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`combineQueries` only accepts array, for example:
```typescript
combineQueries([ this.todosQuery.selectFirst(), this.todosQuery.selectLast() ])
```

## Expected behavior

`combineQueries` should accept the same arguments as `combineLatest` operator, for example:
```typescript
combineQueries(this.todosQuery.selectFirst(), this.todosQuery.selectLast())
```

## What is the motivation / use case for changing the behavior?

A cleaner and more obvious use without looking at the `combineQueries` operator signature.

## Environment

Akita ~5.0.0

**Comment by NetanelBasal** [comment]
The signature you mentioned is deprecated.
