### ISSUE TITLE
selectActive not working for MultiActiveState

### ISSUE THREAD

**Issue by Eralmidia** [datorama/akita#517]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Not sure if this is a bug, but I tried the MultiActiveState for the first time, and I'm a bit confused as to why the selectActive returns undefined when multiple entities are active.

I have created a MultiActiveState store:
![image](https://user-images.githubusercontent.com/12936286/91130223-9b72a780-e6ab-11ea-94c5-a63acc889c97.png)

Then, in a component I do the following test:
![image](https://user-images.githubusercontent.com/12936286/91129510-7467a600-e6aa-11ea-8a0b-c16f58938943.png)

When setting a single active entitiy, this works as expected, giving me a single entity for each console log:
![image](https://user-images.githubusercontent.com/12936286/91129631-a11bbd80-e6aa-11ea-8a49-a37a0ddfcaaf.png)

But if I increase to two active entities:
![image](https://user-images.githubusercontent.com/12936286/91129731-c7d9f400-e6aa-11ea-9094-fdd89a9a89e0.png)

## Expected behavior

selectActive should stream the active entities.

## Minimal reproduction of the problem with instructions

1. Create a MultiActiveStore
2. Subscribe to selectActive
3. Select multiple active entities

## Environment

<pre><code>
Angular version: 10.0

Browser:
- [ X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by NetanelBasal** [comment]
Can you reproduce it? https://stackblitz.com/edit/akita-issue?file=src%2Fapp%2Fauth%2Fstate%2Fauth.query.ts

**Comment by Eralmidia** [comment]
Thanks for the quick reply. I didn't provide a repro since the link in the issue description didn't seem to work:
![image](https://user-images.githubusercontent.com/12936286/91142107-8a786500-e6b0-11ea-865e-16c99be25b76.png)

Here's the repro: https://stackblitz.com/edit/akita-issue-bmkjn7?file=src%2Fapp%2Ftodos%2Fstate%2Ftodos.service.ts

The issue seems to happen when I pass an array of ids to setActive. Not sure if I'm handling the setActive in the service the correct way, but at least it does produce conflicting results for getActive and selectActive.

**Comment by NetanelBasal** [comment]
The docs mention to pass the initial value:

```ts
 super({
    active: []
  });
```

**Comment by Eralmidia** [comment]
Thanks a lot, Netaniel. Great work on Akita, really love it!
