### ISSUE TITLE
Remove element from paginated list in case of using akita server side pagination not working

### ISSUE THREAD

**Issue by fatehMohamed14** [datorama/akita#521]
i'm using a server side pagination and it works perfectly  as described here https://datorama.github.io/akita/docs/plugins/pagination/

     `ngOnInit() {
         this.pagination$ = this.paginatorRef.pageChanges.pipe(
           switchMap(( page ) => {
             const reqFn = () => this.contactsService.getPage({
               page,
               perPage: 10
             });

             return this.paginator.getPage(reqFn);
           })
         );
      }`

but i have a user case when i want o delete an element from the paginated list and using remove is not working

`contactStore.remove(contactID)` 

is not working, do you have an Idea of how to achieve this

**Comment by NetanelBasal** [comment]
You can't—this a server-side plugin. The server is a single source of truth. Imagine that you have server-side filters or sorting applied, the client can't calculate the data.
