### ISSUE TITLE
Strange behaviour when updating an entity created with a constructor

### ISSUE THREAD

**Issue by jingfee** [datorama/akita#522]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have a store entity which basically looks like:

    export class Object {
      [immerable] = true;

      public id: string;
      public property: string;
      public subObject: SubObject;

      constructor(id: string, prop: string) {
        this.id = id;
        this.property= prop;
        this.subObject= new SubjObject();
      }
    }

    export class SubObject {
      [immerable] = true;
    }

The store is configured with producerFn: produce from immer.

Issue is when I use store.add to add a new entity to the store I run into an issue. The entity is added by doing `store.add(new Object(id, property))`.
When I try to update for example 'property', instead of updating the with the value it inserts everything as an object to the id-property, like

    {
      id: {
        id: newValue,
        property: newValue,
        subObject: newValue,
      }
    }

I experience this no matter how I update the entity (I've tried the updateActive and update functions both with and without produce as producerFn)

I have managed to get it to update the entity correctly in two different ways:

1. Instead of using store.add(object) i use store.upsert(object.id, object) to add the new entity to the store.
2. Instead of using `const newObject = new Object(id, property)` to create the object I use 

       const newObject = {
         id: id,
         title: title,
         subObject: {}
       } as Object

Is this a bug with Akita or am I doing something obviously wrong? Any help is appreciated ❤️

**Comment by NetanelBasal** [comment]
You can't use immer with classes.

**Comment by NetanelBasal** [comment]
![image](https://user-images.githubusercontent.com/6745730/91822335-50730a00-ec40-11ea-829e-d0acbebc44d4.png)


https://datorama.github.io/akita/docs/additional/class

**Comment by jingfee** [comment]
> ![image](https://user-images.githubusercontent.com/6745730/91822335-50730a00-ec40-11ea-829e-d0acbebc44d4.png)
> 
> https://datorama.github.io/akita/docs/additional/class

Thanks, I had completely missed that page in the documentation.
