### ISSUE TITLE
Add a 'preSetEntities' method to Store

### ISSUE THREAD

**Issue by fsmiamoto** [datorama/akita#523]
## I'm submitting a...
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
```

## Current behavior
Currently we don't have any way to tap into the state after an call to `set` except on an item by item basis.

## Expected behavior
A method similar to `akitaPreUpdate` that would receive the previous and next state after a
call to `set`.

```ts
akitaPreSetEntities(prevState, nextState)
```

## What is the motivation / use case for changing the behavior?
This is something that could help in the following situation:

You receive some data from an API and use the `set` method on the store:
```ts
interface Item {
  category_id: number;
}
[...]
const items = await fetchFromApi();
this.store.set(items);
```
With the items stored, I would like to perform some computation to derive another data structure, for example:
```ts
interface SumByCategory {
 total: number
// possibly other data...
}
const  sum: {[category_id:number]: SumByCategory} = calculateSumOfItemsByCategory(items);
```
It would be convenient to have this data structure `sum` on the store and derive it only when we update the entities with something like `set`. 
The proposed method would then enrich the state with the derived structure, making it transparent to store consumers.

I'm quite new to Akita so let me know if the feature makes sense 🙂

**Comment by NetanelBasal** [comment]
You can use the `akitaPreAddEntity` hook.

**Comment by fsmiamoto** [comment]
By using the `akitaPreAddEntity`, in my opinion, it would feel a little bit weird accessing and updating the state for each item.
I would also need to 'reset' the computed structure explicitly before calling `set`.

My idea on the proposed method was to treat the `set` as an atomic operation and, with that, be able to enrich the state considering all the entities set.

**Comment by NetanelBasal** [comment]
I'd just override the store set method:

```ts
set(items) {
  super.set(calculateSumOfItemsByCategory(items))
}
```

**Comment by fsmiamoto** [comment]
Fair enough! I think that could work:
```ts
set(items){
  const sum = calculateSumOfItemsByCategory(items);
  super.set(items);
  super.update({sum});
}
```
