### ISSUE TITLE
PaginationPlugin does not update the store and the page data for entities that were already present in the store with outdated state  

### ISSUE THREAD

**Issue by lvoliveira** [datorama/akita#527]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Enter the view with the paginator with an outdated entity in the store. Call the clearCache. The page is loaded from the server with an updated entity state but it is not reflected on the page data returned by the paginator plugin. 

## Expected behavior

When call clearCache and the paginator request new data from the server, the updated data should be added to the store and returned by the plugin in the page data.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-1mfw2x

1. Click on Add outdated user
2. Navigate to Users 

Should list 

ID | Name
-- | --
1 | A
2 | B
3 | C

But it does not. Instead, it lists

ID | Name
-- | --
1 | Outdated User
2 | B
3 | C

## What is the motivation / use case for changing the behavior?

The behavior seems unexpected since the updated data is got from the server but it does not go to the page.

## Environment

<pre><code>
Angular version: ^7.0.1

Browser:
- [x ] Chrome (desktop) version 85
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.22.0  
- Platform:  Linux 

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
It will not work if you update the store manually. **The server is the single source of truth**. Imagine that there are some filters or sorting applied, you can't rely on the client data. You need to fetch the new data from the server.

**Comment by lvoliveira** [comment]
@NetanelBasal  In this case, the manual update of the store is just to simulate an outdated entity on the store (Imagine the entity being updated on the server in the meantime). When you navigate to the users the data, it is being fetched from the server but it does not get updated on the page. 

Digging deep in the code, I've noticed that when we call clearCache for the first time it is not actually cleared, this is causing the outdated entity to continue on the store when the paginator loads the data from the server. Later on, when the paginator gets the data from the server, it tries to do a `store.add` on the fetched entities, but the `add` method does not update an entity that is already in the store, leaving the outdated state of that entity in the store. Finally, the plugin produces the page based on the data present in the store, not the actually fetched data.

**Comment by NetanelBasal** [comment]
Do you want to create a PR that fixed this?

**Comment by lvoliveira** [comment]
> Do you want to create a PR that fixed this?

I can try
