### ISSUE TITLE
Remove clear function from persistState

### ISSUE THREAD

**Issue by pepma** [datorama/akita#532]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

clear function is exposed when creating persistState

## Expected behavior
Remove clear function, 

the clear function calls the clear function of the defined storage

## Environment

<pre><code>
Angular version: 9.1.7

**Comment by NetanelBasal** [comment]
What do you mean? I'm not sure I understand the request.

**Comment by pepma** [comment]
Hi,
I will try to explain better

in [persistState.ts](https://github.com/datorama/akita/blob/master/libs/akita/src/lib/persistState.ts) file:
```
export interface PersistState {
  destroy(): void;
  clear(): void;
  clearStore(storeName?: string): void;
}
```

```
...
clear() {
      storage.clear();
    },
...
```


clear function should not be in PersistState,
It is not the responsibility of the state to remove all keys from the storage

**Comment by NetanelBasal** [comment]
Agree. It's a legacy code that was replaced by `clearStore`. You can open a PR that marked it as deprecated, and we'll remove it in the next major release.
