### ISSUE TITLE
Link to blog return 404 error

### ISSUE THREAD

**Issue by intsashka** [datorama/akita#534]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Link to posts in block do not work.

## Expected behavior

Link to posts in block must be work or deleted.

## Minimal reproduction of the problem with instructions

Steps:
+ Navigate to https://github.com/datorama/akita/
+ Click link "posts" in "Read the blog posts".

Demo:

![bug](https://user-images.githubusercontent.com/13872357/94676094-fea7c780-0344-11eb-9436-dbee6044a2a2.gif)

## What is the motivation / use case for changing the behavior?

Bug is wrong.

## Environment

<pre><code>
Angular version: none

Browser:
- [x] Chrome (desktop) version 85.0.4183.102 (official build), (64 bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by NetanelBasal** [comment]
It doesn't exist anymore. Thanks.
