### ISSUE TITLE
Support for Dynamic Store State (Model with changing values)

### ISSUE THREAD

**Issue by 010pixel** [datorama/akita#536]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

Does Akita support Dynamic Store State (Model with changing values)?
e.g. let's say my `User` model has 5 keys. And in a particular component we require some extra keys. How can we change the keys in model?

**Comment by NetanelBasal** [comment]
You can update the user object.

**Comment by hakimio** [comment]
> e.g. let's say my `User` model has 5 keys. And in a particular component we require some extra keys. How can we change the keys in model?

You can just have some optional user properties. I don't see the problem you are trying to solve here.

**Comment by NetanelBasal** [comment]
I'm closing the issue. Let me know if you have any further questions.
