### ISSUE TITLE
Is update() performing harmful deep copies?

### ISSUE THREAD

**Issue by LifeIsStrange** [datorama/akita#538]
[x] Performance issue
[x] API ergonomics

So if I have a store that has an array of Users.
```Typescript
updateNameOfSecondUser(newName: string) {
this.sessionStore.update(state => ({
      state[1] = newName,
      users: state
 }));
```
Well I'm not even that this syntax is valid, but is it deep copying the array instead of reusing a reference of the anterior state ?
If so, Ibelieve this would mean that Akita would be much slower than conventional stores such as mobx (which would be ironic because they don't even bother to use rxjs).

In Mobx or Vuex, you could do something like
```Typescript
updateNameOfSecondUser(newName: string) {
this.store.users[1] = newName
}
```
Which is 1) ergonomically much more concise and expressive (you can use standard collections APIs such as filter/map, etc)
and 2) does not do any deep copy as it is not needed.

**Comment by NetanelBasal** [comment]
You need to return a new immutable object. You can use [immer](https://datorama.github.io/akita/docs/immer/) with Akita if you want.
