### ISSUE TITLE
Cannot use to create libraries of components since akita has react as a dependency rather than as a peer dependency + dev dependency

### ISSUE THREAD

**Issue by viveceo** [datorama/akita#540]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In order to use hooks in an application, you can only have one instance of React.

This means all external libraries must export react as a peer dependency rather than as a dependency

## Expected behavior

React as peer dependency

## Minimal reproduction of the problem with instructions

Create a library using rollup/webpack

## What is the motivation / use case for changing the behavior?

Create libraries of components connected to the same common state through akita

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Where do you see React? https://github.com/datorama/akita/blob/master/libs/akita/package.json

**Comment by viveceo** [comment]
main package.json

**Comment by viveceo** [comment]
maybe i misunderstand, you are using custom builder to remove all dependencies defined by main package.json in base folder?

**Comment by viveceo** [comment]
https://github.com/datorama/akita/blob/master/package.json

**Comment by NetanelBasal** [comment]
This isn't the library. You're looking at the repo's package.json
