### ISSUE TITLE
Store mutations that triggered as a reaction of an akita select() are ignored by akita

### ISSUE THREAD

**Issue by Michael-Dawkins** [datorama/akita#541]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

- Trigger a mutation in the store
- Akita detects it and fires the select() calls associated to the store
- Another component/service is subscribed to this select() and reacts by doing another mutation in a store
- Akita does not trigger the observables for the select() of this subsequent store mutation

## Expected behavior
I expect any store mutation to trigger the associated queries select calls.

## Minimal reproduction of the problem with instructions

I reproduce the issue on a minimal stackblitz demo, it shoes that the first round of mutation runs fine, but the chained mutation is "ignored" by akita, and the second value change is not displayed.
[stackblitz example](https://stackblitz.com/edit/akita-synchronous-mutations-issue?file=src/app/todos/test/test.component.ts  
)

## What is the motivation / use case for changing the behavior?
As our application grows in complexities, we have more modules starting to interact with each other.
We try to make everything data store driven, even things like reacting to a finished saved, some piece of data that finished loaded.
So it becomes common to have store mutations being triggered as a consequence of an akita query firing in an observable.

At the moment, the only solution I have found is to wrap select() calls in a pipe(observeOn(asyncScheduler)) to force the next mutation to begin in a new callstack.

## Environment

Angular version: 9

Browser:
- [ x ] Chrome (desktop) version 85
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by hakimio** [comment]
To be honest, mutating state inside a query to me seems like a bad application design.
In this case instead of using an extra state variable and updating state inside of query listener, you could just have a derived query parameter. Sth like the following:
```ts
anotherField$ = this.oneField$.pipe(
    filter(val => val === 'FIRST VALUE CHANGED')
  );
```
[stackblitz](https://stackblitz.com/edit/akita-synchronous-mutations-issue-bv4eza?file=src/app/todos/test/test.component.ts)

**Comment by Michael-Dawkins** [comment]
I have given a good thought about this a figured out that what I am trying to accomplish is pretty much an antipattern, as it causes other issues like chain reactions upon loading a store state with redux dev tools time travelling.
Because of this, I have come up with a few guidelines for my team to help avoid these issues altogether :

- Only mutate the store when we are at the conclusion of some user initiated action (we write final and stable state)
- Created a event layer with simple rxjs subjects to represent user actions, and cable observable chains from there as much as possible, instead of cabling them from queries watching the stores.

That way we end up with all mutations being the final state of some user action, meaning it is safe to use redux dev tools to load them back in a debugging scenario for example. It also makes the chains of event clearer, to never have multiple cycle of reactions going through the store, back from the queries and once again into the stores.
