### ISSUE TITLE
ng add can't find app.module.ts

### ISSUE THREAD

**Issue by Waterstraal** [datorama/akita#543]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Installing Akita with ng add throws an error about not being able to find app.module.ts. 
It seems to be looking for `/src/@app/app.module.ts`. The file is located in `/src/app/app.module.ts`

Note: I have a TypeScript path alias set up for @app:  `"@app/*": ["src/app/*"]`

## Expected behavior

It should not throw an error and update `AppModule`

## Minimal reproduction of the problem with instructions

- I run `ng add @datorama/akita` (doesn't matter which additional packages I select to install)
- It shows the following error: `Could not find file for path: /src/@app/app.module.ts`

Output:
```
ng add @datorama/akita
Skipping installation: Package already installed
? � Set up Akita's devtools? Yes
? � Set up Akita's router store? No
? ☄️ Set up Akita's Http Entity Service? No
? � Set up Akita's Firebase Entity Service? No
    ✅️ Added "@datorama/akita" into dependencies
    ✅️ Added "@datorama/akita-ngdevtools" into devDependencies
    � Installing packages...
Could not find file for path: /src/@app/app.module.ts
```

## Environment
<pre><code>Angular: 10.1.3
Angular CLI: 10.1.3
Node: 12.4.0
OS: win32 x64
</code></pre>

tsconfig:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "strict": true,
    "strictPropertyInitialization": false,
    "baseUrl": "./",
    "paths": {
      "@app/*": ["src/app/*"]
    },
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2020",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": ["node_modules/@types", "globals.d.ts"],
    "lib": ["es2018", "dom"]
  },
  "exclude": ["node_modules/**/*", "dist/**/*", "node/**/*", "coverage/**/*", "out-tsc/**/*"]
}
```

**Comment by NetanelBasal** [comment]
It's not related to Akita. We're using the getAppModulePath from `@schematics/angular/utility/ng-ast-utils`. You should open the issue in their repo.
