### ISSUE TITLE
App not working on angular 10 and akita 5.2.5

### ISSUE THREAD

**Issue by silverstory** [datorama/akita#546]
My akita app is not working anymore when upgraded to angular version 10
and also upgraded akita to
@datorama/akita version 5.2.5

Help me! Now!!!

App error is complaining about line 4 and line 8 in this file:
https://github.com/silverstory/akita-socketio/blob/master/src/app/livefeed-list.service.ts

Link to app
https://github.com/silverstory/akita-socketio

**Comment by NetanelBasal** [comment]
https://github.com/datorama/akita/blob/master/BREAKING_CHANGES.md#500

**Comment by silverstory** [comment]
> https://github.com/datorama/akita/blob/master/BREAKING_CHANGES.md#500

Good answer.

I'll try this at home.
