### ISSUE TITLE
Question - How to Access Currently Loaded Store From Service

### ISSUE THREAD

**Issue by ronyf** [datorama/akita#550]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe: Question
</code></pre>

## Question

I have a store per route and I'd like to access the "currently active" store from a service which is accessed from an external component.

How can I fetch said store without knowing its name?

**Comment by NetanelBasal** [comment]
Show some code, please.

**Comment by ronyf** [comment]
To query for the "active" store, I thought to either
```
Object.keys($$stores).filter(storeKey => $$stores[storeKey].store.observers.length > 0)
```
and find the store with observers > 0
or to add an `isActive` to the store which is `true` when I reach the route's `ngOnInit` and `false` when I reach `ngOnDestroy`
and query it using

```
Object.keys($$stores).filter(storeKey => $$stores[storeKey].storeValue.isActive)
```

This way, I'll get the key of the "active" store and then access it.
@NetanelBasal wdyt?

**Comment by NetanelBasal** [comment]
My question was more about the use case. Can you explain it, please?

**Comment by ronyf** [comment]
Sure. we got a hybrid angular application. 
We want the old angular js code to update something in the new angular 2+ store which is currently used.
I want to do it using a service that's downgraded.

**Comment by NetanelBasal** [comment]
We expose a `getStore` method.

**Comment by ronyf** [comment]
`getStore` requires store's class. so I'd still need to go over the global store registry to find the "active" store, right?

**Comment by NetanelBasal** [comment]
I'm not sure I understand the use-case. What do u mean "active" store?

**Comment by ronyf** [comment]
Imagine there's a header that's in angularjs and an interchangeable route in angular 2+.

![image](https://user-images.githubusercontent.com/29537945/98916934-6d477b80-24d4-11eb-8cb9-185624cd8b40.png)

The route can be any of many routes, each of them has its own store.

I want the header to access the store and add something to it.

The header doesn't know which route it currently active and its store.

So I need a way to get the "active" route's store from the header.

I suggested a crude way to access it, and I was wondering if there's a more elegant way.

**Comment by ronyf** [comment]
@NetanelBasal any suggestions? 🙏

**Comment by chenofek** [comment]
I have a similar case   thanks

**Comment by NetanelBasal** [comment]
There is no built-in way to do it. Your code seems OK.
