### ISSUE TITLE
Entity Store: update() by entityId not working as expected

### ISSUE THREAD

**Issue by mmelyp** [datorama/akita#555]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The following Entity Store, is attached to a [local component](https://datorama.github.io/akita/docs/angular/local-state) named "EditableListComponent".

**editable-list-item.store.ts**
```
export interface EditableListItemsState extends EntityState<EditableListItem> {
}

export class EditableListItemStore extends EntityStore<EditableListItemsState> {
	constructor() {
		super({}, {name: `EditableListItemStore-${guid()}`});
	}
}
```

**editable-list-item.query.ts**
```
@Injectable()
export class EditableListItemQuery extends QueryEntity<EditableListItemsState> {
	constructor(protected store: EditableListItemStore) {
		super(store);
	}
}
```

**editable-list-item.ts**
```
export class EditableListItem {
	id: string;
	label: string;
	selected: boolean;
	value: string;

	constructor(
		id: string,
		label: string,
		value: string,
		selected: boolean,
	) {
		this.id = id;
		this.label = label;
		this.value = value;
		this.selected = selected;
	}
}
```

In the EditableListComponent, i'm trying to [update an entity in the store by entityId](https://datorama.github.io/akita/docs/entities/entity-store#update) like this:

`this.editableListItemStore.update(selectedItem.id,` {selected: `event.target.checked});`

Unfortunately, the entity is updated in the store in a strange way.
The entity with the id "entityId" looks like this now:

![Screenshot from 2020-11-16 18-14-48](https://user-images.githubusercontent.com/9610041/99285795-4d97b680-2838-11eb-937c-874bbf025863.png)

It is also happening in Entity Stores which are not related to local components.

## Expected behavior

As far as i understood in [here](https://datorama.github.io/akita/docs/entities/entity-store#update). The "selected"
property should had changed to "true" preserving the rest of the entity state.

**Comment by NetanelBasal** [comment]
You're using a `class` as your model. Read this please: 
https://datorama.github.io/akita/docs/additional/class

**Comment by mmelyp** [comment]
Thank you Netanel, i haven't read this section of the documentation. Great library.
