### ISSUE TITLE
setValueByString.ts: Store's setValue() sets wrong values.

### ISSUE THREAD

**Issue by konczykl** [datorama/akita#557]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other...
</code></pre>

## Current behavior

Restoring array state using StateHistoryPlugin makes it an object instead of an array.
For instance: if I have string array in state ['1'] then change it to ['1', '2'] and restore using undo() makes it { 0: '1', 1: '2' }.
Faulty code:
https://github.com/datorama/akita/blob/master/libs/akita/src/lib/setValueByString.ts#L24

## Expected behavior

Restore previous state without changing its form.

## Minimal reproduction of the problem with instructions

Reproduced issue on stackblitz:
https://stackblitz.com/edit/angular-ivy-nc1tcs?file=src%2Fapp%2Fapp.component.ts

## Environment

<pre><code>
Angular version: 10

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Can you submit a PR with the fix, please?
