### ISSUE TITLE
filterNil does not filter empty arrays or objects

### ISSUE THREAD

**Issue by IAMtheIAM** [datorama/akita#558]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`filterNil` works for truly `undefined` or `null` values emitted by an observable, but does not filter empty arrays or objects.

## Expected behavior
`filterNil` should filter empty arrays and objects also.

The logic is because when calling `reset()` on a store where the initial value is an empty array or object, it immediately emits that empty array or object. That really doesn't need to be emitted, or at least should be filtered by `filterNil`

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## Environment

<pre><code>
Angular version: 9.1.9

Browser:
- [x] Chrome (desktop) version 87.0.4280.66 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 82.0.3 
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by danzrou** [comment]
I think that this operator as it's name should have a single responsibility and filter nullish values. You can however create an operator of your own

**Comment by NetanelBasal** [comment]
What @danzrou said :)
