### ISSUE TITLE
filterNil does not prevent null types

### ISSUE THREAD

**Issue by rosostolato** [datorama/akita#559]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`filterNil` is not removing null or undefined from the generic type:

![image](https://user-images.githubusercontent.com/27731641/99887394-b6a97080-2c22-11eb-915d-39373238bbb4.png)

## Expected behavior
In the example before, `a` and `b` should not be nullable and typescript should not throw error when they are accessed.

## Solution
Change filterNil to the following code:

```ts
import { Observable } from 'rxjs'
import { filter } from 'rxjs/operators'

/**
 * @example
 *
 * query.selectEntity(2).pipe(filterNil)
 */
export const filterNil = <T>(source: Observable<T | undefined | null>) =>
  source.pipe(
    filter(
      <P>(value?: P | null): value is P =>
        value !== null && typeof value !== 'undefined'
    )
  )
```

## Result:
Bug solved:

![image](https://user-images.githubusercontent.com/27731641/99887444-43542e80-2c23-11eb-8cd4-c867d983b331.png)

I'm creating this issue just to be sure if I'm not doing anything wrong. If it's really a bug, I can create the PR.

**Comment by NetanelBasal** [comment]
I'm not sure why your approach is different from https://github.com/datorama/akita/blob/master/libs/akita/src/lib/filterNil.ts#L10

**Comment by rosostolato** [comment]
It never worked for me in all my different projects. Than I searched on Google how to filter and make ts know that your data is not nullable anymore, so I found that code. I replaced the filterNil function and it worked and I wanted to share here

**Comment by NetanelBasal** [comment]
Can you reproduce it on stackblitz, please?

**Comment by rosostolato** [comment]
I tried to reproduce it on a new project and it worked just fine... there must be some inconsistency in the projects I have, I apologize.

I tried this example and it worked:
```ts
export interface MyData {
  id: string;
  name: string;
}

export class AppComponent {
  readonly nullableData$ = new BehaviorSubject<MyData | null>(null);

  readonly filtered$ = this.nullableData$.pipe(
    filterNil,
    map(data => data.id)
  );
}
```
