### ISSUE TITLE
[Question] Concatenate extra URL segments to the base URL in the NgEntityService

### ISSUE THREAD

**Issue by juanmesa2097** [datorama/akita#562]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Problem

I'm currently using the NgEntityService and I need to consume an API that have endpoints like this:

**PUT** `example.com/api/v1/usuarios/1/detalles`
**PATCH** `example.com/api/v1/usuarios/1/status`
**GET** `example.com/api/v1/municipios/departamento/1`

## Example

1. Set the base URL

app.module

```ts
providers: [
  ...
  {
      provide: NG_ENTITY_SERVICE_CONFIG,
      useValue: {
        baseUrl: environment.apiUrl,
      },
  }
]
```

2. Add resource name

users.service

```ts
@NgEntityServiceConfig({
  resourceName: 'usuarios',
})
@Injectable({ providedIn: 'root' })
export class UsersService extends NgEntityService<UsersState> {
  constructor(protected store: UsersStore) {
    super(store);
  }
}
```

3. Call service

account.page.ts

```ts
updateUserDetails(): void {
  this.usersService
    .put<User>({      
      extras: ['detalles'],      // <---   Is there a way to do this?
      mapResponseFn: (res) => res.data as User,
    })
    .subscribe();
}
```

#### WORKAROUND

```ts
updateUserDetails(): void {
  this.usersService
    .put<User>({      
      url: `${environment.apiUrl}/usuarios/detalles`, 
      mapResponseFn: (res) => res.data as User,
    })
    .subscribe();
}
```

## Question

How can I concatenate extra endpoints to the API resource?

## Environment

```
Angular 11.0.0
```

P.D. I know I could use query parameters for some of the examples but I don't have control over the API.

Thanks in advance!

**Comment by NetanelBasal** [comment]
There is no way to do it. You're welcome to submit a PR.

**Comment by juanmesa2097** [comment]
> There is no way to do it. You're welcome to submit a PR.

Ok, thank you. I'll take some time this weekend to work on it!
