### ISSUE TITLE
Missing exports between akita-ng-fire and latest akita

### ISSUE THREAD

**Issue by mrvdot** [datorama/akita#563]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When a new angular app has been freshly installed both with akita and akita-ng-fire it fails to compile. Running `ng serve` results in the following errors:

```
Error: ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 53:36-53
"export 'EntityStoreAction' was not found in '@datorama/akita'

Error: ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 57:36-53
"export 'EntityStoreAction' was not found in '@datorama/akita'

Error: ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 68:40-57
"export 'EntityStoreAction' was not found in '@datorama/akita'

Error: ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 38:30-41
"export 'StoreAction' was not found in '@datorama/akita'

Error: ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 48:30-41
"export 'StoreAction' was not found in '@datorama/akita'

Error: ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 43:4-18
"export 'getStoreByName' was not found in '@datorama/akita'

Error: ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 53:4-24
"export 'runEntityStoreAction' was not found in '@datorama/akita'

Error: ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 57:4-24
"export 'runEntityStoreAction' was not found in '@datorama/akita'

Error: ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 68:8-28
"export 'runEntityStoreAction' was not found in '@datorama/akita'
```

## Expected behavior

Ideally latest versions of akita-ng-fire and akita would work together smoothly.

## Minimal reproduction of the problem with instructions

With a fresh angular install, use `ng add @datorama/akita` and select yes to everything. Due to #547 I then manually updated akita-ng-fire to the latest version (both 3.1.6 and 4.0.0, the same problem persists), so here are the relevant package versions in my package.json:

```
"@datorama/akita": "^4.22.0",
"@datorama/akita-ng-entity-service": "^1.0.0",
"akita-ng-fire": "^4.0.0",
```

## What is the motivation / use case for changing the behavior?

Because no errors is better than errors.

## Environment

<pre><code>
Angular version: 11.0.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v13.9.0
- Platform:  Linux

Others:

</code></pre>

**Comment by mrvdot** [comment]
I realize this may actually belong in the https://github.com/dappsnation/akita-ng-fire/ repo, and if so I am happy to move it over, however I saw a similar issue of #472 and thought perhaps this was similar.

**Comment by NetanelBasal** [comment]
Open an issue in akita-ng-fire, please.

**Comment by mrvdot** [comment]
For anyone else who comes across this, it's simply because  `ng add @datorama/akita` installs old versions across the board. Upgrading to @datorama/akita@^5.2.6 (and updating the various submodules as well) solved the issue.
