### ISSUE TITLE
[Angular] Incorrect unit test example 

### ISSUE THREAD

**Issue by Wykks** [datorama/akita#568]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The test https://datorama.github.io/akita/docs/angular/tests#mocking-the-query is incorrect given the implementation of the component.
```
export class TodosPageComponent implements OnInit {
  todos$ = this.todosQuery.selectAll();
  selectFilter$ = this.todosQuery.selectFilter$; // <== We assign ref in the constructor

  constructor(
    private todosQuery: TodosQuery,
    private todosService: TodosService
  ) {}

  ngOnInit() {
    this.todosService.get().subscribe();
  }
}
```
```
  it('should display the initial filter', () => {
    todosQuery.selectFilter$ = of('active'); // We change the ref after the constructor
    fixture.detectChanges();
    const filter = fixture.debugElement.query(By.css('.filter'));
    expect(filter.nativeElement.innerText).toEqual('active');
  });
```
This doesn't works, since we change the ref of `todosQuery.selectFilter$` _after_  the ref is assigned in the component.

## Expected behavior

Not sure about the best pratice here. I like to do that as well : 
`selectFilter$ = this.todosQuery.selectFilter$;`
So to make it work, we can mock the `selectFilter$` before the `createComponent`, but it's quite tedious to write without ng-mocks/spectator.

## Environment

<pre><code>
Angular version: 10.2.0

**Comment by NetanelBasal** [comment]
You're right. I'd move the initialization to ngOnInit.

**Comment by NetanelBasal** [comment]
It'll be great if you can update the docs and create a PR.
