### ISSUE TITLE
persistState() is not executed when instantiated with useFactory()

### ISSUE THREAD

**Issue by tegain** [datorama/akita#570]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When instantiating persistState() with `useValue` as stated in documentation, it works correctly, and state is indeed persisted in localStorage. However, when persistState() is instantiated with `useFactory`, it doesn't work, state is not persisted in localStorage:

## Expected behavior

State should be persisted even when using `useFactory()`, even when using basic localstorage.

## Minimal reproduction of the problem with instructions
This works as expected:

```
{
    provide: 'persistStorage',
    useValue: persistState({ key: 'stores' })
}
```

This does not work as it should:

```
{
    provide: 'persistStorage',
    useFactory: () => persistState({ key: 'stores' })
}
```

Here is a minimal reproduction (see file `stores.module.ts`): https://stackblitz.com/edit/angular-ivy-3absq6?file=src%2Fapp%2Fstores%2Fstores.module.ts

## What is the motivation / use case for changing the behavior?

I need to use `useFactory` to inject a specific storage (Angular/Ionic async storage), I would expect the following to work correctly:

```
{
    provide: 'persistStorage',
    usefactory: (storage: MyStorageService) => persistState({ key: 'stores', storage }),
    deps: [MyStorageService]
}
```

## Environment

<pre><code>
Angular version: 10.0.14 / Ionic 5.29.0

The issue still exists on latest Angular version (see Stakblitz reproduction project)

Browser:
- [x] Chrome (desktop) version 86
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.14.0  
- Platform:  Windows 10 

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
You need to inject it somewhere so that Angular will instantiate it. Your first approach works because you're calling the function.
