### ISSUE TITLE
Create effects package for Akita

### ISSUE THREAD

**Issue by NetanelBasal** [datorama/akita#571]
Developers that comes from ngrx sometimes want similar functionality as effects in ngrx. I think it'll be nice to develop a package that provides this functionality if someone wants to use it.

Here's what I imagine: ( I'm open to any other suggestions )

```ts
import { Actions } from '@datorama/akita-effects';

export class TodosComponent {
  todos$ = this.query.selectAll();

  constructor(private actions: Actions, private query: TodosQuery) {}

  ngOnInit() {
    this.actions.dispatch(fetchTodos());
  }
}

import { Actions, createEffect } from '@datorama/akita-effects';

class TodosEffects {
  constructor(private actions$: Actions, 
              private service: TodosService) {}

  fetchTodos$ = createEffect(() =>
    this.actions$.pipe(
      ofType(fetchTodos),
      switchMap(() => this.service.fetchTodos())
    )
  );
}

class TodosService {
  fetchTodos() {
    return this.http.get("todos").pipe(
      tap(todos => this.store.set(todos))
    );
  }
}
```

You can save some work and use this package for the actions:

https://github.com/cartant/ts-action/blob/master/packages/ts-action-operators/README.md
https://github.com/cartant/ts-action/blob/master/packages/ts-action/README.md

**Comment by hakimio** [comment]
How is `this.actions.dispatch(fetchTodos())` better than just calling `this.todosService.fetchTodos()` directly? Can you explain what is the problem `effects` solve here? Seems like useless boilerplate to me.

Also, where do you define your `fetchTodos()`/`fetchTodos` in this example? And should it be ` this.actions.dispatch(fetchTodos())` or ` this.actions.dispatch(fetchTodos);`?

**Comment by NetanelBasal** [comment]
I didn't say that it's better :)

Some of the developers coming from ngrx prefer this pattern. You define the `actions` in the `actions` file. 

Imagine a case where you want to do some task when the user logs out. You listen to `authQuery.isLoggedIn$`, but where is the best place to put the subscription? That's where an effect can be useful.

**Comment by hakimio** [comment]
> Imagine a case where you want to do some task when the user logs out. You listen to `authQuery.isLoggedIn$`, but where is the best place to put the subscription? That's where an effect can be useful.

Depends on the task. If it's UI update task, most likely in the UI component, if it's some resource clean-up task, than in the service responsible for managing those resources.

Can you illustrate with some code, how actions are helpful in this case?

**Comment by NetanelBasal** [comment]
I meant a task that doesn't relate to a specific component. For example, a global notifications store that's responsible for showing notifications.

**Comment by hakimio** [comment]
Root component?
```ts
export class AppComponent {

    constructor(
        private notificationService: EntityNotificationService
    ) {
        this.notificationService.listenToEntityChanges();
    }

}
```
What's the better way to do this with actions?

**Comment by NetanelBasal** [comment]
Again, I'm not saying that it's better. It's a matter of style.

**Comment by yackinn** [comment]
@NetanelBasal 

https://github.com/yackinn/akita/blob/master/effects.md

I implemented a solution.
It surely adds a little complexity when using effects although it's optional.

It's a working draft that can be compiled and used.
The Angular update and compilation settings can be reverted.

Please provide some feedback.

**Comment by NetanelBasal** [comment]
@yackinn thanks. Here are my notes:

- I'm not sure why we need the `ActionClass`. It can be a simple constant like in ngrx:

```ts
export const LOAD_NAVIGATION_SUCCESS = createAction("Load Navigation Success", props<{ mainNavigation: MainNavigation }>())
```

- I prefer to avoid decorators and use a function like `createEffect()`.
- I think we can do it without touching the codebase. 

Here is the modified implementation: 

```ts
@NgModule({
  imports: [
      CommonModule,
      AkitaNgEffectModule.forRoot([
        NavigationEffects
      ])
  ],
})
export class CoreDataModule {}



// navigation.actions.ts
export const loadNavigationSuccess = createAction("Load Navigation Success", props<{ mainNavigation: MainNavigation }>())


// navigation.effects.ts
@Injectable({ providedIn: 'root' })
export class NavigationEffects {

  constructor(
    private actions$: Actions,
    private navigationService: NavigationService
  ) {
  }

  loadNavigationSuccess$ = createEffect(() => this.actions$.pipe(
    ofType(loadNavigationSuccess),
    tap(({ mainNavigation }) => {
      this.navigationService.updateNavigationTree(mainNavigation);
    }),
  ));
}


// navigation.service.ts
class NavigationService {
  updateNavigationTree() {
    // update store, HTTP, etc
  }
}


// app.component.ts

export class AppComponent {

  constructor(private actions: Actions) {}

  ngOnInit() {
    this.actions.dispatch(loadNavigationSuccess());
  }
}
```


Where the `Actions` are simply a wrapper for a `Subject`.

**Comment by yackinn** [comment]
Thank you.
True. Let me simplify it.

**Comment by yackinn** [comment]
Is this correct?

```ts
export const updateNavigation = createAction("Update Navigation", props<{ routes: Routes }>())
```

```ts
export class NavigationStore {

  constructor(private actions: Actions) {}

  updateNavigation(routes: Routes) {
	this.update(state => ({ routes, ...state }))
    this.actions.dispatch(updateNavigation({routes}));
  }
}
```

**Comment by NetanelBasal** [comment]
Actions will be dispatched from components.

**Comment by yackinn** [comment]
Sure.
That's much more like ngrx.
Perfectly fine for me.

https://github.com/yackinn/akita/blob/feat/effects/libs/akita/src/lib/plugins/effect/effects.md

The api is much simpler now. That's a plus.
It's still using decorators and it's on Angular 11.

Shouldn't we migrate the entire monorepo?

Please provide a feedback.

**Comment by NetanelBasal** [comment]
> Shouldn't we update the entire monorepo?

What do u mean?

LGTM. 

- I still want to provide the option to use a `createEffect` function, and we should support `forFeature`.
- We don't need to copy the code of the actions library. We should reference it directly in the effects package. 
.

**Comment by NetanelBasal** [comment]
And it should be a library in the libs folder - akita-effects.

**Comment by yackinn** [comment]
I mean updating from Angular 8 to Angular 11.

I copied the parts that we needed to strip out the option to use payload() instead of props().
Do you want to provide both options?

**Comment by NetanelBasal** [comment]
Yes, we don't need to maintain this code. 

I'll update the project to Nx 11 in the next few weeks.

**Comment by yackinn** [comment]
Sure.

**Comment by NetanelBasal** [comment]
You can finish it, add the missing parts, specs, and docs.

**Comment by NetanelBasal** [comment]
Great work!

**Comment by yackinn** [comment]
Thanks. Will do.

**Comment by yackinn** [comment]
@NetanelBasal Should all effects be root scoped and singletons?

**Comment by NetanelBasal** [comment]
We can start with this.

**Comment by yackinn** [comment]
I read an article of yours.
I wanted to leverage this.

Isn't that depreceted due to AOT?
Did you find a way to use ngOnDestroy without explicitly setting it up inside the class?


export function AutoUnsubscribe( blackList = [] ) {

  return function ( constructor ) {
    const original = constructor.prototype.ngOnDestroy;

    constructor.prototype.ngOnDestroy = function () {
      for ( let prop in this ) {
        const property = this[ prop ];
        if ( !blackList.includes(prop) ) {
          if ( property && ( typeof property.unsubscribe === "function" ) ) {
            property.unsubscribe();
          }
        }
      }
      original && typeof original === 'function' && original.apply(this, arguments);
    };
  }

}
