### ISSUE TITLE
[Docs] query.selectActive() does not implement the Observable properly

### ISSUE THREAD

**Issue by IAMtheIAM** [datorama/akita#572]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
this.userQuery.selectActive().subscribe(activeUser => { });
```
Results in `TS2554: Expected 2-3 arguments, but got 1.  Observable.d.ts(51, 39): An argument for 'error' was not provided.`

If I case it to an observable, it works as expected:
```
(this.userQuery.selectActive() as Observable<UserModel>).subscribe(activeUser => {  });
```
## Expected behavior

I should be able to subscribe to `selectActive()` without type casting.

## Minimal reproduction of the problem with instructions

See Above code, in IDE.

## Environment

<pre><code>
Angular version: 9.1.9
Akita version: 5.2.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] typescript version 3.8.3

For Tooling issues:
- Node version: 12.18.1 
- Npm version: 6.14.5
- Platform: Windows 

Others:

IntelliJ IDE
</code></pre>

**Comment by IAMtheIAM** [comment]
Actually, nevermind. I see that by implementing `ActiveState`, the type error goes away.

export interface UserState extends EntityState<UserModel>, ActiveState {}
The [docs ](https://datorama.github.io/akita/docs/entities/active/#selectactive)could more explicitly make a call out to that being necessary.

**Comment by NetanelBasal** [comment]
It is in the first example

**Comment by IAMtheIAM** [comment]
Yeah I see it in the example, but there is no explanation anywhere of the fact that it is necessary or what it does. So I just suggested amending the docs with a simple explanation. Given the fact that this comment (https://github.com/datorama/akita/issues/184#issuecomment-474678716) has 7 reactions, many people are experiencing the same issue and did not know it was necessary.

**Comment by NetanelBasal** [comment]
I'll add it.
