### ISSUE TITLE
Issues with combineQueries | Alternative approach for Queries

### ISSUE THREAD

**Issue by Wykks** [datorama/akita#573]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The way `combineQueries` can be problematic when you combine query and listen to them directly.

Let's say we have a component directly using `selectLoading()`
And somewhere else, a component using a query like this : `combineQueries([this.query.selectLoading(), this.query.myData$])`

Because `combineQueries` wait one tick, then, for one tick the first component update and can cause a layout shifting issue, or flickering issue.

To sum it up, everytime you use a query used elsewhere inside a `combineQueries`, you're going to have some (minor) issues.

## Expected behavior

Here's some solutions to avoid this issue : 

- Use combineLatest  |  Welp, that works but defeat the point of `combineQuery` , so not good in heavy apps.
- Add `.pipe(auditTime(0))` to the component using `selectLoading()`  | Not great because the component should be aware of this, also doesn't works well when we have nested `combineQueries`
- Use `zip` instead of `combineQueries`  |  Only works when the queries changes at the same time

Or a completly different approach : 

Using reselect, we can create selectors like this : 

```
// my-selectors.ts
export const myDataSelector = (state: MyState) =>
  state.data;

export const isLoadingSelector = (state: MyState & { loading: boolean }) =>
  state.loading;

@Injectable({ providedIn: 'root' })
export class MyQuery extends Query<MyState> {
  constructor(protected readonly store: MyStore) {
    super(store);
  }
}

// my.component.ts
import { createStructuredSelector } from 'reselect';

@Component({
...
})
export class MyComponent  {
data$ = this.myQuery.select(createStructuredSelector({
   data: myDataSelector ,
   isLoading: isLoadingSelector
})).pipe(
   map(({isLoading, data}) => isLoading ? 'Loading...' : data)
)
...

// my.component.html
<ng-container *ngIf="data$ | async as data">
{{ data }}
</ng-container>
}
```
(Just an example, we can just put the ternary in a createSelector too here...)

This way we have : 
✔️ Just 1 event per change in vm$
✔️ No desync between direct select to isLoading and the combination of loading and data
✔️ (Bonus) Easier unit testing for selectors (pure functions, without rxjs)
✔️ (Bonus) Better selector compostion and re-calculation performance out of the box (no need to deal with distinctUntilChanged for example)

(Tested, it works great)

What do you think ?
`createSelector` could be integrated in Akita, with some helper like `selectLoading`

## Environment

<pre><code>
Angular version: 10.1.x
Akita version: 5.2.x

**Comment by NetanelBasal** [comment]
Reselect can be used with Akita if you really want or need it. What is your suggestion?

**Comment by Wykks** [comment]
Actually do you acknowledge the issue with combineQueries ? I may have missed something, or is there a good solution to avoid this sync issue ?
I don't really want to use reselect because it's cool, but because it does fix this issue. The rest is, as I stated, "bonus".

About reselect integration, the missing bits are for loading and error selector. There is not proper way to access theses with a pure function because akita queries are tied with the store.

**Comment by NetanelBasal** [comment]
I understand the problem, but I have never encountered it. You have the option to use reselect with Akita, the same as you'd use it in ngrx.


```ts
query.select(getSomethingFromState())
```

You can access the `loading` and `error` state directly.

```ts
const getLoading = state => state.loading;
const getError = state => state.error;
```

**Comment by Wykks** [comment]
Alright,

Yeah I know about accessing loading and error like that, in my first post I actually put this : 
```
export const isLoadingSelector = (state: MyState & { loading: boolean }) =>
  state.loading;
```
But, the typings here are not ideal.

I believe this issue may be often overlooked because most of the time it's just going to cause a minor visual issue. And it's hard to identify the cause.

Thanks for answering 👍
