### ISSUE TITLE
Documentation for PersistNgFormPlugin is missing 

### ISSUE THREAD

**Issue by danielbeckmann** [datorama/akita#576]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Question

The documentation of the [PersistNgFormPlugin](https://datorama.github.io/akita/docs/angular/persist-form) is leading to an outdated URL (netbasal.gitbook.io). Will this page be updated in the next time? Is the `PersistNgFormPlugin` still relevant or is it also deprecated in favor of [ngneat/forms-manager](https://github.com/ngneat/forms-manager)?

**Comment by NetanelBasal** [comment]
It's deprecated in favor of ngneat/forms-manager

**Comment by danielbeckmann** [comment]
Thank you for clarifying
