### ISSUE TITLE
Akita schematics: create service throws exception 'Cannot read property 'lastIndexOf' of undefined'

### ISSUE THREAD

**Issue by SergiusSidorov** [datorama/akita#584]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Run command:
>ng generate @datorama/akita:akita-service --path=/src/app/core/services/settings
Cannot read property 'lastIndexOf' of undefined

## Expected behavior

Should generate new service.

## Minimal reproduction of the problem with instructions

@datorama/akita: 5.3.0
@datorama/akita-ngdevtools: 5.0.3

## Environment

<pre><code>
Angular version: 11.0.5
 
For Tooling issues:
- Node version: 11.0.5
- Platform:  Linux

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Does it work when you don't specify a custom path?

**Comment by SergiusSidorov** [comment]
Everything worked after removing and reinstalling dependencies. Sorry for the inconvenience.
