### ISSUE TITLE
Add GitHub Discussions?

### ISSUE THREAD

**Issue by tony** [datorama/akita#591]
This can be enabled on the repo and can clean up dev related issues and still permit Q&A

https://docs.github.com/en/free-pro-team@latest/discussions/quickstart

Issues: [Questions](https://github.com/datorama/akita/issues?q=is%3Aissue+is%3Aopen+label%3Aquestion), [Discussions](https://github.com/datorama/akita/issues?q=is%3Aissue+is%3Aopen+label%3Adiscussion)

**Comment by NetanelBasal** [comment]
What about Gitter?

**Comment by tony** [comment]
@NetanelBasal

Gitter is also worth trying, not a substitute for a system a like Discussions which is a message board / Q&A system

In my experience w/ gitter: I have it on a few projects but ultimately rarely use it. It required a lot of investment from myself and people who have questions.

As for discussions in GitHub, it can be enabled easily via the Project settings, and issues can be migrated to discussions: Example https://github.com/tmux-python/tmuxp/discussions

**Comment by NetanelBasal** [comment]
Done

**Comment by tony** [comment]
@NetanelBasal Nice we have that now

Do we wanna move discussion / Q&A issues to Discussions? 

![image](https://user-images.githubusercontent.com/26336/103293205-0a8f3e00-49b5-11eb-986a-3e196722b144.png)

e.g. https://github.com/datorama/akita/issues/533

Look up items like this: [Questions](https://github.com/datorama/akita/issues?q=is%3Aissue+is%3Aopen+label%3Aquestion), [Discussions](https://github.com/datorama/akita/issues?q=is%3Aissue+is%3Aopen+label%3Adiscussion)
