### ISSUE TITLE
GetHead or GetDiff for DirtyCheck

### ISSUE THREAD

**Issue by GabDug** [datorama/akita#593]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

You can setHead for a store with the DirtyCheck plugin. You can not retrieve the stored head (or I have not found the way), only the status for the dirty check.

The `getHead()` function in `dirtyCheckPlugin.ts` is protected, and thus not available.

## Expected behavior

It would be nice to be able to get the data stored in the head.
It could also be nice to be able to have the diff directly from Akita.

## What is the motivation / use case for changing the behavior?

It would be nice to be able to get the data in the head, to compute a diff with the current state for instance. If there is a better way to achieve this (DirtyCheck + get the diff between the actual state and the head state), please let me know!

I would also be interested if there is a specific reason not to allow read access to the stored head.

Thanks, and happy holidays for those who are lucky to have some!

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.
