### ISSUE TITLE
[Question/Support] Model Methods..? How to implement this correctly? 

### ISSUE THREAD

**Issue by martinandersen3d** [datorama/akita#597]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>
---

From OOP, I'm used to write my model-class like this:
```
class Person (){
    firstname: String = ''
    lastname: String = ''

    fullname() { return this.firstName + this.lastName }
}
```

Note the method **fullname()** lives inside the class.

---
In Akita my **person.model.ts** looks like this:

```
// person.model.ts

export interface Person {
  firstName: string;
  lastName: string;

}

export function createPerson(params: Partial<Person>) {
  return {
    firstName: '',
    lastName: '',
  } as Person;
}

```

### My Question: 
In the Akita arkitecture, where is the **fullname()** method supposed to be?

➡️ My main goal is that the method is on the model/entity, and not in some controller. As you probably know, way to often, this logic stuff ends up scattered around in "controllers". I would like to avoid that 🤔🥳

**Comment by NetanelBasal** [comment]
https://datorama.github.io/akita/docs/additional/class/
