### ISSUE TITLE
EntityStore idKey is not treated accordingly

### ISSUE THREAD

**Issue by danzrou** [datorama/akita#6]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
EntityStore does not apply the provided idKey in constructor and thus entities & ids are not treated correctly

## Expected behavior
It should accept the idKey given in constructor and treat it accordingly

## Minimal reproduction of the problem with instructions
EntityStore constructor:

```
constructor(private stylesDataService: StylesDataService) {
    super([], {idKey: 'name'});
  }
```

Checking the idKey of the store:

`console.debug(`current store state =`, this._value(), this.config, `idKey=${this.idKey}`);`

Result:
`{idKey: "id", storeName: "styles"} 
{idKey: "id"storeName: "styles" __proto__: Object}  idKey=id`

## Environment

<pre><code>
Angular CLI: 6.0.3
Node: 8.9.4
OS: win32 x64
Angular: 6.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.3
@angular/cdk                      6.1.0
@angular/material                 6.1.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.6.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Which version are you using?

**Comment by NetanelBasal** [comment]
Are you using an EntityStore?

**Comment by danzrou** [comment]
EntityStore: Yes, 
Version:     "@datorama/akita": "^1.1.0"

**Comment by NetanelBasal** [comment]
Not connected - but why are you passing an array to the constructor?

**Comment by NetanelBasal** [comment]
Can you try the new way, please?

```ts
@StoreConfig({
  name: 'styles',
  idKey: 'name'
})
```

**Comment by danzrou** [comment]
That solved it.

As for the array - I misunderstood the difference between the entities and the state at first. The constructor now calls `set([])` with the entities array.

**Comment by NetanelBasal** [comment]
You don't need to call anything in your store. 

Your store should stay clean, for example:

```ts
@StoreConfig({
  name: 'styles',
  idKey: 'name'
})
class StylesStore extend EntityStore<State, Style> {
  constructor() {
    super();
  }
}
```

Then in your component, you should call a service which calls the `set()` method to update the entities for the first time.

```ts
class StylesComponent {
  ngOnInit() {
     this.service.fetchStyles()
  }
}

class StylesService {
  fetchStyles() {
     this.dataService.fetchStyles().subscribe(styles => {
         this.stylesStore.set(styles);
     });
  }
}
```

Please, read the docs for more information. Thanks.
