### ISSUE TITLE
[Support] filterNil doest not filter undefined

### ISSUE THREAD

**Issue by ydemartino** [datorama/akita#606]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am trying to use the filterNil operator to convert my Observable<Entity | undefined> to an Observable<Entity>

```
  selectCustomer(customerId: string): Observable<Customer> {
    return this.customersQuery.selectEntity(customerId).pipe(filterNil); //  error TS2322: Type 'Observable<Customer | undefined>' is not assignable to type 'Observable<Customer>'
  }
```

## Expected behavior

filterNil correctly transforms my Observable<Entity | undefined> to an Observable<Entity>

## What is the motivation / use case for changing the behavior?

When I check the filterNil code on github here: https://github.com/datorama/akita/blob/master/libs/akita/src/lib/filterNil.ts
The code correctly handles undefined. 

But when I check the code in my project, this is the content of filterNil.d.ts:
`export declare const filterNil: <T>(source: Observable<T>) => Observable<Diff<T, null>>;`
This code is missing the undefined type.

## Environment

<pre><code>
Angular version: 11.0.0
Akita: tried with 5.2.3 and 6.0.0
 
For Tooling issues:
- Node version: v12.18.2
- Platform:  Mac

</code></pre>

**Comment by NetanelBasal** [comment]
Can you reproduce it on stackblitz, please?

**Comment by ydemartino** [comment]
I did not manage to reuse the the Akita seed on  stackblitz , so I created a github repository, I hope this is ok: https://github.com/ydemartino/akita-filternil
This compile time error happens here: https://github.com/ydemartino/akita-filternil/blob/master/src/app/app.component.ts#L20

Steps to reproduce:
- ng new app --strict
- ng add @datorama/akita
- Add a feature
- Add this code to demonstrate this issue
`
  selectCustomer(): Observable<Customer> {
    // Compile time error
    return this.customerQuery.selectEntity(1).pipe(filterNil);
  }
`

The issue does not happen when strict flag is off.

**Comment by ydemartino** [comment]
Can I do anything to help for this issue?

**Comment by NetanelBasal** [comment]
See if you can reproduce it.

**Comment by ydemartino** [comment]
Yes, I have been able to reproduce it on this [repo](https://github.com/ydemartino/akita-filternil) and I gave steps to help reproduce.

What I did not understand first is that, this issue only happens when creating Angular project with --strict flag.

**Comment by ydemartino** [comment]
Have you been able to reproduce the issue with the steps I gave?

**Comment by NetanelBasal** [comment]
No. Do you want to create a PR?

**Comment by ydemartino** [comment]
I would if I knew how to fix this issue. But I don't understand why this happens as in [the repo the function](https://github.com/datorama/akita/blob/master/libs/akita/src/lib/filterNil.ts) is clearly filtering undefined.

Have you tried to clone the repo where I reproduced the issue? https://github.com/ydemartino/akita-filternil

**Comment by erosostolato** [comment]
@ydemartino could you test if this code works?

```ts
import { Observable } from 'rxjs'
import { filter } from 'rxjs/operators'

/**
 * @example
 *
 * query.selectEntity(2).pipe(filterNil)
 */
export const filterNil = <T>(source: Observable<T | undefined | null>) =>
  source.pipe(
    filter(
      <P>(value?: P | null): value is P =>
        value !== null && typeof value !== 'undefined'
    )
  )
```

**Comment by ydemartino** [comment]
Here is what I have tried:

```
export class AppComponent {

  selectCustomer(): Observable<Customer> {
    // Compile time error
    return this.customerQuery.selectEntity(1).pipe(filterNil);
    return this.customerQuery.selectEntity(1).pipe(filterNil2);
    return this.customerQuery.selectEntity(1).pipe(filterNil3);
  }

}

export const filterNil2 = <T>(source: Observable<T | undefined | null>) =>
  source.pipe(
    filter(
      <P>(value?: P | null): value is P =>
        value !== null && typeof value !== 'undefined'
    )
  );

export const filterNil3 = <T>(source: Observable<T | undefined | null>) => source.pipe(filter((value): value is Diff<T, null | undefined> => value !== null && typeof value !== 'undefined'));

```

The result is that only the first filterNil is showing a compile time error. 
The second is the one you gave me and the third is the original from the repo. 

My guess is that something is going wrong during the typescript type generation file because the function prototype is going from `(source: Observable<T | undefined | null>)` to `export declare const filterNil: <T>(source: Observable<T>) => Observable<Diff<T, null>>;`
My filterNil.d.ts is missing the undefined type in Diff.

**Comment by NetanelBasal** [comment]
https://codesandbox.io/s/typescript-forked-r2h1c?file=/src/index.ts

**Comment by erosostolato** [comment]
I think it worked on @NetanelBasal's repro

**Comment by ydemartino** [comment]
Yes I don't see any error in the sandbox, but I'm not sure if this actually fixes the issue.

As I said, if I copy/paste the source code from the repo, (as I did with filterNil3 above), I have no error.
As far as I understand this issue, the problem is coming from the filterNil.d.ts typescript file which is missing the Diff undefined.

I think changing the value to T only will not fix the problem as if I have the type `number | undefined`, T will match number and undefined and the output will still be `number | undefined`.

**Comment by rosostolato** [comment]
@ydemartino Now I got what you mean.

I will try later to change the code, build locally and replace in node_modules folder... Will check if it works
