### ISSUE TITLE
What does `dispatch?: boolean` of an effect cause exactly?

### ISSUE THREAD

**Issue by juri-sinitson** [datorama/akita#612]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

On https://datorama.github.io/akita/docs/angular/effects and in the file `node_modules\@datorama\akita-ng-effects\lib\types.d.ts ` is documentaton for `dispatch?: boolean` missing. 
What does `dispatch?: boolean` cause exactly?
My effects didn't work for me until I found that `dispatch` hast to be undefined instead of `false` in my case, say just skipped.

## Expected behavior

`dispatch?: boolean` is documented at least in one of the sources above and ideally also on https://datorama.github.io/akita/docs/best-practices

## Minimal reproduction of the problem with instructions
Just go to https://datorama.github.io/akita/docs/angular/effects or open `node_modules\@datorama\akita-ng-effects\lib\types.d.ts`

## What is the motivation / use case for changing the behavior?
To work with akita optimally

## Environment
Angular version: ~10.1.0
Akita version: ^6.0.0

**Comment by NetanelBasal** [comment]
If you want to return a new action from the effect, you can use `{ dispatch: true }`, and it'll dispatch the returned action for you.

**Comment by yackinn** [comment]
That's correct.

What's  your exact setup?
If this issue still persists can you show a stackblitz or code sample?
You should be using no flag or set ```{dispatch: true}``` if you are returning one or morge actions from your effect.

https://github.com/datorama/akita/blob/e6f0b5d83684e9ad84ddbf065c6c571912b2c50c/libs/akita-ng-effects/src/lib/module-manager.service.ts#L35-L36

**Comment by juri-sinitson** [comment]
The issue is the document one, not the technical one. It works fine for me now, but it took a couple of hours for me to figure out that the beginning effect should not have `dispatch` set to false. I think, it's a mistake of a state management newbe.

That's why I expect `dispatch` to be documented on https://datorama.github.io/akita/docs/angular/effects and in `node_modules\@datorama\akita-ng-effects\lib\types.d.ts`.

Now hen I know, what `dispatch` does, I can also improve the documentation myself.
Should I just do it?

> What's your exact setup?
> If this issue still persists can you show a stackblitz or code sample?
> You should be using no flag or set `{dispatch: true}` if you are returning one or morge actions from your effect.

IIt'll be cumbersome to put the productive app to stackblitz, but for the sake of completeness here is the effects class where I had problem to solve (I renamend some variables and classes before putting the code here). 
The first effect had also `dispatch` put to false, making all the effects useless.

```TypeScript
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Actions, createEffect, ofType } from '@datorama/akita-ng-effects';
import { Observable, of } from 'rxjs';
import { catchError, switchMap, tap } from 'rxjs/operators';

import { ErrorService } from 'src/app/services/error.service';
import { loadFoo, loadFooError, loadFooSuccess } from './foo.actions';
import { FooEntity } from './Foo.model';
import { FooStore } from './Foo.store';

@Injectable()
export class FooEffects {

  constructor(
    private actions$: Actions,
    protected store: FooStore,
    private http: HttpClient,
    private errorService: ErrorService,
  ) {}

  loadFoo$ = createEffect(() =>
    this.actions$.pipe(
      ofType(loadFoo),
      switchMap( _ => this.get().pipe(
          tap((entity: FooEntity) =>
            this.actions$.dispatch(loadFooSuccess(entity)))
        )
      ),
      /* tslint:disable:no-any */
      catchError( (error: any) => {
      /* tslint:enable:no-any */
        this.actions$.dispatch(
          loadFooError(this.errorService.convertToAppError(error))
        );
        return of(error);
      }),
    )
  );

  loadFooSuccess$ = createEffect( () =>
    this.actions$.pipe(
      ofType(loadFooSuccess),
      tap((entity: FooEntity) => this.store.set([entity])),
    ),
    { dispatch: false }
  );

  loadFooError$ = createEffect( () =>
    this.actions$.pipe(
      ofType(loadFooError),
      /* tslint:disable:no-any */
      tap((error: any): void => this.store.setError(error)),
      /* tslint:enable:no-any */
    ),
    { dispatch: false }
  );

  get(): Observable<FooEntity> {
    return this.http.get<FooEntity>('/foo');
  }
}
```

**Comment by NetanelBasal** [comment]
@juri-sinitson you're welcome to submit a PR. Thanks.
