### ISSUE TITLE
[Angular] HMR doc is outdated

### ISSUE THREAD

**Issue by Wykks** [datorama/akita#613]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The documentation here https://datorama.github.io/akita/docs/angular/hmr refer to an old way of setting up HMR in Angular

## What is the motivation / use case for changing the behavior?

Since Angular 11, there's a new option "--hmr" in the CLI.  For now, I'm not sure what to do to make Akita work with this option.
(I tried without success. Maybe something should change in Akita itself too).

## Environment

<pre>
Angular version: 11.1.0

**Comment by NetanelBasal** [comment]
Can you please create a simple repo that demonstrates the issue?

**Comment by erosostolato** [comment]
@NetanelBasal what happens is that akita state reloads with every hot reload, even if you set `(window as any).hmrEnabled = true;`. So if you want to just change a text on the template and hit save, it will reset all your stores.

**Comment by kaeh** [comment]
I agree, right now i don't know what to do to enable Akita HMR handling as there is no need of an hmr.ts file as of Angular 11.

Do you have any idea or plans for this issue ?

Thanks in advance :)

**Comment by NetanelBasal** [comment]
I'll find the time soon to investiagte.

**Comment by NetanelBasal** [comment]
@shaharkazaz any news here?

**Comment by NetanelBasal** [comment]
@erosostolato, the store's ngOnDestroy has been called when you change some text and save?

**Comment by erosostolato** [comment]
@NetanelBasal I created this [stackblitz](https://stackblitz.com/edit/angular-akita-hmr-example?file=angular.json) project so you can test on your own (download and run it locally).  So, I placed a `console.log` on store's `ngOnDestroy` and I could see that it's being called on every hot reloads. I even tried to enable hmr with `(window as any).hmrEnabled = true`, but it has no difference.

**Comment by NetanelBasal** [comment]
Thank you, @erosostolato. I see that Angular re-creates the store on every refresh.

**Comment by erosostolato** [comment]
Welcome, @NetanelBasal. Do you think it's valid to create a sort of a hook for the develop mode only (using `hmrEnable` prop for example) to temporally save the store into the browser's IndexedDb and restore on reload?

**Comment by NetanelBasal** [comment]
Actually, you can use the `persistState`:

```ts
// main.ts

if(!environment.production) {
  persistState()
}
```

**Comment by erosostolato** [comment]
@NetanelBasal Should work just by enabling `persistState()` or should I do anything else? I tried to reproduce that locally but it didn't work.
