### ISSUE TITLE
Problem on undo with StateHistoryPlugin  when property is added on entity

### ISSUE THREAD

**Issue by lilas78** [datorama/akita#619]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

I'm having an entity store, and I use StateHistoryPlugin to handle undo/redo. It works fine, except for one case :

an entity gets a new property

- What I expect : when I do an undo on this entity, I expect to have the entity its in old state, so without the new property

- What I have : after the undo, the entity still has this property

To Reproduce :
[stackblitz](https://akita-books-dejkbp.stackblitz.io)
Click on edit button : this will add a comment on first book
Click on undo => the comment is not removed

See #618 

## Environment

<pre><code>
Angular version:~11.0.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Windows

</code></pre>

**Comment by NetanelBasal** [comment]
In this case, the following should be `replace`, not `update`:

https://github.com/datorama/akita/blob/b3341a12794ad0763f098959c04d26a378536262/libs/akita/src/lib/plugins/plugin.ts#L76

**Comment by lilas78** [comment]
Is this issue goind to be fixed ?

**Comment by NetanelBasal** [comment]
I'm sorry, I'm too busy right now. As I mention, it should be a quick fix. You can create a PR.

**Comment by theorlovsky** [comment]
@NetanelBasal I'm digging into another problem. You can't undo removing an entity, here's the demo:
https://stackblitz.com/edit/angular-ivy-akita-undo-delete?devtoolsheight=33&file=src/app/state/service.ts

I'm planning to open a PR today. I also assume it's a related issue, so I can look into this one as well.

**Comment by NetanelBasal** [comment]
Cool, thanks!

**Comment by theorlovsky** [comment]
My problem with undoing an entity removing is not related to current issue, so I'll open a new one.
