### ISSUE TITLE
selectMany does not use the default sorting in @QueryConfig

### ISSUE THREAD

**Issue by RonnieRocket147** [datorama/akita#624]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using `selectMany` the default sorting specified within `@QueryConfig` is not used.

## Expected behavior

The sorting should be as specified in `@QueryConfig`

## Environment
<pre><code>
Angular version: 11.2.1
Akita version: 5.3.0 + 6.0.0
</code></pre>

**Comment by NetanelBasal** [comment]
Currently, it only works with `selectAll`.

**Comment by RonnieRocket147** [comment]
Thanks for this information
