### ISSUE TITLE
Data retrieve from the API endpoint is always named with the last entry of the MongoDB collection

### ISSUE THREAD

**Issue by jocactus** [datorama/akita#63]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am sending a GET http request to an API endpoint to retrieve data from a MongoDB database with mongoose (MEAN stack).
The data received is always named with the name of the last entry of the collection.

## Expected behavior

The data should have the same name as the database data.

## Minimal reproduction of the problem with instructions

Compare the data display on the stackblitz and the API endpoint :
stackblitz : https://stackblitz.com/edit/angular-2qqqx4
API endpoint : https://dev-api.proforeigner.com/api/nationalities

## What is the motivation / use case for changing the behavior?

I am not retrieving good data to display.

## Environment

<pre><code>
Angular version: 6.1.6

Browser:
- [x] Chrome (desktop) version 68.0.3440.106
 
For Tooling issues:
- Node version: v8.11.3
- Platform:  Mac

Others:

</code>MEAN stack with 
- MongoDB v3.6.7
- Express v4.16.3</pre>

**Comment by NetanelBasal** [comment]
It's happening because by default Akita expects an `id` key as the identifier. Just change it to the mongo key:

```ts
@StoreConfig({ name: 'nationalities', idKey: '_id' })
```
