### ISSUE TITLE
resetStores() not working with EntityStores

### ISSUE THREAD

**Issue by sircon** [datorama/akita#634]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
1) Create an Entity Store
2) Run `resetStores()`
3) The store from step 1 is a normal Store and not an entity store anymore

## Expected behavior
1) Create an Entity Store
2) Run `resetStores()`
3) The store from step 1, to be a fresh new entity store

## Minimal reproduction of the problem with instructions
I can't right now, but I can see the issue in the code here. The `EntityStore` extends the `Store` class, and the `reset()` (https://github.com/datorama/akita/blob/master/libs/akita/src/lib/store.ts#L220) sets the initial state, but for entity stores the initial state also has `...getInitialEntitiesState()`.

## What is the motivation / use case for changing the behavior?
When the user logs out I want to reset the stores, and when it logs in again I want to have a fresh usable stores, now just gives an error when I try to upsert into them!

## Environment
React

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sircon** [comment]
Later in the week I might be able to raise a PR to fix it!

**Comment by NetanelBasal** [comment]
https://github.com/datorama/akita/blob/master/libs/akita/src/lib/entityStore.ts#L60

**Comment by sircon** [comment]
@NetanelBasal yes, but that's in the `EntityStore` constructor.

I might be wrong (and if I am, then the issue might be something else) but when you reset an `EntityStore` (https://github.com/datorama/akita/blob/master/libs/akita/src/lib/store.ts#L220) it just assigns in to the object the `initialState` and skips the `getInitialEntitiesState()`. It doesn't destroy the store and initiates on again, it just "clears" it up.

**Comment by NetanelBasal** [comment]
`this._initialState` should be the value from `super({ ...getInitialEntitiesState(), ...initialState )`

**Comment by sircon** [comment]
It seems you are right indeed! I'll try reproduce the issue on Stackblitz and will get back to you!

**Comment by sircon** [comment]
@NetanelBasal here is a demo of the issue: https://stackblitz.com/edit/react-ts-jpkkwh?file=index.tsx I really think it falls around what I said, but not really sure.

**Comment by sircon** [comment]
Ok, I did some investigation and the issue seems to be here: https://github.com/datorama/akita/blob/607de4f9365572648a274f09351c19773615b2dd/libs/akita/src/lib/store.ts#L298

On init, it seems it didn't load yet the `akitaConfig` and it is not a resettable. Although later when it resets, it is resettable, but the `_initialState` is undefined.

If this
```ts
if (this.isResettable()) {
      this._initialState = initialState;
}
```

turns into this:
```ts
this._initialState = initialState;
```

it works just fine.

**Comment by NetanelBasal** [comment]
https://github.com/datorama/akita/blob/master/libs/akita/src/__tests__/resetStores.spec.ts#L72

**Comment by sircon** [comment]
The specs don't lie ;)

I did further testing and it seems that `akitaConfig` needs to be loaded before the stores are.

I'm closing down the issue, but I think this gives a weird error anyway, maybe having something in the documentation of some sorts about the config would help?

Thanks for the awesome work with Akita!

**Comment by NetanelBasal** [comment]
You're welcome to improve the docs as you wish.
