### ISSUE TITLE
Changelog updates?

### ISSUE THREAD

**Issue by tony** [datorama/akita#640]
Hi there! Just want to keep up with the latest :)

There was recently updates in 6.0 and 6.1, and so on. Is there a place where changes can be tracked?

The only change log I see is at https://github.com/datorama/akita/blob/master/CHANGELOG.md

**Comment by NetanelBasal** [comment]
Sorry, there was an issue with the tool we use - standard version. You can have a look at the commits for now.

**Comment by NetanelBasal** [comment]
Back to normal
