### ISSUE TITLE
selectActiveId and getActiveId don't use the IDType from the State

### ISSUE THREAD

**Issue by leon** [datorama/akita#645]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

We like to create a typescript type for our Ids so it is easy to document where the id is used in code.

```
export type TodoId = string
```

If we have this store

```ts
import { Injectable } from "@angular/core";
import {
  ActiveState,
  EntityState,
  EntityStore,
  StoreConfig
} from "@datorama/akita";

export type TodoId = string;
export interface Todo {
  id: TodoId;
  name: string;
  done: boolean;
}

export interface TodoState extends EntityState<Todo, TodoId>, ActiveState {}

@Injectable({ providedIn: "root" })
@StoreConfig({ name: "todos" })
export class TodoStore extends EntityStore<TodoState> {
  constructor() {
    super();
  }
}

```

and this query

```ts
import { Injectable } from "@angular/core";
import { QueryEntity } from "@datorama/akita";
import { Observable } from "rxjs";
import { TodoId, TodoState } from "./todo.store";

@Injectable({ providedIn: "root" })
export class TodoQuery extends QueryEntity<TodoState> {
  getActiveTodoSomething() {
    // getActiveId() gets typed as ID
    const id = this.getActiveId();

    // but should get typed as
    const correctId: TodoId = this.getActiveId();

    // and this gets typed as Observable<ID>
    const id$ = this.selectActiveId();

    // but should also be Observable<TodoId>
    const correctId$: Observable<TodoId> = this.selectActiveId();
  }
}
```
You can see that I cannot type the `correctId` and `correctId$` because my `TodoId` is a `string` and not a `string | number`

## Expected behavior

If using the State extensions `ActiveState` and `MultiActiveState` the `getActiveId` and `selectActiveId` should return the `IdType` for the store and not the predefined akita `ID`

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/akita-active-id-type?file=src%2Fapp%2Ftodo.query.ts

## What is the motivation / use case for changing the behavior?

I want activeId to have the correct type set in the State Generic

## Environment

<pre><code>
Angular version: 11

**Comment by NetanelBasal** [comment]
You're right, but I'm afraid this will be a breaking change for some users. We'll add it in the next major version. You can get around it for now by doing this:

```ts
export interface TodoState extends EntityState<Todo, TodoId>, ActiveState {
  active: TodoId
}
```

**Comment by leon** [comment]
Great :)
