### ISSUE TITLE
paginatorPlugin not working with 0-based paging

### ISSUE THREAD

**Issue by thegreatanon** [datorama/akita#660]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The `paginatorPlugin` assumes the pages start with 1. If the server assumes the paging is 0-based (page=0 is the first page), 
the following features will not work:
* isFirst
* getFrom
* getTo
* setFirstPage
* prevPage

The documentation describes the `startWith` config option to define the first page. Setting this to 0 will correctly load the first page, but since the start=1 is hardcoded in some of these functions, it will not work reliably. 

## Expected behavior

When setting the startWith config to 0, the plugin should work with a 0-based paging api.

## Minimal reproduction of the problem with instructions

I think it's enough to see the following method:
`paginatorPlugin.ts:232`
```
 setFirstPage() {
    this.setPage(1);
  }
```
to see that the startWith config is not taken into account.

## What is the motivation / use case for changing the behavior?

I have an API that uses 0-based page indexing.

## Environment

<pre><code>
Angular version: 11.2 (not really relevant)

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 87.0
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by thegreatanon** [comment]
I can of course write a wrapper around my HTTP call to +1 / -1 accordingly, but since there's an `startWith` config option I would assume this would work. Or maybe I'm understanding this config option wrong?

**Comment by NetanelBasal** [comment]
It was meant to set the first page that we fire. I think we should also update `this.pagination.currentPage`

**Comment by thegreatanon** [comment]
So you would e.g. use startWith=3 to directly show the third page. Then I indeed misinterpreted the documentation about this parameter. 

What do you mean with:
> I think we should also update this.pagination.currentPage

If working 0-based, you essentially have 'server'-numbers, and user-facing numbers (which are 1-indexed). 

Do you think this warrants a code-change to be able to support 0-based indexes, or is it too niche and I should just keep using the wrapper modifying the page parameter when sending/receiving the request.

**Comment by NetanelBasal** [comment]
I'd go with the simple approach for now because no one complained about it yet :)

**Comment by NetanelBasal** [comment]
I'm closing the issue. If you have any further questions feel free to ask.
