### ISSUE TITLE
`distinctUntilArrayItemChanged` extremely slow on large arrays (massive perf hit)

### ISSUE THREAD

**Issue by lincolnthree** [datorama/akita#664]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`distinctUntilArrayItemChanged` is extremely slow when diffing arrays of 'large' sizes. (Mine is 5000 or so elements large, for example). Since this operator does not use many simple shortcuts for detecting array differences, essentially, it almost always diffs the entire arrays at `O(n^2)`... twice.

For diffing arrays of about 1000 elements in length, this will method result in 2,000,000 comparisons in the worst case. That's a lot :)

This operator does not ever simply compare array length (1), which is probably the simplest way to tell if an element was added or removed without running the entire length of the arrays.

By simply comparing array lengths, many of the redundant checks and balances can be skipped in most cases, or removed altogether. See below for suggestions:

```

// @internal
function distinctUntilArrayItemChanged() {
    return distinctUntilChanged((prevCollection, currentCollection) => {
        if (prevCollection === currentCollection) {
            return true;
        }
        if (isArray(prevCollection) === false || isArray(currentCollection) === false) {
            return false;
        }

        // if (isEmpty(prevCollection) && isEmpty(currentCollection)) {
        if (prevCollection.length !== currentCollection.length)) {

            /*  1: Compare prevCollection.length !== currentCollection.length here since
             * we already know they are both arrays from the logic immediately above.
             * This can certainly shortcut if the lengths are different. Return 'false' instead */

            // return true;
            return false;
        }

        // if item is new in the current collection but not exist in the prev collection
        const hasNewItem = hasChange(currentCollection, prevCollection);
        if (hasNewItem) {
            return false;
        }


            /*  2. Order typically matters in arrays (but this operator will not currently
             * detect order changes.) If that is intentional, then ignore this, otherwise, the
             * two separate calls to `hasChange` can be replaced by a for-loop diff that
             * walks the arrays in-order and simply compares object identity of each element
             *  pair*/

        const isOneOfItemReferenceChanged = hasChange(prevCollection, currentCollection);
        // return false means there is a change and we want to call next()
        return isOneOfItemReferenceChanged === false;
    });
}
// @internal
function hasChange(first, second) {
    const hasChange = second.some(currentItem => {
        const oldItem = first.find(prevItem => prevItem === currentItem);
        return oldItem === undefined;
    });
    return hasChange;
}
```

## Expected behavior

A faster implementation :)

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## What is the motivation / use case for changing the behavior?

Performance is bad :) This operation takes upwards of 300ms for extremely large arrays.

## Environment

<pre><code>
Angular version: 12.0.0-rc.0

Browser:
- All
 
For Tooling issues:
- Node version: All
- Platform:  All

Others:

</code></pre>

**Comment by lincolnthree** [comment]
Additionally, to replace the double comparison of the arrays, you can use the Symmetric Difference to calculate `hasChanged`

See this implementation to replace #num2 above:

  ```
/**
   * Returns an array containing the elements that are unique (contained only in one of N given arrays).
   * See 'symmetric difference': https://en.wikipedia.org/wiki/Symmetric_difference
   *
   * @param arrays The arrays to diff.
   */
  static diff<T>(...arrays: T[][]): T[] {
    return [].concat(...arrays.map((arr, i) => {
      const others = arrays.slice(0);
      this.splice(others, i, 1);
      const unique = [...new Set([].concat(...others))];
      return arr.filter(x => !unique.includes(x));
    }));
```

**Comment by NetanelBasal** [comment]
I think you missed the point here. **If** I remember correctly it goes like this:

```ts
- prevCollection - contains only the filters items you requested ( in `selectMany` )
- currentCollection - contains the entire collection 
```

Do I remember correctly?

**Comment by lincolnthree** [comment]
Maybe? Either way, what if `selectMany` contains a lot of items? (I can certainly work around this, and I think it could still be optimized either way to include length comparison since that should certainly matter?)

**Comment by NetanelBasal** [comment]
I will revisit this function and see what we can do.

**Comment by lincolnthree** [comment]
Oh. Also I discovered this problem initially since I accidentally used this operator in my code. Then I discovered it was `@internal` --> any way to omit this from the TS exports if it is truly internal?

**Comment by NetanelBasal** [comment]
I'll check because sometimes we use functions from the core in our plugins.

**Comment by lincolnthree** [comment]
@NetanelBasal Ah yes. Good old-fashioned API leakage making it into production, gotta love it :D Haha. Happens to all of us.

Thanks for checking into this. I think at minimum the `.length` optimization should be 'logically' safe and will shortcut quite a few operations, unless I've mis-read the code somehow!

**Comment by NetanelBasal** [comment]
I'll check it soon. Thanks!

**Comment by lincolnthree** [comment]
@NetanelBasal No huge rush as I've worked around the issue for now. But appreciated - I just wanted to make sure you were aware of the issue!

**Comment by lincolnthree** [comment]
BTW. Here is the method I use for large Array equality checking if you are interested (note this supports deep equality comparison which is why the worst case is `O(n^3)`. That can be removed or toggled to simple identity comparison to make it `O(n^2)`:

```

  /**
    * Best: O(c)
    * Worst: O(n^3) 
    * 
    * Calculate array & object equality (deeply) WARNING: This could be VERY slow with big objects in
    * the worst case!
    *
    * @param valud The left side comparable value
    * @param other The right side comparable value
    */
  static areEqual<T>(value: T[], other: T[]): boolean {
    if (value === other) {
      return true;
    }

    // Get the value type
    const type = Object.prototype.toString.call(value);

    // If the two objects are not the same type, return false
    if (type !== Object.prototype.toString.call(other)) { return false; }

    // If items are not an object or array, return false
    if (['[object Array]', '[object Object]'].indexOf(type) < 0) { return false; }

    // Compare the length of the length of the two items
    const valueLen = type === '[object Array]' ? value.length : Object.keys(value).length;
    const otherLen = type === '[object Array]' ? other.length : Object.keys(other).length;
    if (valueLen !== otherLen) { return false; }

    // Compare two items
    const compare = (left: any, right: any) => {
      if (left === right) {
        return true;
      }

      // Get the object type
      const itemType = Object.prototype.toString.call(left);

      if (['[object Array]', '[object Object]'].indexOf(itemType) >= 0) {
        // If an object or array, compare recursively
        if (!Arrays.areEqual(left, right)) {
          return false;
        }
      } else {
        // If the two items are not the same type, return false
        if (itemType !== Object.prototype.toString.call(right)) {
          return false;
        }

        if (itemType === '[object Function]') {
          // Else if it's a function, convert to a string and compare
          if (left.toString() !== right.toString()) {
            return false;
          }
        } else {
          // Otherwise, just compare
          if (left !== right) {
            return false;
          }
        }
      }
      return true;
    };

    // Compare properties
    if (type === '[object Array]') {
      for (let i = 0; i < valueLen; i++) {
        if (compare(value[i], other[i]) === false) {
          return false;
        }
      }
    } else {
      for (const key in value) {
        if (value.hasOwnProperty(key)) {
          if (compare(value[key], other[key]) === false) {
            return false;
          }
        }
      }
    }

    return true;
  }
```

**Comment by randallmeeker** [comment]
I'm syncing around 10k records and am seeing slowness as well. I'm working on a workaround myself to not sync so many records but wanted to know how this workaround can be implemented and what else if anything anyone has discovered on this.
