### ISSUE TITLE
Async callbacks in `update`

### ISSUE THREAD

**Issue by Zizico2** [datorama/akita#665]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Are async callbacks allowed in `update`?

## Expected behavior

Async callbacks could be allowed and automatically call `setLoading(true)` and  `setLoading(false)` when necessary. A flag could be received by `update`to toggle this behaviour.

## What is the motivation / use case for changing the behavior?

Reduce boilerplate for something that should be a pretty common use case.

**Comment by NetanelBasal** [comment]
https://datorama.github.io/akita/docs/additional/operators/#setloading
