### ISSUE TITLE
Question: Integration with Apollo GraphQL.

### ISSUE THREAD

**Issue by NGSalvo** [datorama/akita#67]
Hi, first congratulations for quick and new realease, I'm really hyped about it.
Going straight to the point, have you ever used and implemented a graphql endpoint with Apollo? The "problems" starts when using a state manager, such as NgRx, which case the apollo-angular developer is currently working on a solution to "merge" the two generated stores (NgRx and apollo). Yes, Apollo create it own inMemoryCache, creating a separate store.
Do you know a way of doing this? It's necessary? (since I do not know the internal things of Akita); If you're interested, should I make a request from this?
Thanks!

**Comment by NetanelBasal** [comment]
We don't have experience with Apollo. I don't understand why we need cache both in Apollo and Akita? There is no way to disable the cache in Apollo and let Akita take care of this?

**Comment by NGSalvo** [comment]
Thanks for your anwser. I can't help you with this, because I do not know the internal functioning of Apollo. Maybe a reason is: 

> Apollo Client normalizes all of your data so that if any data you previously fetched from your GraphQL server is updated in a later data fetch from your server then your data will be updated with the latest truth from your server.

So, no problem, it was just a simple doubt I have. If you don't use it, I don't see why you should right now. I'm not technically qualified to explain even if I wanted right now. If ever someone get interested in this, then I'll be eager to learn and test. Right now, I'll test Akita alone with a common REST API.
Thanks!
