### ISSUE TITLE
Just a question (Not an isssue)

### ISSUE THREAD

**Issue by stherrienaspnet** [datorama/akita#68]
Hello Akita Team, where can i found and download the source code for your sample application at http://akita.surge.sh/? 

I read also this great post 'The Complete Guide to Authentication in Angular with Akita'
The source code of the post sample application could probably help me since I need to implement first the security using JWT. This is probably already implemented in your sample application at http://akita.surge.sh/.

Thanks!

**Comment by NetanelBasal** [comment]
You can find the app in this repo. https://github.com/datorama/akita/tree/master/playground

Good luck!
