### ISSUE TITLE
[Docs] Persist EntityUI state

### ISSUE THREAD

**Issue by LucaBellomo** [datorama/akita#682]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

there are no informations about persist EntityUI state.

## Expected behavior

It would be nice to have a paragraph about EntityUI in the persist page with an example. 
I figured out that in order to store the entityUI I had to add 'UI/{storeName}' to the "include" prop of persist() param. But the info is missing.

## What is the motivation / use case for changing the behavior?

the information is missing, can be useful to specify how to persist entityUI state.

**Comment by NetanelBasal** [comment]
Thanks. You're welcome to submit a PR.
