### ISSUE TITLE
Security vulnerability found in akita dependency -> ajv

### ISSUE THREAD

**Issue by david4096** [datorama/akita#685]
As detected by snyk, ajv needs to be updated to a more recent version (`6.12.3`)

```
├─┬ @datorama/akita@6.1.3
│ └─┬ schematics-utilities@1.1.3
│   └─┬ @angular-devkit/core@7.3.10
│     └── ajv@6.9.1 
```

To close this issue please upgrade ajv to the latest.

**Comment by zhuweid** [comment]
same here

**Comment by NetanelBasal** [comment]
Upgraded to schematics-utilities@2
