### ISSUE TITLE
Update akita-ng-router-store to Angular 12

### ISSUE THREAD

**Issue by mhosman** [datorama/akita#686]

**Comment by vpallathu** [comment]
My whole application is failing to build due to the same reason. There is another library **akita-filters-plugin** is also failing for me.  I think **akita** is not actively developed to keep up with the latest advancements in other libraries that it depend on.

**Comment by mhosman** [comment]
What's the state of Akita? No updates in tickets, no updates in repos like akita-ng-router-store. We just want to know what's gonna happend or if we should switch to another solution. Thanks.

**Comment by NetanelBasal** [comment]
@mhosman, First, there is no need to be rude. We are not working for you. 

@vervallsweg `akita-filters-plugin` is a third-party library, and we're not responsible for it. 

@mhosman, what's the issue with the current version of ng-router-store? We're working with Angular v12, and it works fine.
