### ISSUE TITLE
Possible Typo into documentation (session.model.ts)

### ISSUE THREAD

**Issue by stherrienaspnet** [datorama/akita#69]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Hello Akita Team, when I was looking at the documentation I detected a possible error on the documentation for sessions.model.ts for the createSession function (missing comma & missing timestamp parameter initialization). Double check me because, I'm still learning Akita and WebStorm is complaining and sometime it produce false warning.

export function createSession({
                                  id = null, firstName = '', lastName = '', token = '', timestamp = new Date()
                              }: Partial<Session>) {
    return {
        id,
        firstName,
        timestamp,
        lastName,
        token
    };
}

**Comment by NetanelBasal** [comment]
Fixed, thanks. Keep up the excellent work.

**Comment by stherrienaspnet** [comment]
I wandering if there is a disavantage of using this way?
export function createSession() {
    return {
        id:null,
        firstName:'',
        lastName:'',
        token:''
    } as Session;
}

**Comment by NetanelBasal** [comment]
What do u mean "this way"? You are not initializing the params.

**Comment by stherrienaspnet** [comment]
Sorry my lack of clarity, into the playground code I Saw different pattern for the creation as follow:
I wonder witch one should I pickup

export function createSession({
  id = null, firstName = '', lastName = '', token = ''
}: Partial<Session>) {
  return {
    id,
    firstName,
    lastName,
    token
  };
}

export function createGenre(params: Partial<Genre>) {
  return {
    ...params
  } as Genre;
}


export function createStory() {
  return {
    title: '',
    story: '',
    draft: false,
    category: 'js'
  } as Story;
}

**Comment by NetanelBasal** [comment]
What works best for you 😀. Usually, it will be the `createGenere` pattern.

**Comment by stherrienaspnet** [comment]
Thanks :)

**Comment by stherrienaspnet** [comment]
One last question for today as I'm starting to use you nice akita cli tool. I wandering when you created session store for production application, did you answer YES to the question <Is it UIStore>? "I not sure if this is usefull for session or not base on your experience.

**Comment by NetanelBasal** [comment]
Not, it's not. If you have any further question feel free to send me a private [email](netanel.basal@datorama.com), so we won't bother the rest. Thanks.
