### ISSUE TITLE
Avoid overlapping states between apps on same port

### ISSUE THREAD

**Issue by jongbonga** [datorama/akita#697]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm using Akita in different apps but with the same patterns.
My session store has the same models in all the app and is persisted until a user signs out of the app.

So when I switch applications, how do I make sure Application B is using the correct store and will not confuse Application A persisted state with its own?
How do I assign an Akita instance to a specific app?

## Expected behavior

Assign store instances to a specific app to avoid overlapping states.

## What is the motivation / use case for changing the behavior?

I just run through an issue where my previous states were showing up on a new app I'm busy with.

## Environment

<pre><code>
Angular version: 12.0.1
Akita: 6.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by NetanelBasal** [comment]
You can use a different storage key
