### ISSUE TITLE
[Entity Service Loader] The Entity Loader does not seem to work correctly

### ISSUE THREAD

**Issue by realnsleo** [datorama/akita#699]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Trying to show loading indicators in an Angular component for `GET`. `POST`, `PUT` and `DELETE` actions is not successful when using the Entity Service Loader.

## Expected behavior

As shown in the Documentation, the `loaders` object from the `NgEntityServiceLoader` now contains loading indicators for each of the PostsService methods; Each one holding an observable boolean value, indicating the method’s loading status. Therefore, when an `HTTP` call is being made, the loader should be able to show the status.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/akita-loader-async-pipe-problem?file=src%2Fapp%2Fhello.component.ts

## Environment

<pre><code>
Angular version: 11.2.7

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x ] Edge version XX

**Comment by NetanelBasal** [comment]
See https://github.com/datorama/akita/pull/670

Update to the latest version and use:

```ts
connector() { 
  return new ReplaySubject(1)
}
```

**Comment by realnsleo** [comment]
Thank you :)

**Comment by realnsleo** [comment]
@NetanelBasal I was able to get this working by Updating and adding the connector to the `Config` object. The following code works perfectly well:

```
# users.component.ts

loaders = this.loader.loadersFor('users');
```

```
# users.component.html

<span *ngIf="loaders.get$ | async">Users are Loading!</span>
```

However, when I am trying to Update a specific entity, the Loading Indicator does not work. Like:

```
# users.component.ts

<span *ngIf="loaders.updateEntity(user.id) | async">Users with ID [{{ user.id }}] is updating.</span>
```

Could I be missing something? Thank you.

**Comment by NetanelBasal** [comment]
Please update the stackblitz.

**Comment by realnsleo** [comment]
@NetanelBasal I can confirm it works as expected on stackblitz:

https://akita-loader-async-pipe-problem-nq7e44.stackblitz.io

The issue is on my code base.
Thanks.
