### ISSUE TITLE
EntityStore - Entities with ID 0

### ISSUE THREAD

**Issue by danzrou** [datorama/akita#7]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x ] Other... Please describe: Question
</code></pre>

## Current behavior
As I did not find related information in documentation, I'm not sure whether it was designed like this on purpose or not.
EntityStore removes all entities when entity id is 0.
In my case I have entities which are generated in app when the id is a sequence starting from 0.
I have modified it to start from 1 but brought this up only for your attention.

I guess its because of the following where `id ?` returns false

```
remove(id?: ID | ID[], resetActive?) {
    if (!toBoolean(id)) this.setPristine();

    const ids = id ? coerceArray(id) : null;
    this.setState(state => _crud._remove(state, ids, resetActive));
  }
```

Version 1.1.0

**Comment by NetanelBasal** [comment]
This a bug. Thanks. I will release a fix in 15min.

**Comment by NetanelBasal** [comment]
You can download v1.1.1. Thanks for the report.
