### ISSUE TITLE
Persiststate and Pristine

### ISSUE THREAD

**Issue by chronicbint** [datorama/akita#70]
[x ] Support request

When using persist state should the store not be set to pristine false, as its restored data from (in this case) local storage.

**Comment by NetanelBasal** [comment]
What is the motivation for this behavior?

**Comment by chronicbint** [comment]
We store various UI states, when the user refreshes the site I want to check if the store has data, if not I set some defaults. This is persisted in local storage and reloaded to state but the pristine flag is still true, even though its been restored from local storage to the store.

**Comment by NetanelBasal** [comment]
Sounds like the correct behavior.

**Comment by chronicbint** [comment]
surely its not pristine as its been loaded from local storage.......I can code around it.

**Comment by NetanelBasal** [comment]
Fixed in 1.8.4, thanks.
