### ISSUE TITLE
error(npm): No matching version found for @datorama/akita@^7.0.0.

### ISSUE THREAD

**Issue by eduardoRoth** [datorama/akita#702]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[X] Other... Please describe: NPM package version not found.
</code></pre>

## Current behavior

I see a commit for version 7.0.0 release, but the latest version for this package in npm is 6.2.0

## Expected behavior

Able to `npm install` version 7.0.0

**Comment by eduardoRoth** [comment]
![image](https://user-images.githubusercontent.com/5419161/123456532-9242b780-d5a8-11eb-8c2c-5554aaca0a21.png)
https://github.com/datorama/akita/commit/3750b8045e83a5373b458050643221b022af5dcb

**Comment by NetanelBasal** [comment]
This was a mistake. The last version is 6.2.0.
