### ISSUE TITLE
Not possible to have 2 "forFeature" effects - "second one wins"

### ISSUE THREAD

**Issue by david-bulte** [datorama/akita#703]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When having two modules that each register "Akita Effects" (AkitaNgEffectsModule.forFeature([]), the second one "wins".

## Expected behavior

When 2 modules register Effects, both Effects should be registered.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/akita-todos-app-fu1tww?file=src%2Fapp%2Fapp.module.ts

In the example application, both FilmsModule and TodosModule register effects (film.effects.ts and todo.effects.ts). When adding a todo via the GUI, both should log to the console. But only the Effect that is part of Module that was last imported is active.

**Comment by NetanelBasal** [comment]
I saw the code and you are right. We need to use the `multi` option [here](https://github.com/datorama/akita/blob/master/libs/akita-ng-effects/src/lib/akita-ng-effects.module.ts#L36).
