### ISSUE TITLE
Allowing different sorting strategies based on state

### ISSUE THREAD

**Issue by DmitryEfimenko** [datorama/akita#71]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently, you can configure how to sort your data by providing a sort function either in the `@QueryConfig` or in `select` query options.
That's awesome, but what if there is a case when you'd want to provide a custom sorting logic based on state. An API that would allow this would look something like this:
```
const sortBy: SortBy<CategoriesState, ICategory> =
   (state) => (a, b) => state.sortByOrderNum ? (a.orderNum - b.orderNum) : a.name.localeCompare(b.name);
@QueryConfig({ sortBy })
```

Unfortunatelly I don't see how such change could be made via a non-breaking change as it's changing the `SortBy` interface.

## What is the motivation / use case for changing the behavior?

Make Akita more flexible

**Comment by DmitryEfimenko** [comment]
Initially, that's almost exactly how I implemented this logic. Except that this logic was inside a custom query method (because I like my components slim):
```
@Injectable({ providedIn: 'root' })
export class CategoriesQuery extends QueryEntity<CategoriesState, ICategory> {
  constructor(
    protected store: CategoriesStore,
    private itemsQuery: ItemsQuery
  ) {
    super(store);
  }
  
  selectCategoryItems() {
	return return combineLatest(
	  this.selectAll(),
	  this.select(s => s.ui.isCustomSort)
	).pipe(([categories, isCustomSort]) => {
	  if(isCustomSort) {
	    categories.sort(mySortingFunction)
	  }
	  return categories;
	})
  }
}
```
but then I found out about `sortBy` option and though that using it would reduce quite a lot of builerplate. If only it allowed access to the state...

**Comment by oleersoy** [comment]
Good point.  Something like:

```
let todos$ = store.observeSorted(comparator);
```
Would be a lot shorter.

**Comment by NetanelBasal** [comment]
@DmitryEfimenko we can change the signature of the SortBy function and don't introduce a breaking change.

export type SortBy<E, S> = ((a: E, b: E, state?: S) => number) | keyof E;

**Comment by DmitryEfimenko** [comment]
you're right.
In this case it looks like the signature of [toArray](https://github.com/datorama/akita/blob/bd811e0f1b136e1401f4a7c45648ca24c2a353b2/akita/src/api/query-entity.ts#L227) function will change to take entire state instead of `ids: ID[], entities: HashMap<E>`. Does that sound right to you, @NetanelBasal ?

I could take a stab at this if you do not have objections.

**Comment by NetanelBasal** [comment]
Yes, that's okay, it's internal method. You can create a PR, thanks.

**Comment by DmitryEfimenko** [comment]
@NetanelBasal Can I get a 🤔 badge? :)

**Comment by oleersoy** [comment]
I think it's badge worthy.

**Comment by NetanelBasal** [comment]
@DmitryEfimenko Of course, which budge?

**Comment by DmitryEfimenko** [comment]
The badge that goes in under the Contributor name on [this page](https://github.com/datorama/akita). It's titled "Ideas, Planning, & Feedback". It looks like 🤔.

**Comment by NetanelBasal** [comment]
No problem.
