### ISSUE TITLE
akita-ng-forms-manager tslib 1.10 dependency

### ISSUE THREAD

**Issue by dipanshu2dj** [datorama/akita#710]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe: package dependency update
</code></pre>

## Current behavior
npm WARN Found: tslib@2.3.0
npm WARN node_modules/tslib
npm WARN   dev tslib@"^2.2.0" from the root project
npm WARN   12 more (@angular/compiler-cli, @angular/compiler, ...)
npm WARN
**npm WARN Could not resolve dependency:
npm WARN peer tslib@"^1.10.0" from @datorama/akita-ng-forms-manager@5.0.2**
npm WARN node_modules/@datorama/akita-ng-forms-manager
npm WARN   @datorama/akita-ng-forms-manager@"^5.0.2" from the root project

## Expected behavior
After upgrading my project to Angular 11, the tslib dependency has 2.2.0 but the akita-ng-forms-manager still has dependency on v1.10.0. Though I am able to perform npm install using --force but I am not sure if it would break anything.
I see akita dependency has already been updated to "^2.0.0".

## Minimal reproduction of the problem with instructions

Angular 11 package.json with akita dependencies.

## Environment

<pre><code>
Angular version: 11.2.14

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows 

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
This library is deprecated. I recommend migrating to [ngneat/forms-manager](https://github.com/ngneat/forms-manager/)
