### ISSUE TITLE
Migration to rxjs 7 fails with akiga-ng-router-store

### ISSUE THREAD

**Issue by mhosman** [datorama/akita#711]
`Package "@datorama/akita-ng-router-store" has an incompatible peer dependency to "rxjs" (requires ">= 6.1.0 < 7", would install "7.2.0").`

× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "............\angular-errors.log" for further details.

**Comment by NetanelBasal** [comment]
Are you using version 7 even though Angular has not yet been upgraded?

**Comment by mhosman** [comment]
Right now I'm using Rxjs version 6.6.7 with Angular 12. Trying to update to Rxjs 7.2.0, the only library that display that error is akita-ng-router-store.

**Comment by simeyla** [comment]
@NetanelBasal Angular 12.2.0 is now officially compatible with v7. But it is still opt-in.

https://twitter.com/BenLesh/status/1423262299880673284?s=20

I'm seeing errors like this:   

`Type 'import("S:/tfs/rr/Defender.NG/node_modules/@datorama/akita/node_modules/rxjs/internal/Observable").Observable<any>' is not assignable to type 'import("S:/tfs/rr/Defender.NG/node_modules/rxjs/dist/types/internal/Observable").Observable<any>'.
`

Do you have advice yet on how to handle this? I'm going to roll back for now.

**Comment by NetanelBasal** [comment]
Update to the latest version.
