### ISSUE TITLE
question: akita having an old @schematics/angular dependency?

### ISSUE THREAD

**Issue by david-bulte** [datorama/akita#718]
Hi, I have a weird problem - not sure whether it is related to akita though.

My "component generator" does not work anymore, I get schema validation errors ("Schematic input does not validate against the Schema"). This problem has started after upgrading to angular 12/NX 12.5.8. Hence I also asked for information at the NX repo ([https://github.com/nrwl/nx/issues/6420](https://github.com/nrwl/nx/issues/6420)).

When I "npm list @schematics/angular", I get the following result:

![image](https://user-images.githubusercontent.com/4194465/126315752-49ef7961-ea74-40da-9989-088ceccebd5a.png)

It seems akita is using an older version, and somehow when I run the schematic, it is using the akita dependency (not that I have specified to do that in angular.json).

*When I remove akita, I do not get the issue, and I can generate components with the schematic without a problem!*

### Environment

angular: ~12.1.2
nx: 12.5.8
"@datorama/akita": "^6.2.1",

### Steps to recreate (copied from the NX ticket):

After removing akita, listing @schematics/angular looks like so:

![image](https://user-images.githubusercontent.com/4194465/126313979-021316c3-42b2-4a70-952d-ace88b6ab2c9.png)

node_modules does *not* contain an entry @schematics/angular:

![image](https://user-images.githubusercontent.com/4194465/126314025-f4698006-2cac-4dd4-874d-d8cfcf081ab9.png)

ng g component *does* work, nx generate @nrwl/angular:component not:

![image](https://user-images.githubusercontent.com/4194465/126314097-16fe95ad-a39c-4952-b88d-ac44a886c983.png)

After reinstalling akita, ng generate and nx generate do not work, both give the same error:

![image](https://user-images.githubusercontent.com/4194465/126314221-56550591-57cc-4ff1-a048-8de02ab358b6.png)

And npm list gives the following result:

![image](https://user-images.githubusercontent.com/4194465/126314584-4d0730c0-d537-4c02-86ce-e21701b88f7d.png)

Notice the old schematics version underneath akita.

node_modules *does* now contain the @schematics/angular package:

![image](https://user-images.githubusercontent.com/4194465/126314388-ffef4d57-fc9d-47e4-a059-0f4d19811da9.png)

*Its component/schema.json file is an old file, it contains old attributes like styleext, entrycomponent etc...*

So I assume now that somehow the akita schematics dependency precedes the NX dependency? But how come initially there is no @schematics/angular package in node_modules, that one is only there after installing akita?

**Comment by david-bulte** [comment]
Closing the issue for now, seems to be related to NX.

**Comment by yonzmeer** [comment]
@david-bulte did you find out why this is happening? 
I have the same issue.
Installing akita forces me to use @angular-devkit/schematics@8.3..

**Comment by charitharumapperuma** [comment]
Adding a custom package resolution worked for me. This will be a workaround until `schematics-utilities` library updates to newer `@schematics/angular` version. (`@datorama/akita` uses `schematics-utilities` as a direct dependancy)

Add following to `package.json` file and the run `yarn install`.

```
package.json
{
    ...
    "resolutions": {
        "@datorama/akita/schematics-utilities/@schematics/angular": "14.0.5"
    }
}
```

> PS: I tested with Angular 14.0.5, Akita 7.1.1, Nx 14.4.2
