### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by carlosvpp** [datorama/akita#72]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

What is the best way to include a store for a component that is going to be reused on different parts in the application and even coexist on the same view? I have a dashboard component that allows the user to create different kind of widgets. A store comes in handy to manage all the different actions and errors. However it kind of feels like I cannot do it with Atika.

**Comment by NetanelBasal** [comment]
I'm not sure I understand your needs. In most cases, stores are singletons, so you'll have one instance per application. What is the problem?

**Comment by carlosvpp** [comment]
I want to create a component, for instance a Dashboard to show widgets, and reuse it multiple times through out the application. However, the component has a store with a particular name and I was wondering if this would cause some kind of conflict. Maybe I'm just confuse by the way ngrx works, where you have a global state and every store/state needs to have unique names. 

This is the application structure that I'm thinking of.

Generic dashboard component:
- module
- services
- view
- state -> store (name: 'dashboard')


Application
 - view 1 -> uses a dashboard component
 - view 2 -> uses a dashboard component

**Comment by NetanelBasal** [comment]
You can use the **same** store throughout your application.

**Comment by mohanramphp** [comment]
In State Machine concept, like Flux, Redux, Akita or anywhere. Store is always be singleton. Consider it as the blueprint of the whole data your application needs to facilitate the UI.

Can you explain in granular level, your use case? 

**I hope, if i understood correctly. Your schema for dashboard widget is same but data model for that schema differs based on the usage of the component.**

Then, create different entity under its parent context.

```javascript 
const appModel = {
    dashboard: {
        chart: {
            ...
        }
    },
    user: {
        chart: {
            ...
        }
    }
}

**Comment by ciesielskico** [comment]
You should have one DashboardStore, and differentiate the different component states by some id

**Comment by NetanelBasal** [comment]
Closing this for now, if you have any further questions, let us know.
