### ISSUE TITLE
NG2007 error when running angular-store-app

### ISSUE THREAD

**Issue by m-ghaoui** [datorama/akita#724]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The angular-store-app does not run because of this error:

```
Error: ../../libs/akita/src/lib/store.ts:48:14 - error NG2007: Class is using Angular features but is not decorated. Please add an explicit Angular decorator.
```

## Expected behavior

The app runs without any errors.

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

* Clone the repo
* `cd .\apps\angular-store-app` (I'm on Windows+Powershell)
* `yarn global add @nrwl/cli`
* `yarn install`
* `nx serve angular-store-app`

Here is the output:

* https://gist.githubusercontent.com/m-ghaoui/c5b0b41aa5e919573dff5bb538055cb4/raw/79dc46012b8b5eb60d59c62918f77c9967ffa144/gistfile1.txt

## What is the motivation / use case for changing the behavior?

Evaluating Akita for my next project.

## Environment

<pre><code>
> ng --version

Angular CLI: 12.1.4
Node: 14.17.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.5
@angular-devkit/core         11.0.5
@angular-devkit/schematics   10.1.7
@schematics/angular          8.3.29

Browser:
N/A
 
For Tooling issues:
- Node version: 14.17.3  
- Platform:  Windows

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Add the Injectable decorator to the Store class.

**Comment by m-ghaoui** [comment]
I added a pull request for this: #726
