### ISSUE TITLE
Collection (collection.json) cannot be resolved

### ISSUE THREAD

**Issue by fstodulski** [datorama/akita#728]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

After running `ng add @datorama/akita` I'm getting this error

`An unhandled exception occurred: Collection "node_modules/@datorama/akita/schematics/collection.json" cannot be resolved.`

## Expected behavior

It should install all schematics.

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

1. `ng new <name>`
2. `ng add @datorama/akita`

## Environment

<pre><code>
@angular-devkit/architect       0.1202.0
@angular-devkit/build-angular   12.2.0
@angular-devkit/core            12.2.0
@angular-devkit/schematics      12.2.0
@schematics/angular             12.2.0
rxjs                            6.6.7
typescript                      4.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.17.0  
- Platform:  MacOS

Others:

</code></pre>

**Comment by nagashimam** [comment]
The same happens to me as well. 

## environment

```
@angular-devkit/architect     0.1202.0 
@angular-devkit/build-angular 12.2.0 
@angular-devkit/core          12.2.0 
@angular-devkit/schematics    12.2.0 
@schematics/angular           12.2.0 
rxjs                          7.3.0 
typescript                    4.3.5 

For Tooling issues:
- Node version: v12.17.0
- Platform:  MacOS

```

**Comment by ernestomar** [comment]
I've the same problem, but I solved downgrading Akita version:

```
npm uninstall  @datorama/akita
ng add @datorama/akita@6.1.3
```

**Comment by NetanelBasal** [comment]
@ernestomar from which version?

**Comment by fstodulski** [comment]
@NetanelBasal 
It seems to be some issue with lates version. 
I worked with `ng add @datorama/akita@6.1.2`

**Comment by nullcast** [comment]
I had the same problem with v6.2.2.
It worked fine with v6.1.3.

**Comment by NetanelBasal** [comment]
We'll check it soon.

**Comment by NetanelBasal** [comment]
Please try v6.2.3.
