### ISSUE TITLE
[Documentation] best-practices / ui

### ISSUE THREAD

**Issue by kovalforpublic** [datorama/akita#729]
## I'm submitting a...

<pre><code>
[+] Bug report
</code></pre>

## Current behavior
After visiting this [link](https://datorama.github.io/akita/docs/best-practices/ui)  , I saw "not found" page

## Expected behavior
 To see page about separation between ui and model. 

## Minimal reproduction of the problem with instructions
Go to the link https://datorama.github.io/akita/docs/best-practices/ui

## What is the motivation / use case for changing the behavior?
 More expressive documentation 
 
 
<img width="707" alt="Screenshot 2021-08-08 at 14 45 12" src="https://user-images.githubusercontent.com/61496807/128630904-9c8c4752-82ab-4ac0-80b9-c531ba721b8b.png">

**Comment by NetanelBasal** [comment]
https://datorama.github.io/akita/docs/ui
