### ISSUE TITLE
[NgEntityService] Support Observable in HttpConfig.mapResponseFn

### ISSUE THREAD

**Issue by snebjorn** [datorama/akita#730]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

It's currently defined as `mapResponseFn?: (res: any) => Entity | Entity[];`

## What is the motivation / use case for changing the behavior?

It would be handy if it could work with observables `mapResponseFn?: (res: any) => Entity | Entity[] | Observable<Entity | Entity[]>;`

That would allow for enriching the response with "async" data. I.E. data from a Web API. Before it's written to the Store.

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by snebjorn** [comment]
Sure, should be easy enough :)

**Comment by snebjorn** [comment]
@NetanelBasal when is the next release planned? Would be nice to have this feature :)

**Comment by NetanelBasal** [comment]
Today

**Comment by NetanelBasal** [comment]
Done
