### ISSUE TITLE
injected persistStorage with multi-key persist returns an array instead of an object

### ISSUE THREAD

**Issue by Maryannah** [datorama/akita#731]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[X] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When implementing the persist state feature and using different keys for each store (see https://datorama.github.io/akita/docs/enhancers/persist-state#separate-branch-in-storage), the injected persistStorage is transformed into an array of elements, which are non-distinctible from each other, whereas using a single-key storage persist returns directly an object : 

![image](https://user-images.githubusercontent.com/46892394/129741714-23187358-2b4f-4489-820d-c9e566f64698.png)

Having migrated from a single-key persist to a multi-key, it makes all of our code unusable since functions like "clearStore" are not accessible directly anymore.

## Expected behavior

A single objet for the persist state should be returned, or an object with keys corresponding to the store names, or an array of objects with at least a "id" key corresponding to a store name.

(I would say the first solution, since one has to use a store name for functions like "clearStore")

Otherwise, maybe I didn't read the documentation properly, although I spent a lot of time looking for the solution, so I would argue that it is missing ? In that case, simply adding it would be enough already !

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-ivy-ecrwqx?file=src%2Fapp%2Fapp.service.ts

Open the console to see the logs. See "app.service.ts" and "app.module.ts" (you can also see the stores in the "stores/" folder, but they're dummy)

## What is the motivation / use case for changing the behavior?

Being able to use the same API, no matter the number of keys used to persist stores in the storage.

## Environment

Everything can be seen on stackblitz

(PS : Akita is awesome nontheless, keep up the goog work !)

**Comment by NetanelBasal** [comment]
You don't have to use the same `key` and `multi. There is nothing special here. We are using DI.

```ts
const providers = [
  { provide: 'settingsPersistStorage', useValue: settingsPersistStorage },
  { provide: 'usersPersistStorage', useValue: usersPersistStorage },
];
```.`

**Comment by Maryannah** [comment]
Noted, maybe you should update the documentation accordingly ? 

![image](https://user-images.githubusercontent.com/46892394/129855094-534ffe81-3303-41a8-b1e7-44af07134491.png)

**Comment by NetanelBasal** [comment]
I will. Thanks
