### ISSUE TITLE
select a piece of store doesn't work if this piece is an object

### ISSUE THREAD

**Issue by HuynhVuong87** [datorama/akita#738]
it works on first action when i check checkbox. If i continue check or uncheck then it doesn't work

please check this stackblitz
https://stackblitz.com/edit/angular-ivy-wbxvso?file=src%2Fapp%2Fapp.component.ts

**Comment by NetanelBasal** [comment]
You are not immutable.

this.settingsStore.update({hiddenSettings: { ...this.hiddenSettings }})
