### ISSUE TITLE
select() and selectAll() don't have the same behavouir

### ISSUE THREAD

**Issue by RobinVdBroeck** [datorama/akita#743]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ X ] Other... Please describe: Disscusion
</code></pre>

## Current behavior
`select('selector')` starts at the root store. 

Example `select('foo')` on a store with pseudo-value:
 `{
  foo: 0,
  entities: [{
    key: 'foo',
   value: 1
  }]
}` will return 0.

However, `selectAll({limitTo: 1, filterBy: (entity) => entity.key=== 'foo'}).pipe(pluck('value')` will return 1.

If you want the expected behavouir, you need to use `selectEntity`.

## Expected behavior

Either `select` should start at 'entity' level, or `selectAll()` should be renamed to `selectAllEntities()` to make it clear we are talking about entities. 
This makes it clear that code like `this.selectAll({limitTo: 1, filterBy: (entity) => entity.key=== 'foo'}).pipe(pluck('value')` cannot be simplified to this.select('foo').

## What is the motivation / use case for changing the behavior?

We had a real life bug because of this. The api is not clear.

**Comment by NetanelBasal** [comment]
`selectAll` exists only in the entity store, and returns an array. The usage of pluck doesn't make sense in this case.

**Comment by RobinVdBroeck** [comment]
It doesn't make sense that `selectAll({limit: 1})` and `select()` don't behave the same way.

**Comment by NetanelBasal** [comment]
`selectAll` returns the entities collection. `select()` returns a specific slice from the store.

**Comment by RobinVdBroeck** [comment]
> `selectAll` returns the entities collection. `select()` returns a specific slice from the store.

That is not clear for a consumer of the api. Akita should adhere to the principle of least suprise.

Another "solution" would be to have select more strictly typed. Akita should know which store interface it is querying, so it should be able to typecheck that it exists. Ie, in pseudocode:

```
interface Store {
  bar: string;
  delta: number;
}
const store: Store = {
  bar: 'x',
  delta: 2
};
store.select('foo'); <-- this can be a compile error, since we know 'foo' is not a key of store (which is 'bar' | 'delta')
```
