### ISSUE TITLE
Class support not working as expected

### ISSUE THREAD

**Issue by Langstra** [datorama/akita#746]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Class support is described here: https://datorama.github.io/akita/docs/additional/class 

It specifies how to use classes inside your stores. Which should not be much more than the `class` that has a `constructor` that accepts 1 argument. 

The issue here is that the query still returns plain json objects instead of class instances.

## Expected behavior

That the query returns class instances.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/github-ap9zbd

Uncommenting the `akitaPreAddEntity` hook fixes the problem, but this is not the way the documentation specifies it.

## What is the motivation / use case for changing the behavior?

I'd like to use classes because they can have methods that'd like to use.

## Environment

<pre><code>
Angular version: 12.2.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version 93.0.961.38 
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Where do you create the Post instances?

**Comment by NetanelBasal** [comment]
I know see that the docs is misleading. It'll do it for you when using `update/upsert`. When you call `add/set`, you should create it manually.

**Comment by NetanelBasal** [comment]
The docs was updated. Thanks.
