### ISSUE TITLE
Add the ability to call backend when cache is empty

### ISSUE THREAD

**Issue by pavankjadda** [datorama/akita#747]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
At present we need to check if query has cache, if not we need make a call to back end manually. See below snippet. 

```
  findAllLanguages(url: string): Observable<Language[]> {
    if (this.languageQuery.getHasCache()) {
      return this.languageQuery.selectAll();
    } else {
      const request$ = this.httpClient.get<Language[]>(url).pipe(tap(languages => this.languageStore.set(languages)));
      return cacheable(this.languageStore, request$);
    }
  }
```

## Expected behavior
The above code is redundant across all services and can be avoided if Akita can check cache and call back end if data does not exist in cache. See the [RTK Query implementation](https://redux-toolkit.js.org/rtk-query/usage/cache-behavior#cache-lifetime--subscription-example). 
> When a request is attempted, if the data already exists in the cache, then that data is served and no new request is sent to the server. Otherwise, if the data does not exist in the cache, then a new request is sent, and the returned response is stored in the cache.

## Minimal reproduction of the problem with instructions
See the [RTK Query implementation](https://redux-toolkit.js.org/rtk-query/usage/cache-behavior#cache-lifetime--subscription-example).

**Comment by pavankjadda** [comment]
@NetanelBasal any plans to add this?

**Comment by NetanelBasal** [comment]
You're welcome to create a PR
