### ISSUE TITLE
Console warnings about deprecated id field when I run schematics

### ISSUE THREAD

**Issue by Den-dp** [datorama/akita#762]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
```
>  ng g af todos/todos
"SchematicsAkitaFeature" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"SchematicsAkitaFeature" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
? What type of service do you want to use? Default
"SchematicsAkitaStore" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"SchematicsAkitaQuery" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"SchematicsAkitaService" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"SchematicsAkitaModel" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
CREATE src/app/todos/state/todos.store.ts (378 bytes)
CREATE src/app/todos/state/todos.query.ts (313 bytes)
CREATE src/app/todos/state/todos.service.ts (727 bytes)
CREATE src/app/todos/state/todo.model.ts (129 bytes)
```

## Expected behavior
no warnings

## Minimal reproduction of the problem with instructions

```
npm i @angular/cli@12 -g
ng new app --minimal --defaults
cd app
ng add @datorama/akita
ng g af todos/todos
```

## What is the motivation / use case for changing the behavior?
Better DX while running `ng g af todos/todos`.

## Environment

<pre><code>
Angular version: 12.2.12

For Tooling issues:
- Node version: v14.18.1
- Platform:  Windows
</code></pre>

**Comment by Den-dp** [comment]
Looks like related to this change in @angular-devkit/core https://github.com/angular/angular-cli/pull/20482 https://github.com/angular/angular-cli/commit/08753138d336fb870a66face70f5624ba64b4c69

**Comment by plamenNachevICB** [comment]
I have the same issue and posted in the angular github.
https://github.com/angular/angular-cli/issues/22202

Using the `npm ls @schematics/angular` command leads to the culprit.

It turn's out that Akita have a dependency on `schematics-utilities@2.0.3`, which has a dependency on `schematics\angular@8.3.29`, that is 5 major versions behind. This needs to be addressed in order for the angular CLI to work again.

**Comment by Den-dp** [comment]
@plamenNachevICB I think this is not really related, since schema.json files really use `id`
https://github.com/datorama/akita/blob/7b594cf22a9a41bf4717177c34cd361e3c6646ca/libs/akita-schematics/src/ng-g/feature/schema.json#L1-L3
and should be migrated to `$id` according to https://github.com/angular/angular-cli/pull/20482

But what you found is the root of another issue described here https://github.com/datorama/akita/issues/727

**Comment by NetanelBasal** [comment]
Should be OK in v7.
