### ISSUE TITLE
getValue() does not return correct value from a Query

### ISSUE THREAD

**Issue by brice-noowu** [datorama/akita#769]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior

If for example I create a query like `getFooValue= this.getValue().ui.foo;` in a `bar.query.ts` file

If I use this query inside a component, I will not get the current value of `foo` but instead I will get it's **initial value** that I have set inside `bar.store.ts constructor => super(initialUiFooState)`.

But if instead I directly call `this.getValue().ui.foo;` in the component, I will get the actual and correct `foo` value.
  
## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/akita-todos-app-udpkw8?file=src/app/todos/todos-page/todos-page.component.ts

Clicking on  "Incorrect foo value" will show the initial `foo` value.

Clicking on "Correct foo value" will show the current and correct `foo`  value.

(`foo` has been updated in `ngOnInit `from "Hello" to "World")

## What is the motivation / use case for changing the behavior?

I would like to use a query for things like `this.getValue().ui.foo;` and not have to use it directly within components or services.

## Environment

<pre><code>
Angular version: 12.1.3

**Comment by NetanelBasal** [comment]
That's how JS works.

**Comment by brice-noowu** [comment]
Sorry that was dumb. Thank you for explaining 👍
