### ISSUE TITLE
Support Request / Use Case possible with akita? Best way to do it?

### ISSUE THREAD

**Issue by MRisto** [datorama/akita#78]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?
Changing from ngrx to akita and make it more structured / simple

## Environment

<pre><code>
Angular version: 6.1.4
</code></pre>

## Question
Hi, I saw many blog posts about akita. I really love the struture of it. We faced some of your issues you wrote in one of your blog-posts. Akita looked promising and we are evaluating, if akita is the way to go for us.

### Use Case
The problem we are facing is, that our data is dynamic and not strictly bound to a structure. So we needed to develop a structure, which we can use to access data, but which is not that strict so we can extend it. I think it is better to show an quick overview.
We have collections. Each collection has a schema, which defines the structure of the items in the collection.

Here is an example structure
<pre><code>
Collections
    | - Materials // (dynamic collection)
    |     | - schema : Schema
    |     | - items // Object
    |     |    | - list : {[itemId:string]:Item} // Object containg all the items key is the itemId ( customId, is unique)
    |     |    |    | - exampleItem // Object
    |     |    |          | - major : Item  // latest major version
    |     |    |          | - last : Item     // latest version (minor)
    |     |    |          | - versions : Item[]  // index is the item version
    |     |    |          | - fullyLoaded : boolean // if the item loaded with all versions, sometimes only the last version was loaded
    |     |    | - fullyLoaded : boolean // if all items where loaded (even if only last versions loaded)
    |     |    | - majorItems : Item[] // reference to the major item (of the list)
    |     |    | - latestItems : Item[] // references to the latest Items   
    | 
    | - Components
    |     | - ...
    |
    | - otherCollection...
</code></pre>

### Main Goals
1. Only  update queries, when something changed. // should be good, because of distinctUntilChanged() 
2. Convenient Queries on all different depths
2.1. majorItem(collectionName, itemId)
2.2. lastItem(collectionName, itemId)
2.3. majorItems(collectionName) //only update, when the array changes -> reference changes, if any changes happen
2.4. majorItems(collectionName) // like 2.3.
2.5 schema(collection) //get the schema
3. Dynamic Queries ( Parameter as FilterFunction)

You provide two different stores. I think for this example the EntityStore wouldnt fit. 

### Questions
1. Is this possible with the Store? To implement the main goals with the example structure?
2.  Is it bad to save the references in an array? (majorItems and latestItems) Or should i save the itemId? -> Then i have too loop through the array and get every majorItem. If i save the reference, i only have to change it, when i update. But the read performance is better. And the overhead by the references should be really small.
3. For the feature we wanted to build dynamic queries. I think this is possible, if we pass the filter as param to the query

Thanks for your help and for any advise.

**Comment by NetanelBasal** [comment]
The basic store is perfect for a dynamic structure. I do not recommend to do **premature optimization**. Browsers are highly optimized to deal with for loops.  The Query gives you all the flexibility that you need.

**Comment by MRisto** [comment]
Thanks for your quick response and help.
But you wouldnt use `forEach` loops?

**Comment by MRisto** [comment]
Yeah, im working on that. I saw akita just a few days ago. So im trying stuff out. But pretty nice module you guys developed. Thanks for your work.

**Comment by MRisto** [comment]
So im working on the store. But i think i didn't understand it that well.

I want to inizialize the item with all the schemas and collections. That worked like a charm. After that im loading all the latest items. So I want to update the latest items.

But i can not only update parts of the store.I get the following errors.
```javascript
TypeError: Cannot add property 5b322b5bea48b02e08e1e564, object is not extensible. 
```

It occurs in the itemsService Part of the code.
```javascript
       const itemDataStructure: ItemDataStructure = {
                    last: item,
                    major: undefined,
                    fullyLoaded: false,
                    versions: [],
                };
                state.collections[collectionName].items.list = {
                    ...state.collections[collectionName].items.list,
                };
                state.collections[collectionName].items.list[item.meta.itemId] = itemDataStructure;
```
This is nice, that you made it like that. 

1. But how can i change something there without createing the whole object new ( From top to down). Then every reference would change and distinctUntilChanged wouldnt work. Or am I missing something?
2. So if a component subscribes to a query, and the component changes the state it gets the same error? That would be nice.

Thank you for your help. I really appreciate it.


Files
### Model

```javascript
export declare type ItemId = string;

export interface Collections {
    [collectionName: string]: Collection;
}

export interface Collection {
    schema: Schema;
    items: ItemsDataStructure;
}

export interface ItemsDataStructure {
    list: ItemsList;
    fullyLoaded: boolean;
    majorItems: ItemId[];
    latestItems: ItemId[];
}

export interface ItemsList {
    [itemId: string]: ItemDataStructure;
}

export interface ItemDataStructure {
    last: Item;
    major: Item;
    versions: Item[];
    fullyLoaded: boolean;
}
```

### Store
```javascript
import {Injectable} from '@angular/core';
import {Store, StoreConfig} from '@datorama/akita';
import {Collections} from "@app/modules/collections/state/collections.model";

export interface CollectionsState {
    collections: Collections;
    isInitialized: boolean;
}

export function createInitialState(): CollectionsState {
    return {
        collections: {},
        isInitialized: false,
    };
}

@Injectable({providedIn: 'root'})
@StoreConfig({name: 'collections'})
export class CollectionsStore extends Store<CollectionsState> {

    constructor() {
        super(createInitialState());
    }

}
```

### CollectionsService
```javascript
import {Injectable} from '@angular/core';
import {ID} from '@datorama/akita';
import {CollectionsStore} from './collections.store';
import {HttpClient} from '@angular/common/http';
import {Schema} from "@meddevo/shared";
import {Collection, Collections, ItemId, ItemsList} from "@app/modules/collections/state/collections.model";

@Injectable({providedIn: 'root'})
export class CollectionsService {

    constructor(private collectionsStore: CollectionsStore,
        private http: HttpClient) {
    }

    initializeCollections(schemas: Schema[]) {
        this.collectionsStore.setState((state) => {
            const collections: Collections = {};
            schemas.forEach((schema) => {
                const items = {
                    list: {},
                    fullyLoaded: false,
                    majorItems: [],
                    latestItems: [],
                };
                collections[schema.collectionName] = {schema: schema, items: items};
            });
            console.log("im here");
            return {
                collections,
                isInitialized: true,
            };
        });
    }
}
```

### Items Service
```javascript
import {HttpClient} from "@angular/common/http";
import {Injectable} from '@angular/core';
import {ItemDataStructure} from "@app/modules/collections/state/collections.model";
import {CollectionsStore} from "@app/modules/collections/state/collections.store";
import {Item} from "@meddevo/shared";

@Injectable({providedIn: 'root'})
export class ItemService {

    constructor(private collectionsStore: CollectionsStore,
        private http: HttpClient) {
    }

    initializeLastItems(collectionName: string, items: Item[]) {
        this.collectionsStore.update((state) => {
            items.forEach(item => {
                const itemDataStructure: ItemDataStructure = {
                    last: item,
                    major: undefined,
                    fullyLoaded: false,
                    versions: [],
                };
                state.collections[collectionName].items.list = {
                    ...state.collections[collectionName].items.list,
                };
                state.collections[collectionName].items.list[item.meta.itemId] = itemDataStructure;
                itemDataStructure.versions[item.meta.v] = item;
            });
            return state;
        });
    }
}
```

**Comment by MRisto** [comment]
Ok. If I understand it right, then every object from top to bottom changes,but not the other leaps of the tree. So when I query something from this only the changing objects will update, because the select uses distinctUntilChanged. But not if i query an other collection, because that object references did not change. I hope i described my question right.

**Comment by NetanelBasal** [comment]
Yes, you are right.

**Comment by NetanelBasal** [comment]
Closing the issue. If you have any further questions, let me know. (netanel.basal@datorama.com)
