### ISSUE TITLE
Collection cannot be resolved

### ISSUE THREAD

**Issue by brice-noowu** [datorama/akita#788]
### Is this a regression?

Yes

### Description

Installing Akita from `ng add` throw `An unhandled exception occurred: Collection "C:\\...\\...\\test-akita\\node_modules\\@datorama\\akita\\schematics\\collection.json" cannot be resolved.`

Tried this on a fresh install, right after initial npm dependencies installation :

![image](https://user-images.githubusercontent.com/49209525/149132320-c2cf3aec-e91a-4063-8c0b-ed5b297c7022.png)

### Please provide a link to a minimal reproduction of the bug

`ng new test-akita && cd test-akita && ng add @datorama/akita`

### Please provide the exception or error you saw

```true
An unhandled exception occurred: Collection "C:\\...\\...\\test-akita\\node_modules\\@datorama\\akita\\schematics\\collection.json" cannot be resolved.
```

### Please provide the environment you discovered this bug in

```true
Angular 13.1.1
Akita 7.1.0
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Should be ok now.
