### ISSUE TITLE
Unit testing example

### ISSUE THREAD

**Issue by b-hobbs** [datorama/akita#79]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

There are a lot of great examples of using Akita but none seem to implement any sort of testing. It would be nice to have an example of unit tests with one of the example projects. It doesn't look like the akita-schematics creates any test files (correct me if i'm wrong I haven't actually used it), would you say testing the actual state pieces are unnecessary? What do you think are the best practices for testing with Akita?

**Comment by NetanelBasal** [comment]
Actually, we've implemented testing files with schematics, but there was a bug in @angular-cli that prevented us from using it. I will try to check again.

You need to test only the custom store methods and mock the places you're using the query, for example, components.

I'll update the docs soon with more examples and let you know. Thanks.

**Comment by NetanelBasal** [comment]
Updated the [docs](https://netbasal.gitbook.io/akita/unit-test/components) and added to schematics the [option](https://github.com/datorama/akita-schematics#generate-tests) to generate spec files.

If you have any further questions, let me know. Thanks.

**Comment by hjalmers** [comment]
Hi I tried to find an example on how to write unit tests when using [Ng Entity Service](https://netbasal.gitbook.io/akita/angular/ng-entity-service), but all I could find in the docs was [this ](https://datorama.github.io/akita/docs/angular/tests) which I can't get working with the Ng Entity Service. Perhaps a basic example could could be added to the docs? Would be really nice with one using Spectator:D
