### ISSUE TITLE
Localforage with datorama/Akita

### ISSUE THREAD

**Issue by 51303014** [datorama/akita#80]
I'm using akita version latest with localforage. I have an issue when I save data in localforage and refresh page and then in localforage have been clear data.
### This is my code localforage : 

```
import { Injectable } from '@angular/core'
import * as localforage from 'localforage'
import { Observable, from } from 'rxjs'
@Injectable()
export class LocalforageService {

  /**
   *
   * @param key
   * @param value
   * @returns {any}
   */
  public static setItem<T>(key: string, value: T): Observable<T> {
    return from(localforage.setItem(key, value))
  }

  /**
   *
   * @param key
   * @returns {any}
   */
  public static getItem<T>(key: string): Observable<T> {
    return from(localforage.getItem(key))
  }
}
```
**This is my code extends Entity**
```
 import { EntityStore, Store } from '@datorama/akita'
   import { LocalforageService } from './localforage.service'

export abstract class OfflineStore<S> extends Store<S> {
  protected constructor(private storageKey: string, initialState: S) {
    super(LocalforageService.getItem(storageKey) || JSON.stringify(initialState))
    this._select(s => s).subscribe(state => {
      LocalforageService.setItem(this.storageKey, JSON.stringify(state))
    })
  }
}

export abstract class OfflineEntityStore<S, E> extends EntityStore<S, E> {
  protected constructor(
    private storageKey: string,
    initialState?: {},
    options?: { idKey?: string },
  ) {
    super( LocalforageService.getItem(storageKey) || JSON.stringify(initialState), options)
      **// I think cause's _select function**
      this._select(s => s).subscribe(state => {
        LocalforageService.setItem(this.storageKey, JSON.stringify(state))
      })
  }
} 

```
When I refresh page I don't get data from state
When I console.log(state) which test and I see value of state = null.
Please help me fix it. 
Thanks

**Comment by NetanelBasal** [comment]
I can't understand anything. Can you format the code, please?

**Comment by NetanelBasal** [comment]
Also, you have a built-in plugin for this. Check out the [pesistState](https://netbasal.gitbook.io/akita/enhancers/persist-state) plugin.

**Comment by 51303014** [comment]
> I can't understand anything. Can you format the code, please?

Ok. I formatted code. Please help me fix it. 
Thanks

**Comment by 51303014** [comment]
> I can't understand anything. Can you format the code, please?

I use add function in EntityStore that insert data into localforage.
```
saveQuoteOffline(quoteId: string): Observable<void> {
    return zip(this.getQuotePdf(quoteId), this.getQuoteDetail(quoteId)).pipe(
      tap(() => {
        const quote = this.query.getEntity(quoteId)
        this.quoteOfflineStore.add(quote)
      }),
    )
  }
```
quoteOfflineStore extends OfflineEntityStore<QuoteOfflineState,Quote> 

Next step as above.
I able to use how to function that implement localforage when I extend the class in your akita library.

Please help me . Thank you !

**Comment by NetanelBasal** [comment]
Why are you not using the built-in [pesistState](https://netbasal.gitbook.io/akita/enhancers/persist-state) plugin? It does precisely this in one line of code.

**Comment by 51303014** [comment]
> Why are you not using the built-in [pesistState](https://netbasal.gitbook.io/akita/enhancers/persist-state) plugin? It does precisely this in one line of code.

Because my system has a lot of data so that I use a button on UI which save data if user wanna "Save offline" work offline.
If I use pesistState when app load. With a lot of data, I think localforage or web SQL will not enough usage that saved.

**Comment by NetanelBasal** [comment]
Here's the solution:

```ts
export class TodosQuery extends QueryEntity<State, Todo> {

  constructor(protected store: TodosStore) {
    super(store);
    this.saveToStorage();
  }

  saveToStorage() {
    this.select().subscribe(state => {
      localStorage.setItem('todosStore', JSON.stringify(state));
    })
  }

}

```

```ts
@StoreConfig({ name: 'todos' })
export class TodosStore extends EntityStore<State, Todo> {
  constructor() {
    super(initialState);
    this.loadFromStorage();
  }

  loadFromStorage() {
    const data = localStorage.getItem('todosStore');
    if (data) {
      this.setState(state => JSON.parse(data));
    }
  }
}

```

You can see it live [here](https://stackblitz.com/edit/akita-todos-app-td57hw).

**Comment by 51303014** [comment]
> Here's the solution:
> 
> ```ts
> export class TodosQuery extends QueryEntity<State, Todo> {
> 
>   constructor(protected store: TodosStore) {
>     super(store);
>     this.saveToStorage();
>   }
> 
>   saveToStorage() {
>     this.select().subscribe(state => {
>       localStorage.setItem('todosStore', JSON.stringify(state));
>     })
>   }
> 
> }
> ```
> 
> ```ts
> @StoreConfig({ name: 'todos' })
> export class TodosStore extends EntityStore<State, Todo> {
>   constructor() {
>     super(initialState);
>     this.loadFromStorage();
>   }
> 
>   loadFromStorage() {
>     const data = localStorage.getItem('todosStore');
>     if (data) {
>       this.setState(state => JSON.parse(data));
>     }
>   }
> }
> ```
> 
> You can see it live [here](https://stackblitz.com/edit/akita-todos-app-td57hw).

Ok. I see. Thank you very much!
