### ISSUE TITLE
Is it possible to publish an Ivy distribution?

### ISSUE THREAD

**Issue by JohanHeyvaert** [datorama/akita#802]
Hi,

We are using Akita and Angular 13. 
Everything works fine, I am only wondering why the CLI shows this info after a yarn install:

```
 >  NX   Angular CLI has been decorated to enable computation caching.

Processing legacy "View Engine" libraries:
- @datorama/akita [es2015/esm2015] (https://github.com/datorama/akita)
- @datorama/akita-ng-router-store [es2015/esm2015] (https://github.com/datorama/akita)
Encourage the library authors to publish an Ivy distribution.
```

Is this advice really relevant for Akita? If so, is this something you'll plan to do?
Any idea what are the consequences if this is not done? 

Thanks for your reply!

**Comment by Rush** [comment]
the consequence is that things will stop working by Angular 14 or smth. Also this is ugly as ngcc is modifying node_modules in-place.

**Comment by NetanelBasal** [comment]
Do you use v7? We've upgraded to ng13.

**Comment by JohanHeyvaert** [comment]
In the meantime, yes! I am sorry about this stupid question, we were unknowingly running behind and still using v6. 
Anyway, thanks for your reply, all is good know!

Also thank you for this fantastic library. 🥇
