### ISSUE TITLE
How to combine different query service

### ISSUE THREAD

**Issue by zverbeta** [datorama/akita#81]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

I have question about combine different query service for getting a value from unrelated modules.

For example i have AQuery, BQuery, CQuery. AQuery and BQuery a queries in unrelated modules, but CQuery needs part of data from AQuery, BQuery

Or it is better to combine different queries directly in the component (I think it worse)

Thank you!

**Comment by NetanelBasal** [comment]
Queries can inject other queries. For example:

```ts
export class AQuery extends QueryEntity {
  constructor(protected store: AStore, private bQuery: BQuery) {
    super(store);
  }

 selectSomthing() {
  // use the various RxJS operators
   return combineLatest(
      this.selectAll(),
      this.bQuery.selectActive()
   )
 }
}
```

**Comment by NetanelBasal** [comment]
You can learn more about it in the following article - [Working with Normalized Data in Akita and Angular](https://netbasal.com/working-with-normalized-data-in-akita-e626d4c67ca4).

If you have any further questions, let me know.
