### ISSUE TITLE
Error message with Persist Form plugin on form containing file input type

### ISSUE THREAD

**Issue by jocactus** [datorama/akita#86]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am using the persist form plugin in my form containing a file input type.
When I navigate back and forth to my form page, I have the following error:

> ERROR
Error: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

## Expected behavior

The file input type should be completed like the other fields.

## Minimal reproduction of the problem with instructions

Here is a stackblitz showing my error message:
[https://stackblitz.com/edit/angular-chk5s8](https://stackblitz.com/edit/angular-chk5s8)

1. Go to the form page and complete the form
2. Go to the homepage
3. Go back to the form page 

## What is the motivation / use case for changing the behavior?

Persist Form plugin should also support file input type.

## Environment

<pre><code>
Angular version: 6.1.9

Browser:
- [x] Chrome (desktop) version 69.0.3497.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by NetanelBasal** [comment]
I don't think you can set the value of an `<input type="file">` because the value represents a local file on the user's filesystem (not just a string).

**Comment by NetanelBasal** [comment]
It's not something related to the plugin. It will not work even if you do it yourself.

**Comment by jocactus** [comment]
Oh you are right. The ` <input type="file">` cannot be set for security reasons.
So I guess I should omit the field in my FormGroup and the PersistNgFormPlugin to remove the error message.
Thanks for your reactivity!

**Comment by NetanelBasal** [comment]
No problem.
