### ISSUE TITLE
State persistance when lazy-loading modular apps

### ISSUE THREAD

**Issue by actra-gschuster** [datorama/akita#88]
## I'm submitting a...
<pre><code>
[x] Support request
</code></pre>

I'm coming from the "redux world", looking for a simpler way to manage state in an ng6 app.
What I'm wondering - is akita able to handle modularized app state, especially regarding persistance?
As far as I understand the docs and code, there's only one call / config to persistState() in the app module where I could include / exclude parts.

**Comment by actra-gschuster** [comment]
Yes, so the state is rehydrated after a page refresh.

**Comment by NetanelBasal** [comment]
When you call persistState() without include/exclude, Akita will sync the whole stores into the local storage.

**Comment by actra-gschuster** [comment]
That's exactly the problem - when a lazy module isn't accessed yet, the stores shape isn't known as it should be configured within the module.

**Comment by NetanelBasal** [comment]
Sorry, I can't understand what you mean. When your lazy modules instantiate the store providers, Akita will sync them to the local storage.

**Comment by actra-gschuster** [comment]
Say I have three modules: App, Auth and Shop.
App and Auth get loaded on startup, Shop is lazy and defines it's own store that is provided when accessed for the first time.
Now the user hits refresh in his browser - how does akita handle the "Shop" store when the lazy module is not accessed?
Akita can't know it's shape or even if it exists, so will it be removed from localstorage upon next save (e.g. because "Auth" store has changed) or will akita simply keep all values as they are?
And how will it populate the stored values to the "Shop" store as soon as it is lazily loaded?

As I told in the first post I'm coming from redux where I've implemented a "provider solution" that checks localStorage whenever a new "store provider" is registered, so I wanted to know if akita is able to handle the same requirement.

**Comment by actra-gschuster** [comment]
OK, I see, I'll give it a try with a fresh project and test if it can replace the current redux implementation as it seems waaaaaay easier to handle.
Thanks for your time & great work :)

**Comment by NetanelBasal** [comment]
No problem. If you have any further questions, let me know. Good luck.
