### ISSUE TITLE
Documentation Conflicts in regards to providing services

### ISSUE THREAD

**Issue by davisb10** [datorama/akita#89]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The [Application Structure Documentation](https://netbasal.gitbook.io/akita/entity-store/application-structure) for the 'suggested' application structure has all the providers being added to the 'providers' array in a Core Module, however the [StackBlitz](https://stackblitz.com/edit/akita-todos-app) follows the new Angular 6 providedIn: 'root' pattern.

## Expected behavior

Documentation and examples should be the same.

**Comment by NetanelBasal** [comment]
This section (the CoreModule) is for lazy loaded modules only.

**Comment by davisb10** [comment]
What is the preferred method? Using them in the CoreModule or using the providedIn: 'root' way?

**Comment by davisb10** [comment]
Alright. That makes sense. Thanks!

**Comment by NetanelBasal** [comment]
Just saw that I have a mistake. There is no need for `CoreModule` with Angular 6. When the providers are wide app singletons, you should use the `providedIn: 'root'` option. Sorry about that. Also updated the docs.
