### ISSUE TITLE
Wrong default value for hasActive()

### ISSUE THREAD

**Issue by tuurbo** [datorama/akita#92]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Default value for hasActive() should be false. But it returns true because it seems to be undefined. EntityState store should probably have active as null by default.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/akita-todos-app-hy37rf?file=src%2Fapp%2Fapp.component.html

## Environment

<pre><code>
Angular version: 6.1.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by twittwer** [comment]
Oh, sorry - I was biased by my environment 🙈
