### ISSUE TITLE
Just a question (Not an isssue)

### ISSUE THREAD

**Issue by jocactus** [datorama/akita#93]
Is is possible to select an entity with another field than the ID?

For instance, I have the following model:
```
export interface User {
  _id: ID;
  status: string;
  gender: string;
  familyName: string;
  givenName: string;
  [ ... ]
  sub: string;
  [ ... ]
  createdAt: Date;
  updatedAt: Date;
}
```

and I'd like to select my User by its sub (which is another ID) because it is more convenient for me.

**Comment by edmundo096** [comment]
That would be a custom filtering.
I think you want `selectAll().filter()`. The filter operator comes from RxJs.

**Comment by NetanelBasal** [comment]
You can treat the `sub` key as the `id` by doing the following:
```ts
@StoreConfig({ name: '...', idKey: 'sub' })
export class ...
}
```

**Comment by jocactus** [comment]
The problem is I already use idKey for my `_id` field.
Can I use 2 ID for the same entity?

**Comment by NetanelBasal** [comment]
No. But if the sub key is also your id why you are not using it instead of _id?

**Comment by jocactus** [comment]
The entity is first created without sub. This operation is done by a user.
After that an admin check this entity and update if it's ok by assigning a sub and others parameters.
So, I cannot use the sub as id at the beginning because it does not exist.

**Comment by NetanelBasal** [comment]
What is the problem using the _id? Can you explain why using sub is more convenient?

**Comment by jocactus** [comment]
On further consideration, there is no problem using _id. Thanks for the answer.
