### ISSUE TITLE
use strict deep freeze to fix IE11 crashes

### ISSUE THREAD

**Issue by omgwtflaserguns** [datorama/akita#94]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Our angular app crashes in IE11 because of "no access to caller attribute in strict mode".

The problem occurs in deep-freeze, an akita internal. 

We replaced the deepFreeze function in akita internals with [strict-deep-freeze](https://github.com/jsdf/deep-freeze/blob/master/index.js) and it resolved the issue. In this implementation caller arguments are explicitly omitted.

## Expected behavior

No crashes in strict mode on IE11.

## Minimal reproduction of the problem with instructions

i think there should no example app needed, happy to provide one if otherwise. :)

## What is the motivation / use case for changing the behavior?

Support of IE11

## Environment

<pre><code>
Angular version: 6.0.3 with CLI

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  8.11.4 
- Platform:  Windows 10 

Others:

</code></pre>

**Comment by omgwtflaserguns** [comment]
I will be free again in about 3 hours, i will create a PR then.

**Comment by NetanelBasal** [comment]
Cool, thanks.
