### ISSUE TITLE
Angular. How can I detect, what kind of action has updated store data?

### ISSUE THREAD

**Issue by romanszedzielorz** [datorama/akita#96]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
Angular - question about store action?

</code></pre>

## Current behavior

Angular. How can I detect, what kind of action has updated store data?
Example:
1) In component I can call Akita service for GET ITEM and SAVE ITEM.
2) Both are updating store ITEM state.
3) In component I have a Subscription to query, but I have no idea, if store was updated because of GET or SAVE.
4) I need to know it, to make different things in component, according to each action.

I have added 'action' variable to store, where I save this value. But the problem is that, when new component is created and subscribe is created and dispatched immediately, my 'action' vabiable is readed too, which is wrong.

Any ideas, what can I do with it?

## Environment

<pre><code>
Angular version: 6.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Why do u need to know the action? Can you give me an example, please?

**Comment by romanszedzielorz** [comment]
For example, I want to inform user (show message):
- 'Data has been refreshed' or 'Data has been resetted' for GET ITEM
- 'Data has been saved' for SAVE ITEM

**Comment by NetanelBasal** [comment]
You can return the http subscription and you will know.

**Comment by romanszedzielorz** [comment]
"You can return the http subscription and you will know." -> I don't understand, what should I do.

This is my Akita store:

**algorithm.store.ts**
<pre><code>
export enum AlgorithmStateAction {
  GET = 'GET',
  SAVE = 'SAVE'
}

export interface AlgorithmState {
  action: AlgorithmStateAction;
  algorithm: Algorithm;
}

export function AlgorithmStateCreateInitialState(): AlgorithmState {
  return {
    action: null,
    algorithm: null
  };
}

@Injectable({ providedIn: 'root' })
@StoreConfig({ name: 'algorithm' })
export class AlgorithmStore extends Store<AlgorithmState> {

  constructor() {
    super(AlgorithmStateCreateInitialState());
  }

}
</pre></code>

**algorithm.query.ts**
<pre><code>
@Injectable({ providedIn: 'root' })
export class AlgorithmQuery extends Query<AlgorithmState> {

  loading$ = this.selectLoading();
  error$ = this.selectError();

  algorithm$ = this.select(state => {
    return state.algorithm;
  });

  get action(): AlgorithmStateAction {
    const snapshot = this.getSnapshot();
    return snapshot.action;
  }

  constructor(protected store: AlgorithmStore) {
    super(store);
  }

}
</pre></code>

**algorithm.service.ts**
<pre><code>
@Injectable({ providedIn: 'root' })
export class AlgorithmService {

  constructor(
    private algorithmStore: AlgorithmStore,
    private algorithmDataService: AlgorithmDataService
  ) { }

  getAlgorithm() {
    this.algorithmStore.setLoading(true);

    this.algorithmDataService.getAlgorithm().subscribe((dataServiceResult: Algorithm) => {
      const algorithm = plainToClass(Algorithm, dataServiceResult);

        this.algorithmStore.update(state => ({
          algorithm: algorithm,
          action: AlgorithmStateAction.GET
        }));
        this.algorithmStore.setLoading(false);
      },
        (err: HttpErrorResponse) => {
          // displaying errors 400 is handled by AuthInterceptor
          this.algorithmStore.setError(err);
          this.algorithmStore.setLoading(false);
        });
  }

  getAlgorithm() {
    (...)
        this.algorithmStore.update(state => ({
          algorithm: algorithm,
          action: AlgorithmStateAction.SAVE
        }));
    (...)
  }

  clearStore() {
      this.algorithmStore.update(state => (AlgorithmStateCreateInitialState()));
      this.algorithmStore.setPristine();
  }
}
</pre></code>

**some Angular component**
<pre><code>
this.algorithmQuery.algorithm$.subscribe(algorithm => {
        switch (this.algorithmQuery.action) {
          case AlgorithmStateAction.GET:
            (...)
            break;
          case AlgorithmStateAction.SAVE:
            (...)
            break;
        }
      });
</pre></code>

Like I have written above. The problem is that, when new component is created and subscribe is created and dispatched immediately, my 'action' vabiable is readed too, which is wrong, because action stored in store is some old action, that is not important, even wrong on component initialize, but I can't remove it, because it's necessary for future component store actions.

**Comment by NetanelBasal** [comment]
You have two options: 

You can use the operator`skip(1)`.

You can return the subscription:
```ts
  getAlgorithm() {
    this.algorithmStore.setLoading(true);

    return this.algorithmDataService.getAlgorithm().pipe(
      tap((dataServiceResult: Algorithm) => {
      const algorithm = plainToClass(Algorithm, dataServiceResult);

        this.algorithmStore.update(state => ({
          algorithm: algorithm,
          action: AlgorithmStateAction.GET
        }));
        this.algorithmStore.setLoading(false);
      },
        (err: HttpErrorResponse) => {
          (...)
        });
  }
```

And in your component:
```ts
getAlgorithm().subscribe(() => {
   // here you know that you perform the get action 
})

saveAlgorithm().subscribe(() => {
   // here you know that you perform the save action 
})
```

**Comment by edmundo096** [comment]
Looks good.
This is like creating an Effect isn't it?

**Comment by NetanelBasal** [comment]
You can say so.

**Comment by romanszedzielorz** [comment]
@NetanelBasal 
Looks good. Thank you for this idea.
