### ISSUE TITLE
hasEntity() with array of ID[]

### ISSUE THREAD

**Issue by jocactus** [datorama/akita#98]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Is it possible to have `hasEntities(ID[])` to check if an array of values are available in the store?

**Comment by NetanelBasal** [comment]
I would add to the existing hasEntity() the ability to take also an array. Do you want to create a PR, please?

**Comment by NetanelBasal** [comment]
Supported in v1.13.0.
